### ISSUE TITLE
Drawers: add option to display as an overlay instead of sliding content out of the way

### ISSUE THREAD

**Issue by joshtynjala** [BowlerHatLLC/feathers#1010]
In other words, a drawer is currently on the bottom and the content needs to slide out of the way to reveal it. There should be a way for the drawer to be on top and slide over the content.

**Comment by eliatlas** [comment]
+ 1

**Comment by mikhailkuts** [comment]
+1

**Comment by animenexo** [comment]
+1

**Comment by 22ROUND** [comment]
+1 would be great, thanks Josh

**Comment by amosl** [comment]
+1 
this is the way all android apps use it

**Comment by bangersandflash** [comment]
This would be really handy. Has anyone found a workaround in the interim?

**Comment by teotigraphix** [comment]
Great addition, thanks!

**Comment by cmdaniel** [comment]
+1

**Comment by joshtynjala** [comment]
No need for a +1 anymore. It's already here! Take a look at the [openMode](http://feathersui.com/api-reference/feathers/controls/Drawers.html#openMode) property.

**Comment by cmdaniel** [comment]
Awesome!

Em quinta-feira, 18 de fevereiro de 2016, Josh Tynjala <
notifications@github.com> escreveu:

> No need for a +1 anymore. It's already here! Take a look at the openMode
> <http://feathersui.com/api-reference/feathers/controls/Drawers.html#openMode>
> property.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/BowlerHatLLC/feathers/issues/1010#issuecomment-185949229>
> .
>


-- 
Atenciosamente,

Daniel C. Melo
Fixo: (31) 3213-9716
Celular: (31) 9102-7900
E-mail: danielcm@industria-i.com.br
Skype: industriai

www.industria-i.com.br
