### ISSUE TITLE
Label vertical alignment

### ISSUE THREAD

**Issue by SamYStudiO** [BowlerHatLLC/feathers#1015]
New Label background and padding properties are great!
I guess you could add a aligment property?

Thx for your work!

**Comment by mariommoreno** [comment]
We are using the LayoutGroup workarround, but using only uppercase fonts the text does not look aligned due to the lower parts of some lowercase letters (ex: pqgj). Any workaround for this issue?

**Comment by joshtynjala** [comment]
It's an issue in Flash Text Engine. It doesn't seem to report dimensions properly. I have a workaround that looks pretty safe to use, but I won't be applying it until after Feathers 2.3 is released.

In the meantime, you can set baselineFontSize on the TextBlockTextRenderer to a larger font size. This should increase the ascent without affecting the descent, I think. If I recall correctly, you also need to pass the same FontDescription that is used by the ElementFormat to the baselineFontDescription property for baselineFontSize to work.

**Comment by mariommoreno** [comment]
Thank you, we will wait for the new release (Starling 2.0 compatible?).
Meantime we'll check your workaround.

_____________________

*Mario Morales Moreno*
 Tel. (+34) 678 43 73 72

**Comment by joshtynjala** [comment]
Yes, the next version after 2.3 is planned to be compatible with Starling 2.0.

**Comment by joshtynjala** [comment]
Vertical alignment will be supported by all text renderers in Feathers 3.1 using the appropriate property on starling.text.TextFormat.
