### ISSUE TITLE
TileLayout, variable Row Height?

### ISSUE THREAD

**Issue by manofspirit** [BowlerHatLLC/feathers#1077]
Hi

Currently TileLayout has rows of same sizes and when an item expands its size on click then all the rows jumps. It'd be really great if only that row increase its height instead of all the rows, this will enable us to make items that expand collapse.

Thanks

**Comment by joshtynjala** [comment]
It's a good suggestion.

**Comment by joshtynjala** [comment]
Closing because this can be achieved pretty easily with FlowLayout, if you manually set the width of the items.
