### ISSUE TITLE
New Component: Table / DataGrid

### ISSUE THREAD

**Issue by neokeats** [BowlerHatLLC/feathers#109]
hi, 
i think it should be in the toolbox.

**Comment by manofspirit** [comment]
Hi Josh, Can we expect DataGrid in 3.0? That'd be another great addition after  Tooltips.

**Comment by joshtynjala** [comment]
I don't think there will be time to implement a DataGrid component in 3.0. I already have a lot on my plate. Tool tips were easy to add in an afternoon when I needed a break from other stuff, but a DataGrid will be a much bigger multi-day task.

**Comment by yuheng85** [comment]
I have implemented a Datagrid component for Staring Builder, it uses MultiColumnGridLayout. The layout was once part of Feathers but not any more. I don't think it's implemented to a product ready level but we do use it in many of our internal tools.

https://github.com/mindjolt/starling-builder-editor/blob/master/src/starlingbuilder/util/feathers/DataGrid.as

**Comment by aammfe** [comment]
We are developing a health care app that require Data Grid with following feature
- Each row is selectable and 1 cell can be editable (just like Flex)
- data is sortable by touch/clicking column headers
- fully customisable renderer (both editor/renderer)

**Comment by AMBTech** [comment]
Feathers has almost all the components required for Pro Development. Only missing pieces are DataGrid and Tree Control. I hope Josh work on DataGrid right after 3.0

**Comment by yooni126** [comment]
Josh, like Tree , work on DataGrid , we want it really :(
