### ISSUE TITLE
List: support different first and last item renderers, similar to GroupedList

### ISSUE THREAD

**Issue by mariommoreno** [BowlerHatLLC/feathers#1114]
This could be useful in the same way it is for grouped lists.

In my case, I'm using the last item renderer as a "Load More..." button.
With "lastItemRenderer" this could be done easily.

**Comment by joshtynjala** [comment]
In Feathers 2.3, List will now support setItemRendererFactoryWithID() and factoryIDFunction, which will allow multiple item renderer types at any position (not just first and last). Closing.
