### ISSUE TITLE
VerticalSpinnerLayout, HorizontalSpinnerLayout: add support for disabling infinite scrolling

### ISSUE THREAD

**Issue by Pandan** [BowlerHatLLC/feathers#1157]
Would be great to have the ability to disable infinite scrolling in the SpinnerList.
In my case I want the ability that the spinnerList provides, that let's me have a list that snaps for each list item. But just don't want it to scroll infinite(wrap around) I tried using the list for this setting snapToPages to true but seems like this doesn't work as in the spinnerList.

**Comment by joshtynjala** [comment]
In addition to setting snapToPages to true, you would also need to set pageHeight. By default, it will be the full height of the list, but you would want it to be the height of an item renderer instead.

**Comment by Pandan** [comment]
Thanks, I will test this.
