### ISSUE TITLE
Alert not fitting contents

### ISSUE THREAD

**Issue by kevinfoley** [BowlerHatLLC/feathers#1169]
If the combined width of the buttons on an alert is greater than the width of the message body while distributed button widths is disabled, the buttons can become misaligned and the background sized improperly

![alertbug](https://cloud.githubusercontent.com/assets/7231744/8884314/a344dc0e-320a-11e5-9cda-727dd88f1f4a.jpg)

**Comment by kevinfoley** [comment]
It might help if I didn't set the maximum width of the alert too small, wouldn't it?

**Comment by joshtynjala** [comment]
I was just about to mention that maxWidth may be involved. Glad you figured it out!

**Comment by kevinfoley** [comment]
The more I think about this, the more I feel Feathers should throw an error when this situation occurs, since the cause isn't immediately obvious and result is never desirable.

**Comment by joshtynjala** [comment]
A cosmetic issue shouldn't result in a runtime error, regardless of how difficult it may be to track down the cause.

Imagine if a developer calculated a maxWidth dynamically, based on screen size or something. A user could try the app on a device that wasn't available to the developer for testing. A runtime error could cause parts of the app to stop working. For the user, the app is completely broken, when they should only need to encounter a minor visual glitch.

**Comment by joshtynjala** [comment]
I'll see if I can possibly make use of the new FlowLayout. That will allow the buttons to appear on multiple rows.

**Comment by kevinfoley** [comment]
That was certainly a better solution than what I had suggested. Many thanks!
