### ISSUE TITLE
releaseLineCreationData missing !

### ISSUE THREAD

**Issue by khoamoc** [BowlerHatLLC/feathers#1176]
optimize memory by using releaseLineCreationData after createTextLine and createTextLine of TextBlock
Instructs the text block to release all the temporary data associated with the creation of text lines. 
--> in function: refreshTextLines in TextBlockTextRenderer class
http://help.adobe.com/en_US/FlashPlatform/reference/actionscript/3/flash/text/engine/TextBlock.html#releaseLineCreationData()

**Comment by joshtynjala** [comment]
This is by design. Your link explains why:

> to maximize performance for rebreaking the lines (for example when the container is resized) the releaseLineCreationData() method should not be called.
