### ISSUE TITLE
Pasting into TextInput is broken in IOS 8.4

### ISSUE THREAD

**Issue by greglindquist** [BowlerHatLLC/feathers#1180]
Hey guys, 

I just tested my Flash v18 mobile app on an iPhone 6 IOS 8.4 device in landscape mode. Oddly, when I give focus to the text input control, I can long hold on the text input to get the paste option to appear in IOS 8's native paste functionality. When I tap paste, it deselects the text input (which also hides the soft keyboard) and doesn't paste any content.  Any ideas? This seems to be working great in previous versions of IOS 8 and seems new to me.

Thanks!

**Comment by joshtynjala** [comment]
Thanks for reporting. I'll take a look.

**Comment by joshtynjala** [comment]
I'm not able to reproduce this issue in today's iOS 9 update. It appears are some other iOS 9 issues with TextInput that I need to address, but pasting works correctly when I tap Paste.
