### ISSUE TITLE
Rename Button's .label property to .text

### ISSUE THREAD

**Issue by kevinfoley** [BowlerHatLLC/feathers#1182]
The button's `label` property should be renamed `text`, for three reasons:

1. Consistency of usage with the Label class, where the text is accessed via the `text` property
2. Consistency with other GUI libraries (.NET, Java Swing, Starling, Unity, Android, etc, all use a `text` property or `setText()` method)
3. Eliminating ambiguity (users might expect the `label` property of a button to be accessing an instance of Label instead of a String)

(Of course, there may be a good reason you went with the name "label" instead of "text" that I'm not aware of)

**Comment by joshtynjala** [comment]
Naming the property "label" was a no-brainer,  considering the history of this convention in the Flash platform.

mx.controls.Button
spark.components.Button
fl.controls.Button

All of those classes, created by Adobe, use the name label, and thousands of Flash developers have experience with those other component frameworks.

Regardless, if I changed it, I would be needlessly breaking legacy code for little benefit. At this point, it's not going to happen.
