### ISSUE TITLE
Scale3Image: Minor forgotten code

### ISSUE THREAD

**Issue by rdoi** [BowlerHatLLC/feathers#1183]
Scale3Image.as:510 there is an extra redundant code forgotten in the line:

public function validate():void {
...
var scaledThirdRegionSize:Number = (this._frame.height - this._textures.firstRegionSize - this._textures.secondRegionSize) * oppositeEdgeScale;***sumFirstAndThird = scaledFirstRegionSize + scaledThirdRegionSize;***
var sumFirstAndThird:Number = scaledFirstRegionSize + scaledThirdRegionSize;
...
}

Just to let you know.

**Comment by joshtynjala** [comment]
Thank you!
