### ISSUE TITLE
Validating a screen containing an empty FlowLayout causes a crash

### ISSUE THREAD

**Issue by kevinfoley** [BowlerHatLLC/feathers#1184]
When attempting to validate a screen that contains a LayoutGroup that uses a FlowLayout and has no children, FeathersControl will throw an ArgumentError from setSizeInternal, line 1862.

Tested using a PanelScreen with AnchorLayout.

**Comment by joshtynjala** [comment]
Thank you. This issue is easy to reproduce, even without a PanelScreen.

	var group:LayoutGroup = new LayoutGroup();
	group.layout = new FlowLayout();
	this.addChild(group);

**Comment by kevinfoley** [comment]
Great, thanks Josh! Speedy as always!
