### ISSUE TITLE
Scroll Events of children inside parent scrolling not firing

### ISSUE THREAD

**Issue by interactivemartin** [BowlerHatLLC/feathers#1189]
I have this Screen:

Which has several horizontal scrollers. They scroll horizontally, and the panel scrolls vertically. The thing is with feathers (prior to 2.2.0) If the panelScreen was scrolling, and I scrolled an horizontal scroller, it stopped. Now it doesn't fire the scroll event till the main PanelScreen has stopped scrolling. 

package com.im.screens
{
	
	import com.distriqt.extension.camera.Camera;
	import com.distriqt.extension.camera.CameraMode;
	import com.greensock.easing.Strong;
	import feathers.controls.Alert;
	import feathers.controls.Button;
	import feathers.controls.Callout;
	import feathers.controls.ImageLoader;
	import feathers.controls.Label;
	import feathers.controls.LayoutGroup;
	import feathers.controls.List;
	import feathers.controls.Panel;
	import feathers.controls.PanelScreen;
	import feathers.controls.PickerList;
	import feathers.controls.renderers.DefaultListItemRenderer;
	import feathers.controls.renderers.IListItemRenderer;
	import feathers.controls.ScrollContainer;
	import feathers.core.PopUpManager;
	import feathers.data.ListCollection;
	import feathers.display.Scale9Image;
	import feathers.layout.AnchorLayout;
	import feathers.layout.AnchorLayoutData;
	import feathers.layout.HorizontalLayout;
	import feathers.layout.HorizontalLayoutData;
	import feathers.layout.VerticalLayout;
	import feathers.layout.VerticalLayoutData;
	import feathers.textures.Scale9Textures;
	import flash.display.Loader;
	import flash.display3D.Context3DTextureFormat;
	import flash.geom.Point;
	import flash.geom.Rectangle;
	import flash.net.URLLoader;
	import flash.net.URLRequest;
	import flash.text.TextFormat;
	import flash.text.TextFormatAlign;
	import starling.display.Quad;
	import starling.textures.Texture;
	import starling.textures.TextureSmoothing;
	
	import starling.core.Starling;
	import starling.display.DisplayObject;
	import starling.display.Image;
	import starling.events.Event;
	
	public class ResultScreen extends BaseScreen
	{
		public static const FAKE_DATA:Boolean = true;
		
		private var backArrow:Button;
		private var popup:GeneralLoader;
		private var horizontalList:List;
		private var answer:Object;
		private var scrollContainers:Array;
		
		public function ResultScreen()
		{
			super();
		}
		
		override protected function initialize():void
		{
			super.initialize();

			if (!FAKE_DATA)
			{
				initSettings(); 
				createGraphics(); 
				createListeners(); 				
			}else fakeInit();
		}
		
		
		private function fakeInit():void
		{
			var urlLoader:URLLoader = new URLLoader();
			urlLoader.addEventListener("complete", onLoaderComplete);
			urlLoader.load(new URLRequest("http://demos.interactivemartin.com/ocr/test.json"));
		}
		
		private function onLoaderComplete(e:*):void 
		{
			answer = JSON.parse((e.target as URLLoader).data);
			
			initSettings(); 
			createGraphics(); 
			createListeners(); 
		}
		
		//////////////////////////////////////////////////////////
		
		private function initSettings():void 
		{
			if (!FAKE_DATA) answer = DataResults.OCR_IMAGE_RESULTS.answer; 
			
			this.verticalScrollPolicy = Panel.SCROLL_POLICY_AUTO;
			this.horizontalScrollPolicy = Panel.SCROLL_POLICY_OFF;
		}
		
		private function createGraphics():void
		{
			createHeaderItems(); 
			
			var panelLayout:VerticalLayout = new VerticalLayout(); 
			panelLayout.horizontalAlign = VerticalLayout.HORIZONTAL_ALIGN_JUSTIFY;
			panelLayout.gap = 40 * Globals.scaleFactor;
			layout = panelLayout;
			
			createImageScrollers(); 
			
		}
		
		private function createImageScrollers():void 
		{
			for each (var item:Object in answer ) 
			{
				
				var label1:Label = new Label(); 
				label1.wordWrap = true; 
				label1.styleName = OptimaVisionTheme.THEME_STYLE_NAME_LABEL_RESULT_TITLE_STYLE;
				
				var label1LayoutData:HorizontalLayoutData = new HorizontalLayoutData(100);
				label1.layoutData  = label1LayoutData;
				label1.paddingTop = Globals.scaleValue(40);
				
				//label1.x = 20;
				//Globals.normalizePosition(label1); 
				addChild(label1);
				label1.text = (item.source as String).toUpperCase();	
				
				var label2:Label = new Label(); 
				label2.wordWrap = true; 
				addChild(label2);
				label2.text = (item.translation as String).toUpperCase();
								
				var scrollContainer:ScrollContainer = new ScrollContainer(); 
				addChild(scrollContainer);
				scrollContainer.height = 300;
				
				var containerLayout:HorizontalLayout = new HorizontalLayout(); 
				containerLayout.verticalAlign = HorizontalLayout.VERTICAL_ALIGN_JUSTIFY;
				containerLayout.gap = 20 * Globals.scaleFactor;
				scrollContainer.layout = containerLayout;
				
				scrollContainer.verticalScrollPolicy = ScrollContainer.SCROLL_POLICY_OFF;
				scrollContainer.horizontalScrollPolicy = ScrollContainer.SCROLL_POLICY_AUTO;
				
				var scrollCointainerLayoutData:HorizontalLayoutData = new HorizontalLayoutData(100);
				scrollContainer.layoutData = scrollCointainerLayoutData;
				
				
				scrollContainers = new Array(); 
				//Create Image Objects
				var i:int = 0; 
				for each (var imageURL:String in item.images ) 
				{
					var loader:ImageLoader = new ImageLoader();
					 loader.source = imageURL;
					 
					 loader.smoothing = TextureSmoothing.BILINEAR; 
					 scrollContainer.addChild( loader );
					 
					 scrollContainer.addEventListener(Event.SCROLL, onHorizontalScroll);
					 
					 scrollContainers.push(scrollContainer);
					 
					 i++;
				}
				
			}
			
			
		
			
		}

		private function createListeners():void
		{
			backArrow.addEventListener(Event.TRIGGERED, onBackButtonTriggered); 
			this.addEventListener(Event.SCROLL, onMainListScroll);
					
		}
		
		private function onMainListScroll(e:Event):void 
		{
			
			trace ("*executing* >> [ResultScreen.onMainListScroll] ");
			
			for each (var scroller:ScrollContainer in scrollContainers)
			{
				scroller.stopScrolling();
			}
		}
		
		private function onHorizontalScroll(e:Event):void 
		{
			this.stopScrolling(); 
		}		
		

		
		override protected function draw():void
		{
			super.draw();
		}
		
		override public function dispose():void
		{
			super.dispose();
		
		}
			
	}

}

**Comment by joshtynjala** [comment]
I responded to your post in the forums.
