### ISSUE TITLE
Button Skin for Button.STATE_UP not taken into account for touches.

### ISSUE THREAD

**Issue by interactivemartin** [BowlerHatLLC/feathers#1191]
I am using 2.3.0.

I have buttons that have a Button.STATE_UP skin (a plain red texture), but for some reason, when I tap on the red zone, the touches are not detected. They are well detected, though, in the bounds of the icon image (greenish zone -  I painted the icon directly in the image in photoshop). The background zone of the button should count for the touches, no? 

    protected function setButtonIconOnlyStyles( button:Button ):void 
    {
            var skinSelector:SmartDisplayObjectStateValueSelector = new SmartDisplayObjectStateValueSelector();
            skinSelector.defaultValue = null;
			
            skinSelector.setValueForState( mColorRed, Button.STATE_UP );

            button.stateToSkinFunction = skinSelector.updateValue;
			button.stateToIconFunction = headerStateToIcon;
			
			button.gap = Number.POSITIVE_INFINITY;
            button.minGap = mSmallPaddingSize;
            button.minWidth = button.minHeight = mControlSize;
            button.paddingLeft = button.paddingRight = mLargePaddingSize;
            button.defaultLabelProperties.elementFormat = mDefaultUIElementFormat;
            button.disabledLabelProperties.elementFormat = mDefaultUIElementFormat;
            button.iconOffsetY = -3 * mScale;
           
            button.paddingTop = mRegularPaddingSize;
            button.paddingBottom = mRegularPaddingSize;

            button.defaultLabelProperties.elementFormat = mDefaultUIElementFormat;
            button.disabledLabelProperties.elementFormat = mDefaultUIElementFormat;
    }

![testbtn](https://cloud.githubusercontent.com/assets/8929287/9579798/73fa1ab4-4ff5-11e5-81ff-baad64d37321.png)

**Comment by joshtynjala** [comment]
It's because you don't have a background skin in any other state. You'll notice that the background skin disappears when you hover your mouse over the button. When that happens, there's nothing there to touch.

**Comment by interactivemartin** [comment]
I understand. If I want a button with the icon and transparent background,
the elegant way would be to put a transparent background for the state?

On Monday, August 31, 2015, Josh Tynjala <notifications@github.com> wrote:

> It's because you don't have a background skin in any other state. You'll
> notice that the background skin disappears when you hover your mouse over
> the button. When that happens, there's nothing there to touch.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/BowlerHatLLC/feathers/issues/1191#issuecomment-136470981>
> .
>


-- 
___________________________________

*Martín Lombana* / CEO & Founder
INTERACTIVE*MARTIN*  —  CREATIVE AGENCY

*OFFICE* : +34 946 759 137  | MOBILE: +34 633 63 02 35
*WEB *: INTERACTIVEMARTIN.COM <http://www.interactivemartin.com/>
*FACEBOOK *: FACEBOOK.COM/INTERACTIVEMARTIN
<http://facebook.com/interactivemartin>
*TWITTER*: TWITTER.COM/INTMARTIN <http://twitter.com/intmartin>

**Comment by joshtynjala** [comment]
Yes, a Quad or another display object with alpha set to 0 works nicely.

**Comment by interactivemartin** [comment]
Understood. Thanks!

On Monday, August 31, 2015, Josh Tynjala <notifications@github.com> wrote:

> Yes, a Quad or another display object with alpha set to 0 works nicely.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/BowlerHatLLC/feathers/issues/1191#issuecomment-136473761>
> .
>


-- 
___________________________________

*Martín Lombana* / CEO & Founder
INTERACTIVE*MARTIN*  —  CREATIVE AGENCY

*OFFICE* : +34 946 759 137  | MOBILE: +34 633 63 02 35
*WEB *: INTERACTIVEMARTIN.COM <http://www.interactivemartin.com/>
*FACEBOOK *: FACEBOOK.COM/INTERACTIVEMARTIN
<http://facebook.com/interactivemartin>
*TWITTER*: TWITTER.COM/INTMARTIN <http://twitter.com/intmartin>

**Comment by interactivemartin** [comment]
I used    skinSelector.defaultValue = mColorTransparent;
 (mColorTransparent is 9SliceScaleTexture, with a transparent background),
but it doesn't change anything.

According to the Docs, if I set the defaultValue like that, and do not set
any other State (because I want my button to be transparent, with an icon
in the center, but be touchable in all it's zone...) It should work no?


___________________________________

*Martín Lombana* / CEO & Founder
INTERACTIVE*MARTIN*  —  CREATIVE AGENCY

*OFFICE* : +34 946 759 137  | MOBILE: +34 633 63 02 35
*WEB *: INTERACTIVEMARTIN.COM <http://www.interactivemartin.com/>
*FACEBOOK *: FACEBOOK.COM/INTERACTIVEMARTIN
<http://facebook.com/interactivemartin>
*TWITTER*: TWITTER.COM/INTMARTIN <http://twitter.com/intmartin>

**Comment by joshtynjala** [comment]
Yes, that should work.

**Comment by interactivemartin** [comment]
Strange then. Because if I set it, as a default, to red , and now all the
backgrounds are red, still I can not touch them in some zones.

The Style Setter for this button is this:

protected function setButtonIconOnlyStyles( button:Button ):void
{
            var skinSelector:SmartDisplayObjectStateValueSelector = new
SmartDisplayObjectStateValueSelector();
            skinSelector.defaultValue = mColorRed;
            button.stateToSkinFunction = skinSelector.updateValue;
button.stateToIconFunction = headerStateToIcon;
button.gap = Number.POSITIVE_INFINITY;
            button.minGap = mSmallPaddingSize;
            button.minWidth = button.minHeight = mControlSize;
            button.paddingLeft = button.paddingRight = mLargePaddingSize;
            button.defaultLabelProperties.elementFormat =
mDefaultUIElementFormat;
            button.disabledLabelProperties.elementFormat =
mDefaultUIElementFormat;

            button.paddingTop = mRegularPaddingSize;
            button.paddingBottom = mRegularPaddingSize;

            button.defaultLabelProperties.elementFormat =
mDefaultUIElementFormat;
            button.disabledLabelProperties.elementFormat =
mDefaultUIElementFormat;
        }


Strange...

___________________________________

*Martín Lombana* / CEO & Founder
INTERACTIVE*MARTIN*  —  CREATIVE AGENCY

*OFFICE* : +34 946 759 137  | MOBILE: +34 633 63 02 35
*WEB *: INTERACTIVEMARTIN.COM <http://www.interactivemartin.com/>
*FACEBOOK *: FACEBOOK.COM/INTERACTIVEMARTIN
<http://facebook.com/interactivemartin>
*TWITTER*: TWITTER.COM/INTMARTIN <http://twitter.com/intmartin>

**Comment by joshtynjala** [comment]
Perhaps there's something transparent on the display list above the button(s)? Have you tried in an empty project?

**Comment by interactivemartin** [comment]
Attatched a project, With a simple Theme, and just the Button Style. No
other things in front of the buttons... and this happens.

http://we.tl/DcGcDzMpWE

Take a close look how , in the edges, it doesn't really pick up the
touches. Notice how my finger is on top of the button, and there is an
area, where the touches do not happen (if the icon does not change to red,
and dissapears, it's not doing it propertly)


___________________________________

*Martín Lombana* / CEO & Founder
INTERACTIVE*MARTIN*  —  CREATIVE AGENCY

*OFFICE* : +34 946 759 137  | MOBILE: +34 633 63 02 35
*WEB *: INTERACTIVEMARTIN.COM <http://www.interactivemartin.com/>
*FACEBOOK *: FACEBOOK.COM/INTERACTIVEMARTIN
<http://facebook.com/interactivemartin>
*TWITTER*: TWITTER.COM/INTMARTIN <http://twitter.com/intmartin>

**Comment by joshtynjala** [comment]
Can you simplify the project? I just spent a couple of minutes trying to get it running, but there must be some asset that I've put in the wrong place or something. It would be better if you could switch it over to embedded assets for me. Then, just create the button in the main class. No need for a StackScreenNavigator and all that extra stuff when all that matters here is one button.

**Comment by interactivemartin** [comment]
Voilà, as you requested. Down to 3 classes. Embedded Theme Assets. All my
project, except my certs.:

http://we.tl/obbc9vrNIX

I think it's more a touch issue in iOS than other thing... because if you
run it in the desktop, it will pick up the pixels just fine.... till the
last one. But as you could see in the video, I was pressing on top of the
button on one side, and it didn't pick it up.

Thanks :)


___________________________________

*Martín Lombana* / CEO & Founder
INTERACTIVE*MARTIN*  —  CREATIVE AGENCY

*OFFICE* : +34 946 759 137  | MOBILE: +34 633 63 02 35
*WEB *: INTERACTIVEMARTIN.COM <http://www.interactivemartin.com/>
*FACEBOOK *: FACEBOOK.COM/INTERACTIVEMARTIN
<http://facebook.com/interactivemartin>
*TWITTER*: TWITTER.COM/INTMARTIN <http://twitter.com/intmartin>

**Comment by joshtynjala** [comment]
If it works properly on desktop, then there's probably not anything I can do in Feathers. Something in Starling may be misconfigured, or it may have something to do with iOS.

It's worth noting that touch events are dispatched at a specific pixel. Even if the edge of your finger is overlapping the button, it won't matter if the center of the touch (or whatever rules iOS uses to figure out exactly where a touch happens) is off the edge of the button.

**Comment by interactivemartin** [comment]
Understood. Sorry for the trouble then.
:)

On Tuesday, September 1, 2015, Josh Tynjala <notifications@github.com>
wrote:

> If it works properly on desktop, then there's probably not anything I can
> do in Feathers. Something in Starling may be misconfigured, or it may have
> something to do with iOS.
>
> It's worth noting that touch events are dispatched at a specific pixel.
> Even if the edge of your finger is overlapping the button, it won't matter
> if the center of the touch (or whatever rules iOS uses to figure out
> exactly where a touch happens) is off the edge of the button.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/BowlerHatLLC/feathers/issues/1191#issuecomment-136516892>
> .
>


-- 
___________________________________

*Martín Lombana* / CEO & Founder
INTERACTIVE*MARTIN*  —  CREATIVE AGENCY

*OFFICE* : +34 946 759 137  | MOBILE: +34 633 63 02 35
*WEB *: INTERACTIVEMARTIN.COM <http://www.interactivemartin.com/>
*FACEBOOK *: FACEBOOK.COM/INTERACTIVEMARTIN
<http://facebook.com/interactivemartin>
*TWITTER*: TWITTER.COM/INTMARTIN <http://twitter.com/intmartin>
