### ISSUE TITLE
MXML or Initialisation scrollwheel issue in Scroller/List

### ISSUE THREAD

**Issue by jesperstarkar** [BowlerHatLLC/feathers#1192]
The following produces this bug:

	<f:List width="500">
		<f:layoutData>
			<f:AnchorLayoutData>
				<f:top>0</f:top>
				<f:bottom>0</f:bottom>
			</f:AnchorLayoutData>
		</f:layoutData>	
	</f:List>

This fixes the bug:

	<app:creationComplete>
		<![CDATA[
			sourceList = new List();
			var sourceAnchors:AnchorLayoutData = new AnchorLayoutData(0, Number.NaN, 0, 0);
			sourceList.width = 500;
			sourceList.layoutData = sourceAnchors;
			this.addChild(sourceList);
		]]>
	</app:creationComplete>

**Bug:**
When using ScrollWheel/Touchpad on Macbook Pro/OS X, the scroller (List) always resets and starts from the top, on each new scroll. This happens if the list is added through MXML, but not if added manually. I have reason to think some race condition/metrics or initialisation is the problem, but haven't researched it well enough to conclude.

**Comment by joshtynjala** [comment]
I was able to reproduce initially, and then I noticed that I forgot to set a layout on the parent component. This did the trick:

	<f:layout>
		<f:AnchorLayout/>
	</f:layout>

Maybe you forgot to give the parent an AnchorLayout?

Also, can you submit MXML-related bugs to [feathers-sdk](https://github.com/BowlerHatLLC/feathers-sdk) in the future? Thank you!
