### ISSUE TITLE
Scale3Image / Scale9Image: scaling or stretching when using scaleX / scaleY?

### ISSUE THREAD

**Issue by psmtec-dklein** [BowlerHatLLC/feathers#1196]
I noticed that Scale3Image and Scale9Image don't override the setter for scaleX / scaleY, so they actually **scale the whole** Image instead of **stretching the center** (like when setting width / height).

I managed to fix my usecase by overriding them, not sure if it's 100% correct, but it's working for now.

```javascript
		override public function set scaleX( value : Number ) : void {
			this._width = this._hitArea.width = this.width * value;
			this._layoutChanged = true;
			this.invalidate();
		}

		override public function set scaleY( value : Number ) : void {
			this._height = this._hitArea.height = this.height * value;
			this._layoutChanged = true;
			this.invalidate();
		}
```

Now i'm wondering, is the **scaling** the intended functionality or an oversight?

**Comment by joshtynjala** [comment]
Scaling is the intended behavior.
