### ISSUE TITLE
Alert doesn't update layout when ImageLoader loads

### ISSUE THREAD

**Issue by kevinfoley** [BowlerHatLLC/feathers#1198]
When creating an Alert using Alert.show(), if an ImageLoader is provided as the icon, and the ImageLoader's source is a URL, the Alert's layout will not update when the ImageLoader loads.

    var imageLoader:ImageLoader = new ImageLoader();
    imageLoader.source = myURL;	
    var alert:Alert = Alert.show(message, title, new ListCollection([{label: "OK"}]), imageLoader, true, true);

**Comment by joshtynjala** [comment]
Thanks! It's probably not listening for the resize event. I'll get it fixed!

**Comment by kevinfoley** [comment]
Hi Josh,

This issue occurs again in Feathers 3.1.1. I believe ImageLoader is having exactly the same problem as before; it does not trigger a layout update when the image loads

**Comment by joshtynjala** [comment]
@kevinfoley Thanks! I can reproduce with Feathers 3.1.x. It appears to be working correctly with the latest Feathers 3.2 code on Github.
