### ISSUE TITLE
Add release dates to RELEASENOTES.md

### ISSUE THREAD

**Issue by kevinfoley** [BowlerHatLLC/feathers#1199]
This is a very minor concern, and I know you can find release dates at https://github.com/BowlerHatLLC/feathers/releases , but it would be nice to see them next to the headers in RELEASENOTES.MD. E.g.:

# 2.3.0 (in prerelease)
-Item 1
-Item 2

# 2.2.0 - August 11, 2015
-Item 1
-Item 2

**Comment by joshtynjala** [comment]
That's a good idea. I'll keep it in mind!

**Comment by kevinfoley** [comment]
Wow, that was a fast reply! Thanks Josh! :)
