### ISSUE TITLE
DateTimeSpinner: support background skin

### ISSUE THREAD

**Issue by harry248** [BowlerHatLLC/feathers#1203]
Setting the width of a DateTimeSpinner control just sets the width of the containing layout group and horizontally centers the control within. I would expect it to fill the whole layout group. Despite that - a wonderful new component!

**Comment by joshtynjala** [comment]
Based on many of the screenshots I was looking at, I think that the UIDatePicker in iOS centers the lists when the width is very large. I tried to copy that behavior. Here's an example:

![wide-uidatepicker](https://cloud.githubusercontent.com/assets/141885/10023992/d913d384-6109-11e5-8818-09aca76a0394.jpg)

I notice that I didn't give DateTimeSpinner a background skin. That's something that I should add.

**Comment by harry248** [comment]
That may be right but I think it would still be a nice addition to have it distribute the list widths, just for custom ui's.
