### ISSUE TITLE
SimpleScrollBar: respect SCROLL_POLICY_ON

### ISSUE THREAD

**Issue by gene-pavlovsky** [BowlerHatLLC/feathers#1208]
It appears that SimpleScrollBar doesn't respect scrollPolicy value of SCROLL_POLICY_ON. The scroll bar (the thumb) becomes visible only when maxScrollPosition is greater than zero (i.e. content is larger than viewport).
Expected behaivor: SimpleScrollBar's thumb should be always visible (and auto-size to the maximum width) if scrollPolicy is SCROLL_POLICY_ON. Only when scrollPolicy is SCROLL_POLICY_AUTO, should the scroll bar's thumb be hidden if maxScrollPosition is 0.

**Comment by joshtynjala** [comment]
When I was implementing this, I determined that showing the scroll bar when the maxScrollPosition is 0 does not match the behavior of native scroll bars that are similar to SimpleScrollBar.

Additionally, when a ScrollBar is used with SCROLL_POLICY_ON and the maxScrollPosition is 0, the thumb is hidden, and only the track is visible. That's another reason why hiding the thumb is the correct behavior.

**Comment by gene-pavlovsky** [comment]
Ok it makes sense. So if I want the always-visible behavior, I should implement another ScrollBar (perhaps extending SimpleScrollBar), with a track skin.

**Comment by joshtynjala** [comment]
Yes, that's a great way to get the behavior that you want.
