### ISSUE TITLE
Scroller should have a horizontalScrollBarPosition property (top or bottom)

### ISSUE THREAD

**Issue by gene-pavlovsky** [BowlerHatLLC/feathers#1209]
Scroller has a verticalScrollBarPosition property that allows the vertical scroll bar to be located on the left/right side of the container. It makes as much sense to also provide a horizontalScrollBarPosition property, allowing the horizontal scroll bar to be located on the top/bottom side of the container.

**Comment by joshtynjala** [comment]
Indeed, it does make sense. So far, no one has asked for it, so it hasn't had a high priority compared to other potential new features.

**Comment by joshtynjala** [comment]
Closed in #1507

**Comment by gene-pavlovsky** [comment]
Thanks Josh
