### ISSUE TITLE
PopUpManager.popups

### ISSUE THREAD

**Issue by manofspirit** [BowlerHatLLC/feathers#1211]
should return all the opened popups so we can do tasks such as
- close all the popups
- etc

**Comment by joshtynjala** [comment]
PopUpManager.root may be useful here. If you pass your own Sprite to PopUpManager.root, you may be able to simply call PopUpManager.root.removeChildren() to remove all pop-ups.

**Comment by manofspirit** [comment]
what i currently need is know whether there are any popups or not, this way i can hide classic flash content which always appear over popups. 

if(PopupManager.popups.length > 0)
hideFlashContent

**Comment by joshtynjala** [comment]
Here's one way that you can provide your own value for PopUpManager.root:

	var popUpRoot:Sprite = new Sprite();
	Starling.current.stage.addChild(popUpRoot);
	PopUpManager.root = popUpRoot

Then, you can check if the value of numChildren is greater than 0.

	if(PopUpManager.root.numChildren > 0)
	{
		//hide flash content
	}

**Comment by joshtynjala** [comment]
Cleaning up as duplicate of #794
