### ISSUE TITLE
Reusing a Callout with one label: label's width get stuck and doesn't update.

### ISSUE THREAD

**Issue by gene-pavlovsky** [BowlerHatLLC/feathers#1213]
I'm displaying error messages using a Callout with a Label. I'm reusing the same Label and Callout to avoid creating new objects. The simplified code:
```actionscript
		private var callout:Callout;
		private var label:Label;
		
		private function showCallout(message:String, origin:DisplayObject):void {
			if (!callout) {
				label = new Label();
				callout = Callout.show(label, origin, Callout.DIRECTION_DOWN, false);
				callout.disposeOnSelfClose = false;
			}
			else {
				callout.origin = origin;
				PopUpManager.addPopUp(callout, false, false);
			}
			label.text = message;
		}
```
When the first (short) error message is displayed, everything looks good, label and callout are sized appropriately for the text.
Showing some more (short) messages also doesn't make a problem.
But after I show a long message (wide enough that the text gets truncated or wrapped - I tried with wordWrap on and off), the label and the callout become as wide as the stage allows, and they get stuck in that state. Showing a subsequent (short) message doesn't shrink them back to size appropriate for the text.
I've found a workaround, which is setting ``label.maxWidth`` to ``stage.stageWidth - callout.paddingLeft - callout.paddingRight``. If I do that, the label and callout are sized appropriately.
The problem seems to be in the Label - I've tried reusing the Label but creating a new Callout every time, but this doesn't help. Initially I did ``label.text = message`` before showing the callout, after I moved it after showing the callout, the problem seems to be fixed, but for some reason it's happening again. However it might be not just Label's fault. If I show the label by adding it as a child to my UI, then removing after user interaction, there is no misbehavior with sizing.

![callout_1](https://cloud.githubusercontent.com/assets/2841193/10147753/21d7484e-665a-11e5-99b2-c5e10bfe6634.png)
![callout_2](https://cloud.githubusercontent.com/assets/2841193/10147755/21e140ec-665a-11e5-8212-bb3febd2f4ed.png)
![callout_3](https://cloud.githubusercontent.com/assets/2841193/10147754/21dda996-665a-11e5-96cc-71001b8f292b.png)

**Comment by joshtynjala** [comment]
> But after I show a long message (wide enough that the text gets truncated or wrapped - I tried with wordWrap on and off), the label and the callout become as wide as the stage allows, and they get stuck in that state.

This is the important part about this issue. Once the Callout has reached a maximum width, it will need to set the width property of its content. When that happens, the content will no longer be able to automatically resize itself. If you want to be sure that the content resizes, you need to tell the content to auto-size again.

Setting `label.width = NaN` should do the trick.

**Comment by gene-pavlovsky** [comment]
So it's not a bug?
``label.width = NaN`` is only half helpful.
If I do this every time I set the label text, the screenshot #3 looks same as screenshot #1, however screenshot #2 still looks same (label's width = max possible width, too wide for the wrapped text in question). So how do I make the label's width shrink back to become appropriate for the wrapped text. I suppose the Callout doesn't know how the text will wrap, so it sets the width property of the label, then after the text finishes rendering and wraps, the width should be updated again somehow.
So far only setting ``label.maxWidth = stage.stageWidth-2*callout.padding`` makes the label correctly size with any length of text.

**Comment by joshtynjala** [comment]
No, it's not a bug. That's how Callout is intended to behave when its content needs to be resized to fit.

Screenshot 2 looks like a separate bug, actually. It appears that the text renderer measures itself differently than it renders. To me, it looks the text renderer is reporting a width as if the word "arguments" should appear on the first line. However, when the text actually gets rendered, the inaccuracy of floating point math is causing the width of the first line to appear larger than when it was originally measured, and then the word "arguments" gets incorrectly moved to the second line.

The tricky part is figuring out where exactly the floating point math is introducing a small error. In other words, where it's reporting a value like 100.0000000001 instead of 100. I have ways of working around these edge cases, so it's just a matter of finding where it happens. Which text renderer are you using? What is the name of the font and the size? This info may help me reproduce the issue on my computer.

**Comment by gene-pavlovsky** [comment]
Can a small FP error give so big difference in how it looks?
DeviceCapabilities.dpi = 125
Starling.contentScaleFactor = 1
scaledDPI = 125
_originalDPI = 264
scale = 0.4734848484848485
Font is DejaVuSansMono, 11 (Math.round(24 * scale))
Using TextBlockTextRenderer.
My SWF size is set to 306x544. Callout padding is 5, stagePadding = 0. If I set label.maxWidth = 296 (or smaller), the problem doesn't occur.

Appreciate you investigating this, Josh! Let me know if you need more info.

**Comment by joshtynjala** [comment]
It actually wasn't a floating point error. It simply looked that way in the screenshot by coincidence.

I was able to adjust how Callout manages the dimensions of its content. It makes use of minWidth/maxWidth more often, so this should limit the case where the content's width needs to be set to a fixed value by the Callout.

**Comment by gene-pavlovsky** [comment]
Josh, I've just tried the Callout from your commit, still experiencing same behavior as before...

**Comment by joshtynjala** [comment]
Actually, no need to dig deeper. I see where I didn't account for the stage dimensions in this fix.

**Comment by joshtynjala** [comment]
Okay, now the latest code should fix the issue in screenshot 2.

**Comment by gene-pavlovsky** [comment]
It does indeed seem to be fixed! Thanks, Josh.
