### ISSUE TITLE
Memory leaks: forgot to removeEventListener on many classes

### ISSUE THREAD

**Issue by khoamoc** [BowlerHatLLC/feathers#1215]
It took me the whole morning to figured out these, you forgot to removeEventListener on these classes.
It seems like you ALWAYS forget to removeEventListener(Event.ADDED_TO_STAGE and removeEventListener(Event.REMOVED_FROM_STAGE, in EVERY classes, please check other classes too, there must be many Listener that still not removed, and they're the root of memory leaks.
can't believe they exist for such a long time :)

------------------------------------

Class BaseDefaultItemRenderer:
			this.removeEventListener(Event.TRIGGERED, itemRenderer_triggeredHandler);

Class Button:
			this.removeEventListener(TouchEvent.TOUCH, button_touchHandler);
			this.removeEventListener(Event.REMOVED_FROM_STAGE, button_removedFromStageHandler);
	
			
Class FeathersControl:	
			this.removeEventListener(Event.ADDED_TO_STAGE, feathersControl_addedToStageHandler);
			this.removeEventListener(Event.REMOVED_FROM_STAGE, feathersControl_removedFromStageHandler);
			this.removeEventListener(Event.FLATTEN, feathersControl_flattenHandler);
			this._styleNameList.removeEventListener(Event.CHANGE, styleNameList_changeHandler);

Class Drawers	
			this.removeEventListener(Event.ADDED_TO_STAGE, drawers_addedToStageHandler);
			this.removeEventListener(Event.REMOVED_FROM_STAGE, drawers_removedFromStageHandler);
			this.removeEventListener(TouchEvent.TOUCH, drawers_touchHandler);
			this._topDrawer.removeEventListener(FeathersEventType.RESIZE, drawer_resizeHandler);
			this._rightDrawer.removeEventListener(FeathersEventType.RESIZE, drawer_resizeHandler);
			this._bottomDrawer.removeEventListener(FeathersEventType.RESIZE, drawer_resizeHandler);
			this._leftDrawer.removeEventListener(FeathersEventType.RESIZE, drawer_resizeHandler);
			Starling.current.nativeStage.removeEventListener(KeyboardEvent.KEY_DOWN, drawers_nativeStage_keyDownHandler);

Class TextInput
			this.removeEventListener(TouchEvent.TOUCH, textInput_touchHandler);
			this.removeEventListener(Event.REMOVED_FROM_STAGE, textInput_removedFromStageHandler);
			
Class TabBar
			this.toggleGroup.removeEventListener(Event.CHANGE, toggleGroup_changeHandler);
			
Class StackScreenNavigator
			this.removeEventListener(FeathersEventType.INITIALIZE, stackScreenNavigator_initializeHandler);

			
Class BaseScreenNavigator
			this.addEventListener(Event.ADDED_TO_STAGE, screenNavigator_addedToStageHandler);
			this.addEventListener(Event.REMOVED_FROM_STAGE, screenNavigator_removedFromStageHandler);

Class SimpleScrollBar
			this.removeEventListener(Event.REMOVED_FROM_STAGE, removedFromStageHandler);
			this.track.removeEventListener(TouchEvent.TOUCH, track_touchHandler);
			this._repeatTimer.removeEventListener(TimerEvent.TIMER, repeatTimer_timerHandler);
			this.thumb.removeEventListener(TouchEvent.TOUCH, thumb_touchHandler);
				
Class Scroller
			this.removeEventListener(Event.ADDED_TO_STAGE, scroller_addedToStageHandler);
			this.removeEventListener(Event.REMOVED_FROM_STAGE, scroller_removedFromStageHandler);

Class ScrollBar
			this.removeEventListener(Event.REMOVED_FROM_STAGE, removedFromStageHandler);
			this.thumb.removeEventListener(TouchEvent.TOUCH, thumb_touchHandler);
			this.minimumTrack.removeEventListener(TouchEvent.TOUCH, track_touchHandler);
			this.maximumTrack.removeEventListener(TouchEvent.TOUCH, track_touchHandler);
			this.decrementButton.removeEventListener(TouchEvent.TOUCH, decrementButton_touchHandler);
			this.incrementButton.removeEventListener(TouchEvent.TOUCH, incrementButton_touchHandler);
			this._repeatTimer.removeEventListener(TimerEvent.TIMER, repeatTimer_timerHandler);
				
Class Screen
			this.removeEventListener(Event.ADDED_TO_STAGE, screen_addedToStageHandler);
							
Class LayoutGroup
				this.removeEventListener(Event.ADDED_TO_STAGE, layoutGroup_addedToStageHandler);
				this.removeEventListener(Event.REMOVED_FROM_STAGE, layoutGroup_removedFromStageHandler);

**Comment by joshtynjala** [comment]
I'm afraid that you are mistaken. The added listeners are functions defined on the same objects that are dispatching the events. An object that references itself cannot cause a memory leak. This is one situation where removing an event listener is not required.

Regardless, when a Starling display object is disposed, all of its event listeners are automatically removed. If I were required to remove these listeners, Starling would handle it for me, so I still wouldn't need to call removeEventListener() manually.

I appreciate the effort you put in to track all of these down. I'm sorry it wasn't actually required, but at least you learned something new!
