### ISSUE TITLE
ButtonGroup with VerticalLayout ignores the distributeButtonSizes property

### ISSUE THREAD

**Issue by Klug76** [BowlerHatLLC/feathers#1217]
ButtonGroup with VerticalLayout now ignores the distributeButtonSizes property - why? Accroding to the source code (ButtonGroup.as), this line has changed: ```this.verticalLayout.distributeHeights = this._distributeButtonSizes;``` => ```verticalLayout.distributeHeights = true;```.

**Comment by joshtynjala** [comment]
This appears to be a mistake. It should be the HorizontalLayout where it's always set to true.

**Comment by Klug76** [comment]
I do not understand why it is necessary to remove this option for HorizontalLayout - everything runs good with it in both layouts in the version 2.2? Now toolbars in my app looks ugly :(

**Comment by joshtynjala** [comment]
It's not being removed. When distributeButtonSizes is set to false, and the direction is horizontal, FlowLayout is used instead. This allows the buttons to appear on multiple lines.
