### ISSUE TITLE
Themes that embed their assets should dispatch COMPLETE on the next frame

### ISSUE THREAD

**Issue by gene-pavlovsky** [BowlerHatLLC/feathers#1218]
This is the MetalWorksMobileTheme constructor:
```actionscript
		public function MetalWorksMobileTheme(scaleToDPI:Boolean = true)
		{
			super(scaleToDPI);
			this.initialize();
			this.dispatchEventWith(Event.COMPLETE);
		}
```

This is my application code
```actionscript
		public static var theme:MetalWorksMobileThemeBase();
		
		private function initView():void {
			theme = new MetalWorksMobileTheme();
			//theme = new MetalWorksMobileThemeWithAssetManager();
			theme.addEventListener(Event.COMPLETE, onThemeInit);
			theme.load();
		}
		
		private function onThemeInit():void {
			// Create the UI controls.
			...
		}
```

This code will work with MetalWorksMobileThemeWithAssetManager but not with MetalWorksMobileTheme since ``theme.addEventListener()`` code runs after the ``COMPLETE`` event has already been dispatched right in the theme's constructor.
I think dispatching the COMPLETE event should be delayed.
This way the same application code can be used whether the used theme embeds assets or loads them dynamically (e.g. theme with an AssetManager).
I think it's the best solution would be to add a ``public load()`` method to the theme's base class that must be called by the app to initialize / load the theme.
Alternatively, a theme could use a ``Timer`` or an ``ENTER_FRAME`` handler to delay dispatching the event.

```actionscript
		public function MetalWorksMobileTheme(scaleToDPI:Boolean = true)
		{
			super(scaleToDPI);
		}
			
		// Defined in MetalWorksMobileThemeBase as an empty method.
		override public function load():void {
			this.initialize();
			this.dispatchEventWith(Event.COMPLETE);
		}
```

**Comment by joshtynjala** [comment]
I've been meaning to remove the event entirely on themes with embedded assets. It just hasn't been a priority.

**Comment by joshtynjala** [comment]
I should add that I recently added the IThemeWithAssetManager interface, so it's easy to detect if a theme will dispatch Event.COMPLETE or not. However, I'm considering giving it a more generic name so that it can apply to any theme that loads its assets asynchronously (not only with AssetManager).

**Comment by gene-pavlovsky** [comment]
I actually saw that interface. Well it's up to you, I've added my own base class for themes, which keeps some of the common functionality to reduce boilerplate code in the actual theme, with a load() method that is responsible for dispatching Event.COMPLETE.

**Comment by gene-pavlovsky** [comment]
New name is much better!
