### ISSUE TITLE
ImageLoader: Texture will not be disposed for ImageLoader in master branch

### ISSUE THREAD

**Issue by rozd** [BowlerHatLLC/feathers#1224]
It seems that in current (master branch) implementation ImageLoader will never dispose texture loaded by nested loader. As I can see the _isTextureOwner flag will be always false in cleanupTexture() method, due to it is resetting in source setter.

**Comment by joshtynjala** [comment]
Ah yes, I see that if a second image has different dimensions, the original texture doesn't get disposed. Good find. Thanks!
