### ISSUE TITLE
Picker List dont dispath Event.CHANGE

### ISSUE THREAD

**Issue by alevys** [BowlerHatLLC/feathers#1228]
Hi!
PickerList dont dispath Event.CHANGE

**Comment by joshtynjala** [comment]
I cannot reproduce this issue. It is working correctly for me. Please note that if you're using the new BottomDrawerPopUpContentManager that will be available in Feathers 2.3, it will not dispatch Event.CHANGE until you close the pop-up list.

If that's not it, can you share some code that reproduces the issue?
