### ISSUE TITLE
Drawer can't be dragged by touching on it

### ISSUE THREAD

**Issue by harry248** [BowlerHatLLC/feathers#1233]
On Android a drawer can be dragged by touching on the the drawer itself. In feathers you can only drag the drawer by touching outside of it. Would be nice if the Android behaviour could be reflected.

**Comment by joshtynjala** [comment]
This wouldn't have made sense when the content was moved and the drawer remained stationary, but now that the drawers can appear as an overlay, I agree. Thanks for pointing this out!
