### ISSUE TITLE
using AddOnFunctionStyleProvider skin button not effect !

### ISSUE THREAD

**Issue by foodyi** [BowlerHatLLC/feathers#1237]
```		
            new MinimalMobileTheme();
			function setExtraStyles(button:Button):void{
				button.defaultIcon = new Quad(10,10,0xff0000);
				button.upSkin = new Quad(100,30,0xff00ff);
				button.downSkin = new Quad(100,30,0xffff00);
				trace(button.downSkin);
			};
			
			var button:Button = new Button();
			button.styleProvider = new AddOnFunctionStyleProvider(button.styleProvider,setExtraStyles);
			button.label = "Click me";
			button.x = 200;
			button.y = 150;
			this.addChild(button);
```

setExtraStyles is triggered , and button's defaultIcon is added to button, but upSkin and downSkin are still default style , as i know, AddOnFunctionStyleProvider will apply theme style to button,then run setExtraStyles function to apply new style instead old one, but it is not work.

**Comment by joshtynjala** [comment]
The theme sets the Button's [stateToSkinFunction](http://feathersui.com/api-reference/feathers/controls/Button.html#stateToSkinFunction) property. This takes precedence over upSkin and downSkin. You should be able to set stateToSkinFunction to null.
