### ISSUE TITLE
ScrollBar: Hide tracks when nothing to scroll

### ISSUE THREAD

**Issue by sjabberwocky** [BowlerHatLLC/feathers#1240]
In current implementation of scrollbar it hides only thumb, increment and decrement buttons and track bars when nothing to scroll without those buttons and its looks ugly.

**Comment by joshtynjala** [comment]
You can use SCROLL_POLICY_AUTO instead of SCROLL_POLICY_ON to hide the scroll bar when there's nothing to scroll.
