### ISSUE TITLE
AnchorLayout: label with word wrap does not measure properly

### ISSUE THREAD

**Issue by joshtynjala** [BowlerHatLLC/feathers#1242]
See forum thread: http://forum.starling-framework.org/topic/anchor-layout-wrapped-text-padding

Code to reproduce:

	var group:LayoutGroup = new LayoutGroup();
	group.width = 200;
	group.layout = new AnchorLayout();
	this.addChild(group);

	var label1:Label = new Label();
	label1.name = "one";
	label1.wordWrap = true;
	label1.text = "TextboxTwo";
	label1.layoutData = new AnchorLayoutData(10, 10, NaN, 10);
	group.addChild(label1);

	var label2:Label = new Label();
	label2.name = "two";
	label2.wordWrap = true;
	label2.text = "In diam orci, molestie eget lacus id, finibus vestibulum lectus. Etiam commodo massa nec erat gravida fermentum.";
	var labelLayoutData:AnchorLayoutData = new AnchorLayoutData(10, 10, 10, 10);
	labelLayoutData.topAnchorDisplayObject = label1;
	label2.layoutData = labelLayoutData;
	group.addChild(label2)

**Comment by teotigraphix** [comment]
Man this is so weird, I had this same problem today using an anchor layout and a Label.

I pinned left and right and it still didn't work, so I ended up just setting a maxWidth for now.
