### ISSUE TITLE
TextFieldTextRenderer gutter size

### ISSUE THREAD

**Issue by SamYStudiO** [BowlerHatLLC/feathers#1245]
Hi Josh,

I still sometimes get invisible last line from multiline text (i guess depending on typo used), even when using "useGutter" from TextFieldTextRenderer. In most cases making gutter size to 5 or 6 instead of 4 fix the problem.
What do you think about adding a gutterSize property along with useGutter?

Thx

**Comment by joshtynjala** [comment]
If setting useGutter to true doesn't work, then it's an issue of flash.text.TextField reporting the wrong dimensions for its text. Increasing the gutter size, unfortunately, isn't a good solution. A TextField's built-in gutter does not change size. Making this value configurable might provide a hacky workaround for some cases, but it will also lead to wildly incorrect results in many cases. It will cause wrapped text to start breaking at different words, which means that the text will have a different number of lines for measurement and rendering, and you'll have an even bigger problem.

Can you try setting useSnapshotDelayWorkaround to true? This often fixes the issue when TextField gives us the wrong width and height.
