### ISSUE TITLE
Scrolltext ignores leading

### ISSUE THREAD

**Issue by MatthewVisser** [BowlerHatLLC/feathers#1248]
When I create a scroll text and set its formating via _scrolltext.textFormat = _textFormat. It ignores the leading property. It always ends up as zero.

**Comment by joshtynjala** [comment]
I cannot reproduce this issue. The leading property of the TextFormat seems to be working as expected.

However, if you're using a theme, and you're trying to set the textFormat property outside of the theme, you should be sure to use an AddOnFunctionStyleProvider or to create a new style name for ScrollText. If the theme is also trying to set the textFormat property, you may have a conflict, and the theme will take precedence.

[Introduction to Feathers themes](http://feathersui.com/help/themes.html) gives an example of using AddOnFunctionStyleProvider and [Extending Feathers themes](http://feathersui.com/help/extending-themes.html) explains how to create a new style name.
