### ISSUE TITLE
Drawers not animating properly when closing in OPEN_MODE_ABOVE

### ISSUE THREAD

**Issue by izzmeifter** [BowlerHatLLC/feathers#1249]
I have a DrawersApplication. When using Drawers.OPEN_MODE_BELOW everything works as expected, but when switching to OPEN_MODE_ABOVE calling toggleXXXDrawer, the drawer animates properly when opening, but when closing it ignores the animation and just closes immediately.

I should note, It does however close properly when clicking outside the drawer.

**Comment by joshtynjala** [comment]
It should be fixed now. Thanks!
