### ISSUE TITLE
TabBar isEnabled weirdness

### ISSUE THREAD

**Issue by teotigraphix** [BowlerHatLLC/feathers#1252]
I am trying to set the isEnabled of theTabBar and it seems that if you don't have isEnabled in the dataProvider, once set to false, you cannot re-enable the TabBar with tabBar.isEnabled = true.

It seems this code;

```
protected function commitEnabled():void
{
	for each(var tab:ToggleButton in this.activeTabs)
	{
		tab.isEnabled &&= this._isEnabled;
	}
}
```

Is causing the problem, specifically &&=, I honestly don't get what that is doing but you should check whether the dataProvider item actually contains isEnabled or this code is a bug IMO.

Let me know if I am seeing it wrong.

**Comment by joshtynjala** [comment]
The issue can be easily reproduced with the following code:

	var tabs:TabBar = new TabBar();
	tabs.dataProvider = new ListCollection(
	[
		{ label: "Test" },
		{ label: "Two", isEnabled: false },
		{ label: "Three", isEnabled: true },
	]);
	this.addChild(tabs);
	tabs.isEnabled = false;
	tabs.validate();
	tabs.isEnabled = true;

I think I have it fixed properly locally, and I'm working on some unit tests.

**Comment by teotigraphix** [comment]
Nice, was it the operator?

**Comment by joshtynjala** [comment]
Not exactly. That part isn't changed. It was that the isEnabled value wasn't always set to the proper value before that operator was used.

**Comment by izzmeifter** [comment]
Currently having this exact problem with SDK 2.3.

Tried calling isEnabled a few times, as well as adding in some validation. Nothing seems to bring it back to being enabled.

**Comment by joshtynjala** [comment]
Yes, this issue was probably present in 2.3 too.

**Comment by izzmeifter** [comment]
Sorry, just noticed the fix was applied to 3. Haven't been able to update as were locked down for a launch but will as soon as we launch. Thanks Josh.
