### ISSUE TITLE
flattening Label with nativeFilter / DropShadowFilter changes label position

### ISSUE THREAD

**Issue by skizzo** [BowlerHatLLC/feathers#1254]
When calling the **flatten()** function on a _DisplayObjectContainer_ that contains a _Label_ with a _nativeFilter_ (_DropShadowFilter_) added to its _TextFieldTextRenderer_, the Label is offset (only on its x-axis) by the amount of pixels that have been specified as the _DropShadowFilter_'s blur radius. 

[Here's an example.](http://imgur.com/hTbh0zC)

**Steps to reproduce**:
1. create DisplayObjectContainer
2. create Label with DropShadowFilter as a nativeFilter, blurX / blurY > 0
3, add Label to DisplayObjectContainer
4. flatten DisplayObjectContainer

**Comment by joshtynjala** [comment]
Thank you. I can reproduce the issue with the following code:

	new AeonDesktopTheme();
	
	var container:Sprite = new Sprite();
	this.addChild(container);
	var label:Label = new Label();
	label.text = "Hello World";
	label.textRendererProperties.nativeFilters = [new DropShadowFilter(0, 45, 0xffffff, 1, 50, 50, 5)];
	container.addChild(label);
	container.flatten();
	
	var container2:Sprite = new Sprite();
	this.addChild(container2);
	var label2:Label = new Label();
	label2.text = "Hello World";
	label2.textRendererProperties.nativeFilters = [new DropShadowFilter(0, 45, 0xffffff, 1, 50, 50, 5)];
	container2.addChild(label2);
