### ISSUE TITLE
Scroller: null object reference error in nativeStage_mouseWheelHandler()

### ISSUE THREAD

**Issue by andrewmillion** [BowlerHatLLC/feathers#1256]
Sometimes I get this error:

> TypeError: Error #1009: Cannot access a property or method of a null object reference.
	> at feathers.controls::Scroller/nativeStage_mouseWheelHandler()[game/src/feathers/controls/Scroller.as:5603]

```actionscript
 if(this.contains(this.stage.hitTest(HELPER_POINT, true)))
```

It can be fixed like this - 

```actionscript
if (this.stage != null)
    if(this.contains(this.stage.hitTest(HELPER_POINT, true)))
```

Fix it please. Thanks

**Comment by joshtynjala** [comment]
The nativeStage_mouseWheelHandler listener is removed in Event.REMOVED_FROM_STAGE. It shouldn't be possible for stage to be null there. Checking if it's null is only a workaround, and I'd rather focus on the underlying cause.

In the Event.REMOVED_FROM_STAGE listener, the mouse wheel listener is removed Starling.current.nativeStage. Do you have multiple Starling instances? That might explain why the listener wasn't removed properly before the stage was set to null...
