### ISSUE TITLE
SpinnerList clips repeated children to the left

### ISSUE THREAD

**Issue by psmtec-dklein** [BowlerHatLLC/feathers#1257]
Hello, i experience a child clipping issue with a horizontal spinnerlist.

It's a simple setup, 5 items using the default itemrenderer and a custom display object in the icon field.
When i scroll to the right it works ok until the "9th" element.
When "10" becomes the selected one, "9" is clipped before it completely leaves the screen to the left. It seems to happen when the itemrenderer (1) for "9" leaves the area of the selected item (2).

![image](https://cloud.githubusercontent.com/assets/6904909/11588614/3ef86e60-9a82-11e5-85d3-fff14f768cae.png)

This is a simple example that reproduces it (using the MetalWorksMobileTheme).
I experience this issue in Feathers 2.2 and 2.3-beta.

```
		private function createChildren() : void {
			var hsl : HorizontalSpinnerLayout = new HorizontalSpinnerLayout();
			hsl.verticalAlign = HorizontalSpinnerLayout.VERTICAL_ALIGN_JUSTIFY;
			hsl.gap = 64;
			hsl.paddingBottom = 128;

			var sl : SpinnerList = new SpinnerList();
			sl.layout = hsl;
			sl.width = stage.stageWidth;
			sl.height = stage.stageHeight;
			sl.dataProvider = new ListCollection();
			sl.itemRendererProperties.itemHasLabel = false;
			sl.itemRendererProperties.iconField = 'display';
			addChild(sl);

			for (var index : int = 0; index < 5; ++index) {
				var item : LayoutGroup = new LayoutGroup();
				item.width = 256;
				item.height = 256;
				item.backgroundSkin = new Quad(4, 4, 0xff0000);

				var itemData : Object = {
					display : item
				};

				sl.dataProvider.push(itemData);
			}

			var indexLabel : Label = new Label();
			addChild(indexLabel);

			sl.addEventListener(Event.CHANGE, function() : void {
				indexLabel.text = sl.horizontalPageIndex.toString();
			});
		}
```

**Comment by psmtec-dklein** [comment]
Update:

Clipping gets worse (meaning even earlier), the more often the items get repeated.
And i think it's the gap in the HorizontalSpinnerLayout that affects when items get clipped too early (+gapsize for every full repeat of the list), not the stuff in the picture i attached.

**Comment by joshtynjala** [comment]
It was easy to reproduce the issue with your code. Thank you!
