### ISSUE TITLE
StackScreenNavigator: support swipe to go back like iOS

### ISSUE THREAD

**Issue by joshtynjala** [BowlerHatLLC/feathers#1264]

**Comment by GV3** [comment]
BIG +1

**Comment by sdvarela** [comment]
+1 to this feature :+1:

**Comment by izzmeifter** [comment]
Agreed. +1

**Comment by mateo-kozomara** [comment]
+1 would be awesome to have this

**Comment by serjek** [comment]
oops, missed this one. vote for this. Referenced issue has a class extended to support this feature, as temporarily solution.

**Comment by GV3** [comment]
Any updates on this issue Josh?
Do you have it scheduled in a version already? :)

**Comment by joshtynjala** [comment]
I won't be planning future versions until after 3.0 is done.

**Comment by DerBensch** [comment]
+1 would be very useful

**Comment by subdan** [comment]
+1

**Comment by subdan** [comment]
I very want this feature.

**Comment by subdan** [comment]
I found a bug with transition when isSwipeToPopEnabled = true; If I swipe very fast (from left edge to left edge + 10-20px) transition stops and both screens is visible on the screen.
