### ISSUE TITLE
Callout arrowOffset does nothing

### ISSUE THREAD

**Issue by novacoder** [BowlerHatLLC/feathers#1265]
When I show Callout by this code 
callout = Callout.show(label, calloutOrigin, Callout.DIRECTION_UP, false);

Then change callout.arrayOffset - the collout's arrow doesn't change its position.

**Comment by joshtynjala** [comment]
Are you using a theme? Could it be that the theme is overriding the value?

**Comment by novacoder** [comment]
Yes, i set this parameter only in theme function. And it doesn't work.

пятница, 18 декабря 2015 г. пользователь Josh Tynjala написал:

**Comment by joshtynjala** [comment]
The documentation for [`arrowOffset`](http://feathersui.com/api-reference/feathers/controls/Callout.html#arrowOffset) notes that you should not use this property when using Callout.show():

> If you use `Callout.show()` or set the `origin` property manually, you should avoid manually modifying the `arrowPosition` and `arrowOffset` properties.

That's because the arrow offset is calculated automatically when the Callout is displayed with an origin.

This property is working as intended. What is it that you are trying to do?

**Comment by novacoder** [comment]
Thank you for clarification.

I need to do bubble as in attached screenshot

2015-12-18 21:17 GMT+02:00 Josh Tynjala <notifications@github.com>:

**Comment by joshtynjala** [comment]
There is no screenshot attached. I think you need to attach it on the Github website instead of through email.

**Comment by novacoder** [comment]
![screenshot_4](https://cloud.githubusercontent.com/assets/3682229/11906811/085d3dfc-a5d8-11e5-9a79-86e402610d31.png)

**Comment by joshtynjala** [comment]
You'll need to create the Callout using the constructor and new keyword instead of Callout.show(). Then, you'll need to manually add it to the display list (perhaps to the PopUpManager), and then position it yourself. If you do it this way, then arrowOffset can be customized.
