### ISSUE TITLE
Parameter typo error in TabBar documentation

### ISSUE THREAD

**Issue by berkayk** [BowlerHatLLC/feathers#1267]
Small typo error in TabBar documentation in **Skinning the Tabs** section [here](http://feathersui.com/help/tab-bar.html).

    getStyleProviderForClass( Button )
    .setFunctionForStyleName( setTabStyles, TabBar.DEFAULT_CHILD_STYLE_NAME_TAB ); 

should be

    getStyleProviderForClass( Button )
    .setFunctionForStyleName( TabBar.DEFAULT_CHILD_STYLE_NAME_TAB, setTabStyles );

**Comment by joshtynjala** [comment]
Thank you! I'll get it fixed.

**Comment by joshtynjala** [comment]
All fixed. Thanks again!
