### ISSUE TITLE
Feathers 3.0 Migration Guide

### ISSUE THREAD

**Issue by joshtynjala** [BowlerHatLLC/feathers#1268]
The [Feathers 3.0 Migration Guide](http://feathersui.com/help/migration-guide-3.0.html) is now available.

**Comment by GV3** [comment]
Could you write an example of what is now the best approach to use instead of "selectedUpLabelProperties", and the others?
Thank you in forward

**Comment by joshtynjala** [comment]
The text renderers have functions that let you set different font styles for each state. For instance, TextBlockTextRenderer has [setElementFormatForState()](http://feathersui.com/api-reference/feathers/controls/text/TextBlockTextRenderer.html#setElementFormatForState()). Here's one way that you might use it:

button.labelFactory = function():ITextRenderer
{
	var textRenderer:TextBlockTextRenderer = new TextBlockTextRenderer();
	textRenderer.styleProvider = null;
	textRenderer.elementFormat = defaultFormat;
	textRenderer.setElementFormatForState(ButtonState.SELECTED_UP, selectedUpFormat);
	return textRenderer;
};

If you want to do it inside a theme, you could target the Button.DEFAULT_CHILD_STYLE_NAME_LABEL style name instead, or set a customLabelStyleName.

Feel free to look at the example themes for more code samples. You may not have realized, but the example themes in Feathers 2.3 were actually already migrated to this new technique.
