### ISSUE TITLE
FlowLayout includeInLayout problem

### ISSUE THREAD

**Issue by teotigraphix** [BowlerHatLLC/feathers#1270]
I have a container that uses a FlowLayout, after all the children are created in my mediator I set the first child's includeInLayout and visible to false.

The problem is I would expect this to automatically call invalidate size and layout but the child is hidden and the second child resides as if the first child is still in the layout.

```
<f:LayoutGroup xmlns:f="library://ns.feathersui.com/mxml"
               xmlns:fx="http://ns.adobe.com/mxml/2009"
               xmlns:common="tones.view.controls.common.*" 
               xmlns:controls="tones.view.controls.*">

    <f:layout>
        <f:FlowLayout rowVerticalAlign="middle"
                      gap="{ThemeProperties.gap}" padding="{ThemeProperties.padding}"/>
    </f:layout>

    <f:Button id="patternButton"
              triggered="dispatchEventWith(EVENT_PATTERN_TRIGGER)"/>
```

After creationComplete (actually during the event).
`
control.patternButton.visible = control.includeInLayout = false;
`

Where control is patternButton.

**Comment by teotigraphix** [comment]
Ah damn, scratch this. HAHA OMG I just noticed my bug when reading this, control is the LayoutGroup so I had a bug and I am not actually setting patternButton's includeInLayout. 

To many things going on. :) NOT A BUG.

**Comment by joshtynjala** [comment]
It's always after you ask someone else that you suddenly realize something that you missed before! :smile:
