### ISSUE TITLE
DateTimeSpinner: runtime error when changing minimum property

### ISSUE THREAD

**Issue by joshtynjala** [BowlerHatLLC/feathers#1273]
See forum thread: http://forum.starling-framework.org/topic/datetimespinner-error

**Comment by joshtynjala** [comment]
The following code will reproduce the issue.

	var dateSpinner:DateTimeSpinner = new DateTimeSpinner();
	this.addChild(dateSpinner);
	dateSpinner.editingMode = DateTimeSpinner.EDITING_MODE_DATE;
	var today:Date = new Date();
	dateSpinner.minimum = new Date(1960, 0, 1);
	dateSpinner.maximum = new Date(today.fullYear + 5, 0, 1);
	dateSpinner.value = today;
	dateSpinner.validate();
	
	var now:Date = new Date();
	dateSpinner.value = now;
	dateSpinner.minimum = new Date(now.fullYear, now.month - 3, 1);

**Comment by ryanphonefusion** [comment]
Hey with a little more testing... you can actually replicate the bug by changing that second part to be like this....

var now:Date = new Date();
dateSpinner.value = now;
dateSpinner.minimum = null;
