### ISSUE TITLE
Tree Control

### ISSUE THREAD

**Issue by manofspirit** [BowlerHatLLC/feathers#1276]
A tree control with customizable collapse/expand icons'd be really helpful for business app development.

**Comment by aammfe** [comment]
@Josh, Any  near future plans for a Tree Control? If not, then can you suggest how should i proceed with a custom implementation of a tree control

**Comment by joshtynjala** [comment]
No plans near term. You'll probably want to use HierarchicalCollection. You might be able to reuse code from List and ListDataViewPort, if you want to implement it properly. However, there's a lot going on in those classes, and you may not want to take on the complexity. A simpler implementation without all the bells and whistles like layout virtualization may be good enough.
