### ISSUE TITLE
BitmapFontTextRenderer doesn't take into account BitmapFont's offsetX and offsetY property

### ISSUE THREAD

**Issue by generagames** [BowlerHatLLC/feathers#1277]
I've been recently working with Bitmap Fonts, using the source files generated by the indicated tools at "Displaying Text": http://wiki.starling-framework.org/manual/displaying_text , and I found that some fonts are exported with character offset errors.

This seems to be a common problem, as I can see in Starling's BitmapFont docs: http://doc.starling-framework.org/v1.7/starling/text/BitmapFont.html#offsetX a couple of properties offsetX and offsetY to fix these errors, but those params don't seem to be used in any place inside the BitmapFontTextRenderer.

I easily managed to include these params in the lines 1015 to 1028 (but I don't know if I did right, hehe)

> if(this._wordWrap || isAligned)
> {
> 	var charLocation:CharLocation = CHAR_LOCATION_POOL.length > 0 ? CHAR_LOCATION_POOL.shift() : new CharLocation();
> 	charLocation.char = charData;
> 	charLocation.x = currentX + (charData.xOffset + **font.offsetX**) * scale;
> 	charLocation.y = currentY + (charData.yOffset + **font.offsetY**) * scale;
> 	charLocation.scale = scale;
> 	CHARACTER_BUFFER[CHARACTER_BUFFER.length] = charLocation;
> 	wordLength++;
> }
> else
> {
> 	this.addCharacterToBatch(
> 		charData, 
> 		currentX + (charData.xOffset + **font.offsetX**) * scale, 
> 		currentY + (charData.yOffset + **font.offsetY**) * scale, 
> 		scale);
> }

I hope it helps, thanks.

**Comment by joshtynjala** [comment]
Could you share a font that requires these properties? It would help me confirm the fix. Thanks!

**Comment by generagames** [comment]
Sure Josh, here you go.
[EstoyBueno.zip](https://github.com/BowlerHatLLC/feathers/files/115894/EstoyBueno.zip)
![font_offset_export_error](https://cloud.githubusercontent.com/assets/12172835/12787281/1241be9c-ca95-11e5-9085-6df0133d6a23.jpg)

I encountered that issue using Littera ( http://kvazars.com/littera/ ) and setting the font size to 50 (but it seems it happens from 26 or so). I had then to adjust manually the font offsetY to -27.

**Comment by joshtynjala** [comment]
Thank you! I'll take a look.
