### ISSUE TITLE
StackScreenNavigator pushScreen

### ISSUE THREAD

**Issue by SamYStudiO** [BowlerHatLLC/feathers#1281]
Hi Josh,

Shouldn't pushScreenfrom  StackScreenNavigator  check if activescreen is the same than pushing screen to avoid stacking same screen multiple times? That check could be done when calling pushScreen but maybe this is ok do do it internally?

**Comment by joshtynjala** [comment]
Actually, I've found that there can be reasons to push the same screen multiple times. For example, in an app with user profiles, if you click on a user's friend's profile, it will be displayed with the same screen, but different data.

**Comment by SamYStudiO** [comment]
Indeed this may be usefull when using same screen and different data, didn't thought about that even i already did it ;)

**Comment by joshtynjala** [comment]
:laughing:
