### ISSUE TITLE
Binding problem in Flex Library project

### ISSUE THREAD

**Issue by BawarR** [BowlerHatLLC/feathers#1282]
After creation of ActionScript class with bindable property in mobile Flex Library Project, FlashBuilder  shows error "Unknown problem Unknown Flex Problem".

For mxml files (with bindable properties) everything works fine, library compiles without errors and binding works in app.

FeatherSDK 2.3.0 with AIR19

**Comment by joshtynjala** [comment]
Duplicate BowlerHatLLC/feathers-sdk#32
