### ISSUE TITLE
Text Missing line

### ISSUE THREAD

**Issue by SamYStudiO** [BowlerHatLLC/feathers#1284]
Hey Josh,

Sorry to bother you again with cutting text, i know this is really a TextField problem, but this is a recurring problem on each project for me, maybe we can discuss about it with a concrete example.
```
// Using TextFieldTextRenderer
var label : Label = new Label();
label.textRendererProperties.textFormat = new TextFormat( "Cerigo" , 12 , 0x000000 );
label.textRendererProperties.wordWrap = true;
label.textRendererProperties.embedFonts = true;
label.text = "CONDITIONS GENERALES D’UTILISATION";
label.width = 150;
addChild( label );
```
font : [Cerigo.zip](https://github.com/BowlerHatLLC/feathers/files/124520/Cerigo.zip)

Using this example if starling scaleFactor is 1 or 2 works fine but when scaleFactor is 1.5 last text line do not show up (testing on desktop with ADL).
First thing first can you reproduce it?

In most case when i got this pb this is a 1 or 2 pixels story that are missing from texfield height. So from TextfieldTextRenderer i often add a extra pixel from measure method result: 
```
result.y = newHeight + 1;
```
and in our example even rouding up does the trick: 
```
result.y = Math.ceil( newHeight );
```

I'm not sure this is the best place to patch it but maybe this example may help you find a nice workaround for those cutting problems ;)

Thanks!

**Comment by joshtynjala** [comment]
Duplicate #1253

I can reproduce the issue, and I plan to fix it by the time that Feathers 3.0 is released.
