### ISSUE TITLE
TiledRowsLayout, TiledColumnsLayout: properties to distribute tiles to full width and height

### ISSUE THREAD

**Issue by joshtynjala** [BowlerHatLLC/feathers#1285]
See thread: http://forum.starling-framework.org/topic/tilelayout-items-take-all-the-height-available

**Comment by SamYStudiO** [comment]
Hey Josh couldn't this be applied to vertical/horizontal layout as well? As we discussed here http://forum.starling-framework.org/topic/distribute-space-with-horizontal-layout

**Comment by joshtynjala** [comment]
Yes, distributing the gaps instead of the widths/heights could be an interesting feature on the tile layouts too.

**Comment by izzmeifter** [comment]
Agreed with adding to tile layouts :)

**Comment by manofspirit** [comment]
@joshtynjala any plans for 3.1?

**Comment by joshtynjala** [comment]
I'll see what I can do...

**Comment by manofspirit** [comment]
appreciate a lot 👍

**Comment by manofspirit** [comment]
i see distributeWidths in TiledRowsLayout but not distributeHeights.
what i want to do is provide fix number of columns that take distributed height and width, something like this
var listLayout:TiledRowsLayout = new TiledRowsLayout();
			listLayout.useSquareTiles = false;
			listLayout.requestedColumnCount = 7;
			listLayout.distributeWidths = true;
			listLayout.distributeHeights = true;

**Comment by joshtynjala** [comment]
There's a reason why this isn't closed yet. ;)

**Comment by manofspirit** [comment]
oh alright, ill wait for the update then :)
Thanks once.
