### ISSUE TITLE
List skining with itemRendererProperties

### ISSUE THREAD

**Issue by SamYStudiO** [BowlerHatLLC/feathers#1287]
Hi Josh,

i got weird behaviour skinning list component using this simple code (feathers 3.0)
```
var list : List = new List();
list.dataProvider = new ListCollection(new <String>
[
	"Apple",
	"Banana",
	"Cherry",
	"Grape",
	"Lemon",
	"Orange",
	"Watermelon"
]);
list.itemRendererProperties.defaultSkin = new Quad( 10 , 10, 0xff0000 );
list.setSize( 200 , 200 );
list.clipContent = true;
addChild( list );
```

Actually only last item from list got its red background (all other items have no background). This is same problem with other properties like defaultIcon, etc...
Additionnaly shouldn't clipContent mask items with elastic edge when dragging outside list boudingbox?

Thx

**Comment by joshtynjala** [comment]
A Quad cannot be added to more than one parent, so you must use itemRendererFactory or a theme if you want to pass skins to every item renderer.

**Comment by SamYStudiO** [comment]
my bad!
Thanks!
