### ISSUE TITLE
rounding problem in BitmapFontTextRenderer

### ISSUE THREAD

**Issue by nnukem** [BowlerHatLLC/feathers#1288]
In BitmapFontTextRenderer in function layoutCharacters on line ~ 1050 

```
if(this._wordWrap)
	{
	while(currentX > maxLineWidth)
	{
	        currentX -= maxLineWidth;
	        currentY += lineHeight;
    }
}
```
The condition in while loop sometimes is true because there is difference only on least significant number. Therefore positioning of BirmapFontTextRenderer in other components fails. I've fixed it temporarily by rounding currentX and maxLineWidth 

```
if(this._wordWrap)
			{
				var cx:int = Math.round(currentX)
				var mlw:int = Math.round(maxLineWidth)
				
				while(cx > mlw)
				{
					cx -= mlw;
					currentY += lineHeight;
				}
				
				currentX = cx
				
			}

```

**Comment by joshtynjala** [comment]
Thank you! Could you possibly share a font, and some code, that will reproduce this issue? It will be easier for me if I don't need to figure out how to reproduce it through trial and error. Thanks!

**Comment by nnukem** [comment]
I think i can prepare example and send it to you. I'll try tomorrow.
16 lut 2016 18:19 "Josh Tynjala" <notifications@github.com> napisał(a):

**Comment by nnukem** [comment]
Hi. Here is example of this bug.
[BitmapFontTextRendererBugExample.zip](https://github.com/BowlerHatLLC/feathers/files/134045/BitmapFontTextRendererBugExample.zip)
