### ISSUE TITLE
(ver. 3.0) LayoutGroup::backgroundSkin doesn't redraw when size changed

### ISSUE THREAD

**Issue by Klug76** [BowlerHatLLC/feathers#1289]
When changing the size of the container backgroundSkin is not redrawn. Code:
```
		private function test1(): void
		{
			var panel: LayoutGroup = new LayoutGroup();
			panel.backgroundSkin = new Quad(1, 1, 0x00ff00);
			panel.setSize(200, 200);
			addChild(panel);
			Starling.juggler.tween(panel, 5, { width: 300 } );
		}
```

**Comment by GV3** [comment]
Hi Josh,

I have a similar issue with a LayoutGroupListItemRenderer....

The ItemRenderer has a ToggleButton child which was working perfectly with ANY amount of items... until I migrated to Feathers 3.0... NOW... when I open the list with a different data, the background of some items is not resized properly... 

If the item is newly instantiated it works fine, the height of the item, the width, everything is as it should, EXCEPT the background of the ToggleButton, this correct itself only when draw() is called again.

I assume that the newly instantiated items are working perfectly, and the reused items are still using the background sized for the previous data.

Please let me know your thoughts on this.
