### ISSUE TITLE
Incompatibility after Starling commit  [a3d71b6], Lists behave oddly

### ISSUE THREAD

**Issue by GV3** [BowlerHatLLC/feathers#1292]
After pulling the newest Starling, with the latest Feathers, realized that the lists stop working properly.

I'm right now on this commits:

Feathers [a519208]
Starling[16f299]

If pulled the next Starling commit (Starling [a3d71b6]: now using the clipping (scissor) rectangle ....) the lists start behaving completely odd. The heights are wrong, the scrolling changes the height of the list, the positions are wrong... Masking or clipping are in general a disaster.

Please let me know if I am missing to migrate my code to be compatible after that Starling commit.

Thanks

G.V

**Comment by joshtynjala** [comment]
It sounds like there may be a bug in Daniel's new code. I'll take a look and report what I find to him.

**Comment by joshtynjala** [comment]
Opened Gamua/Starling-Framework#804

**Comment by joshtynjala** [comment]
Daniel has fixed the issue in Starling. Thank you for reporting it.
