### ISSUE TITLE
Header back button has a weird appearance

### ISSUE THREAD

**Issue by seyfullahbilgin** [BowlerHatLLC/feathers#1293]
var header:Header = new Header();
header.title = "I'm a header";
			
var backButton:Button = new Button();
backButton.label = "Back";
backButton.styleNameList.add( Button.ALTERNATE_STYLE_NAME_BACK_BUTTON );
		
header.leftItems = new <DisplayObject>[ backButton ];
header.width = 480;
header.height = 80;
this.addChild( header );

![image](https://cloud.githubusercontent.com/assets/7899713/13146252/7bcd5d48-d65d-11e5-80c5-7671a9b93cba.png)

Feathers 3.0 
Starling 2.0

**Comment by joshtynjala** [comment]
Is that the desktop or mobile version of the MetalWorks theme? Did you subclass it or make any other changes?

**Comment by seyfullahbilgin** [comment]
It is MetalWorks mobile theme and i didn't change anything.

**Comment by joshtynjala** [comment]
I cannot reproduce this issue. Something in your project may be out of date. Perhaps you forgot to update MetalWorksMobileTheme to the version from Feathers 3.0.

**Comment by seyfullahbilgin** [comment]
i have updated the feathers and starling source code from github just now.

![image](https://cloud.githubusercontent.com/assets/7899713/13179648/7bc178cc-d72d-11e5-98fe-928520816fe8.png)

Also i have tested with Minimal Mobile Theme but result was the same.

![image](https://cloud.githubusercontent.com/assets/7899713/13179760/00aecb84-d72e-11e5-871b-0e7b182be7f8.png)

Full source code:

```
package
{
	import flash.display.Sprite;
	import starling.core.Starling;
	
	public class Application extends Sprite
	{
		private var _starling:Starling;
	
		public function Application()
		{
			this._starling = new Starling(Main, this.stage);
			this._starling.start();
		}
	}
}



package
{
	import feathers.controls.Button;
	import feathers.controls.Header;
	import feathers.controls.Label;
	import feathers.themes.MetalWorksMobileThemeWithAssetManager;
	import feathers.themes.MinimalMobileThemeWithAssetManager;
	
	import flash.filesystem.File;
	
	import starling.display.DisplayObject;
	import starling.display.Sprite;
	import starling.events.Event;
	import starling.utils.AssetManager;
	
	public class Main extends Sprite
	{
		
		public function Main()
		{
			this.addEventListener(Event.ADDED_TO_STAGE, addedToStageHandler);
		}
		
		private function addedToStageHandler(event:Event):void
		{
			this.removeEventListener(Event.ADDED_TO_STAGE, addedToStageHandler);
			
			//var theme:MetalWorksMobileThemeWithAssetManager = new MetalWorksMobileThemeWithAssetManager( File.applicationDirectory.resolvePath("assets").url );
			var theme:MinimalMobileThemeWithAssetManager = new MinimalMobileThemeWithAssetManager( File.applicationDirectory.resolvePath("assets").url );
			
			theme.addEventListener( Event.COMPLETE, theme_completeHandler );
		}

		private function theme_completeHandler( event:Event ):void
		{	
			var header:Header = new Header();
			header.title = "I'm a header";
			
			var backButton:Button = new Button();
			backButton.label = "Back";
			backButton.styleNameList.add( Button.ALTERNATE_STYLE_NAME_BACK_BUTTON );
			backButton.addEventListener( Event.TRIGGERED, backButton_triggeredHandler );
			header.leftItems = new <DisplayObject>[ backButton ];
			header.width = 480;
			this.addChild( header );
		}
		
		private function backButton_triggeredHandler( event:Event ):void
		{
			trace("back");
		}
	
	}
}

```

**Comment by joshtynjala** [comment]
I can reproduce using MetalWorksMobileThemeWithAssetManager, but not MetalWorksMobileTheme. That was the difference.

**Comment by seyfullahbilgin** [comment]
Sorry, i am new for Starling&Feathers :)

**Comment by joshtynjala** [comment]
Thank you for reporting this issue. It has been fixed.
