### ISSUE TITLE
Animating LayoutData

### ISSUE THREAD

**Issue by GV3** [BowlerHatLLC/feathers#1296]
Dear Josh, 

I'm now animating the layoutData and have difficulties figuring out where this should happen. I suppose that this goes in the preLayout, but then it takes time and different frames until the layout is animated.

What approach do you recommend in matters of invalidating and using the postLayout or preLayout functions when animating. 

For example, let's say you have a List with multiple ItermRenderers, each with 3 elements inside positioned with an AnchorLayout. Now let's imagine that on selection the layoutData of each of this 3 elements changes influencing both their relative position and the size of the list item.

If the idea is to have a fluid animation of all the internal elements, and items in the list, how or where would you start the animations, which invalidation would you call when, etc...?

Thanks

**Comment by joshtynjala** [comment]
This is not a bug report or feature request. Can you please post questions at http://forum.starling-framework.org? Thank you!

**Comment by GV3** [comment]
http://forum.starling-framework.org/topic/animating-layoutdata#post-89898

Sitting there for a while now ;)

Whenever you find some time, thank you
