### ISSUE TITLE
Drawers: Crash on opening drawer if no top drawer defined

### ISSUE THREAD

**Issue by kevinfoley** [BowlerHatLLC/feathers#1303]
After migrating an existing project to Feathers 3.0, I get a crash in Drawers on line 4173:

> [Fault] exception, information=TypeError: Error #1009: Cannot access a property or method of a null object reference.

This line checks the mask property of _topDrawer, but I have not created a topDrawer. It looks like you aren't checking if the drawer exists before trying to read its mask property.

Additionally, you may want to consider refactoring the Drawers class so that you don't have 4 sets of nearly identical code for the top, left, bottom, and right drawers.

**Comment by joshtynjala** [comment]
> After migrating an existing project to Feathers 2.0

Do you mean 3.0?

**Comment by joshtynjala** [comment]
> Additionally, you may want to consider refactoring the Drawers class so that you don't have 4 sets of nearly identical code for the top, left, bottom, and right drawers.

I would like to, but there's just enough variation in the code that it doesn't seem particularly straight forward to refactor. Considering that it has worked well so far with only minor issues, I'm inclined to leave it be and focus on other things.

**Comment by kevinfoley** [comment]
Yes, 3.0. I keep mixing up the new version numbers for Starling and Feathers. This problem is with the latest code from GitHub.

**Comment by joshtynjala** [comment]
Thanks. I'll get it fixed today!

**Comment by joshtynjala** [comment]
Thanks again! I got it fixed.
