### ISSUE TITLE
Theme assets missing

### ISSUE THREAD

**Issue by harry248** [BowlerHatLLC/feathers#1310]
Would be nice if you could bundle the theme assets like you did in version 2.x Not everybody is using Animate CC.

**Comment by joshtynjala** [comment]
There are no assets to bundle anymore. The texture atlas is generated directly from Animate CC...

**Comment by joshtynjala** [comment]
I think I can export individual PNGs from the Animate CC library. Maybe I can put together a ZIP download next to the FLA file.

**Comment by harry248** [comment]
Would be great, thanks!
