### ISSUE TITLE
HierarchicalCollection: add the ability to update the header/footer only

### ISSUE THREAD

**Issue by Klug76** [BowlerHatLLC/feathers#1314]
The `HierarchicalCollection::updateItemAt` function allows to update only one sub-item or the whole group. Please add the ability to update the header/footer only. The current implementation is limited to `updateItemAt(idx)`, which is slow if the group contains many elements, and causes unpleasant side effect - changes scrolling position of the `GroupedList` component.

**Comment by joshtynjala** [comment]
Unfortunately, the collection knows nothing of headers and footers. It only knows of groups and items. You could have your header items dispatch an event when properties change that the renderer could listen for and update itself.
