### ISSUE TITLE
ImageSkin: defaultTexture, scale9Grid assign order

### ISSUE THREAD

**Issue by marpies** [BowlerHatLLC/feathers#1315]
Texture provided by ImageSkin.defaultTexture (instead of the constructor) is not resized when scale9Grid is assigned after defaultTexture.

```as3
// Texture is not resized, only after click
var skin:ImageSkin = new ImageSkin();
skin.defaultTexture = texture;
skin.scale9Grid = scale9Grid;
...
```

```as3
// Works fine
var skin:ImageSkin = new ImageSkin();
skin.scale9Grid = scale9Grid;
skin.defaultTexture = texture;
...
```

It didn't matter when using older commit, unfortunately, I can't pinpoint exact commit.

**Comment by joshtynjala** [comment]
This may be a bug in `starling.display.Image`, since `ImageSkin` is just a subclass. I'll take a look.

**Comment by joshtynjala** [comment]
When you say "not resized", what exactly do you mean?

**Comment by marpies** [comment]
It happens when switching Feathers sources only.

Before the button is interacted with:
![Image](https://dl.dropboxusercontent.com/u/32758508/Screenshots/before.png)

After interaction:
![Image](https://dl.dropboxusercontent.com/u/32758508/Screenshots/after.png)

**Comment by joshtynjala** [comment]
Are you seeing this happening with the example themes too? Or is that just a mock-up?

**Comment by marpies** [comment]
Yes, I can reproduce it using the current MetalWorksMobileTheme.

Changing setButtonStyles method from this...
```as3
var skin:ImageSkin = new ImageSkin(this.buttonUpSkinTexture);
```
...to this...
```as3
var skin:ImageSkin = new ImageSkin();
skin.defaultTexture = this.buttonUpSkinTexture;
```
...will result in the first screenshot above.

**Comment by marpies** [comment]
I took current Feathers and replaced just the ImageSkin with the older ImageSkin and it works fine, so definitely something with that class.

The older ImageSkin I have is around 12kB, current one around 18kB.

**Comment by teotigraphix** [comment]
I'm getting this to, this is may custom theme.

before interaction:

![lyd0o](https://cloud.githubusercontent.com/assets/226417/13844796/5f787ae0-ec12-11e5-8cc4-46607cdae899.png)

after interaction:

![ul9z6](https://cloud.githubusercontent.com/assets/226417/13844799/632cf5d0-ec12-11e5-926e-76e54d9ba452.png)

**Comment by joshtynjala** [comment]
The issue can be reproduced with `starling.display.Image`:
	
	var image:Image = new Image(null);
	image.texture = Texture.fromColor(10, 10, 0xffff00);
	image.scale9Grid = new Rectangle(1, 1, 8, 8);
	image.width = 500;
	image.height = 500;
	this.addChild(image);

If you think this behavior is incorrect, I recommend reporting an issue to [Gamua/Starling-Framework](https://github.com/Gamua/Starling-Framework/issues). I'm not sure if this is the behavior that Daniel intended. Normally, after changing the `texture` property without , you need to call `readjustSize()`Perhaps setting scale9Grid should call `readjustSize()`.

**Comment by joshtynjala** [comment]
I guess I could probably simply mention @PrimaryFeather to ask his opinion. :smile: 

Daniel, what are your thoughts about [my previous post](https://github.com/BowlerHatLLC/feathers/issues/1315#issuecomment-198026571) in this thread.

**Comment by PrimaryFeather** [comment]
Thanks for adding me to the loop!

While this behavior is actually intended, I think your idea of calling `readjustSize()` implicitly when a `scale9Grid` is assigned is how it ought to be done. A `scale9Grid` only makes sense with a texture, and you typically use the size of the texture to calculate the scale9-values. I can't imagine any negative side effects.

I'll sleep over it, but I'm pretty sure I'll make that change. I'll post it here once it's done! :smile:

**Comment by teotigraphix** [comment]
Thanks for commenting @PrimaryFeather . :)

**Comment by joshtynjala** [comment]
Thanks, Daniel!

Once, Daniel makes the change, I'll make the ImageSkin constructor argument optional again, since there won't be strange side effects to worry about.

**Comment by PrimaryFeather** [comment]
Done! → https://github.com/Gamua/Starling-Framework/commit/fe4cb4a280cacc27c5f0ca5dba77d910d1c71a74
