### ISSUE TITLE
HorizontalLayout overfow from parent container size

### ISSUE THREAD

**Issue by SamYStudiO** [BowlerHatLLC/feathers#1317]
Hi Josh,

Using simple code like this one : 
```
var group : LayoutGroup = new LayoutGroup();
group.backgroundSkin = new Quad( 10 , 10 , 0xeeeeee );
var text : Label = new Label();
text.wordWrap = true;
text.text = "i'm a lonnnnnnnnnnnnnnnnnnnnnnnnnnnnnng text";
group.addChild( text );
group.width = 100;
addChild( group );
```
text won't wrap.
We may have already discuss about this one but can't get any trace of it or maybe related to this one https://github.com/BowlerHatLLC/feathers/issues/1210? ;)

**Comment by joshtynjala** [comment]
The Label will not wrap unless it's width or maxWidth is set. You've set the LayoutGroup's width, but that alone won't change the Label's width.

I see that you've mentioned HorizontalLayout in the issue title, but it's not used in your code. Using percentWidth with HorizontalLayoutData is one way to ensure that the Label's width stays within the bounds of the LayoutGroup, of you want the Label to resize when the group resizes.

**Comment by SamYStudiO** [comment]
Sorry my example is indeed incomplete
```
var group : LayoutGroup = new LayoutGroup();
var layout : HorizontalLayout = new HorizontalLayout();
group.layout = layout;
group.backgroundSkin = new Quad( 10 , 10 , 0xeeeeee );
var image : ImageLoader = new ImageLoader();
image.source = "http://static.nbclearn.com/files/nbcarchives/site/images/flash-logo.jpg";
group.addChild( image );
var text : Label = new Label();
text.wordWrap = true;
text.text = "i'm a lonnnnnnnnnnnnnnnnnnnnnnnnnnnnnng text";
group.addChild( text );
addChild( group );
group.width = 200;
```
You could indeed use maxWidth with label to fix this but if you don't know container size (when container is nested from other layoutgroups and you got more elements from your horizontal align group), it's getting harder to set that maxWidth to avoid that overflow from container (you need to wait for a draw then compute maxWidth, set it and then wait for next redraw).
Setting `new HorizontalLayoutData( 50 )` on both elements has no effect but scaled up icon.

I guess it would make sense when you set a fixed size on a container, children should fit in it? I mostly work on mobile but i guess with a desktop resizable content this could be a pain.

**Comment by joshtynjala** [comment]
I can reproduce this issue. Thanks!

The following addition to your code should work, but it doesn't. That's a bug.

    text.layoutData = new HorizontalLayoutData(100);

> I guess it would make sense when you set a fixed size on a container, children should fit in it?

Not really. It depends on the layout.

If it weren't a performance concern, the LayoutGroup's clipContent property would be true by default, and any children that were larger than the container's bounds would be clipped. That would be a slightly better situation because children would never be drawn outside the edges of the parent container.

**Comment by SamYStudiO** [comment]
Wow thats a quick fix! :)
will try it tomorrow,
Thx!
