### ISSUE TITLE
LayoutGroup minWith/minHeight

### ISSUE THREAD

**Issue by SamYStudiO** [BowlerHatLLC/feathers#1318]
Hello Josh,

I'm trying to have item renderer using LayoutGroupListItemRenderer smaller than my original background size but it seems actually minWith/minHeight are forced to match background original size, my background skin is a scale9 image and i can't make it smaller, any chance to have an ability to disabled this behaviour?

Thx!

**Comment by joshtynjala** [comment]
If you set the minWidth or minHeight properties directly, that explicit value will always take precedence.

**Comment by SamYStudiO** [comment]
i guess it should but actually from LayoutGroup refreshViewPortBounds method, it seems minHeight/minWith are overwritten even if set explicitly when value is less than original background size
```as3
if(this.originalBackgroundWidth === this.originalBackgroundWidth && //!isNaN
	this.originalBackgroundWidth > minWidth)
{
	minWidth = this.originalBackgroundWidth;
}
if(this.originalBackgroundHeight === this.originalBackgroundHeight && //!isNaN
	this.originalBackgroundHeight > minHeight)
{
	minHeight = this.originalBackgroundHeight;
}
```

**Comment by joshtynjala** [comment]
Okay, I'll take a look.

It's worth noting that LayoutGroup hasn't gone through the saveMeasurements() conversion from #1165, and that involves much smarter calculation of minimum dimensions. Once it's done, if you use ImageSkin, you'll be able to override the minWidth and minHeight of the skin, and LayoutGroup will respect that value.

**Comment by teotigraphix** [comment]
So will this make AnchorLayout behave nicer when no constraints are applied?

**Comment by joshtynjala** [comment]
@teotigraphix I don't think this will affect AnchorLayout in any way, but it would help if I understood what you think could be improved with AnchorLayout. Perhaps a code sample to demonstrate an issue?

**Comment by teotigraphix** [comment]
Ah well I use the layout a lot and one thing that bugs me is if there are no constraints applied to anything it collapses on itself and does not use it's children's min width/height for it's own min width/height.

But yes now that I think about it, I would need to set something up to show you. If I can completely recreate my issue I will create an issue for it so it's documented.

**Comment by joshtynjala** [comment]
Does the container using AnchorLayout have layoutData with percentWidth and/or percentHeight? If so, then yes, this will indeed help.

**Comment by teotigraphix** [comment]
Yeah I am pretty sure, that is why I didn't say anything because I remember it was something specific.

**Comment by SamYStudiO** [comment]
Hello Josh,
i can confirm saveMeasurements() conversion fixed this one, you may close it then ;)
Thx!

**Comment by joshtynjala** [comment]
Great! Thanks for letting me know!
