### ISSUE TITLE
Stange issues when using ImageLoader with LayoutGroupListItemRenderer

### ISSUE THREAD

**Issue by SamYStudiO** [BowlerHatLLC/feathers#1320]
Hello Josh,

I got stange behaviours with ImageLoader and LayoutGroupListItemRenderer, here is an example : 
```as3
var list : List = new List();
list.setSize( 200 , 500 );
list.dataProvider = new ListCollection( [ {} , {} , {} ] );
list.itemRendererType = CustomItemRenderer;
list.addEventListener( Event.TRIGGERED , function ()
{
	var t : Tween = new Tween( list , 5 );
	t.moveTo( 200 , 0 );
	Starling.juggler.add( t );
} );
addChild( list );
```
CustomItemRenderer: 
```as3
class CustomItemRenderer extends LayoutGroupListItemRenderer
{
	override protected function initialize() : void
	{
		super.initialize();

		var image : ImageLoader = new ImageLoader();
		image.source = R.drawable.bottle; // replace with your own texture
		backgroundSkin = image;
		height = 200;

		var label : Label = new Label();
		label.text = "hello";
		addChild( label );

		new TapToTrigger( this );
	}
}
```

First i can't get imageLoader displayed at startup, i need to scroll a bit to make the image appear.
But the trickiest one is when you click a item to move the List, only text is actually moving, and again scrolling make the image move to the right position.
I actually notice this issue when switching from a screen to another using a slide transition but to make the example easier i just made the list moving.
It may be a Starling issue, but replacing ImageLoader with Image fixes it, so i guess you could have a look first.
Of course moving an ImageLoader alone won't reproduce this, so i tried to add a mask or clipRect to an ImageLoader an no pb either.

**Comment by GV3** [comment]
I had the same problem and solved it replacing it with the Image too... 

I also have a another case, don't know if it's related... I have a button with a skin background in the ItemRenderer and when the item renderer is reused the sizes of the item renderer and the button adapt properly to the size of the new label, all except the background image of the button. The latter keeps the size of the old label until I scroll or select the item.

**Comment by joshtynjala** [comment]
Thanks! I can reproduce this issue.

The background skin of a LayoutGroup is not actually a child of the LayoutGroup. I render it manually. It seems that if the background skin is a Sprite (which FeathersControl extends), it can cause issues like this where the children don't reposition properly.

Daniel showed me how to render display objects manually, so this *should* work. I'm working with him to figure it how to address this issue.
