### ISSUE TITLE
inefficient function in the TextBlockTextRenderer

### ISSUE THREAD

**Issue by Klug76** [BowlerHatLLC/feathers#1323]
Please do not call the `TextBlockTextRenderer::alignTextLines()` function from `TextBlockTextRenderer::measure()` to avoid extra large `_measurementTextLineContainer` shape size in a case of `textAlign==TextBlockTextRenderer.TEXT_ALIGN_RIGHT`. This function is called with an argument `width==MAX_TEXT_LINE_WIDTH==1000000`, that may even cause crash the application.
![extra_large_line](https://cloud.githubusercontent.com/assets/1420061/13999511/ab679cc0-f14d-11e5-8b93-0658c81254b9.PNG)

**Comment by joshtynjala** [comment]
I'm not sure how that could crash an application. However, yes, I agree that the alignment should be skipped during measurement since it doesn't affect the measurement.

**Comment by Klug76** [comment]
Thanks for the quick fix! I have not even created a minimal test case with exception..
