### ISSUE TITLE
TextInput: add iconPosition property

### ISSUE THREAD

**Issue by serjek** [BowlerHatLLC/feathers#1328]
TextInput is lacking ability to set icon position to the right side of text editor. This could be useful for cases like on screenshot:

<img width="618" alt="screenshot 2016-04-04 17 41 32" src="https://cloud.githubusercontent.com/assets/18265157/14251617/e47a287a-fa94-11e5-9332-af5bf2eda2e7.png">
<img width="628" alt="screenshot 2016-04-04 17 42 10" src="https://cloud.githubusercontent.com/assets/18265157/14251631/f7d2c72e-fa94-11e5-8960-fa84bbf53ab0.png">

Current workaround requires playing around with custom paddingRight and backgroundSkin, and this doesn't feel quite right.

**Comment by kevinfoley** [comment]
@joshtynjala  Any plans to add this in the near future?
