### ISSUE TITLE
StackScreenNavigator: add swipe gesture to pop to previous view

### ISSUE THREAD

**Issue by serjek** [BowlerHatLLC/feathers#1329]
iOS NavigationController has this handy built-in feature to pop to previous view. This is especially important on tall phones like anything past iPhone4s, because "back" button is usually far out of quick thumb reach for user, and this gets rather annoying when returning back from nested menus or from secondary screens. So I extended StackScreenNavigator by merging Drawers code into it to support swipe-to-back as well.

Please use this code as you see fit.
https://gist.github.com/serjek/c31cd8cb12e305a1895a5c04675aeeec

**Comment by joshtynjala** [comment]
Duplicate #1264
