### ISSUE TITLE
List/Scroller viewport/scrolling issue after resizing

### ISSUE THREAD

**Issue by harry248** [BowlerHatLLC/feathers#1330]
Since one of the last commits I have a problem with the List/Scroller control. When rotating from portrait to landscape or the other way round, the List control seems to remember the maximum width/height of the contents and is scrollable in the respective direction. For example starting in landscape mode, the list is scrollable only vertically. Rotating to portrait mode, the list ist is suddenly also scrollable horizontally as far as the item renderers have been wide (they resized correctly) in landscape mode.

**Comment by joshtynjala** [comment]
Thanks! I can reproduce, and I'll get it fixed.
