### ISSUE TITLE
Extending Screen errors with Feathers 3 and Starling 2 Beta

### ISSUE THREAD

**Issue by joe-complete-grp** [BowlerHatLLC/feathers#1331]
After updating to Starling 2 and Feathers 3 Betas I'm getting various errors on my main view classes which extend Feathers 'Screen'.

Primarily the following errors on each of my templates
- interface method hasEventListener in interface IFeathersEventDispatcher is implemented with an incompatible signature in class ScreenTemplateB
- interface method clipRect in interface IFeathersControl not implemented by class ScreenTemplateB
- interface method hasVisibleArea in interface IFeathersDisplayObject not implemented by class ScreenTemplateB

Everything working fine with previous versions of both Starling and Feathers pre update

I cant help but think I have missed something regarding compatibility between the betas?

Any help is appreciated.

**Comment by joshtynjala** [comment]
The references to clipRect and hasVisibleArea in the errors mean that you still have a version of Feathers 2 in your project.

**Comment by joe-complete-grp** [comment]
Thanks Josh, that did resolve the errors on the templates however it has raised a new error 
that was not present using the older versions of both Starling & Feathers. The scroll container class is now throwing a null object exception on line 775  (see intellij debug output attached). I presumed 'this.stage' was null however when checking with the previous SWCs 'this.stage' also is null a the same point in the code execution so I'm a little lost. 

Please note that commenting out the scroll container results in the app compiling correctly and also I am using the screen.properties inject method.

![starling-snap](https://cloud.githubusercontent.com/assets/13379082/14287699/af808f62-fb4b-11e5-8181-7c3d5d7f298b.PNG)

Once again any help is appreciated.

**Comment by joshtynjala** [comment]
Are you using the Feathers 3.0.0-alpha build? Or are you using the latest source code from Github? I think the alpha build had an issue in ScrollContainer's initialize() that has since been fixed.

**Comment by joe-complete-grp** [comment]
Yes I was using the Alpha from the site, updated to the git version and this is resolved, cheers!

Might have to switch back versions though as this is prod project. That said starling/feathers have always been rock solid stable so not sure if its a huge risk.
