### ISSUE TITLE
ImageLoader ignores mask property

### ISSUE THREAD

**Issue by serjek** [BowlerHatLLC/feathers#1332]
Problem:
Once ImageLoader is created it will ignore the mask property until it fires the COMPLETE event, even if it's source comes from assets manager.

How to reproduce:
1. Create ImageLoader and add valid source from external file or from assets manager
2. Apply Quad mask to it
3. Observe that mask is ignored in both case.

Expected: ImageLoader retains mask and applies it to internal image once it is created. It makes sense if ImageLoader ignores mask property if it is loading from external file, but having to set mask only after COMPLETE event for texture that is already loaded feels wrong.

**Comment by joshtynjala** [comment]
ImageLoader currently uses the mask for itself to support the scaleMode property. I will try to mask the internal Image instead.
