### ISSUE TITLE
Call to a possibly undefined method excludeFromCache through a reference with static type Painter.

### ISSUE THREAD

**Issue by kwonyounggu** [BowlerHatLLC/feathers#1336]
Hello,

I am trying to use Feathers UI first time using Starling 2.0 and faced a problem.

Would you like to help with the following error message?

1. Error Message: Call to a possibly undefined method excludeFromCache through a reference with static type Painter.

2. Error file: StageTextTextEditor.as
3. Actionscript code statement: painter.excludeFromCache(this); in line 1150

4. Starling version: 2.0
5. Feather version: 3.0

Thank you very much in advance.

**Comment by joshtynjala** [comment]
Please update to a newer commit of Starling 2.0! excludeFromCache() was added very recently.
