### ISSUE TITLE
Layouts distributeHeights/Width forces Starling 2.0 to render every frame

### ISSUE THREAD

**Issue by serjek** [BowlerHatLLC/feathers#1341]
VerticalLayout.distributeHeights and HorizontalLayout.distributeWidths causes Starling 2.0 to render every frame even with skipUnchangedFrames == true.

More to it, making VerticalLayout.distributeHeights = true in ComponentsExplorer drops FPS to below 10:
in ComponentsExplorerTheme.setLabelScreenStyles replace layout with following 
```
var verticalLayout:VerticalLayout = new VerticalLayout();
verticalLayout.distributeHeights=true;
screen.layout = verticalLayout;
```
and check LabelsScreen. Note the FPS drop and Stats box never turn green.

**Comment by joshtynjala** [comment]
Thank you! I can reproduce this issue.
