### ISSUE TITLE
Scroller: "revealScrollBars" method doesnt display correctly at ver. 3.0.0-beta

### ISSUE THREAD

**Issue by daicemirror** [BowlerHatLLC/feathers#1346]
Hi
I tried feathers.examples.transitionsExplorer.
In addition to "AllTransitionsScreen", other screens have the code:
`
override protected function initialize():void
                {
			...
			this._list.revealScrollBars();
			 ...
                }
`
                
work normally.

But in AllTransitionsScreen:
                `private function transitionInCompleteHandler(event:Event):void
		{
			...
			this._list.revealScrollBars();
		}`
this doesn't show a hint bar.
The same issues in other examples.

(I tried above at least version, both situations work failure.)

**Comment by daicemirror** [comment]
I change the theme with MinimalMobileTheme.
It showed different results.
However, I still can not find the reason.

**Comment by joshtynjala** [comment]
Thanks! I'll figure it out.
