### ISSUE TITLE
Bug: ScrollContainer miscalculates horizontalPageCount on iPad Air 2 (Feathers 2.3)

### ISSUE THREAD

**Issue by kevinfoley** [BowlerHatLLC/feathers#1347]
We have a ScrollContainer set to use horizontal paging. Three controls are added to the ScrollContainer; each is center-aligned and they are positioned at stage.stageWidth * .5, stage.stageWidth * 1.5, stage.stageWidth * 2.5.

On desktops and Android devices, the ScrollContainer works fine. However, on an iPad Air 2, the ScrollContainer miscalculates the horizontalPageCount as "0" and does not allow us to scroll between pages. If I force the horizontalScrollPolicy on, I can drag the container just far enough to see the edge of the control on the second page, but the ScrollContainer won't allow us to actually scroll between pages.

Using the debugger I have verified that all three controls are children of the ScrollContainer's layout viewport and have the correct coordinates and dimensions, and the ScrollContainer itself has the correct width and pageWidth (the width of the screen).

**Comment by joshtynjala** [comment]
There's a good chance that this is fixed in 3.0. Can you give it a try?

**Comment by kevinfoley** [comment]
Thanks for the response. This is a very large project and we're trying to meet a consumer release date in May. As such I am not sure I feel comfortable moving to a beta platform, or if we can spare the time to upgrade both Starling and Feathers. I'll see what I can manage.

**Comment by kevinfoley** [comment]
We weren't able to upgrade to 3.0 before launch. For a workaround, I positioned an empty label within the bounds of the third page, which seems to get Feathers to calculate the pagecount correctly. If you'd like, feel free to close this issue.
