### ISSUE TITLE
Many incorrectly displayed issues when the window is resized.(ver. 3.0.0-beta)

### ISSUE THREAD

**Issue by daicemirror** [BowlerHatLLC/feathers#1350]
This tested with feathers.examples.componentsExplorer on Air project.

Convenient to reproduce, you can select "Grouped List" tab.
Then use the mouse to change the width of the window until near the left menu.
Can see that many texts become shorter.
When resizing window back, those texts were not restored.

If Changing the width of the window beyond the left menu, right content may disappear after resize back.
Repeat several times may have different results.

Most occur in the header and list component.

Another tested with feathers.examples.drawersExplorer.
Some similar case occur to display popUpContentManager of PikerList.
The popUpContentManager was not restored to normal size.
ex: Incorrectly displayed on DropDownPopUpContentManager when window resized to small height.

**Comment by joshtynjala** [comment]
> If Changing the width of the window beyond the left menu, right content may disappear after resize back.

For things that disappear completely, it's Gamua/Starling-Framework#850 again. The text becoming truncated is a different issue, though. I think I know why it's happening, and it should be pretty easy to fix.

> Some similar case occur to display popUpContentManager of PikerList.
> The popUpContentManager was not restored to normal size.

I can reproduce this too. Thanks!

**Comment by joshtynjala** [comment]
> Some similar case occur to display popUpContentManager of PikerList.
> The popUpContentManager was not restored to normal size.

I decided to move this to a separate issue: #1353
