### ISSUE TITLE
Drawers:Get some issues when I tested in examples.drawersExplorer.(ver. 3.0.0-beta)

### ISSUE THREAD

**Issue by daicemirror** [BowlerHatLLC/feathers#1351]
In Main Class.
a.
when  `_drawers.minimumDragDistance = 2`
Top and bottom drawer animation is skiped.

b.
Prerequisite below:
 `topDrawer.autoSizeMode = AutoSizeMode.STAGE` or `bottomDrawer.autoSizeMode = AutoSizeMode.STAGE`
And left or right drawer is docked.

Start to do:
Top or bottom drawer is undocked after docked.

Result:
Left and right drawer background disappeared.

Grateful  for your hard work.

**Comment by joshtynjala** [comment]
Part b was caused by Gamua/Starling-Framework#850

Regardless, I prefer not to set the dimensions of sub-components to negative values, so my workaround is actually a fix because that should have been the original behavior.
