### ISSUE TITLE
The distributedWidths property is not working on the HorizontalLayout when using virtualLayout

### ISSUE THREAD

**Issue by GV3** [BowlerHatLLC/feathers#1357]
The distributedWidths property is not working on the HorizontalLayout when using virtualLayout.

The vitualLayout is on, the HorizontalLayout will take the first item in the data and use it as the typical item. This is all good.... when the layout method runs, it will first calculate the distributedWidths accordingly and assign this width to the item ... to THEN override this correct value with the calculatedTypicalItemWidth.(See the code) 

```
 else if(calculatedTypicalItemWidth >= 0)
{
    //if all items must have the same width, we will
    //use the width of the typical item (calculatedTypicalItemWidth).
    item.width = itemWidth = calculatedTypicalItemWidth;
}
```

AND the calculatedTypicalItemWidth is WRONG because at the time the calculatedTypicalItemWidth was calculated the distributeWidths property was not taken into consideration.

I will in the mean time calculate and pass an explicit width for the items.

Please let me know if my interpretation of the code is wrong.

to reproduce, I'm using this code:

```
var daysList:List = new List();
var dayList_horizontalLayout:HorizontalLayout = new HorizontalLayout();
dayList_horizontalLayout.distributeWidths = true;
dayList_horizontalLayout.gap = 0;
dayList_horizontalLayout.padding = 0;
dayList_horizontalLayout.requestedColumnCount = 7;
dayList_horizontalLayout.horizontalAlign = HorizontalLayout.HORIZONTAL_ALIGN_CENTER;
daysList.layout = dayList_horizontalLayout;
daysList.layoutData = new AnchorLayoutData(0,0,NaN,0);
daysList.dataProvider = new ListCollection(
                [
                    {"label":"S"}
                    ,{"label":"M"}
                    ,{"label":"T"}
                    ,{"label":"W"}
                    ,{"label":"T"}
                    ,{"label":"F"}
                    ,{"label":"S"}
                ]);

```

**Comment by joshtynjala** [comment]
distributeWidths isn't meant to work with useVirtualLayout. I should automatically set useVirtualLayout to false automatically when distributeWidths is set to true.

As a workaround, you can set useVirtualLayout to false manually.

**Comment by GV3** [comment]
Try that, but got his error when turning useVirtualLayout manually to false:

[Fault] exception, information=ArgumentError: A component's width cannot be NaN.

inside of the saveMeasurements method of the FeathersControl Class for that List

**Comment by joshtynjala** [comment]
Well, that's the correct solution, but it must be a bug elsewhere. I'll investigate.

**Comment by GV3** [comment]
Great thanks.

And I think it would be great if both the useVirtualLayout and the distributeWidths could be set to true.

Like I wrote above, maybe if the calculatedTypicalItemWidth would take into consideration if the distributeWidths == true, then both the useVirtualLayout and the distributeWidths could be set to true and work together properly.

**Comment by joshtynjala** [comment]
If distributeWidths is true, all items will be visible, so there won't be any virtual items. With that in mind, why do you think it would be great?

**Comment by GV3** [comment]
Well, I'll tell you what I expected from my code.

In the code above I use requestedColumnCount = 7 and distributeWidths = true and the default useVirtualLayout=true.

so I expected the HorizontalLayout to display only 7 items per page, one per column, also to distribute their width to 1/7 of the width of the List, and to have the list using virtual layout for performance.

I hope it makes sense to you

**Comment by GV3** [comment]
I correct myself, the pagination is in the TiledRowsLayout and not in the HorizontalLayout.

**Comment by GV3** [comment]
Info:

the [Fault] exception, information=ArgumentError: A component's width cannot be NaN. disappeared when I removed the .requestedColumnCount = 7;

Now all works as expected

**Comment by joshtynjala** [comment]
Which version of Feathers are you using? I'm not seeing the runtime error caused by setting requestedColumnCount = 7 in 3.0.

**Comment by GV3** [comment]
I'm on the commit 0c31b4c with the tag "v3.0.0-beta" and it's important that the List is on an AnchorLayout to reproduce it.

**Comment by joshtynjala** [comment]
Yes, I tested with an AnchorLayout.
