### ISSUE TITLE
Request: Rename "light" labels to "bright" in sample themes

### ISSUE THREAD

**Issue by kevinfoley** [BowlerHatLLC/feathers#1360]
The sample Metal Works Mobile Theme uses the word "light" for white labels, e.g. `lightElementFormat`, `setLightLabelStyles()`. This terminology can be confusing when extending the MetalWorksMobileTheme for a custom theme, if the custom theme incorporates any fonts with a light _weight_. For example, if the theme uses Open Sans and Open Sans Light, what would we call the element format for a white label that uses Open Sans Light? `lightLiteElementFormat`? 

I can't think of a suitable synonym for "light" when discussing font weights other than "lite", but "bright" is a decent synonym for "light" when discussing colors, e.g. `brightLightElementFormat`, `darkLightElementFormat`.

This might sound like an inconsequentially rare issue, but it actually comes up frequently for me. Whenever I create a new theme, I start by extending MetalWorksMobileTheme, and it seems like every time I'm hired to work on a client's existing Feathers app, they _also_ started with MetalWorksMobileTheme.

**Comment by joshtynjala** [comment]
I suspect that if you're changing the font, you're probably using completely different textures too. At that point, you might as well start renaming variables. It's no longer an extended MetalWorksMobileTheme with such drastic changes, so why worry about keeping the existing variable names, you know? A quick "rename" refactor in your IDE, and it has a new name.

Regardless, to differentiate the weight from the color, you might try something like "lightColorLightWeight". Maybe "lightThin" instead. Or you could name it after the kind of components that are going to use this font style, like "labelElementFormat" or something like that. There are a lot of variations that are coming to mind.

Thanks for sharing your experience, but at this point, I'm going to leave it as-is.

**Comment by kevinfoley** [comment]
> I suspect that if you're changing the font, you're probably using completely different textures too. At that point, you might as well start renaming variables. It's no longer an extended MetalWorksMobileTheme with such drastic changes

Not true at all. All you need to do to replace the textures is override the `initializeTextures()` function. Your variable names, e.g. `buttonUpSkinTextures` , are completely generic and I've never seen the need to rename anything besides the light element formats. Of course new style providers and element formats will get added, but that's the point of inheritance, it lets you add new functionality without having to edit the existing code.

**Comment by joshtynjala** [comment]
> Not true at all. All you need to do to replace the textures is override the initializeTextures() function. 

"Completely" may not have been the right word. I was thinking mostly about the texture files rather than the code related to the textures.

> Of course new style providers and element formats will get added, but that's the point of inheritance, it lets you add new functionality without having to edit the existing code.

If you're using a different font, you already need to edit the existing code to remove the original embedded font.
