### ISSUE TITLE
Using the mouse wheel does not stop animation on Scroll Container with InteractionMode.TOUCH_AND_SCROLL_BARS

### ISSUE THREAD

**Issue by pchertok** [BowlerHatLLC/feathers#1361]
If I "throw" the scroll container then immediately use the mouse wheel the scroll container will respond to the mouse wheel but will then continue with the "throw" animation until it completes.  I believe the correct behaviour is that whenever I use the mousewheel it should cancel any active animation.  Clicking the scrollbar while the "throw" animation is happening produces the correct behaviour.

**Comment by joshtynjala** [comment]
I cannot reproduce in a simple case. It appears to be working correctly. Is there any chance that your throw and the mouse wheel are scrolling in different directions? That's the only thing I can think of that might be different.

**Comment by pchertok** [comment]
In my limited test at the office you are correct, it seems to be working
correctly.  I'll provide an update when I get home with specifics on my
implementation.

On Mon, May 2, 2016 at 11:42 AM, Josh Tynjala <notifications@github.com>
wrote:

> I cannot reproduce in a simple case. It appears to be working correctly.
> Is there any chance that your throw and the mouse wheel are scrolling in
> different directions? That's the only thing I can think of that might be
> different.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/BowlerHatLLC/feathers/issues/1361#issuecomment-216271978>
>



-- 
Phillip Chertok

**Comment by pchertok** [comment]
I am unable to reproduce currently so I'll assume I did something wrong initially.  I'll make another issue if I encounter it again in the meantime I believe this can be closed.

**Comment by joshtynjala** [comment]
Thanks for double-checking!
