### ISSUE TITLE
Numeric Stepper only preserves value after hitting ENTER in editable field.

### ISSUE THREAD

**Issue by pchertok** [BowlerHatLLC/feathers#1363]
If i manually enter a value into a numeric stepper and then hit the increment or decrement buttons the button will modify the value that was in it prior to my editing.

If i hit the enter key on my keyboard while the field is in focus then the value is committed and the buttons work properly.

I believe the behaviour should be that the value is committed as soon as it is changed.

**Comment by joshtynjala** [comment]
Ideally, it should commit on focus out (to avoid issues with multi digit numbers), and I'm surprised it's not doing that. It's probably that the NumericStepper considers itself still in focus when touching one if its buttons. I'll get it fixed. Thanks!

**Comment by pchertok** [comment]
It's not occurring when I focus on any other component either.  It is
only committing when I hit the enter key.

On Sun, May 1, 2016 at 10:44 PM, Josh Tynjala <notifications@github.com>
wrote:

> Ideally, it should commit on focus out (to avoid issues with multi digit
> numbers), and I'm surprised it's not doing that. It's probably that the
> NumericStepper considers itself still in focus when touching one if its
> buttons. I'll get it fixed. Thanks!
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/BowlerHatLLC/feathers/issues/1363#issuecomment-216095599>
>



-- 
Phillip Chertok

**Comment by joshtynjala** [comment]
Sigh. Text editing in the Flash runtimes gives me constant headaches. It just seems to constantly break.

Which text editor are you using with the TextInput?

**Comment by pchertok** [comment]
I am not entirely sure (don't have access to that code right now) but I am using the default one used in the MetalworksDesktop theme.

**Comment by pchertok** [comment]
I can confirm this is indeed fixed.
