### ISSUE TITLE
Remove dependance on Starling.current and replace with a way to support multiple Starling instances.

### ISSUE THREAD

**Issue by pchertok** [BowlerHatLLC/feathers#1364]
Currently the use of the Starling.current property makes it difficult to create Feathers applications that exist on multiple Native Windows.

I realize this is a big change so it might be helpful to discuss the correct approach.

**Comment by joshtynjala** [comment]
It's not really a big change. I have a stageToStarling() utility function that I've begun using, but some older code still references Starling.current.

**Comment by pchertok** [comment]
Awesome to hear.  I suppose the next step would be tying a theme to one of
those instances so you could have 1 theme for 1 instance and another theme
for another instance.  I think that's off topic though.

On Mon, May 2, 2016 at 10:46 AM, Josh Tynjala <notifications@github.com>
wrote:

> It's not really a big change. I have a stageToStarling() utility function
> that I've begun using, but some older code still references
> Starling.current.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/BowlerHatLLC/feathers/issues/1364#issuecomment-216255019>
>



-- 
Phillip Chertok

**Comment by joshtynjala** [comment]
With the latest 3.1 commits, Starling.current is only used as a fallback. Additionally, an instance of StyleNameFunctionTheme is now tied to a specific Starling instance (at the time of theme instantiation, whichever Starling instance is current will be used). A separate theme can be instantiated for each separate Starling instance.

During testing, I was able to open several NativeWindows successfully. Each had a new instance of the theme.
