### ISSUE TITLE
Add locationChanging event to webview

### ISSUE THREAD

**Issue by oskaraqp** [BowlerHatLLC/feathers#1365]
it will help to detect location changing, stop propagation if needed and process the new location requested

**Comment by joshtynjala** [comment]
Thanks for the suggestion!

Duplicate #1239

**Comment by oskaraqp** [comment]
Ohh sorry I didn't see it was a duplicated request, any reason why it has not been implemented yet?

**Comment by joshtynjala** [comment]
There has been more interest in other new features, so it hasn't had a high priority.

**Comment by oskaraqp** [comment]
If I want to update this, which is the normal process? I use sourcetree, update the files and ask for a push ?

**Comment by joshtynjala** [comment]
1. Fork the repository on Github.
1. Check out your fork locally.
1. Create a new branch for each separate feature or bug fix.
1. Commit your changes to your new branch.
1. Push your branch to your fork on Github.
1. Open a pull request.

**Comment by oskaraqp** [comment]
Ok I did the change and created a pull request, please let me know if it was made correctly. Thanks
