### ISSUE TITLE
Infinite loop when Modify this._menu.width = 100 in the feathers.examples.transitionsExplorer.Main Class

### ISSUE THREAD

**Issue by daicemirror** [BowlerHatLLC/feathers#1368]
Testing with feathers.examples.transitionsExplorer.

Modify code at line 72 in feathers.examples.transitionsExplorer.Main Class
`this._menu.width = this.stage.stageWidth / 3;`
to
`this._menu.width = 100;`
And then compile.
Infinite loop happen after click on the menu.

if set `this._menu.width = 50;`
That Happen immediately after compilation.

Thanks.

**Comment by joshtynjala** [comment]
Thank you! I can reproduce this issue.

**Comment by daicemirror** [comment]
It's work! great job! Thanks!

I stumbled upon a little problem when set `this._menu.width = 50;
The menu can be horizontal scrolled but not restored correctly.

**Comment by joshtynjala** [comment]
Good find. I'll get it fixed!
