### ISSUE TITLE
TextInput: ensure that range is selected before listeners receive FeathersEventType.FOCUS_IN on keyboard focus change

### ISSUE THREAD

**Issue by oskaraqp** [BowlerHatLLC/feathers#1369]
I've added addEventListener( FeathersEventType.FOCUS_IN, inputNameFocusInHandler ); to an textinput control and I always get selectionBeginIndex = selectionEndIndex I've used also focus out with the same result, I've added a listener to a button to detect it and same result.

**Comment by joshtynjala** [comment]
> I've added addEventListener( FeathersEventType.FOCUS_IN, inputNameFocusInHandler ); to an textinput control and I always get selectionBeginIndex = selectionEndInde

When you touch on a TextInput, it places the cursor by the nearest character. No characters will be selected, so that's the expected behavior.

In the case of using the tab key to navigate to a TextInput, the selection does not get updated until after FeathersEventType.FOCUS_IN is finished dispatching. Currently, you may need to wait a frame to get the selection range after keyboard focus change. I'll look into it, though. I may be able to get it to select the range before your listener receives FeathersEventType.FOCUS_IN.

> I've used also focus out with the same result, I've added a listener to a button to detect it and same result.

StageTextTextEditor needs to its scroll position back to the beginning on focus out, and that requires changing the selection because Adobe AIR's StageText API is, unfortunately, very limited.

TextFieldTextEditor doesn't reset it selection range on focus out, since it has more control over scroll position. All other text editors, besides StageTextTextEditor, should work the same way.

**Comment by oskaraqp** [comment]
All this makes perfect sense, the new change you propose will be really helpfull, one thing is that I don't see focus in change after the first selection so maybe tha could be a problem in case I selecto one range first and then change my mind and make other change, maybe each time we made a new selection we could fire focus in, or maybe a new event for foxus selection change.

**Comment by oskaraqp** [comment]
Hi josh, is it possible to move this line this.stageText.selectRange(1, 1); on stageText_focusOutHandler function to the end of the function? the reason is that since the range is changed to 1 before focus out is fired, once I check focus out in my application the real range selected is lost and I always get 1 as index selected, I did the change and it works but no sure which one would be the problem to put that line of code after focus_out is fired like this 

protected function stageText_focusOutHandler(event:FocusEvent):void
		{
			this._stageTextHasFocus = false;
			//since StageText doesn't expose its scroll position, we need to
			//set the selection back to the beginning to scroll there. it's a
			//hack, but so is everything about StageText.
			//in other news, why won't 0,0 work here?

			//this.stageText.selectRange(1, 1);

			this.invalidate(INVALIDATION_FLAG_DATA);
			this.invalidate(INVALIDATION_FLAG_SKIN);
			this.dispatchEventWith(FeathersEventType.FOCUS_OUT);
			
			this.stageText.selectRange(1, 1);
		}

btw the reason to do this is because I have a keyboard on screen and once I press on a key I lost focus but I need to knwo where th cursor was in order to start modyfing from there. Thanks.

**Comment by joshtynjala** [comment]
That may be something I can do. I'll play around with it.

> btw the reason to do this is because I have a keyboard on screen and once I press on a key I lost focus but I need to knwo where th cursor was in order to start modyfing from there. Thanks.

Setting the new maintainTouchFocus property on StageTextTextEditor to true may be able to help you with this one. It will prevent the StageText from losing focus when you touch something else.

**Comment by oskaraqp** [comment]
Awesome I'll play with that property, thanks for trying my suggested change,  Im already using it on desktop app and no issues.

**Comment by oskaraqp** [comment]
This property doesn't look to have some effect as soon as I press somewhere else I lost the focus on the textfield, I'm not using focus manager btw, let me know if there's more info related as I was no able to find docs or samples related on the web. Btw have you checked the change I did doesn't alter the normal behaviour of the API?

**Comment by joshtynjala** [comment]
Make sure that you're using AIR 22 and that your swf-version is not for an older version. maintainTouchFocus uses a feature that was just recently added to StageText. It also does not work when simulating on desktop in ADL. Only on a real device. FocusManager is not required.

It is not in a stable version (only on Github), so there are no online docs yet.

> Btw have you checked the change I did doesn't alter the normal behaviour of the API?

Not yet. I have a reminder to check it out when I have some time.

**Comment by oskaraqp** [comment]
Yes I'm using version 22.0.0.153 and yes the swf is updated, this is a desktop application using flash cs6 on windows, using the github version the files were updated today, I'll keep testing.

**Comment by joshtynjala** [comment]
If it's a desktop app, it won't work. It seems that StageText only supports cancelling mouse/touch focus change on mobile. However, if you use TextFieldTextRenderer, I think you can get it to work on desktop. It now has the same maintainTouchFocus property too.

**Comment by oskaraqp** [comment]
ok I'll test that, thank you.
