### ISSUE TITLE
tileHorizontalAlign = HorizontalAlign.JUSTIFY; Does't work as expected.

### ISSUE THREAD

**Issue by GV3** [BowlerHatLLC/feathers#1370]
Hi I'm having the following issue with the TiledRowsLayout.

A ScrollContainer with 3 Panel children in a TiledRowsLayout... the ScrollContainer is on an AnchorLayout and I expected that the `tileHorizontalAlign = HorizontalAlign.JUSTIFY;` property would resize the width of the Panels to fill the space of the tile and look as in the image below.

![inbox](https://cloud.githubusercontent.com/assets/1840077/15138051/9241f834-168d-11e6-8cba-1bb0c6dc6b3b.png)

The panels do not resize to the width of the tile, and instead they ust take the size of the content... 

But.... the `tileHorizontalAlign = HorizontalAlign.JUSTIFY` is working, becuase all the tiles take the width of the widest tile.

This is the code:

```
        var listContainerLayout:TiledRowsLayout = new TiledRowsLayout();
        listContainerLayout.paging = TiledRowsLayout.PAGING_HORIZONTAL;
        listContainerLayout.useSquareTiles = false;
        listContainerLayout.tileHorizontalAlign = HorizontalAlign.JUSTIFY;
        listContainerLayout.tileVerticalAlign = VerticalAlign.TOP;
        listContainerLayout.horizontalAlign = HorizontalAlign.CENTER;
        listContainerLayout.verticalAlign = VerticalAlign.TOP;
        listContainerLayout.requestedRowCount = 1;
        listContainerLayout.requestedColumnCount = 1;
        scrollContainer.layout = listContainerLayout;
```

Is it wrong to expect that the Panels will fill up the space of the Column when using` tileHorizontalAlign = HorizontalAlign.JUSTIFY;`?

Currently I had to give the Panel a specific width, but I feel very uncomfortable about doing so.

**Comment by joshtynjala** [comment]
Your confusion is with what the size of the tile should be. Even if a page only shows one tile, that doesn't mean that the tile will fill the entire width of the page. The tile width is the width of the largest child in the container.

**Comment by joshtynjala** [comment]
There is a feature request open to add a way to make the tiles fill the entire container: #1285

**Comment by GV3** [comment]
I understand... May I ask you how would you solve this situation then in the meantime if you would like to have the width of the container in the current version of Feathers?

Another question also related to the tiles. I have the panel in the image above growing vertically with each item added to the list... But I want that at some point the panel doesn't grow more... At the moment, I'm using max height... But I wonder if there is a way that the Panel knows that the height of the tile doesn't allow it to grow more and for it to remain constrained within the area of the tile. Any ideas how to achieve this? 

This could be part of the new feature request if you find it relevant

**Comment by joshtynjala** [comment]
> I understand... May I ask you how would you solve this situation then in the meantime if you would like to have the width of the container in the current version of Feathers?

You might be able to use the pageWidth or the width of the container in some kind of calculating.

> But I wonder if there is a way that the Panel knows that the height of the tile doesn't allow it to grow more and for it to remain constrained within the area of the tile. Any ideas how to achieve this? 

VerticalAlign.JUSTIFY will make the panel fill the entire height of the tile, but the Panel will never be smaller than the tile, so it wouldn't grow until stopping. maxWidth really is your best option. Off the top of my head, I can't really think of a good way to do it differently.

**Comment by GV3** [comment]
Understood, thanks Josh
