### ISSUE TITLE
Alert: button group horizontal alignment ignored if distributeButtonSizes == true

### ISSUE THREAD

**Issue by serjek** [BowlerHatLLC/feathers#1371]
Following code should render buttongroup with buttons filling alert's footer, but they got aligned to left instead.

```
protected function setAlertButtonGroupStyles(group:ButtonGroup):void
		{
			group.direction = Direction.HORIZONTAL;
			group.horizontalAlign = HorizontalAlign.JUSTIFY;
			group.verticalAlign = VerticalAlign.JUSTIFY;
			group.distributeButtonSizes = true;
			group.gap = this.smallGutterSize;
			group.padding = this.smallGutterSize;
			group.customButtonStyleName = THEME_STYLE_NAME_ALERT_BUTTON_GROUP_BUTTON;
}

```
<img width="510" alt="screenshot 2016-05-13 19 20 10" src="https://cloud.githubusercontent.com/assets/18265157/15254493/264efb14-1948-11e6-83fa-f6b5b282eaaa.png">

**Comment by joshtynjala** [comment]
I replaced setAlertButtonGroupStyles() in BaseMetalWorksMobileTheme with your code, and I could not reproduce the issue. For me, the buttons filled the entire width of the alert.

**Comment by serjek** [comment]
Oh right! I forgot about setting 
```
alert.maxWidth = 220;
alert.minWidth = 220;
```
in AlertScreen. Sorry!
