### ISSUE TITLE
Error when press Back button on Android device on StageWebView

### ISSUE THREAD

**Issue by khoamoc** [BowlerHatLLC/feathers#1372]
Hi, I got this error every time I press the Back button on my Android device when viewing web view.

ArgumentError: Error #1063: Argument count mismatch on com.vinaok.layout::WebScreen/backButton_triggeredHandler(). Expected 1, got 0.
	at feathers.controls::Screen/screen_nativeStage_keyDownHandler()[C:\Users\ANH2\Desktop\lab\feathers\controls\Screen.as:340]
	at flash.events::EventDispatcher/dispatchEventFunction()
	at flash.events::EventDispatcher/dispatchEvent()
	at flash.display::Stage/dispatchEvent()
	at StageWebViewImpl/onKeyDown()

**Comment by joshtynjala** [comment]
It looks like you assigned backButton_triggeredHandler to the screen's backButtonHandler property. When the screen calls its backButtonHandler, it passes zero arguments. However, it looks like that's an event listener that you created with one argument. You either need to make the argument optional, or you need to call a different function.

**Comment by joshtynjala** [comment]
To be clear, this is unrelated to StageWebView.

**Comment by khoamoc** [comment]
Hi, I do NOT assign any handler, for that screen, the backButton_triggeredHandler is the handler of the physical Back button on android device.

**Comment by joshtynjala** [comment]
According to the stack trace, screen_nativeStage_keyDownHandler() appears to calling your backButton_triggeredHandler() function. It should only be doing that if you set the backButtonHandler property.
