### ISSUE TITLE
TapToSelect could use a method to pass the children in the CustomItemRenderer that are to be ignored.

### ISSUE THREAD

**Issue by GV3** [BowlerHatLLC/feathers#1373]
In the BaseDefaultItemRenderer we have the `isSelectableOnAccessoryTouch`, which is great!

We also have now the TapToSelect and the TapToTrigger, which are Genius solutions for the custom ItemRenderers!

But now I'm writing a custom Item renderer with interactive children (Button, checkbox, etc...) and don't find an easy way to avoid the TapToSelect from dispatching. I was hoping to find a method to set the Children to be ignored by the Tap or Touch, example `this._tapToSelect.ignore(_aToogleButton)`;

If there is an easy way to achieve this, please enlighten me. I have listeners on the TRIGGER event of the button and try to stop propagation, but it's not working.

`event.stopImmediatePropagation();
event.stopPropagation();`

**Comment by joshtynjala** [comment]
Makes sense! I'll try to get it into the next version.

**Comment by GV3** [comment]
Thanks Josh!
Any ideas how to make it work in the meantime? Or should I go to the good-old touchHandler in the Renderer?

**Comment by joshtynjala** [comment]
You could either subclass it and override the listener, or create your own touch event listener.
