### ISSUE TITLE
IFeathersControl and Starling Sprite

### ISSUE THREAD

**Issue by khoamoc** [BowlerHatLLC/feathers#1375]
Hi, 
Upon moving from Starling 1.7 + Feathers 2.3 to Starling 2.0 + Feathers 3.0, i got this error, is this a change in Starling or Feathers? ( this works on Starling 1.7 and Feathers 2.3)
--------------------
Stack : 
1067: Implicit coercion of a value of type starling.display:Sprite to an unrelated type feathers.core:IFeathersControl.
---------------
Code:
public class Main extends Drawers{
.....
this.bottomMenuHolder = new Sprite();
this.bottomDrawer = this.bottomMenuHolder;

**Comment by joshtynjala** [comment]
Drawers now requires a Feathers component. A Sprite cannot be used as a drawer anymore. You might consider switching to LayoutGroup instead.

**Comment by joshtynjala** [comment]
I'll add a note to the migration guide.
