### ISSUE TITLE
Desktop - TextInput cursor some times never switches back to the pointer from the bar

### ISSUE THREAD

**Issue by teotigraphix** [BowlerHatLLC/feathers#1376]
I can't get a repro on this but it does it at least half the time.

If you have an input focused, then quickly mouse out you cannot get the pointer icon back.

**Comment by joshtynjala** [comment]
Which ITextEditor?

**Comment by teotigraphix** [comment]
This is what I have in my theme;

```
    public function setTextInputTextEditorStyles(textEditor:StageTextTextEditor):void
    {
        textEditor.fontFamily = "Helvetica";
        textEditor.fontSize = font.regularFontSize;
        textEditor.color = FontFactory.LIGHT_TEXT_COLOR;
        textEditor.disabledColor = FontFactory.DISABLED_TEXT_COLOR;
    }
```

**Comment by joshtynjala** [comment]
Okay, good to know. It may be that StageText is causing issues with Starling's hover events.

Is there any chance that this is happening specifically when you scroll with the mouse wheel? Or does it happen when you move the mouse too?

**Comment by teotigraphix** [comment]
It's a weird bug, I am trying to reproduce it but I am sure it has to do with mouse down -> hover out or something.

It's not that important, I ma just running my mobile apps as desktop for some people to test, so it's not like its some released thing but others may run into it on the desktop.

**Comment by teotigraphix** [comment]
Oops wrong button. :)

**Comment by joshtynjala** [comment]
> I am sure it has to do with mouse down -> hover out or something.

That's what I needed to know! It's when TouchPhase.ENDED happens outside the bounds of the TextInput. I can reproduce.

**Comment by teotigraphix** [comment]
HA, yeah I knew it had something to do with a "drag" gesture, that's what it felt like.
