### ISSUE TITLE
TextCallout ignores maxWidth

### ISSUE THREAD

**Issue by DerBensch** [BowlerHatLLC/feathers#1378]
I am using the errorString property on the TextInput noticed if the TextCallout would be bigger than the stageWidth the maxWidth ist set and the textRenderer should show multiple lines. In my case it only shows one line.

I reproduced the problem by adding a TextCallout directly:
```actionscript
var textCallout:TextCallout = new TextCallout();
textCallout.maxWidth = 300;
textCallout.text = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla nunc neque, scelerisque nec ex in, aliquam porttitor dolor. Nullam quis eros non ligula pharetra efficitur.";
addChild(textCallout);
```

The text is cut off after one line. If you change maxWidth to width it works correctly.

Is this a bug or am I misunderstanding something?

**Comment by joshtynjala** [comment]
That sounds like a bug to me!

**Comment by joshtynjala** [comment]
I could not reproduce what you describe, actually. Setting either maxWidth or width would cause the text to be truncated for me. Neither would wrap to the next line. Regardless, I added a wordWrap property to TextCallout, and it defaults to true, so wrapping will happen unless you explicitly disable it.

**Comment by DerBensch** [comment]
I can still reproduce this issue.
Here is the code of the initialize function of the root class:

```actionscript
override protected function initialize():void {
	super.initialize();

	var textCallout:TextCallout = new TextCallout();
	textCallout.width = 300;
	textCallout.textRendererFactory = textRendererFactory;
	textCallout.text = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla nunc neque, scelerisque nec ex in, aliquam porttitor dolor. Nullam quis eros non ligula pharetra efficitur.";
	addChild(textCallout);

	textCallout = new TextCallout();
	textCallout.y = 100;
	textCallout.maxWidth = 300;
	textCallout.textRendererFactory = textRendererFactory;
	textCallout.text = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla nunc neque, scelerisque nec ex in, aliquam porttitor dolor. Nullam quis eros non ligula pharetra efficitur.";
	addChild(textCallout);
}
```

And here is the result:

![image](https://cloud.githubusercontent.com/assets/18053962/15542583/a57a3df2-2291-11e6-8e83-5ec1b70f3cce.png)

**Comment by joshtynjala** [comment]
That's weird. I can reproduce with your original code now, but it was working fine yesterday.

**Comment by DerBensch** [comment]
Strange. At least you could reproduce it :)
I will test if the fix works on Friday.
Thank you

**Comment by DerBensch** [comment]
Ok, it works correctly.
