### ISSUE TITLE
An Error is triggered by keyboard.

### ISSUE THREAD

**Issue by daicemirror** [BowlerHatLLC/feathers#1379]
Testing in feathers.examples.componentsExplorer.
I modified the code in ComponentsExplorerTheme Class below.
`ComponentsExplorerTheme extends MetalWorksDesktopTheme`
To quickly test keyboard functionality.
Then using spacebar to close the alert message in AlertScreen.
There is an error would be triggered.

Another problem is when I test changing focus target by Tab+Shift key in ButtonScreen, the focus target could be selected Cyclically.
However, Forward selection loop would be stopped at the List of MainMenu.
Is this a bug?

Thanks!

**Comment by joshtynjala** [comment]
> Then using spacebar to close the alert message in AlertScreen.
> There is an error would be triggered.

Thank you! I can reproduce this issue.

>  However, Forward selection loop would be stopped at the List of MainMenu.

There are no other components on MainMenuScreen that may receive focus. It is still looping, but it always returns to the same list. This is working as intended.

**Comment by daicemirror** [comment]
Hi, I may provide a bad description before.
When the focus on List on MainMenuScreen, backwards selection(Tab+Shift ) can loop focus on components between ButtonGroupScreen and MainMenuScreen.
But forward selection didn't.
This is an expected behavior?

**Comment by joshtynjala** [comment]
When the list on MainMenuScreen is focused, I cannot make it change focus to anything in the ButtonGroupScreen when I use Shift+Tab. The other screens are disposed when the MainMenuScreen is shown, so that does not seem possible.

**Comment by daicemirror** [comment]
That is strange.  I can reproduce this behavior after updating.
By only changing this code `ComponentsExplorerTheme extends MetalWorksDesktopTheme` in ComponentsExplorerTheme Class.
The focus frame could be moved to the Forward Button of ButtonScreen from the List of MainMenuScreen  ,when I use Shift+Tab.

**Comment by joshtynjala** [comment]
Can you write out some detailed steps to reproduce the issue? Maybe I'm just not understanding exactly when I should try to do it.

**Comment by daicemirror** [comment]
There are no more detailed steps to reproduce...
What I do is just using Shift+Tab key and check it out.
![animation](https://cloud.githubusercontent.com/assets/18619085/15369895/365f6eee-1d67-11e6-9736-a586dca9cf31.gif)
On the above, there is the loop focus behavior.
Hope I do not have a wrong description.

**Comment by joshtynjala** [comment]
Your screenshot tells me what I was missing. I didn't know you were testing in a tablet layout. I was using a phone layout to test, so only the main menu was visible.

**Comment by joshtynjala** [comment]
I can reproduce. I opened a separate issue since this is completely unrelated to the runtime error with the Alert buttons: #1380

**Comment by daicemirror** [comment]
So that's how it is.
I was thinking it was caused by my poor English.
Maybe a little..  ha ha

Thanks as always!
