### ISSUE TITLE
Bottom Drawer does not initially size correct with left drawer docked

### ISSUE THREAD

**Issue by teotigraphix** [BowlerHatLLC/feathers#1382]
The initial measurement takes into account the content area of the Drawer, not the full stage.

Once touch dragged, you get image 2.

I waited on this, I found it the other day but I am now using beta2 sdk, so I am posting.

![capture](https://cloud.githubusercontent.com/assets/226417/15428580/3735e66e-1e6a-11e6-9061-791e06aec61d.PNG)

![capture2](https://cloud.githubusercontent.com/assets/226417/15428583/39971dc4-1e6a-11e6-8b8e-eff043936629.PNG)

**Comment by teotigraphix** [comment]
BTW, I did switch to BottomDrawerPopUpContentManager but I thought I would post this before I forgot.

**Comment by joshtynjala** [comment]
> Once touch dragged, you get image 2.

So does that mean that you initially opened it without dragging? Such as by setting isBottomDrawerOpen or by calling toggleButtonDrawer()?

**Comment by teotigraphix** [comment]
Yes;

```
toggleButtonDrawer()
```

**Comment by joshtynjala** [comment]
Thanks! I'll take a look.

**Comment by joshtynjala** [comment]
The leftDrawer isn't docked, is it? Both the left drawer and bottom drawer are open? I never thought someone would try that...
