### ISSUE TITLE
Can't get the expected dimensions of tabBar after tabBar.validate() was called.

### ISSUE THREAD

**Issue by daicemirror** [BowlerHatLLC/feathers#1384]
This test is on TabBarScreen of componentsExplorer example.
add code below in TabBarScreen  class:
```
override protected function initialize():void
{
	...
	trace(_tabBar.width);//0
	_tabBar.validate();
	trace(_tabBar.width);//214
	this.addEventListener( FeathersEventType.CREATION_COMPLETE, creationCompleteHandler );
}
private function creationCompleteHandler(e:Event):void 
{
	trace(_tabBar.width);//826
}
```
This issue is same for _tabBar.direction = "vertical".

Thanks!

**Comment by joshtynjala** [comment]
The width of the TabBar is set by the TabBarScreen's AnchorLayout. Not by the TabBar itself. With that in mind, it won't be set until the TabBarScreen validates too. A listener for FeathersEventType.CREATION_COMPLETE is indeed the correct place to get the width after the first validation of the screen. Alternatively, you could possibly override draw() and get the width after super.draw(). The right approach kind of depends on exactly why you need the width

**Comment by daicemirror** [comment]
I see.
Thanks for your patient !
