### ISSUE TITLE
Feature question - ListCollection.selectedIndex/Item

### ISSUE THREAD

**Issue by teotigraphix** [BowlerHatLLC/feathers#1388]
Hi,

I use the ListCollection extensively for backing change delegation on concrete model vectors.

I find myself over and over again adding selectedIndex/Item to my model when it could really be appropriate in ListCollection.

My thought is, all you would need is a selectedIndexChange type added to CollectionEventType, and some simple logic to check when items are removed to update the index to a valid index and dispatch the change event.

Thoughts?

**Comment by joshtynjala** [comment]
This sounds like a great place for you to create a subclass. Multiple components might use the same ListCollection, but they may also need different selected indices, so the base ListCollection needs to remain more flexible.

**Comment by teotigraphix** [comment]
Yeah, yeah, yeah. :) I was about to close it, but I wanted to see how you would come back and smack me for even considering it. haha

Then again, I started stepping through my code and how I get change listeners from the List and realized this wouldn't solve anything.

But I think you know me by now, sometimes I talk before thinking, it's ok sometimes.

**Comment by joshtynjala** [comment]
😄
