### ISSUE TITLE
Unnecessary assignment in TextBlockTextRenderer

### ISSUE THREAD

**Issue by Klug76** [BowlerHatLLC/feathers#1390]
Found unnecessary assignment in TextBlockTextRenderer, maybe something is missing?
```
				var line:TextLine = textLines[i];
				if(line.validity === TextLineValidity.VALID)
				{
					lastLine = line;
					textLines[i] = line;//???
					continue;
```

**Comment by joshtynjala** [comment]
It should be perfectly safe to make this change, but I'm extra paranoid close to a stable release. I'm going to leave it until I start working on 3.1.
