### ISSUE TITLE
Some case get into Infinite loop.

### ISSUE THREAD

**Issue by daicemirror** [BowlerHatLLC/feathers#1391]
Testing with componentsExplorer example in a tablet layout.
Case a:
Click PickerList button on PickerListScreen.
Case b:
Trigger the bottom Button on TextCalloutScreen and then resize the width of window close to value of callout's width.(The same issues on CalloutScreen.)
Case c:
Trigger the left Button on TextCalloutScreen and then resize the height of window close to value of callout's height.(Set callout.padding = 100 could reproduce easier.)

Thanks!

**Comment by joshtynjala** [comment]
Yeah, I found "Case a" yesterday. I have the infinite loop fixed locally, but it was partially caused by another issue that I'm still fixing. I'll check that Case b and c are fixed too.
