### ISSUE TITLE
VerticalLayout not laying out two horizontal layouts with percentages, height is wrong

### ISSUE THREAD

**Issue by teotigraphix** [BowlerHatLLC/feathers#1393]
This stumped me for a while, because it was a regression, I had code that made an easy 2 row, 4 item grid where each tile was the same square size.

When I went back to that code, the vertical layout is sizing the first row the same size as it's height instead of 1/2.

Since we have two rows in the vertical layout, you would expect 2 rows, not one stretched full. I tried to boil my code down the best I could, this does demostrate the bug. I just have it in an Application with a single VerticalLayout

```
            protected function this_initializeHandler(event:starling.events.Event):void
            {
                var button:ToggleButton;
                
                var hl:HorizontalLayout;
                var vld:VerticalLayoutData;
                
                var top:LayoutGroup = new LayoutGroup();
                hl = new HorizontalLayout();
                vld = new VerticalLayoutData(100, 100);
                
                top.layout = hl;
                top.layoutData = vld;
                
                var bottom:LayoutGroup = new LayoutGroup();
                hl = new HorizontalLayout();
                vld = new VerticalLayoutData(100, 100);
                
                bottom.layout = hl;
                bottom.layoutData = vld;
                
                for (var i:int = 0; i < 4; i++)
                {
                    button = createButton(i);
                    top.addChild(button);
                }
                
                for (i = 4; i < 8; i++)
                {
                    button = createButton(i);
                    bottom.addChild(button);
                }
                
                addChild(top);
                addChild(bottom);
            }
            
            private function createButton(index:int):ToggleButton
            {
                var button:ToggleButton = new ToggleButton();
                button.layoutData = new HorizontalLayoutData(100, 100);
                button.hasLabelTextRenderer = false;
                return button;
            }
```

**Comment by joshtynjala** [comment]
I can reproduce, and it looks like this is a side effect of my fixes from #1367. This is going to be a tricky one.

**Comment by teotigraphix** [comment]
Damn that sucks. For now I just rewrote the 2 components to use FeathersControl and I am just manually laying out the children. I was lazy anyway doing what I did. :)

**Comment by joshtynjala** [comment]
Okay, so i think I have it working properly now. That layout with the two rows is fixed, and virtualization with the previous test cases from #1367 is still working.

I had to add a bit of a hack in there to avoid an issue where a container might invalidate every frame and hurt performance. I think I know how to fix it without the hack, but I'm wary to make that particular change right before a release. It would be better for me to try it once I start working on 3.1 so that people have more time to test it out. In the meantime, I think the hack won't have as many potential side effects.

I'll merge the mxml branch right away next week so that you can try it out with your layouts.

**Comment by teotigraphix** [comment]
Ok, I have a pretty good sense of the performance with all my other complex components so I should be able to spot any weirdness if introduced.
