### ISSUE TITLE
TextFieldTextEditor freezes UI for 1 sec

### ISSUE THREAD

**Issue by subdan** [BowlerHatLLC/feathers#1397]
Hello.

I downloaded Feathers UI 3.0.0, and Starling 2.0.1.
I compiled and run HelloWorld example.
Everything is ok, but when I change default textRendererFactory from TextBlockTextRenderer to TextFieldTextRenderer:

```
	protected static function textRendererFactory():ITextRenderer
		{
			return new TextFieldTextRenderer();
		}

```

UI freezes for 1 sec. Why?

![Screenshot](http://subdan.ru/123.png)

Button.createLabel method time is 938 ms. When I use TextBlockTextRenderer time is 1 ms!

I added trace in the initialize function of the TextFieldTextRenderer class.

```
override protected function initialize():void
		{
			if(this.textField === null)
			{
				this.textField = new TextField();
				var starling:Starling = this.stage !== null ? this.stage.starling : Starling.current;
				var scaleFactor:Number = starling.contentScaleFactor;
				this.textField.scaleX = scaleFactor;
				this.textField.scaleY = scaleFactor;
				this.textField.mouseEnabled = this.textField.mouseWheelEnabled = false;
				trace("Before", getTimer());
				this.textField.selectable = false;
				trace("After", getTimer());
				this.textField.multiline = true;
			}
		}
```

And gotten this output:
Before 601
After 1518

Why selectable = false takes 917 ms?

**Comment by joshtynjala** [comment]
It's an Adobe AIR bug.

https://bugbase.adobe.com/index.cfm?event=bug&id=4131841

**Comment by subdan** [comment]
Ok. Thanks.
