### ISSUE TITLE
3D Transition causes that the content appears weird.

### ISSUE THREAD

**Issue by daicemirror** [BowlerHatLLC/feathers#1401]
Add code below in the Main class of TransitionsExplorer example.
```
override protected function initialize():void
{
    ...
    var panel:Panel = new Panel();
    content1.addChild( panel );
    panel.title = "Tools";
    var xPosition:Number = 0;
    for(var i:int = 0; i < 5; i++)
    {
        var quad:Quad = new Quad( 100, 100, 0xff0000 );
        quad.x = xPosition;
        panel.addChild( quad );
        xPosition += quad.width + 10;
    }
}
```
Then using  Flip or Cube Transition can reproduce that the Panel content displays weird at appearing.

Some components get similar problems if changing Transition to Flip or Cube in ComponentsExplorer example.
![animation](https://cloud.githubusercontent.com/assets/18619085/16172688/02adb058-35c0-11e6-8257-b1c97e691478.gif)

Thanks!

**Comment by joshtynjala** [comment]
If you set clipContent to false on the Panel, it will work. I believe this is simply a limitation of Starling. 3D effects and masks don't play well together.
