### ISSUE TITLE
Could you please give binding an event handler?

### ISSUE THREAD

**Issue by flashflexpro** [BowlerHatLLC/feathers#1404]
When you get binding working.

Flex binding's destination has to be a setter, which means:

<?:Binding source="country.city.street.house" destination="selectedHouse"/> selectedHouse has to be a setter, the problem is is that we do not know which change( country change? city change? street or house changed ) is triggering this setter, so,

Would you please give binding an event handler( in addition to setter ), for example

<?:Binding source="country.city.street.house" handle="onHouseChange( someChangedEvent )"/>

the someChangedEvent would be the event that triggering the setter, so developers can access more infomation like someChangedEvent.target.

Thankyou!

**Comment by joshtynjala** [comment]
I would prefer not to change the way that something from Flex behaves.
