### ISSUE TITLE
ScreenDensityScaleFactorManager scale issue

### ISSUE THREAD

**Issue by khoamoc** [BowlerHatLLC/feathers#1405]
Hi, i got issue with ScreenDensityScaleFactorManager:
Working Feathers 2.3 code: ( my customised image button )
			this.button = new Button();
			this.button.styleProvider = null;
			this.button.defaultSkin = new Image( Cfg.assets.getTexture("Btn_FBlogin") );
			this.button.hasLabelTextRenderer = false;
			this.addChild(this.button);
it's not working with Feathers 3, when I use ScreenDensityScaleFactorManager, the skin keep zooming. ( I also tried AddOnFunctionStyleProvider but also zooming ) but when using Feathers 3 starling viewport stageWidth and stageHeight, it works

**Comment by joshtynjala** [comment]
When using ScreenDensityScaleFactorManager, the scaling is now controlled by Starling with contentScaleFactor. This means that it becomes important to choose the right scale factor when creating your textures (either directly or with the AssetManager). With Feathers 2.3, you probably created all of your textures with scale factor 1. This may not necessarily be true with ScreenDensityScaleFactorManager.

If your textures are meant to be scaled same amount as the textures in the example themes, you want to use scale factor 2. The original textures in the example themes are designed specifically for this scale factor.

In the future, or is probably better to ask a question like this on [the forums](http://forum.starling-framework.org). More of the experts in the community will have a chance to answer. Thanks!
