### ISSUE TITLE
Basic app, restoring on Android is a blank screen

### ISSUE THREAD

**Issue by teotigraphix** [BowlerHatLLC/feathers#1407]
I didn't know whether to post this on the forum or sdk or here. So I just decided here but I am using the SDK.

I have the most simple app;

```
<?xml version="1.0" encoding="utf-8"?>
<f:Application xmlns:f="library://ns.feathersui.com/mxml"
               xmlns:fx="http://ns.adobe.com/mxml/2009"
               theme="feathers.themes.MetalWorksMobileTheme"
               initialize="this_initializeHandler(event)">

    <f:layout>
        <f:VerticalLayout horizontalAlign="center"
                          verticalAlign="middle"/>
    </f:layout>

    <f:Label text="Hello Test App!"/>

    <fx:Script>
        <![CDATA[
            import starling.events.Event;
            
            protected function this_initializeHandler(event:starling.events.Event):void
            {
            
            }
        ]]>
    </fx:Script>

</f:Application>
```

When running this on my Nexus 7 (2nd gen) Android 6.0.1 the initial app loads fine and displays the correct text. But when navigating out of the app with back or recent apps button, then navigating back into the app(without a destroy call), the screen is just black, the background and label are gone.

I'm posting this because either I have something completely stupid wrong with MetaWorksMobile swc setup OR something is wrong with context restore or something.

So yeah, I have a few apps that use my own custom async theme and they work fine with restoring, but I needed to make this simple app for some of my testers and I realized it does not restore correctly.

**Comment by teotigraphix** [comment]
A little more info. I am debugging this on Android and I have activate and deactivate handlers. When I exit the app with the active apps button, I get deactivate and go back into the app I get activate. 

I have breakpoints at both locations.

Now I haven't used this theme in a long time but it's the embedded version not the asset manager version. So we have MetalWorksMobileTheme.atlasTexture_onRestore().

I am NOT getting a call to this method on activate. Isn't this supposed to fire on Android after the app has been restored as the top level application?

**Comment by joshtynjala** [comment]
> So we have MetalWorksMobileTheme.atlasTexture_onRestore().

> I am NOT getting a call to this method on activate. Isn't this supposed to fire on Android after the app has been restored as the top level application?

Yes, atlasTexture_onRestore should be called by Starling after the context is re-created.

**Comment by joshtynjala** [comment]
This is a Starling 2 bug:
http://forum.starling-framework.org/topic/starling-20-black-screen-after-returning-from-background

There are two known workarounds:

1) Set skipUnchangedFrames to false on the application.

2) On activate, manually call Starling's start() and render() functions.

**Comment by joshtynjala** [comment]
However, I see that StarlingBootstrap does not stop rendering on mobile when the app deactivates (and restart it on activate). I'm going to fix that, and this will end up calling start(), which should be enough to make it work automatically in most cases.

**Comment by teotigraphix** [comment]
Maybe that is why my themes work in my Caustic apps? I have a subclass of StarlingBootstrap and I call start and stop in the activate and deactivate handlers.

**Comment by joshtynjala** [comment]
Most likely. In 3.0.2, you shouldn't need to do that.

**Comment by teotigraphix** [comment]
So is this just something that like feathers 3.x is new and people haven't run into it yet? It seems like this could affect a lot of apps if people were not stopping and starting Starling.

**Comment by joshtynjala** [comment]
I've noticed that a lot of people who are using the SDK write their own bootstrap class. Most likely, they're stopping and starting Starling in their custom bootstrap, and this issue doesn't come up.

There's also the fact that not many people use the SDK compared to the UI library, so this issue doesn't affect everything using Feathers 3.0.

**Comment by teotigraphix** [comment]
Ah yeah, short sighted thinking on my part. I am having a dumb moment here but what is it about people using Feathers themes in the UI that is different from the SDK?

**Comment by izzmeifter** [comment]
Interesting. Using the SDK and 3.0.1 were not experiencing anything like this, and we've not added in any workarounds.

**Comment by joshtynjala** [comment]
This issue has nothing to do with the theme. For some reason, when skipUnchangedFrames is true, Starling doesn't properly render when the app comes back from the background on Android (so you get a black screen). If you call start() on activate, Starling automatically calls setRequiresRedraw(), which seems to jump start everything again.

I don't know how I missed including stop() and start() Starling in StarlingBootstrap when on mobile, but it'll be there now, so this issue shouldn't come up.

**Comment by joshtynjala** [comment]
@izzmeifter Are you using a custom bootstrap for Starling? If so, then you might be doing the right thing to avoid the issue.

It's also worth mentioning that this seems to affect Android specifically. However, it also might not affect all versions of Android.

**Comment by izzmeifter** [comment]
Essentially at this point, were just using the 2.3 Bootstrap until we can resolve the scaling issue. I'll try updating to the 3.0.2 Bootstrap and test it and try to resolve our scaling stuff. Thanks @joshtynjala  and thanks @teotigraphix for mentioning this.

**Comment by joshtynjala** [comment]
If you're using an older StarlingBootstrap, then skipUnchangedFrames is probably false. To see the issue, skipUnchangedFrames needs to be true.
