### ISSUE TITLE
Feathers Label component doesn't update text if skipUnchangedFrames is set to true

### ISSUE THREAD

**Issue by subdan** [BowlerHatLLC/feathers#1411]
I use Label with TextBlockTextRenderer.
To fix this issue I call setRequiresRedraw(); in Label.as class:

```
/**
* @private
*/
protected function refreshTextRendererData():void
{
  this.textRenderer.text = this._text;
  Starling.current.setRequiresRedraw();
  this.textRenderer.visible = this._text && this._text.length > 0;
}
```

**Comment by joshtynjala** [comment]
I am not able to reproduce this issue. With the following code, the label text is updated correctly when the button is triggered:

	var label:Label = new Label();
	label.move(50, 50);
	label.text = "Hello World";
	this.addChild(label);
	
	var button:Button = new Button();
	button.label = "Click Me";
	button.addEventListener(Event.TRIGGERED, function():void
	{
		label.text = "New Text";
	});
	button.move(50, 100);
	this.addChild(button);

I also tried using a delayed call, instead of the button, to avoid affecting other parts of the display list, and the label still updated:

	Starling.juggler.delayCall(function():void
	{
		label.text = "New Text";
	}, 2.0);

Can you provide some code that will reproduce the issue? I'd like to be able to test it, and possibly write an automated test. Thank you!

**Comment by 22Round** [comment]
@joshtynjala I had the same issue when I updated label text value with TweenLite class, it skipped some frames, than manually called onUpdate callbeck setRequiresRedraw() and everything fixed.

**Comment by izzmeifter** [comment]
Having a somewhat similar issue but with TextInput. Changing a TextInput from visible=false to visible=true sometimes doesn't show any of the content. Currently investigating (Android only)

Turning off skipUnchangedFrames does fix the issue.

**Comment by subdan** [comment]
Check the next code:
```
package
{
	import feathers.controls.Label;
	import feathers.controls.text.TextBlockTextRenderer;
	import feathers.core.ITextRenderer;

	import flash.text.engine.ElementFormat;
	import flash.text.engine.FontDescription;
	import flash.text.engine.FontLookup;
	import flash.utils.setTimeout;

	import starling.display.Sprite;

	public class StarlingRoot extends Sprite
	{
		private var question:Label;

		public function StarlingRoot()
		{
			question = new Label();
			question.width = 500;
			question.textRendererFactory = function ():ITextRenderer
			{
				var renderer:TextBlockTextRenderer = new TextBlockTextRenderer();
				var font:FontDescription = new FontDescription("Arial");
				font.fontLookup = FontLookup.DEVICE;
				renderer.elementFormat = new ElementFormat(font, 24, 0x000000);
				return renderer;
			};
			question.text = "Initial text";
			addChild(question);

			setTimeout(changeText, 1000);
		}

		private function changeText():void
		{
			question.text = "New text";
		}
	}
}
```

If I comment `question.width = 500;` line text change.

**Comment by joshtynjala** [comment]
@subdan Thanks! That's exactly what I needed.

**Comment by joshtynjala** [comment]
For my own future reference, here's a simpler test case:

	var text:TextBlockTextRenderer = new TextBlockTextRenderer();
	text.x = 50;
	text.y = 50;
	text.width = this.stage.stageWidth - text.x;
	text.text = "Hello World";
	this.addChild(text);
	
	Starling.juggler.delayCall(function():void
	{
		trace("changing text!");
		text.text = "New Text";
	}, 2.0);

TextBlockTextRenderer can be changed to TextFieldTextRenderer, StageTextTextEditor, or TextFieldTextEditor to reproduce a similar issue in those classes.

**Comment by joshtynjala** [comment]
This seems critical enough to release a 3.0.3 update. However, I plan to wait until at least the end of next week to release it, just in case any other important issues come up.

In the meantime, if you want to use stable code, download the v3.0.x branch from Github. If you're fine with potentially unstable code, use the master branch.

**Comment by subdan** [comment]
Thank you very much, Josh!
