### ISSUE TITLE
FlowLayout: scroll range incorrect with horizontalAlign

### ISSUE THREAD

**Issue by daicemirror** [BowlerHatLLC/feathers#1414]
Replace the following code in FlowLayoutScreen class from LayoutExplorer example.
```
for(var i:int = 0; i < this.settings.itemCount; i++)
{
	var size:Number = 100;
	var quad:Quad = new Quad(size, size, 0xff8800);
	if (i == 3) {
		quad.width = 1000;
	}
	this.addChild(quad);
}
```
Then compiling and changing flowLayout screen's horizontalAlign setting to "center" or "right".
In this case, left and right scrolling range is Incorrect in flowLayout.
Thanks!

**Comment by joshtynjala** [comment]
Thanks! I can reproduce.
