### ISSUE TITLE
Documentation: ScreenDensityScaleFactorManager: "Providing textures for every scale factor is optional"

### ISSUE THREAD

**Issue by GV3** [BowlerHatLLC/feathers#1422]
Hi Josh,

In the documentation of the ScreenDensityScaleFactorManager class, can we find read that "Providing textures for every scale factor is optional" and I'm sure that you have described how to do this somewhere in the wiki or blog... To add a link in the asdocs to that explanation or example  would be of great help.

What do you think?

**Comment by joshtynjala** [comment]
There isn't really anything else to describe. If a texture has a different scale than the current contentScaleFactor, Starling automatically resizes it. That's it. It "just works".

Does that help? Do you think that I should tweak that paragraph a little so that it's more clear that there's literally nothing more you need to do because Starling handles it? Or is there something more that you're still confused about? I'd be happy to answer further questions.

**Comment by GV3** [comment]
What I understood is that we can optionally upload or embed different textures, one unique for each scale factor, and pass them all the different atlases (regular, @x2, @x3 ) to the Theme or the ScreenDensityFactorManager. This class would then know which Atlas to use for each device.

I prefer to be able to load a pixel perfect atlas done for each of the scales than to have only the  @x2 scaling up and down.

Is this what was meant by "Providing textures for every scale factor is optional"?

**Comment by joshtynjala** [comment]
If you want to provide multiple sets of assets, you are responsible for choosing the correct one based on the current contentScaleFactor.

**Comment by GV3** [comment]
To have a public "calculatedScaleFactor" property in the ScreenDensityScaleFactorManager class would help.

I'm currently extending ScreenDensityScaleFactorManager to be able to read this value.

**Comment by joshtynjala** [comment]
What does that offer that Starling's contentScaleFactor doesn't?

**Comment by GV3** [comment]
I thought Starling's contentScaleFactor is set AFTER I pass the atlas... 🤔 But judging by your answer, I assume I'm wrong to believe that 🤓 I'll double check once I'm back at the computer (texting from the phone)

**Comment by GV3** [comment]
Confirmed, Starling's contentScaleFactor displays the correct information.

Thank you Josh
