### ISSUE TITLE
Error #2175 when PickerList dataProvider is null or empty

### ISSUE THREAD

**Issue by harry248** [BowlerHatLLC/feathers#1423]
> [Fault] exception, information=Error: Error #2175: One or more elements of the content of the TextBlock has a null ElementFormat.

Happens since the change to starling.text.TextFormat. When a data provider is set immediately on the control, the error does not occur.

**Comment by joshtynjala** [comment]
Thank you. I can reproduce with the following code:

	new MetalWorksMobileTheme();
	var list:PickerList = new PickerList();
	this.addChild(list);
	Starling.juggler.delayCall(function():void
	{
		trace("set data");
		list.dataProvider = new ListCollection([{label: "One"}]);
	}, 0.5);
