### ISSUE TITLE
Scrolling user experience of scroller.

### ISSUE THREAD

**Issue by daicemirror** [BowlerHatLLC/feathers#1425]
Hi Josh, I have an obsession for a long time.
I always feel not smooth movement of scroller component when I slide the scroller component quickly and continuously.
Finally, I found the point of this behavior occurs.
(I tested other web app or mobile app, the following gesture should be able to work.)
If you slide out very momentarily on scroller, throwVertically() will not be triggered in stage_touchHandler function when stage_touchHandler funciton received TouchPhase.ENDED.
Continuous slide would be interrupted.

And I have verified the movement of slide that has occurred in scroller_touchHandler functoin.
(Excluding the impact of minimumDragDistance on starting.)
But I am not sure why the movement was ignored, because the test used my custom movement property.
I can only guess some calculation was stopped early on TouchPhase.ENDED.
I add one line of the following code:
```
protected function stage_touchHandler(event:TouchEvent):void
{
	...
	else if(touch.phase == TouchPhase.ENDED)
	{
		if(!this._isDraggingHorizontally && !this._isDraggingVertically)
		{
			ExclusiveTouch.forStage(this.stage).removeEventListener(Event.CHANGE, exclusiveTouch_changeHandler);
		}
		if (this._touchPointID >= 0) scroller_enterFrameHandler(null);// <----- this line!
		this.removeEventListener(Event.ENTER_FRAME, scroller_enterFrameHandler);
                ...
```
That can fix the problem.
Could you check this issue?
(It may be unable to use the mouse to reproduce this issue.)
Thank you very much.

EDIT:  "throwVertically() will not be triggered" from "throwHorizontally() will not be triggered".

**Comment by joshtynjala** [comment]
I think know what you're talking about. I've seen some strangeness like that sometimes too. I'll take a look!

**Comment by daicemirror** [comment]
Sorry, last time I said "throwVertically() will not be triggered in stage_touchHandler function" that I am wrong.
The correct behavior is throwVertically() will be triggered but throwVertically() get pixelsPerMS = 0 by _velocityX = 0.
throwVertically() get 0 that causes scrolling is stopped or ignored in the beginning because scroller will throwTo current scrollposition.
I did further tests on my phone with once lilting slide.
```
MyList.IDS = "ABC";
MyList.minimumDragDistance = -1;
```
````
//Scroller.as
public var IDS:String;
private var mIsDrag:Boolean = false;;
private var mMovement:Point = new Point();
protected function scroller_touchHandler(event:TouchEvent):void
{
	var _touch:Touch = event.getTouch(this);
	if (_touch)
	{
		switch(_touch.phase)
		{
			case TouchPhase.BEGAN:
				if (IDS == "ABC") trace("BEGAN");
				mMovement.setTo(0, 0);
				break;
			case TouchPhase.MOVED:
				if(IDS == "ABC") trace("MOVED");
				if (!mIsDrag) {
					mIsDrag = true;
				}
				if (mIsDrag) {
					_touch.getMovement(this, mMovement);
				}
				break;
			case TouchPhase.ENDED:
				if(IDS == "ABC") trace("ENDED", mMovement);//_touch.globalX or_touch.globalY on the last TouchPhase.MOVED and TouchPhase.ENDED is the same.
				mIsDrag = false;
				break;
		}
	}
        //Just to make sure whether there is movement occurs
...
}

protected function throwVertically(pixelsPerMS:Number):void
{
	if(IDS == "ABC") trace("throwVertically::pixelsPerMS", pixelsPerMS, "mMovement::", mMovement);//check
	...
}

protected function scroller_enterFrameHandler(event:Event):void
{
        ...

	if(IDS == "ABC") trace("scroller_enterFrameHandler::calculate::_velocityY::", this._velocityY);//check
}

```
here is the trace I got.
```
//Scrolling occurs
BEGAN
scroller_enterFrameHandler::calculate::_velocityY:: 0
MOVED
scroller_enterFrameHandler::calculate::_velocityY:: -8.25
MOVED
ENDED (x=170, y=-286)
throwVertically::pixelsPerMS -4.125 mMovement:: (x=170, y=-286)
```
```
//Scrolling did not occurs
BEGAN
scroller_enterFrameHandler::calculate::_velocityY:: 0
MOVED
ENDED (x=274, y=-440)
throwVertically::pixelsPerMS 0 mMovement:: (x=274, y=-440)
```
if added `if (this._touchPointID >= 0) scroller_enterFrameHandler(null);// <----- this line!`
```
BEGAN
scroller_enterFrameHandler::calculate::_velocityY:: 0
MOVED
ENDED (x=261, y=-298)
scroller_enterFrameHandler::calculate::_velocityY:: -11.461538461538462
throwVertically::pixelsPerMS -5.730769230769231 mMovement:: (x=261, y=-298)
```
This time get the correct scrolling because _velocityY != 0.
But I know that my amendment is not circumspect.
Hope this can help you to fix it, thanks for your hard work.

**Comment by joshtynjala** [comment]
Thanks! This should be working properly now.

**Comment by daicemirror** [comment]
Scrolling work properly now!
But when BEGAN->MOVED->ENDED occurs, there are still some problems.
I found two casess when BEGAN->MOVED->ENDED scrolling occurs:
a. Item of list will be selected simultaneously if scrolling starts on that item.
b. Next one touch(id) action will be ignored after BEGAN->MOVED->ENDED scrolling occurs.

**Comment by joshtynjala** [comment]
> BEGAN->MOVED->ENDED

Can you explain exactly what you mean here? Obviously, all touches have BEGAN, MOVED, and ENDED phases, so it is not clear to me.

**Comment by daicemirror** [comment]
I mean what is only triggered TouchPhase.MOVED once.
Such as the trace log I got from my previous test.
The issue always and  only occurs in BEGAN->MOVED(once)->ENDED process.

**Comment by joshtynjala** [comment]
I always see multiple TouchPhase.MOVED events no matter how careful I am, so I'm not sure how to reproduce your issue.

**Comment by daicemirror** [comment]
HaHa.. sorry, that is very embarrassing.
Basically, this is a quick tapping action with a little movement.
I will look for what I can do more for you.

**Comment by daicemirror** [comment]
I found a way to reproduce this issue completely without mobile.
Please add following codes in ListScreen.as:
```
override protected function initialize():void
{
		this._list.itemRendererFactory = function():IListItemRenderer
		{
			...
			renderer.height = 600;//To make sure the simulated target will be triggered.
			return renderer;
		}
		...			
		_list.addEventListener(FeathersEventType.RENDERER_ADD, onRendererAdd);
}
private function onRendererAdd(e:Event, renderer:DefaultListItemRenderer):void 
{
	_list.removeEventListener(FeathersEventType.RENDERER_ADD, onRendererAdd);

	var touch:Touch = new Touch(0);
	touch.target = renderer;

	Starling.juggler.delayCall(function():void {
		touch.globalX = 250;
		touch.globalY = 300;
		touch.phase = "began";
		renderer.dispatchEvent(new TouchEvent("touch", Vector.<Touch>([touch]), true));
	}, 1.0);
	
	Starling.juggler.delayCall(function():void {
		touch.globalX = 250;
		touch.globalY = 250;
		touch.phase = "moved";
		renderer.dispatchEvent(new TouchEvent("touch", Vector.<Touch>([touch]), true));

		touch.phase = "ended";
		renderer.dispatchEvent(new TouchEvent("touch", Vector.<Touch>([touch]), true));
	}, 1.1);
}
```

**Comment by joshtynjala** [comment]
That change should clear up the issue. On TouchPhase.MOVED, it now checks if a drag has started. This will put up the "touch blocker" before TouchPhase.ENDED so that item renderers will fail the hit test (and they won't be triggered). The current velocity is still saved on Event.ENTER_FRAME (and possibly one last time on TouchPhase.ENDED, like in the previous commit).

**Comment by daicemirror** [comment]
I can no longer reproduce this issue, also on mobile.
Thanks again!
