### ISSUE TITLE
Header: Method calculateExtraOSStatusBarPadding() calculates wrong height for iPhone 6s Plus

### ISSUE THREAD

**Issue by GV3** [BowlerHatLLC/feathers#1426]
The iOS design guidelines describe that the status bar has a height of 20pt. When debugging on an iPhone 6S plus and iPhone 6 Plus (both in the Simulator and on the phone) this method calculates the OS bar padding to 13.333.

The size is displayed correctly on all other devices (iPhone 5, iPhone 5s, iPhone 6s).

The method `calculateExtraOSStatusBarPadding()`, which calculates the height of the status bar this way:

`return IOS_STATUS_BAR_HEIGHT * Math.floor(DeviceCapabilities.dpi / IPHONE_1X_DPI) / Starling.current.contentScaleFactor;`

But does not take into consideration the downsampling occurring in both models above mentioned.

Both the iPhone 6 plus and the iPhone 6S Plus are rendered at 3x but downsampled and displayed at 401 ppi.

Find here a great guide for the iPhone sizes: 
[https://www.paintcodeapp.com/news/ultimate-guide-to-iphone-resolutions](url)

A proposal would be to change the Math.floor method for a Math.ceil method.

`return IOS_STATUS_BAR_HEIGHT * Math.ceil(DeviceCapabilities.dpi / IPHONE_1X_DPI) / Starling.current.contentScaleFactor;`

**Comment by GV3** [comment]
Related to:

https://github.com/BowlerHatLLC/feathers/issues/840

**Comment by GV3** [comment]
Hi @joshtynjala , could you reproduce and confirm this issue?

**Comment by joshtynjala** [comment]
I have not yet had a chance to try to reproduce.

It's strange, though. After Adobe finally added support for the full resolution of the iPhone 6 Plus to AIR, I adjusted the calculation to give it more padding, and everything looked perfect.

**Comment by GV3** [comment]
As illustrated in the image below, the iPhone 6 (Display Zoom) and the iPhone 6 Plus both render at 3x and display at 401 PPI.

<img width="991" alt="screen shot 2016-07-25 at 1 47 13 pm" src="https://cloud.githubusercontent.com/assets/1840077/17100440/a4e9e768-526e-11e6-91d9-8993642795c1.png">

Let's consider the current code:

`return IOS_STATUS_BAR_HEIGHT * Math.floor(DeviceCapabilities.dpi / IPHONE_1X_DPI) / Starling.current.contentScaleFactor;`

And let's use the values of the iPhone 6 Plus:

`return 20 * Math.ceil(401 /163) / 3;`

What gives us 13.333

The current only possible PPI are 163 (1x), 326(2x) and 401(3x).

I don't think it's related to the support of Adobe for the full resolution of the iPhone 6 Plus. Instead, I think it relates to the actual PPI used by Apple for their devices, which is also available via DeviceCapabilities.dpi.

**Comment by joshtynjala** [comment]
I'm just saying saying that I remember that it was working correctly previously. Something must have changed in AIR or iOS since then.

**Comment by joshtynjala** [comment]
Well, anyway, this calculation is now based on the same technique that ScreenDensityScaleFactorManager uses. This should more easily allow a range of densities to use the same scale.
