### ISSUE TITLE
StageTextTextEditor stops working after 6ec99988beec3f22564663ca942c03c59ec8be23 commit

### ISSUE THREAD

**Issue by subdan** [BowlerHatLLC/feathers#1428]
Josh, You added these lines:
```
+			var textAlign:String = this._fontWeight;
+			if(textAlign === null)
+			{
+				if(textFormat !== null && textFormat.horizontalAlign)
+				{
+					textAlign = textFormat.horizontalAlign;
+				}
+				else
+				{
+					textAlign = TextFormatAlign.START;
+				}
+			}
+			this.stageText.textAlign = textAlign;
```

My app crashes with the next error:
`[Fault] exception, information=ArgumentError: Error #2008: Parameter textAlign must be one of the accepted values.`

Why did you add this line?
`var textAlign:String = this._fontWeight;`
Text align can't be equal to font weight.

**Comment by joshtynjala** [comment]
Copy paste error, obviously. :)
