### ISSUE TITLE
[v2.3] Scale3Image crash when disposed

### ISSUE THREAD

**Issue by b005t3r** [BowlerHatLLC/feathers#1429]
If you create a Scale3Image, add it to stage and, on the same frame, remove and dispose it, it's still going to try to validate and will cause a crash, because its internal QuadBatch is already disposed.

**Comment by joshtynjala** [comment]
Thank you, but Scale3Image had been removed in 3.x, so closing.

**Comment by b005t3r** [comment]
Maybe just set it to "won't fix" or something, so people who still use 2.3x will see that such problem exists.
