### ISSUE TITLE
FeathersControl.hitTest() gives different results for different _isQuickHitAreaEnabledvalues

### ISSUE THREAD

**Issue by b005t3r** [BowlerHatLLC/feathers#1431]
If ```isQuickHitAreaEnabled``` is set to ```true``` entire control is "clickable" - no matter if there's a child display object in the exact place your trying to click (clicking an empty space results in receiving a touch). If set to ```false``` however, you can only interact with those parts of the control, which are covered by clickable children, so clicking in the boundaries of the control doesn't always result in receiving a touch event.

This is inconsistent and because ```isQuickHitAreaEnabled``` is just an optimization, results should be exactly the same regardless of its value (if clicking inside the control's boundaries, a touch event should always be triggered).

**Comment by joshtynjala** [comment]
isQuickHitAreaEnabled is working as designed. The strict rectangular hit area is a restriction of using this optimization.

**Comment by b005t3r** [comment]
So you think it makes sense that it works this way? Because it doesn't make sense to me to have a button which I cannot click.

**Comment by joshtynjala** [comment]
If isQuickHitAreaEnabled is true, and you don't have any children that are clickable, then yes, it makes total sense. It's the same as if you had a starling.display.Sprite with no clickable children. It wouldn't be clickable.
