### ISSUE TITLE
TextArea, TextFieldTextEditorViewPort: Left edge of text cut off when editing on iOS

### ISSUE THREAD

**Issue by kevinfoley** [BowlerHatLLC/feathers#1432]
When editing the text in a TextArea that uses TextFieldTextEditorViewPort, the left edge of the text gets cut off on iOS. The left edge of the text does not get cut off when not editing the text. 

The caret is not visible if it is on the first character of a line, and the width of the missing portion of the text seems to be about equal to the width of the caret.

This behavior occurs regardless of the padding properties of the TextArea or TextFieldTextEditorViewPort. Tested using Feathers 3.0.2 / AIR 22 / iOS 9.3.2

Not editing:
![textnotcutoff](https://cloud.githubusercontent.com/assets/7231744/17306516/49472aa2-57e5-11e6-9259-c4eb72eb5fef.png)
Editing:
![textcutoff](https://cloud.githubusercontent.com/assets/7231744/17306515/473e825a-57e5-11e6-8d85-27025e3b83dc.png)

**Comment by joshtynjala** [comment]
[Adobe Bug #4009346: TextField with TextFieldType.INPUT on iOS cuts off text on left side when focused ](https://bugbase.adobe.com/index.cfm?event=bug&id=4009346)

**Comment by kevinfoley** [comment]
Ah, shoot. Looks like you reported that a while ago and they haven't fixed it yet. Do you have any workaround or are we stuck at the moment?

**Comment by joshtynjala** [comment]
I saw it listed in the most recent beta release notes under known issues. That's often a sign that they're planning to work on it soon.

A multiline StageTextTextEditor with TextInput could potentially be a workaround. StageText does not have the same issue.

**Comment by kevinfoley** [comment]
Good point, I don't know why I'm even using a TextArea in a mobile app...

**Comment by joshtynjala** [comment]
I see this listed under both known issues and fixed issues in the AIR 23 beta from Aug 3. It could be fixed!

**Comment by joshtynjala** [comment]
Closing because this is fixed in AIR 23.
