### ISSUE TITLE
List: can't change item renderer factories if index changes

### ISSUE THREAD

**Issue by daicemirror** [BowlerHatLLC/feathers#1433]
For convenience to reproduce, please modify following code in  AutoCompleteScreen class of componentsExplorer example.

```
this._input.source = new LocalAutoCompleteSource(new ListCollection(new <String>
[
    "Apple",
    "Apple02",
    "Apple03",
    "Apple04",
    "Apple05",
    "Apple06",
    "Apple07",
    "Apple08",
    "Apple09",
    "Apple10",
    "Apricot"
]));

_input.listFactory = function():List
{
    var _list:List = new List();
    _list.styleProvider = null;

    _list.setItemRendererFactoryWithID( "foot-item", function():IListItemRenderer {
        var renderer:DefaultListItemRenderer = new DefaultListItemRenderer();
                renderer.height = 300;
        renderer.styleProvider = null;
        renderer.defaultSkin = new Quad(1, 1, 0xFFFF00);
        return renderer;
    });

    _list.factoryIDFunction = function( item:Object, index:int ):String
    {
        if(index == _list.dataProvider.length - 1)
        {
            return "foot-item";
        }
        return null;
    };

    _list.itemRendererFactory = function():IListItemRenderer
    {
        var renderer:DefaultListItemRenderer = new DefaultListItemRenderer();
        renderer.height = 300;
        return renderer;
    };

    return _list;
}
```

Case:
~~a. AutoComplete's popupList will create all suggestion items of list when popupList's height have not been limited in the first opening.
    reproduce step: type "ap" and watch that itemRendererFactory function will be called.~~

~~b. If popupList don't have backgroundSkin(_list.styleProvider = null), following steps will get an error:
    1. type "ap" and wait popupList to show up.
    2.Then type "s" (become "aps")~~

c. When I type "ap" and Then type "ple02", I can't get the expected "foot-item" style of itemRenderer.
Because the below codes of ListDataViewPort class.

```
var typicalRenderer:IListItemRenderer = IListItemRenderer(this._rendererMap[typicalItem]);
if(typicalRenderer)
{
    //at this point, the item already has an item renderer.
    //(this doesn't necessarily mean that the current typical
    //item was the typical item last time this function was
    //called)

    //the index may have changed if items were added, removed or
    //reordered in the data provider
    typicalRenderer.index = typicalItemIndex;
}
```

The same typicalItem cause factoryIDFunction to be ignored. 

Thanks!

**Comment by joshtynjala** [comment]
a. This is by design. You can set the height or maxHeight of the List. You could also set the requestedRowCount on a VerticalLayout.
b. Thanks! I will investigate.
c. Thanks! I will investigate. I think I've encountered this one before. At the time, I wasn't sure how to support this without hurting performance too much. I will look again, though.

**Comment by daicemirror** [comment]
Thanks for your hard work!
In case c, factoryIDFunction seems difficult to support virtualLayout.
For now, I extend DefaultListItemRenderer class and override commitData() to achieve the same result I need.
I have an idea! If there is a function like _list.itemRenderDataCommit = function( render:IListItemRenderer ):void{ }, I can do the same thing outside of itemRenderer.
But I do not know whether it is practical.

And I found another issue:
Please add following code to original AutoCompleteScreen class.
```
_input.listFactory = function():List
{
	var _list:List = new List();
	_list.styleProvider = null;
	
	_list.backgroundSkin = new quad(1, 1, 0xFF8040);

	_list.itemRendererFactory = function():IListItemRenderer
	{
		var renderer:DefaultListItemRenderer = new DefaultListItemRenderer();
		renderer.styleProvider = null;
		renderer.height = 300;
		return renderer;
	};
	return _list;
}
```
Step: type "ap" and then type "r", watch changes in popupList's background.

If you replace the different setting of backgroundSkin below, you can see the different result.
```
//skin-A
var _skin:ImageLoader = new ImageLoader();
_skin.source = Texture.fromColor(100, 100, 0xFF8040);
_skin.scale9Grid = new Rectangle(20, 0, 40, 10);
_list.backgroundSkin = _skin;

//skin-B
var _skin:ImageSkin = new ImageSkin(Texture.fromColor(100, 100, 0xFF8040));
_skin.scale9Grid = new Rectangle(20, 0, 40, 10);
_list.backgroundSkin = _skin;

//skin-C
var _skin:Image = new Image(Texture.fromColor(100, 100, 0xFF8040));
_skin.scale9Grid = new Rectangle(20, 0, 40, 10);
_list.backgroundSkin = _skin;
```
Only skin-C can get the same behavior of setting _list.backgroundSkin = new quad(1, 1, 0xFF8040);
Or maybe I do something wrong.

**Comment by joshtynjala** [comment]
> And I found another issue:

Can you post a screenshot?

**Comment by daicemirror** [comment]
Skin-A
![skina](https://cloud.githubusercontent.com/assets/18619085/17382174/22863e34-5a02-11e6-979a-8acc19c0f791.gif)

Skin-B
![skin-b](https://cloud.githubusercontent.com/assets/18619085/17382168/1d0fc4a2-5a02-11e6-9ec5-d2c815accd98.gif)
Skin-C
![skin-c](https://cloud.githubusercontent.com/assets/18619085/17382232/61bcd3a6-5a02-11e6-884f-7d76cfcef44a.gif)

**Comment by joshtynjala** [comment]
I have fixed the runtime error caused by b. I also fixed the issues with ImageLoader and ImageSkin.

**Comment by joshtynjala** [comment]
For my own future reference, here's some simplified code that will reproduce (c) with only a List (no AutoComplete required):

	var button:Button = new Button();
	button.label = "Click Me";
	button.addEventListener(Event.TRIGGERED, function():void
	{
		list.dataProvider.removeItemAt(list.dataProvider.length - 1);
	});
	button.move(20, 20);
	this.addChild(button);
	
	var list:List = new List();
	list.dataProvider = new ListCollection(
	[
		{ label: "One" },
		{ label: "Two" },
		{ label: "Three" },
		{ label: "Four" },
		{ label: "Five" },
	]);
	list.factoryIDFunction = function(item:Object, index:int):String
	{
		if(index === (list.dataProvider.length - 1))
		{
			return "last-item";
		}
		return null;
	};
	list.setItemRendererFactoryWithID("last-item", function():IListItemRenderer
	{
		var itemRenderer:DefaultListItemRenderer = new DefaultListItemRenderer();
		itemRenderer.defaultSkin = new Quad(1, 1, 0x990099);
		return itemRenderer;
	});
	list.move(20, 100);
	this.addChild(list);
