### ISSUE TITLE
Add Tooltip documentation

### ISSUE THREAD

**Issue by kevinfoley** [BowlerHatLLC/feathers#1434]
It looks like help documentation for the Tooltip feature is supposed to be located at http://feathersui.com/help/tool-tips.html , but currently no help documentation exists.

**Comment by joshtynjala** [comment]
Thanks! Looks like that got lost in the shuffle. Here's the short version:

If you're not using one of the example desktop themes, like MetalWorksDesktopTheme, you will need to enable the ToolTipManager manually:

```
ToolTipManager.setEnabledForStage(stage, true);
```

If you set the [toolTip](http://feathersui.com/api-reference/feathers/core/FeathersControl.html#toolTip) property on a component:

```
button.toolTip = "Hello";
```

By default, the ToolTipManager creates a Label with style name Label.ALTERNATE_STYLE_NAME_TOOL_TIP.

**Comment by kevinfoley** [comment]
Thanks. I've tried those steps, but something isn't working. I've created the style provider for `Label.ALTERNATE_STYLE_NAME_TOOL_TIP` but it doesn't look like tooltips are getting created regardless. Are there any other settings I should look at?

**Comment by joshtynjala** [comment]
I'm not sure what to tell you... Even if you don't skin the tool tip with a background, you should see the text floating above the component. Just hover your mouse over the component, and it will appear after 0.5 seconds.

**Comment by kevinfoley** [comment]
Whoops, I was holding the button down instead of hovering over it! That's normally how I implement tooltips on mobile, but that's not the right way on a PC!

It does remind me that I was going to suggest you implement that solution on mobile - if the user presses and holds a button (which you already track with the DOWN state), show a tooltip after the delay period. If the user decides they don't want to press the button, they can slide their finger off of it. It can be hard to read a tooltip around your finger, but in some cases that's a better solution than nothing at all.

**Comment by joshtynjala** [comment]
I opened #1435 for mobile tool tip support similar to Android's long press
