### ISSUE TITLE
Invalid touch. Touch ID must be >= 0.

### ISSUE THREAD

**Issue by harry248** [BowlerHatLLC/feathers#1436]
I have a List with a VerticalLayout contained inside a ScrollContainer with a VerticalLayout. The ScrollContainer has paging enabled and the List is on the second page (I set both ScrollContainer and the List and also the pageWidth/pageHeight of the ScrollContainer to match the stage width/height). Scrolling to the second page, containing the List and then scrolling the List, I get the following exception:

[Fault] exception, information=ArgumentError: Invalid touch. Touch ID must be >= 0.

Caused by line 120 in ExclusiveTouch.

Maybe a bug?

**Comment by joshtynjala** [comment]
Yes, it might be a bug. Can you put together some code that will reproduce the issue?

**Comment by joshtynjala** [comment]
Nevermind! I can reproduce.

**Comment by harry248** [comment]
Sorry, had no time yet, wanted to create an example on the weekend. Thanks for fixing!
