### ISSUE TITLE
List.handlePendingScroll() _dataProvider null reference error

### ISSUE THREAD

**Issue by teotigraphix** [BowlerHatLLC/feathers#1438]
This is sort of out of the blue but I have code refreshing a dataProvider and this happened for the first time.

```L:1521 var item:Object = this._dataProvider.getItemAt(this.pendingItemIndex);```

```
feathers.controls::List/handlePendingScroll	
feathers.controls::Scroller/draw	
feathers.controls::List/draw	
feathers.core::FeathersControl/validate	
feathers.core::ValidationQueue/advanceTime	
starling.animation::Juggler/advanceTime	
starling.core::Starling/advanceTime	
starling.core::Starling/nextFrame	
starling.core::Starling/onEnterFrame	
```

BTW pendingItemIndex was 0 , _selectedIndex was -1.

**Comment by joshtynjala** [comment]
Thanks! Looks easy enough to fix.

**Comment by teotigraphix** [comment]
I'm just trying to figure out what I did to make it happen, it's continuously doing it now when I remove an item.

**Comment by teotigraphix** [comment]
Ok by adding;

```
         view.validate();
            view.dataProvider = null;
```

to the call it seemed to flush the validation so it must be a weird timing issue. I will use that hack until you fix it and release.

**Comment by joshtynjala** [comment]
scrollToDisplayIndex() sets pendingItemIndex. I think for this to happen, you would need to call scrollToDisplayIndex() and then set dataProvider to null before the List can validate.

**Comment by teotigraphix** [comment]
Weird, I have this;

```
    private function refreshDataProvider():void
    {
        if (rack.machine.hasMachineSelection)
        {
            var scales:ListCollection = rack.machine.selectedSequencer.model.pianoRollDataProvider;
            view.itemRendererType = ScaleListItemRenderer;
            view.dataProvider = scales;
            view.scrollToDisplayIndex(getIndexOfNoteOrNearestMiddleC(scales));
        }
        else
        {
            view.validate();
            view.dataProvider = null;
        }
    }
```

But Nothing is happening when I actually remove the machine. So that call is not actually being called during any close frames.
