### ISSUE TITLE
Rename Button customLabelStyleName to customTextRendererStyleName

### ISSUE THREAD

**Issue by kevinfoley** [BowlerHatLLC/feathers#1440]
The Button class has a customLabelStyleName property, but this property expects a text renderer style name, not a label style name. This is likely to cause confusion, and should be renamed to customTextRendererStyleName to match the properties of Label.

Currently it works like this:

    protected function setBoldDetailLabelStyles(label:Label):void {
        label.customTextRendererStyleName = STYLE_NAME_BOLD_DETAIL_TEXT_RENDERER;
    }	

    protected function setBoldDetailLabelTextRendererStyles(textRenderer:TextBlockTextRenderer):void {
        textRenderer.elementFormat = this.smallUIDarkElementFormat;
        textRenderer.disabledElementFormat = this.smallDisabledElementFormat;
    }

    protected function setSmallButtonStyles(button:Button):void {
        setBaseButtonStyles(button);
        button.customLabelStyleName = STYLE_NAME_BOLD_DETAIL_LABEL; //wrong
        button.customLabelStyleName = STYLE_NAME_BOLD_DETAIL_TEXT_RENDERER; //correct
    }

**Comment by joshtynjala** [comment]
It follows the same naming convention as many other properties on the Button class, including label, labelFactory, labelOffsetX, labelOffsetY, defaultLabelProperties, and DEFAULT_CHILD_STYLE_NAME_LABEL. I would need to change all of these. This would be too drastic a change, in my opinion, for a temporary bit of minor confusion. I'm willing to break backwards compatibility sometimes, but this one doesn't seem worth the effort.

Ideally, the label property might have been named text, and then everything else would have probably been named differently. However, I followed in the footsteps of other ActionScript frameworks like Flex and the Flash Pro components, and called the property label.

**Comment by kevinfoley** [comment]
@joshtynjala Sorry to bring this up again, but this is one of the things I get hung up on the most. It's easy to forget that `BaseDefaultItemRenderer` extends `Button`, and that the `customLabelStyleName` on an item renderer also requires a _text renderer_ style name.

Would you be willing to compromise by calling it `customLabelTextRendererStyleName`? If not, I'll drop it! :)
