### ISSUE TITLE
[2.3x] App freezes (probably an infinite layout loop)

### ISSUE THREAD

**Issue by b005t3r** [BowlerHatLLC/feathers#1442]
So I have this custom list item renderer, which has 3 labels added to it. It uses horizontal layout to lay-out the labels, so the two first ones use only as little space as needed and the third one gets the rest of remaining space. Here's the code:

```as3
    public function ChatListItemRenderer() {
        layoutData = new VerticalLayoutData(100, 0);

        _dateLabel = new Label();
        _dateLabel.alpha = 0.7;
        _dateLabel.layoutData = new HorizontalLayoutData(NaN, 100);
        _dateLabel.textRendererFactory = function():ITextRenderer {
            var renderer:BitmapFontTextRenderer = new BitmapFontTextRenderer();
            renderer.textFormat = new BitmapFontTextFormat("hero_glow_18pt", NaN, Color.WHITE, TextFormatAlign.CENTER);
            return renderer;
        };

        _playerNameLabel = new Label();
        _playerNameLabel.layoutData = new HorizontalLayoutData(NaN, 100);
        _playerNameLabel.textRendererFactory = function():ITextRenderer {
            var renderer:BitmapFontTextRenderer = new BitmapFontTextRenderer();
            renderer.textFormat = new BitmapFontTextFormat("hero_glow_18pt", NaN, UIConst.STANDARD_UI_COLOR, TextFormatAlign.CENTER);
            return renderer;
        };

        _textLabel = new Label();
        _textLabel.layoutData = new HorizontalLayoutData(100, 100);
        _textLabel.textRendererProperties.wordWrap = true;
        _textLabel.textRendererFactory = function():ITextRenderer {
            var renderer:BitmapFontTextRenderer = new BitmapFontTextRenderer();
            renderer.textFormat = new BitmapFontTextFormat("hero_glow_18pt", NaN, Color.WHITE, TextFormatAlign.LEFT);
            return renderer;
        };

        var horizontalLayout:HorizontalLayout = new HorizontalLayout();
        horizontalLayout.gap = 6;
        layout = horizontalLayout;

        addChild(_dateLabel);
        addChild(_playerNameLabel);
        addChild(_textLabel);
    }
``` 

My problem is it causes the app to freeze (something has to be spinning in an endless loop, but I can't just pause the debugger and see what it is). I found out that if I change ```NaN```s to ```0```s in the ```HorizontalLayoutData```s it doesn't freeze the app, but it also doesn't lay-out the labels in a correct way (the first two just show "..." and are really small).

How do I find out what's going on? How do I fix it? Am I doing something wrong? I had problems like this before (I event submitted a couple of issues), but what always seemed to fix it was calling ```validate()``` manually on some components. It doesn't work this time.

**Comment by joshtynjala** [comment]
I think there were some issues before Feathers 3.0 when nesting VerticalLayout and HorizontalLayout and both were using percentage dimensions.

Instead of passing VerticalLayoutData with percentWidth 100 to your item renderer's layoutData, try setting the horizontalAlign property of the VerticalLayout to VerticalLayout.HORIZONTAL_ALIGN_JUSTIFY. The issue should not be present with this combination. Additionally, it will be better for performance. percentWidth = 100 is a little slower than HORIZONTAL_ALIGN_JUSTIFY.

**Comment by b005t3r** [comment]
OK, it fixed one problem and introduced another.

Everything works except the third and widest label ```_textLabel``` has to be multiline to display a long text. Currently it's just one line and it displays only as much as it fits in one line. How do I change that? 

I experimented a bit and now my list's layout is created like so:
```as3
        var chatListLayout:VerticalLayout = new VerticalLayout();
        chatListLayout.hasVariableItemDimensions = true;
        chatListLayout.useVirtualLayout = true;
        chatListLayout.horizontalAlign = VerticalLayout.HORIZONTAL_ALIGN_LEFT;
```

and my renderer currently looks like this:

```as3
        //layoutData = new VerticalLayoutData(100, NaN);

        _dateLabel = new Label();
        _dateLabel.alpha = 0.7;
        _dateLabel.textRendererFactory = function():ITextRenderer {
            var renderer:BitmapFontTextRenderer = new BitmapFontTextRenderer();
            renderer.textFormat = new BitmapFontTextFormat("hero_glow_18pt", NaN, Color.WHITE, TextFormatAlign.CENTER);
            return renderer;
        };

        _playerNameLabel = new Label();
        _playerNameLabel.textRendererFactory = function():ITextRenderer {
            var renderer:BitmapFontTextRenderer = new BitmapFontTextRenderer();
            renderer.textFormat = new BitmapFontTextFormat("hero_glow_18pt", NaN, UIConst.STANDARD_UI_COLOR, TextFormatAlign.CENTER);
            return renderer;
        };

        _textLabel = new Label();
        _textLabel.wordWrap = true;
        _textLabel.textRendererProperties.wordWrap = true;
        _textLabel.textRendererFactory = function():ITextRenderer {
            var renderer:BitmapFontTextRenderer = new BitmapFontTextRenderer();
            renderer.textFormat = new BitmapFontTextFormat("hero_glow_18pt", NaN, Color.WHITE, TextFormatAlign.LEFT);
            return renderer;
        };

        var horizontalLayout:HorizontalLayout = new HorizontalLayout();
        horizontalLayout.gap = 6;
        layout = horizontalLayout;

        addChild(_dateLabel);
        addChild(_playerNameLabel);
        addChild(_textLabel);
```

Everything is fine except everything being just one line and I can now scroll the list up and down, which is OK, as well as left and right, which is something I don't want.

How do I fix that?

**Comment by joshtynjala** [comment]
Try this instead:

``` actionscript
chatListLayout.horizontalAlign = VerticalLayout.HORIZONTAL_ALIGN_JUSTIFY;
```

VerticalLayout.HORIZONTAL_ALIGN_LEFT will not restrict the width of items, so they will be allowed to grow larger than the list, and it will result in horizontal scrolling, as you discovered.

**Comment by b005t3r** [comment]
Tried it as well, before left align. Same result, but no scrolling to left or right.

**Comment by joshtynjala** [comment]
This should do the trick!

``` actionscript
_textLabel.layoutData = new HorizontalLayoutData(100);
```

**Comment by b005t3r** [comment]
It works! Thanks God and you Josh, it finally does work! My sanity went down significantly, though.
