### ISSUE TITLE
LayoutGroup w/ImageSkin background not resizing properly to it's children

### ISSUE THREAD

**Issue by izzmeifter** [BowlerHatLLC/feathers#1443]
We have a LayoutGroup that was using a Quad as a background. Inside the LayoutGroup was a TextInput that would resize larger when the user hit Return (wordwrap=true) and would resize smaller if they removed the text back to one line (or hit submit and the textInput was cleared) - we resize it by measuring a label and set height on the TextInput.

Since changing the backgroundSkin on the LayoutGroup to an ImageSkin (we require scale9), the group never resizes back down even though the TextInput does.

I hope that makes sense. I would expect the layout group to resize to it's child component as it did prior to using the ImageSkin, but it doesn't.

**Comment by joshtynjala** [comment]
Are you using 3.0.x, or the latest on Github? There's a good chance that this one is already fixed.

**Comment by izzmeifter** [comment]
Sorry, using 3.0.3. Glad to hear it's probably fixed. Thanks!

**Comment by joshtynjala** [comment]
I have confirmed with the following code that this reproduces in 3.0.x, but it is working correctly in the latest commits on Github:

	var group:LayoutGroup = new LayoutGroup();
	group.backgroundSkin = new ImageSkin(Texture.fromColor(10, 10, 0xff00ff));
	var label:Label = new Label();
	label.text = "Hello\nWorld\nHi, there!";
	group.addChild(label);
	group.move(10, 10);
	this.addChild(group);
	group.addEventListener(TouchEvent.TOUCH, function(event:TouchEvent):void
	{
		var touch:Touch = event.getTouch(group, TouchPhase.BEGAN);
		if(!touch)
		{
			return;
		}
		label.text = "Hello";
	});
