### ISSUE TITLE
VerticalLayout. Negative values in the side dimentions

### ISSUE THREAD

**Issue by SelStrom** [BowlerHatLLC/feathers#1444]
Feathers 3.0.2 VerticalLayout.layout() line 966 
If the minWidth or minHeight equals 0, and padding have positive values, the validateItems method provides the minWidth and the minHeight with negative values. This causes the endless cycle in the BitmapFontTextRenderer at code (line 788):
`while(currentX > maxLineWidth && !MathUtil.isEquivalent(currentX, maxLineWidth))
                {
                    currentX -= maxLineWidth;
                    currentY += lineHeight;
                }`

because the maxLineWidth equals negative.
Perhaps this bug appears somewhere else.

**Comment by joshtynjala** [comment]
Can you put together some simple example code that reproduces the issue? I'm having trouble coming up with something based on your description alone. Thanks!
