### ISSUE TITLE
ImageLoader support for uploadFromBitmapDataAsync()

### ISSUE THREAD

**Issue by harry248** [BowlerHatLLC/feathers#1447]
Would be nice if the ImageLoader control would support the new uploadFromBitmapDataAsync() method of AIR 23.

**Comment by varadig** [comment]
+1

**Comment by jamikado** [comment]
It would really be a better idea to submit a Starling feature request for this. Feathers just uses Starling's Texture classes and support for uploadFromBitmapDataAsync needs to come from within the Starling Texture wrapper classes, not Feathers

**Comment by joshtynjala** [comment]
Yes, @jamikado is correct. Once Starling exposes an API, I can use it in Feathers too.

**Comment by harry248** [comment]
@joshtynjala  Can you estimate when ImageLoader will support the feature too? Sorry for the impatience! 😄

**Comment by joshtynjala** [comment]
Daniel added support to Starling yesterday. I was waiting on that. Soon.

**Comment by vm2-mobile-devs** [comment]
Hi Josh,
can you give some estimated date to when Feathers will use the uploadFromBitmapDataAsync()? or can i use/test it with the current prerelease version 3.2.0? 
Thanks!

**Comment by joshtynjala** [comment]
It will definitely be supported by the time I release Feathers 3.2, but I haven't implemented it yet. Feathers is updated every 4-6 months, so you can probably make a rough guess at the maximum time based on when 3.1 was released.

**Comment by joshtynjala** [comment]
Unfortunately, I've run into an issue that makes it difficult to properly optimize asynchronous texture uploads by reusing an existing texture if the dimensions are the same. I asked Daniel for his thoughts on why the async callback doesn't seem to be working correctly, and we'll escalate to Adobe if needed: Gamua/Starling-Framework#940

I can create a new texture or clear the existing one first, but that's not ideal. Creating/clearing before an asynchronous upload probably isn't slower than reusing a texture with a synchronous upload, but I'll need to do further tests, if that ends up being my only option.

**Comment by joshtynjala** [comment]
Daniel has determined that my findings with async uploads is a bug in AIR. Please vote on the following issue:

[AIR-4198247: TEXTURE_READY event dispatched too soon when uploading to RectangleTexture repeatedly](https://tracker.adobe.com/#/view/AIR-4198247)
