### ISSUE TITLE
AutoComplete sends request on removing item

### ISSUE THREAD

**Issue by RehanUlHassan** [BowlerHatLLC/feathers#1449]
how can i prevent Feathers AutoComplete to NOT send request when user remove the selected value....???

**Comment by joshtynjala** [comment]
Do you mean when the user selects all text and presses backspace/delete?

**Comment by RehanUlHassan** [comment]
yes, when user presses backspace.....the text gets empty and request is sent again

**Comment by joshtynjala** [comment]
Thank you. I will investigate.

**Comment by joshtynjala** [comment]
URLAutoCompleteSource does not cache results, unless the urlRequestFunction takes 0 arguments. The request will be sent any time that the text changes. In Flash Player on the web, it should use the browser's cache automatically, but it may send the request every time on AIR.

Your best option, if you want results to be cached, is to subclass URLAutoCompleteSource or to create a custom IAutoCompleteSource.

**Comment by manofspirit** [comment]
@joshtynjala I believe he is not asking about caching but rather a way to prevent sending a request when there is no text in autocomplete, because in some cases you dont want to send a request, so adding a flag should serve both purposes when a developer wants to make a request with empty autocomplete or not.
I'm also facing same issue, i tried passing null rather than URLRequst when text was empty but got null error.

**Comment by joshtynjala** [comment]
AutoComplete doesn't send any requests if the text is an empty string, though. I tested that to be sure yesterday. I'm going to need more information to reproduce if that's not the case.

**Comment by RehanUlHassan** [comment]
![animation](https://cloud.githubusercontent.com/assets/11446280/18546029/3b487418-7b55-11e6-8fef-20840c8d1cb1.gif)
i've attached this .gif which shows the bug, when i remove whole text by pressing backspace , feather still sends a request with empty text

**Comment by joshtynjala** [comment]
I guess I'm going to need some code that can reproduce the issue. I tried the following, but it definitely does not call the function when the text is an empty string.

	var input:AutoComplete = new AutoComplete();
	input.source = new URLAutoCompleteSource(function(text:String):URLRequest
	{
		trace("text: \"" + text + "\"");
		return new URLRequest("result.json");
	});
	this.addChild(input);
