### ISSUE TITLE
[v2.3] ListDataViewPort invalid while-loop

### ISSUE THREAD

**Issue by b005t3r** [BowlerHatLLC/feathers#1450]
In ```ListDataViewPort```, on line1256 there's a while-loop which looks like this:

```as3
while(!itemRenderer)
itemRenderer.data = item;
itemRenderer.index = index;
itemRenderer.owner = this._owner;
itemRenderer.factoryID = factoryID;
```

I'm pretty sure there's something missing there :)

**Comment by joshtynjala** [comment]
I think you missed the `do` on [line 1229](https://github.com/BowlerHatLLC/feathers/blob/v2.3.0/source/feathers/controls/supportClasses/ListDataViewPort.as#L1229). 😄

**Comment by b005t3r** [comment]
Ah, yes :) There's a missing ```;``` as well, so I figured it's a standard while-loop :)

**Comment by joshtynjala** [comment]
You know, in my 12 years of ActionScript, I never realized that you're supposed to put a semicolon after a do-while loop. Only recently, IntelliJ IDEA started highlighting when the semicolon is missing. I thought that was weird at first. Then, I was also writing some Java, and that's more strict, so it gave me a compiler error when I left it out.

**Comment by b005t3r** [comment]
Yes, in Java/C/C++/C# the semicolon is required there :)
