### ISSUE TITLE
BaseDefaultItemRenderer commitData() and _owner

### ISSUE THREAD

**Issue by teotigraphix** [BowlerHatLLC/feathers#1451]
I was curious as to the dependency on _owner in commitData().

I wanted to use the DefaultListItemRenderer outside of a List and after 15 minutes realized that if it's not owned by a Scroller, none of the properties are updated.

Use case: use this class for custom "list" implementations because of it's robustness. My custom component is not a Scroller, but a NavigationDrawer with collapsable items and I wanted to use this as the Header.

**Comment by joshtynjala** [comment]
It looks like this particular usage of owner isn't necessary, but I think it may have been in the past. There are other places where owner is assumed not to be null, though. I'll see what I can do.

**Comment by teotigraphix** [comment]
Thanks!
