### ISSUE TITLE
4k ImageLoader Bitmap Image Memory Leak

### ISSUE THREAD

**Issue by MatthewVisser** [BowlerHatLLC/feathers#1454]
The ImageLoader component will leak Bitmap Image memory when you use very large images and change the source quickly not giving the imageLoader a chance to complete its load.

Here's a link to a FlashBuilder 4.7 project that demonstrates the issue with the large images included.

https://www.dropbox.com/s/rqfvinzon2w7o6z/fptest.zip?dl=0

**Comment by joshtynjala** [comment]
Yes, I can see memory going up in this example. I'll investigate further.

**Comment by joshtynjala** [comment]
I have made the following three commits that improve how ImageLoader works in this situation:

756a40f8e15fa5972997e88f14a7dd03eef82ac6
2051d778f08cae297f155befb5ec3c3318aad091
15d5bce5fc8ef4a27d30d9cfcbc1586727fd1ecb

In your example app, the memory still rises while the list is scrolling. It's like AIR is overwhelmed by how much data it's getting, so it can't unload things fast enough. I don't think I can do anything about that. However, once the list stops scrolling, the loaders will complete over time, and their data can be garbage collected normally. I am able to force garbage collection in Scout several times, and I can see the memory going back down.

I'm going to consider this issue resolved, so I'm closing it. However, you are free comment, if you have additional concerns to discuss.

**Comment by MatthewVisser** [comment]
Great thanks for having a look. 

Yes it does feel like AIR is getting overwhelmed and issue with AIR rather then Feathers.

In my use case I might have 30 products. And you can scroll left or right one at a time. Or you click a menu and jump to any product which might scroll the list through 20 items before stopping.

I will give the new imageLoader code a go and report back.

Will these new fixes work in 2.3? Reason being I have 50+ machines locked to AIR version 19.

**Comment by joshtynjala** [comment]
> Will these new fixes work in 2.3?

I don't think you'll have any trouble backporting this change to Feathers 2.3.

> Reason being I have 50+ machines locked to AIR version 19.

Well, if you decide that you want to upgrade, those machines have a new enough AIR version to run Starling 2 and Feathers 3! Feathers 3 is built with -swf-version=30, which targets Flash Player and AIR 19.

**Comment by MatthewVisser** [comment]
Awesome thanks again Josh. Good to know I have that option. Thanks for taking a look at this so quickly as well.

Are these minimum requirements for desktop apps correct then?

https://github.com/BowlerHatLLC/feathers

https://github.com/BowlerHatLLC/feathers/tree/v3.0.x

**Comment by joshtynjala** [comment]
Those are the officially supported versions. If you run into a Feathers bug that only occurs in an older version of AIR (and not in the same version of Flash Player), I reserve the right to decide that I won't fix it. I think that's unlikely to happen, though.

With the availability of captive runtime, targeting the newest AIR version is usually a no-brainer. I haven't touched the shared runtime in years. I'm not even sure if the shared runtime is installed on my own computer anymore.

**Comment by MatthewVisser** [comment]
Great thanks for the info.
