### ISSUE TITLE
TextInput: Strange iOS tooltip behavior

### ISSUE THREAD

**Issue by GV3** [BowlerHatLLC/feathers#1461]
Hi Josh, 

I'm experiencing a strange iOS tooltip behavior and would like to share to see if you have noticed, if it's just me, and of course if there is a way to avoid it.

NOTE: A prerequisite for this behavior is to have text copied before, any text, just needs to be on saved the clipboard.

Type in a regular default TextInput control any text, and then programmatically set the text to emptyString ''.

The prompt text will appear correctly but the "Paste" tooltip will appear and stay until the user types a char, taps again on the textInput, or the control loses focus.

Is this a normal behavior?

Thanks,

GV

**Comment by joshtynjala** [comment]
Feathers definitely isn't doing anything to request the copy/paste menu. AIR doesn't expose an API like that, as far as I know. This behavior must be caused by something in the native code, either in AIR or in iOS.

**Comment by GV3** [comment]
Here's a clue... If you set focus twice rapidly, or double tap... the copy/paste menu will appear...

I'll investigate and debug if setting the text to "", the way I do it, dispatches any unexpected FOCUS_IN Events

**Comment by GV3** [comment]
Is still a mystery, but I haven't given up in finding how to solve it or the origin. 

:)
