### ISSUE TITLE
Style conflicts with Flex

### ISSUE THREAD

**Issue by DerBensch** [BowlerHatLLC/feathers#1463]
If I try to compile the current pre-release version with Flex I get the following compiler errors:

Declaration of style 'direction' conflicts with previous declaration in C:\Program Files\Adobe\Adobe Flash Builder 4.7 (64 Bit)\sdks\4.15.0\frameworks\libs\spark.swc(spark.components:NumericStepper).
Declaration of style 'interactionMode' conflicts with previous declaration in C:\Program Files\Adobe\Adobe Flash Builder 4.7 (64 Bit)\sdks\4.15.0\frameworks\libs\spark.swc(spark.components:NumericStepper).

If I remove the style meta tags in the PageIndicator, Scroller, ButtonGroup, ProgressBar, ScrollBar, SimpleScrollBar, Slider, TabBar it seems to fix the problem.

**Comment by joshtynjala** [comment]
I tried building the Components Explorer example with Apache Flex 4.15.0, but I didn't see any errors or warnings.

```
<Apache Flex 4.15>/bin/amxmlc --source-path+=../../source/ --source-path+=../../third-party/starling --source-path+=../../themes/MetalWorksMobileTheme/source/ --output=output/ComponentsExplorer.swf source/ComponentsExplorer.as
```

Are you using Feathers inside an app that also uses the Flex framework?

**Comment by DerBensch** [comment]
Yes, it is a Flex application in an AS application it doesn't happen.

**Comment by joshtynjala** [comment]
Can you try building Feathers as a SWC? That may work better than the source code. If that doesn't work, you could try loading the Feathers part of the app as a separate SWF. Or convert thing thing to all Feathers or all Flex.

**Comment by DerBensch** [comment]
I used Feathers as a external library. It's even a non-Flex library. It should be compiled to a SWC and used as such. I'm not at my working computer at the moment. I will try a few things tomorrow. At the moment my solution is to delete all the [Style] meta tags of Feathers.

**Comment by joshtynjala** [comment]
You may be able to manipulate -keep-as3-metadata to make it build without [Style] metadata.

**Comment by DerBensch** [comment]
Unfortunately the -keep-as3-metadata= compiler option doesn't work. I searched a bit for the problem and it seems like the solution of the Flex team is to use other names for the styles. I'm curious. Why do you need the style metadata tags? I thought they are only used for the MXML editor to show the styles with their options. So it would be unnecessary for Feathers to have them.

**Comment by teotigraphix** [comment]
[Style] tags get documented in ASDoc, there "are" an API.

**Comment by joshtynjala** [comment]
Yes, they're for asdoc so that properties used for styling are displayed in a different section than regular properties. They aren't needed by the regular compiler or IDEs.

**Comment by DerBensch** [comment]
Ok. Thanks.
Maybe you could rename the styles to not collide with the Flex styles?
It doesn't matter that much. It's ok for me to delete the style metadata tags every time I update Feathers.
I think it's not that common that someone uses Flex and Feathers at the same time.

**Comment by joshtynjala** [comment]
I'm going to double-check if I can get the asdoc template to render any type of metadata. Maybe I can switch it to something like [StyleProperty] or [FeathersStyle] or something like that instead. It may be that asdoc can only handle [Style], though.

**Comment by joshtynjala** [comment]
Yeah, it looks like [Style] is hardcoded in asdoc, and I can't access custom metadata. I tried -keep-as3-metadata with asdoc, but unfortunately, nothing extra was added to the output.

**Comment by joshtynjala** [comment]
One last thing you could try is using the AIR SDK & Compiler to build the Feathers SWC. Since ASC 2.0 isn't intended to be used with the Flex framework, it may not include the [Style] metadata in the final SWC.

**Comment by DerBensch** [comment]
That's what I'm doing at the moment. I try if using the Flex compiler instead of ASC 2.0 helps, tomorrow. Maybe the -keep-as3-metadata isn't integrated in ASC 2.0.

**Comment by joshtynjala** [comment]
I'm closing the issue, but if you have any more thoughts, feel free to comment. I will still receive notification.

**Comment by rui-cruz** [comment]
I'm having this issue too.. and as I am doing a desktop app, for simple views and stuff above stage3D layer, it would much faster for me to prototype all with old-school fxg's and skins.

Compiling feathers with -keep-as3-metadata didn't worked for me, I tried to compile with -use-resource-bundle-metadata but said that is no longer used.. then I monkey the metadata.xml inside frameworks folder and comment the Style section, but no luck too... 

seems that the only way is to comment the [Style(name's that throws error :(

Someone have other solution?

Thank you,
Rui

**Comment by joshtynjala** [comment]
Commenting them out in Feathers is probably the only solution, besides changing the Apache Flex compiler to be smarter about which classes it actually cares about. It won't hurt anything in Feathers to do that. As I mentioned, the metadata is only used for documentation.
