### ISSUE TITLE
Change component state on touch with utility similar to TapToTrigger

### ISSUE THREAD

**Issue by joshtynjala** [BowlerHatLLC/feathers#1465]
Separated from #1464

@teotigraphix:

> One other question, how about exposing the core down, move, up events as well? Could maybe have an enabled so they are not being dispatched if you don't want them?

@joshtynjala

> What kind of different API are you expecting here? I'm not sure what would be simpler than TouchEvent.TOUCH...

@teotigraphix:

> Well, I may be missing something but;
> 
> If I want to listen for TouchEvent, I would have to write my own handler. Using TapToTrigger, you already track the touchPointID.
> 
> So within target_touchHandler(), dispatching the correct touch event that is NOT actually a touch but based on the logic of that handler is what I am talking about.
> 
> Take for example, the Button's touch handler, you would dispatch these events where you call change state.
> 
> I am just asking for an encapsulation of the touch handler that dispatches events in a concrete place based on the state of the touccPointID that I would not have to track.
> 
> Since you are already doing that in TapToTrigger, I figured it's the natural place to encapsulate those "state changes".
> 
> Maybe I am asking for kind of state events then, not so much "touch" events. I like using your stuff because you know exactly what the framework is doing, when I write my own handlers, sometimes I feel I may be missing something.

**Comment by teotigraphix** [comment]
NICE!
