### ISSUE TITLE
Shared constants should be moved into their own classes

### ISSUE THREAD

**Issue by joshtynjala** [BowlerHatLLC/feathers#147]
Constants from Scroller that are exposed through List and ScrollContainer.
Constants shared by layout implementations.
Constants exposed by Button, but used in subclasses.

Etc.

**Comment by joshtynjala** [comment]
It took nearly four years, but all the shared constants are migrated. Whew!

**Comment by teotigraphix** [comment]
Congratulations, I know how that feels. :) Ah don't you just love design decisions that make more work down the road.

**Comment by joshtynjala** [comment]
I think I originally wanted to do this *before* 1.0, but I felt I shouldn't hold back the release any longer. I probably should have done it anyway, but oh well. 😄
