### ISSUE TITLE
factoryIDFunction called only once

### ISSUE THREAD

**Issue by harry248** [BowlerHatLLC/feathers#1473]
I am setting a HierarchicalCollection as the data provider of a GroupedList. The collection contains several items but the factoryIDFunction of the GroupedList is always only called once with the first item of the data provider. Seems as if this is a bug.

**Comment by joshtynjala** [comment]
I tried adding the following code to the GroupedListScreen in the components explorer example, and the console displayed the text for every visible item from the HierarchicalCollection:

	this._list.factoryIDFunction = function(item:Object):String
	{
		trace(item.text);
		return null;
	};

When I scrolled to the bottom, the remaining items all appeared in the console. It appears to be working correctly.

Can you put together some simplified example code that would allow me to consistently reproduce the issue? Thanks!

**Comment by harry248** [comment]
I also tried with a null return value and it worked, so I thought it must depend on the renderers I return from setItemRendererFactoryWithID(). Some of these custom renderers did not contain any controls yet and this caused the problem. As soon as I had added some controls to them, factoryIDFunction was called for every item in the data provider.

**Comment by joshtynjala** [comment]
I guess it had something to do with the measurement. Glad you figured it out!
