### ISSUE TITLE
Autocomplete returns 16777215 on all elements.

### ISSUE THREAD

**Issue by raresn** [BowlerHatLLC/feathers#1474]
Hello,
I have an autocomplete element that displays "16777215" in the autocomplete list.
If I search for something it returns the correct amount of items, but all are "16777215".

The objects inside the ListCollection looks like this:
```
public class Person extends Object
{

public var name:String;

public function Person(name:String = null)
{
    this.name = name;
}
public function toString():String
{
    return name
}
}
```
the list collection is an vector of persons
```
var persons:Vector.<Person> = getAllPeople();
myAutoComplete.source = new LocalAutoCompleteSource(new ListCollection(persons));
```

**Comment by joshtynjala** [comment]
I tried the following code with your Person class, but I could not reproduce the issue. Can you provide a little more information?

	var persons:Vector.<Person> = new <Person>[];
	for(var i:int = 0; i < 1000; i++)
	{
		persons[i] = new Person(i.toString());
	}
	persons[persons.length] = new Person("16777215");
	var myAutoComplete:AutoComplete = new AutoComplete();
	myAutoComplete.source = new LocalAutoCompleteSource(new ListCollection(persons));
	myAutoComplete.move(20, 20);
	this.addChild(myAutoComplete);

**Comment by raresn** [comment]
Hey Josh!
My Person class had a variable called "label" - this messed up everything. I refactored it and after this everything returned back to normal.
