### ISSUE TITLE
LongPress not working (SDK 3.1.0 Beta 2)

### ISSUE THREAD

**Issue by izzmeifter** [BowlerHatLLC/feathers#1475]
Just trying out some of the touch utils. TapToTrigger and TapToSelect work perfectly, but when trying LongPress in the same basic list, nothing seems to happen. Example is pretty straight forward.

Note, I am only trying one util at a time, so there is no ordering issues.

**In custom ItemRenderer**
this._longPress = new LongPress(this);

**In Mediator**
eventMap.mapListener(screen.list, FeathersEventType.LONG_PRESS, onLongPress);

**Comment by joshtynjala** [comment]
The event does not bubble, so you cannot listen for it from the List.

**Comment by joshtynjala** [comment]
Event.TRIGGERED doesn't bubble either, but the reason that TapToTrigger works is because the List dispatches its own separate Event.TRIGGERED with the item in the data property. Technically, it's not the same event. Anyway, List does not have a concept of long press, so you'd need to dispatch that manually, if you wanted it.

**Comment by izzmeifter** [comment]
Makes sense.. Thanks Josh.

**Comment by izzmeifter** [comment]
Out of curiosity however. Why does the list only dispatch Event.TRIGGERED when I add the TapToTrigger(this). Otherwise It doesn't. That to me seems like the event is bubbling? These are on custom renderers with no other touchHandlers wired up.

**Comment by joshtynjala** [comment]
List specifically listens for Event.TRIGGERED on the item renderer, and then it dispatches its own Event.TRIGGERED. If the item renderer doesn't dispatch Event.TRIGGERED, the List won't either. It does not get dispatched again by the list's parent, so it is not bubbling.
