### ISSUE TITLE
VerticalLayout the horizontalAlign set to center  Location will be confused

### ISSUE THREAD

**Issue by hbinnet** [BowlerHatLLC/feathers#1477]
The horizontalAlign of theVerticalLayout is disabled when it is set to center  Location will be confused

**Comment by hbinnet** [comment]
the version 3.1.0-beta2

**Comment by joshtynjala** [comment]
I'll take a look!

**Comment by joshtynjala** [comment]
I cannot reproduce this issue. I tried the following code, and everything looks centered correctly:

	var group:ScrollContainer = new ScrollContainer();
	var layout:VerticalLayout = new VerticalLayout();
	layout.horizontalAlign = HorizontalAlign.CENTER;
	group.layout = layout;
	for(var i:int = 0; i < 10; i++)
	{
		var child:Quad = new Quad(80 + Math.random() * 20, 10, 0xff00ff);
		group.addChild(child);
	}
	group.width = 200;
	group.backgroundSkin = new Quad(1, 1, 0x666666);
	this.addChild(group);

Can you put together some code that will reproduce the issue? Thank you!

**Comment by hbinnet** [comment]
@joshtynjala 
Sorry, I have a problem with my code,  Thank you!  josh
