### ISSUE TITLE
TextInput + BitmapFontTextEditor + setFocus() = no focusOut event.

### ISSUE THREAD

**Issue by Incubatio** [BowlerHatLLC/feathers#1479]
### Description

Problem is pretty simple, if you call setFocus() on a non-focused textField using BitmatFontTextEditor, the event focusOut won't be triggered when it should.

Note that:
If a user click on the text input, problem doesn't reproduce.
If we use stageTextTextEditor, problem doesn't reproduce.

My practical case:
I want a user to click a button, the button display a textInput and setFocus on it (so the user doesn't need an extra click to type in).
### Environment

**Starling version**:: 2.1
**Feathers version**:: 3.0.4 and 3.1.0-beta2
### Code Sample

``` actionscript
      var ti:TextInput = new TextInput();
      ti.textEditorFactory = function():ITextEditor {
        return new BitmapFontTextEditor();
      }

      ti.setSize(200, 50);
      ti.x = 120;
      ti.y = 120;
      ti.text = 'test test';
      addChild(ti);

      ti.setFocus();
      ti.selectRange(ti.text.length);

      for each(var e:String in ['focusIn', 'focusOut']) {
        ti.addEventListener(e, function(e:Event):void {
          trace(e);
        });
      }
```

The code above will log "[Event type="focusIn" bubbles=false]", however it is not possible to trigger focusOut unless the user clicks on the TextInput. Click that shouldn't be necessary as setFocus is called to avoid that precise user action.

**Comment by joshtynjala** [comment]
Thanks! I'll take a look.
