### ISSUE TITLE
GroupedList: RangeError: Error #1125: The index 0 is out of range 0 with duplicate header data

### ISSUE THREAD

**Issue by harry248** [BowlerHatLLC/feathers#1481]
I am using a GroupedList with a VerticalLayout:

const layout:VerticalLayout = new VerticalLayout();
layout.horizontalAlign = HorizontalAlign.JUSTIFY;
layout.gap = Styles.GAP_MEDIUM;
layout.stickyHeader = true;

I am getting the following exception, as soon as the data provider contains more than only a few items (5 groups, 60 items), when scrolling to the bottom:

[trace] Error: feathers.controls.supportClasses::GroupedListDataViewPort returned to validation queue too many times during validation. This may be an infinite loop. Try to avoid doing anything that calls invalidate() during validation.
[trace]     at feathers.core::FeathersControl/invalidate()[/xxx/src/feathers/core/FeathersControl.as:1965]
[trace]     at feathers.controls.supportClasses::GroupedListDataViewPort/layout_changeHandler()[/xxx/src/feathers/controls/supportClasses/GroupedListDataViewPort.as:2860]
[trace]     at starling.events::EventDispatcher/invokeEvent()[/xxx/src/starling/events/EventDispatcher.as:147]
[trace]     at starling.events::EventDispatcher/dispatchEvent()[/xxx/src/starling/events/EventDispatcher.as:118]
[trace]     at starling.events::EventDispatcher/dispatchEventWith()[/xxx/src/starling/events/EventDispatcher.as:196]
[trace]     at feathers.layout::VerticalLayout/layout()[/xxx/src/feathers/layout/VerticalLayout.as:1210]
[trace]     at feathers.controls.supportClasses::GroupedListDataViewPort/draw()[/xxx/src/feathers/controls/supportClasses/GroupedListDataViewPort.as:1189]
[trace]     at feathers.core::FeathersControl/validate()[/xxx/src/feathers/core/FeathersControl.as:2018]
[trace]     at feathers.core::ValidationQueue/advanceTime()[/xxx/src/feathers/core/ValidationQueue.as:168]
[trace]     at starling.animation::Juggler/advanceTime()[/xxx/src/starling/animation/Juggler.as:354]
[trace]     at starling.core::Starling/advanceTime()[/xxx/src/starling/core/Starling.as:402]
[trace]     at starling.core::Starling/nextFrame()[/xxx/src/starling/core/Starling.as:387]
[trace]     at starling.core::Starling/onEnterFrame()[/xxx/src/starling/core/Starling.as:601]

When scrolling to the top there is another exception:

[trace] RangeError: Error #1125: The index 0 is out of range 0.
[trace]     at Vector$object/http://adobe.com/AS3/2006/builtin::removeAt()
[trace]     at feathers.controls.supportClasses::GroupedListDataViewPort/findRendererForHeader()[/xxx/src/feathers/controls/supportClasses/GroupedListDataViewPort.as:1888]
[trace]     at feathers.controls.supportClasses::GroupedListDataViewPort/findUnrenderedData()[/xxx/src/feathers/controls/supportClasses/GroupedListDataViewPort.as:1742]
[trace]     at feathers.controls.supportClasses::GroupedListDataViewPort/refreshRenderers()[/xxx/src/feathers/controls/supportClasses/GroupedListDataViewPort.as:1587]
[trace]     at feathers.controls.supportClasses::GroupedListDataViewPort/draw()[/xxx/src/feathers/controls/supportClasses/GroupedListDataViewPort.as:1162]
[trace]     at feathers.core::FeathersControl/validate()[/xxx/src/feathers/core/FeathersControl.as:2013]
[trace]     at feathers.controls::Scroller/refreshViewPort()[/xxx/src/feathers/controls/Scroller.as:3588]
[trace]     at feathers.controls::Scroller/draw()[/xxx/src/feathers/controls/Scroller.as:3538]
[trace]     at feathers.controls::GroupedList/draw()[/xxx/src/feathers/controls/GroupedList.as:2959]
[trace]     at feathers.core::FeathersControl/validate()[/xxx/src/feathers/core/FeathersControl.as:2013]
[trace]     at feathers.core::ValidationQueue/advanceTime()[/xxx/src/feathers/core/ValidationQueue.as:168]
[trace]     at starling.animation::Juggler/advanceTime()[/xxx/src/starling/animation/Juggler.as:354]
[trace]     at starling.core::Starling/advanceTime()[/xxx/src/starling/core/Starling.as:402]
[trace]     at starling.core::Starling/nextFrame()[/xxx/src/starling/core/Starling.as:387]
[trace]     at starling.core::Starling/onEnterFrame()[/xxx/src/starling/core/Starling.as:601]

At first I thought it may be a problem with my custom item renderer but it also happens when switching to the DefaultGroupedListItemRenderer, so I think this may be a bug?

**Comment by harry248** [comment]
Ok, just found the problem. One of the headers inside the collection had the same value as another. Renaming it fixed the error. Sorry for making noise...

**Comment by joshtynjala** [comment]
> [trace] RangeError: Error #1125: The index 0 is out of range 0.

I can reproduce this error with the following code:

	var list:GroupedList = new GroupedList();
	list.dataProvider = new HierarchicalCollection(
	[
		{
			header: "Group 1",
			children:
			[
				{ label: "Aardvark" },
				{ label: "Alligator" },
				{ label: "Alpaca" },
				{ label: "Anteater" },
				{ label: "Baboon" },
				{ label: "Bear" },
				{ label: "Beaver" },
				{ label: "Canary" },
				{ label: "Cat" },
			]
		},
		{
			header: "Group 1",
			children:
			[
				{ label: "Deer" },
				{ label: "Dingo" },
				{ label: "Dog" },
				{ label: "Dolphin" },
				{ label: "Donkey" },
				{ label: "Dragonfly" },
				{ label: "Duck" },
				{ label: "Dung Beetle" },
			]
		}
	]);
	list.setSize(200, 200);
	this.addChild(list);

GroupedList actually detects when duplicate items appear in the data provider, and displays an error like this:

> GroupedListDataViewPort: renderer map contains bad data. This may be caused by duplicate items in the data provider, which is not allowed.

It looks like duplicate headers and footers are not detected the same way. If you had had a similar error, you'd at least have a clue to look for duplicates. I'm going to leave this issue open to improve the error messaging in a future version.
