### ISSUE TITLE
VideoPlayer For Mobile  problem

### ISSUE THREAD

**Issue by hbinnet** [BowlerHatLLC/feathers#1487]
VideoPlayer There is only the sound on the mobile side, there is no picture

**Comment by joshtynjala** [comment]
Try upgrading to AIR 24 beta. I saw some people were having similar issues on Android, but this version fixed them.

If this is an issue on both Android and iOS, then you probably need to change your encoding settings for the video. Some videos simply cannot be played on mobile, even if they work fine on desktop.

That's about all I can do to help. Playing the video is entirely controlled by AIR.

**Comment by hbinnet** [comment]
Thank you!
