### ISSUE TITLE
ToggleButton defaultSelectedLabelProperties not working

### ISSUE THREAD

**Issue by BlackTeaLeaf** [BowlerHatLLC/feathers#1491]
Excuse me
ToggleButton on 3.0.4, 3.1.0, Master version
Are the following properties currently not working?

defaultSelectedLabelProperties
selectedDownLabelProperties
selectedHoverLabelProperties
selectedUpLabelProperties

**Comment by joshtynjala** [comment]
Yes, it appears that I had broken these properties. I have fixed them, and I will including the fix in the upcoming version 3.1.1.

However, please be aware that these properties are considered deprecated, so you are encouraged to migrate away from them.
