### ISSUE TITLE
ImageLoader: Extract getting cache key from source into separate method

### ISSUE THREAD

**Issue by rozd** [BowlerHatLLC/feathers#1496]
Hi Josh, 

I think it would be good if ImageLoader has a separate method that converts current source into key for texture cache, some like this:

```as3
protected function getSourceKey():String
{
    return _source as String;
}
```

It will allow to override this method in subclasses and add support for caching textures loaded from other source than URL, for example from `IFilePromise` implementations. 

This new method should not have many side effects onto existent code except you probably have to change signature for the method:

```as3
protected function createTextureOnRestore(texture:Texture, source:String, 
    format:String, scaleFactor:Number):Function;
```

to 

```as3
protected function createTextureOnRestore(texture:Texture, source:Object, 
    format:String, scaleFactor:Number):Function
```

How do you think is there a reason to add such method?

Thanks

**Comment by joshtynjala** [comment]
This seems like a good improvement. Thanks for the suggestion!
