### ISSUE TITLE
Identical then and else branches of an if-statement in BaseMetalWorksMobileTheme

### ISSUE THREAD

**Issue by Klug76** [BowlerHatLLC/feathers#1499]
Found identical `then` and `else` branches of an `if`-statement in BaseMetalWorksMobileTheme:
```
			if(progress.direction == Direction.VERTICAL)
			{
				fillSkin.width = this.smallControlSize;
				fillSkin.height = this.smallControlSize;
			}
			else
			{
				fillSkin.width = this.smallControlSize;
				fillSkin.height = this.smallControlSize;
			}
 ```
and
```
			if(progress.direction == Direction.VERTICAL)
			{
				fillDisabledSkin.width = this.smallControlSize;
				fillDisabledSkin.height = this.smallControlSize;
			}
			else
			{
				fillDisabledSkin.width = this.smallControlSize;
				fillDisabledSkin.height = this.smallControlSize;
			}
```

**Comment by joshtynjala** [comment]
Looks like you missed that one is setting the dimensions of fillSkin and the other is doing the same with fillDisabledSkin! 😄

**Comment by teotigraphix** [comment]
Actually the if / else of each do the same thing(on the same instances with same values), I think that is what he was talking about.

**Comment by joshtynjala** [comment]
They aren't the same instance, though. They're two separate Image instances:

    var fillSkin:Image = new Image(this.buttonUpSkinTexture);

    var fillDisabledSkin:Image = new Image(this.buttonDisabledSkinTexture);

**Comment by teotigraphix** [comment]
No I didn't mean that, maybe I am out of context here but;

```
if(progress.direction == Direction.VERTICAL)
			{
				fillSkin.width = this.smallControlSize;
				fillSkin.height = this.smallControlSize;
			}
			else
			{
				fillSkin.width = this.smallControlSize;
				fillSkin.height = this.smallControlSize;
			}
```

Could be written; (without the if() )

```
				fillSkin.width = this.smallControlSize;
				fillSkin.height = this.smallControlSize;
```

Am I missing something? Or do you have the if() for symanitcs of direction even though they use the same code.

**Comment by joshtynjala** [comment]
Oh, got it.
