### ISSUE TITLE
AIR 24 packaging issue

### ISSUE THREAD

**Issue by timoisalive** [BowlerHatLLC/feathers#1500]
I'm having a hard time to believe this would be a Feathers issue, but I have no other lead to follow...

My actual app and a minimal test app both crash on iOS when packaged with the latest AIR 24.0.0.177. The crash occurs when I use "ipa-ad-hoc" or "ipa-test" target, but when using "ipa-test-interpreter" the app runs fine. Also, with AIR 23 all targets are fine. I'm testing on iPhone 6 (iOS 10.0.1) and iPad 2 (iOS 9.3).

The crash outputs a log entry into Diagnostics & Usage with this kind of exception type:

Exception Type:  EXC_BAD_ACCESS (SIGSEGV)
Exception Subtype: KERN_INVALID_ADDRESS at 0x0000000000000010
Termination Signal: Segmentation fault: 11
Termination Reason: Namespace SIGNAL, Code 0xb
Terminating Process: exc handler [0]
Triggered by Thread:  0

I've occasionally seen such exceptions and unfortunately never have learned how to debug such issues...

My minimal test project includes one Feathers Button on Starling stage with nothing but a single Quad. If I leave out the Button, or use a Starling Button instead of the Feathers button, the app runs fine. The Feathers is up to date, 3.1.1.

**Comment by timoisalive** [comment]
I was debugging more and discovered another strange behavior.

Here's my app source:

```actionscript
package {
    
    import flash.display.Sprite;
    import flash.display.StageScaleMode;
    import flash.events.Event;
    import flash.geom.Rectangle;
    
    import starling.core.Starling;
    import starling.events.Event;
    
    [SWF(width="0", height="0", backgroundColor="#000000")]
    public class Main extends Sprite {
        
        public function Main() {
            stage.scaleMode = StageScaleMode.NO_SCALE;
            stage.addEventListener(flash.events.Event.RESIZE, handleInitStageResize);
        }
        
        private function handleInitStageResize(event:flash.events.Event):void {
            if(stage.stageHeight == 0 || stage.stageWidth == 0) return;
            stage.removeEventListener(flash.events.Event.RESIZE, handleInitStageResize);
            
            new Starling(StarlingView, stage);
            Starling.current.addEventListener(starling.events.Event.ROOT_CREATED, onStarlingRootCreated);
        }
        
        private function onStarlingRootCreated(event:starling.events.Event):void {
            Starling.current.removeEventListener(starling.events.Event.ROOT_CREATED, onStarlingRootCreated);
            Starling.current.start();
            
            Starling.current.viewPort = new Rectangle(0, 0, stage.stageWidth, stage.stageHeight);
            Starling.current.stage.stageWidth = stage.stageWidth;
            Starling.current.stage.stageHeight = stage.stageHeight;
            
            var starlingView:StarlingView = Starling.current.root as StarlingView;
            starlingView.initialize();
        }
        
    }
    
}

import feathers.controls.Button;

import starling.display.Quad;
import starling.display.Sprite;

internal class StarlingView extends Sprite {
    
    public function StarlingView() {}
    
    public function initialize():void {
        var quad:Quad = new Quad(1000, 1000, 0xffffff);
        addChild(quad);
        
        var button:Button = new Button();
        button.label = "Button label";
        addChild(button);
    }
    
}
```
And here's my app descriptor:
```
<?xml version="1.0" encoding="utf-8" ?>
<application xmlns="http://ns.adobe.com/air/application/24.0">

    <id>com.beigeelephant.thisissand</id>
    <filename>Main</filename>
    <name>Main</name>
    <versionNumber>2.3.0</versionNumber>

    <initialWindow>
        <content></content>
        <visible>true</visible>
        <autoOrients>true</autoOrients>
        <fullScreen>true</fullScreen>
        <renderMode>direct</renderMode>
        <depthAndStencil>true</depthAndStencil>
        <softKeyboardBehavior>none</softKeyboardBehavior>
    </initialWindow>

    <iPhone>
        <InfoAdditions>
            <![CDATA[
			<key>UIDeviceFamily</key><array><string>1</string><string>2</string></array>
			<key>UIPrerenderedIcon</key><true/>
			<key>UIApplicationExitsOnSuspend</key><false/>
            ]]>
        </InfoAdditions>
        <requestedDisplayResolution>high</requestedDisplayResolution>
    </iPhone>

</application>
```
It all works fine packaged with AIR 23.

With AIR 24 I'm able to debug on device fine, but making an ad hoc distribution package introduces the trouble.

As such, the app just crashes on launch with above mentioned exception details.

If I comment out the Feathers button it runs fine.

But if I comment out the `stage.scaleMode = StageScaleMode.NO_SCALE;` line, the app does NOT crash, but instead goes black right after launch, no matter if the Feathers Button is included or not. Similar behavior as described here https://forums.adobe.com/thread/2229692.

Go figure. I think I revert to AIR 23 for now...

**Comment by joshtynjala** [comment]
You should submit an issue to Adobe Bugbase with your minimal test project. If AIR is crashing, that's super important to Adobe, and they'll want to fix it.

**Comment by timoisalive** [comment]
Adobe is informed in the above mentioned thread.

**Comment by joshtynjala** [comment]
Closing because this is something that Adobe needs to fix.
