### ISSUE TITLE
VideoPlayer Event.READY does not fire

### ISSUE THREAD

**Issue by rcoenen** [BowlerHatLLC/feathers#1504]
Air V23 for desktop / Feathers UI 3.1.1

Can't assign texture to player as Event.Ready never fires

**Comment by joshtynjala** [comment]
Closing for now. If you provide some code that will reproduce this issue, please feel free to reopen.

**Comment by salesbuddy** [comment]
Hi there, I came across a similar issue and found that certain videos did not fire the Event.ready. I dont know much about video formats but I can provide an MP4 video which wont fire Event.Ready if you need

**Comment by joshtynjala** [comment]
This was actually determined to be an Adobe AIR bug. If you can consistently reprice with certain video files, it would be best to provide them to Adobe. Here's the bug report for AIR:

https://tracker.adobe.com/#/view/AIR-4150401
