### ISSUE TITLE
Scroller: Feature request, to support _horizontalScrollBarPosition

### ISSUE THREAD

**Issue by GV3** [BowlerHatLLC/feathers#1506]
Currently, the scrollers support verticalScrollBarPosition so that the developer can decide on which side of the scroller should the scroll bar be positioned (RelativePosition.LEFT, RelativePosition.RIGHT)

Is becoming a new design trend in mobile Apps to have the scroll bar on the top of the scroller instead of always fix on the bottom as it would be on web-browsers.

I propose the use of the property _horizontalScrollBarPosition which would accept  RelativePosition.TOP and RelativePosition.BOTTOM (default)

I have modified my forked version of Feathers, and I'm committing the pull request as soon as I finish posting this issue, to be able to use the ID #----- as a ref in the commit.

**Comment by joshtynjala** [comment]
Duplicate #1209

**Comment by joshtynjala** [comment]
I'll be happy to merge your upcoming pull request, but just out of curiosity, can you point to any mainstream real-world apps that put the scroll bar on the top? I have never seen that before. Seems strange.

**Comment by GV3** [comment]
Of course :) 
 - Instagram : they use in the HOME screen, as weel as in the  <3  screen (Following, You).
 - Pinterest: In the messages/notifications screen

**Comment by GV3** [comment]
I think we will be seeing more implementations soon :)

Let's say you have a swipe-able navigation with a TabsNav (let's say) on the top displaying 3 or 4 titles. Using the scroll bar serves both as a title underline, for the selected tab, as a page-indicator, AND it's animation when tapping the tabs to select helps communicate to the user that he/she can swipe through the content.

**Comment by joshtynjala** [comment]
Oh, I see what you're talking about. In Instagram, I think the ❤️ screen is just a tab bar, though, and not actually a scroll bar. The Feathers TabBar can actually animate a selection indicator like that in version 3.1, by the way. On the Instagram home screen, it's behaving a little differently, but I think it's similar. I can see that it changes size depending on whether it's under the logo or one of the icon buttons. I suspect it's a part of that top navigation bar somehow. Kind of a modified tab bar, maybe.

Anyway, you can do this with TabBar already. However, I see nothing wrong with having horizontalScrollBarPosition to match verticalScrollBarPosition.

**Comment by GV3** [comment]
` The Feathers TabBar can actually animate a selection indicator like that in version 3.1, by the way`

GREAT :D , I didn't notice this before, thanks!
