### ISSUE TITLE
When adding components to screen and calling validate() immediately with a Starling.juggler.delayCall, components position get a flashing.

### ISSUE THREAD

**Issue by daicemirror** [BowlerHatLLC/feathers#1508]
Hi Josh.
Please test below code in ButtonScreen class at ComponentsExplorer example.
```
                override protected function initialize():void
		{
			super.initialize();
			
			Starling.juggler.delayCall(onDelay, 2);   //--Test A
			
			//setTimeout(onDelay, 2000);   //--Test B

                       //Starling.juggler.delayCall(onDelay, 0);   //--Test C
		}

                protected function onDelay():void
		{
			this.title = "Button";
			
			this._normalButton = new Button();
			this._normalButton.label = "Normal Button";
			this._normalButton.addEventListener(Event.TRIGGERED, normalButton_triggeredHandler);
			this.addChild(this._normalButton);

			_normalButton.validate();   //--add this line
			...

```
In Test A and Test C, you can see that normalButton in the wrong place(0,0) at the beginning.
After one frame normalButton can get the right position.
Interestingly, Test B dose not have this problem.
I dont know what's going on with that.
Please take a look, thank you!

**Comment by joshtynjala** [comment]
Call `this.validate()` at the end of onDelay(), and you're good to go. Unfortunately, this is something that I cannot fix.

Feathers has a ValidationQueue that gets added to Juggler, and it validates anything that's invalid every frame. When you call Starling.juggler.delayCall(), the ValidationQueue has already been added to the Juggler, so the DelayedCall gets added after the ValidationQueue. When the delayed call happens, the ValidationQueue has already been updated by the Juggler for the current frame, so the next automatic validation is on the next frame. When you call _normalButton.validate(), you're validating that one component immediately, but the screen's layout is still in the queue. Unfortunately, there are no other events after the Juggler is updated and before Starling renders.
