### ISSUE TITLE
Swipe velocity (feature request/enhancement)

### ISSUE THREAD

**Issue by dr-andy** [BowlerHatLLC/feathers#1509]
On mobile swiping a list or similar is not as smooth as native. This is because AIR didn't provide us a velocity information for swipe gestures. But in **AIR 24** there is a new property for swipe gesture: velocity. 
From release notes (http://fpdownload.macromedia.com/pub/labs/flashruntimes/shared/air24_flashplayer24_releasenotes.pdf):
"Starting AIR 24, AIR Developers can read the velocity property for on Android and iOS to estimate strength of the swipe. This value Swipe events will be in pixels per second."

I hope you can add that functionality to scrolls so it feels more native and smooth. Thanks.

**Comment by joshtynjala** [comment]
Scrollers already accurately calculate the velocity of touch movements. This property doesn't actually provide any new information that Feathers can use.
