### ISSUE TITLE
HorizontalLayout and includeInLayout

### ISSUE THREAD

**Issue by harry248** [BowlerHatLLC/feathers#1510]
I have some issues when using a LayoutGroup with a HorizontalLayout and children that have their  includeInLayout property set to false.

1. The gap set on the HorizontalLayout is still being used for each not included child
2. distributeWidths set to true doesn't seem to be affected by includeInLayout

**Comment by joshtynjala** [comment]
1. I tested with the following code which adds five buttons to a LayoutGroup with HorizontalLayout. The middle three buttons have includeInLayout set to false. I could not reproduce. The gap between the first and last button is only 10 pixels.

	var group:LayoutGroup = new LayoutGroup();
	group.move(20, 20);
	var layout:HorizontalLayout = new HorizontalLayout();
	layout.gap = 10;
	group.layout = layout;
	this.addChild(group);
	for(var i:int = 0; i < 5; i++)
	{
		var button:Button = new Button();
		if(i > 0 && i < 4)
		{
			button.includeInLayout = false;
		}
		group.addChild(button);
	}
	//display a 10 pixel quad to make comparison easy
	var gapQuad:Quad = new Quad(10, 10, 0xff00ff);
	gapQuad.x = 20;
	this.addChild(gapQuad);

2. I can reproduce this issue with the following code:

	var group:LayoutGroup = new LayoutGroup();
	group.width = this.stage.stageWidth;
	var layout:HorizontalLayout = new HorizontalLayout();
	layout.distributeWidths = true;
	group.layout = layout;
	this.addChild(group);
	for(var i:int = 0; i < 5; i++)
	{
		var button:Button = new Button();
		if(i > 0 && i < 4)
		{
			button.includeInLayout = false;
		}
		group.addChild(button);
	}
