### ISSUE TITLE
Todos demo incompatible override

### ISSUE THREAD

**Issue by duffel** [BowlerHatLLC/feathers#1511]
stage_resizeHandler in Main.as is conflicting with stage_resizeHandler in ScrollContainer

**Comment by joshtynjala** [comment]
Strangely, I'm not getting this error. Which SDK and version are you using the compile the project? I'm using AIR SDK & Compiler 24.0.0.180.

**Comment by duffel** [comment]
I updated everything to the latest versions. Starling & Feathers masters from github. AIR SDK & Compiler 24.0.0.180. I'm still getting the error. I'm using AnimateCC to compile so maybe that's the problem.

Compiler errors from Main.as:
1023: Incompatible override.
1024: Overriding a function that is not marked for override.
1000: Ambiguous reference to stage_resizeHandler.
1000: Ambiguous reference to stage_resizeHandler.

Main.as has stage_resizeHandler.
Main extends PanelScreen which inherits from ScrollContainer.
ScrollContainer also has stage_resizeHandler.
If I rename the handler to stage_resizeHandler_1 in Main everything works fine.

**Comment by joshtynjala** [comment]
Yeah, Animate uses its own fork of the ActionScript compiler. Even if you update to a newer AIR SDK, it keeps using its super old compiler.

I'll get this fixed to make Animate happy. 🙄
