### ISSUE TITLE
Scroller: (Top/Bottom/LeftRight)PullView covers the content of the scroller

### ISSUE THREAD

**Issue by GV3** [BowlerHatLLC/feathers#1514]
Hi Josh,

I'm assuming that the current behavior is by design, but since it could be a bug I'll write it here and not in the Forums.

The __PullViews are covering the content of the Scroller. And still, I think it would be great if the (Top/Bottom/LeftRight)PullView could be optionally under the items instead of always visually over them.

Let's imagine I (a user) pull down the scroller and display a TopPullView, a three dots (···) or a loading spinner appears, it might now take a few seconds to load the content, and if I scrolls back down while the content is loaded, the __PullView will remain on top of everything. 

As a user I would expect the list items (or Scroller content) to cover the __PullView, while it's loading (or doing anything else) it's ok that it remains in place, the pull view must not scroll up with the rest until the COMPLETE is dispatched, but I would certainly expect the content to cover it.

What do you think?

**Comment by joshtynjala** [comment]
Gmail (at least on Android) keeps the pull view on top of the content until completion if you scroll down after it is activated. That's a prominent real world example that I based the behavior on, so yes, it is by design. However, I think it makes sense to add a property to control whether the pull view covers the content or scrolls with it when active. I don't think it makes sense to hide the pull view by putting it under the content. Unless there's a good example of that on iOS or Android.

**Comment by GV3** [comment]
Hi Josh, I'll paste here a few good examples I've found on iOS where the loading wheel hides behind the content when scrolling back down after is activated.

I have seen two main cases, 1) the view either stays in place and the content overlaps it, or 2) the view scrolls up with the content.

- Mail (App). case 1
- Twitter. case 2
- Facebook. case 1

NOTE: I made the snaps AFTER the view was completely pulled and while I was waiting for the content to update.

![f4](https://cloud.githubusercontent.com/assets/1840077/21562231/87123e4a-ce77-11e6-91c5-85c640f7aa64.jpeg)
![f3](https://cloud.githubusercontent.com/assets/1840077/21562230/871046bc-ce77-11e6-8579-eb8310f27b6f.jpeg)
![f2](https://cloud.githubusercontent.com/assets/1840077/21562233/872772ba-ce77-11e6-9dae-6c03bff91c76.jpeg)
![f1](https://cloud.githubusercontent.com/assets/1840077/21562232/87137256-ce77-11e6-8d72-0b53ccf56f5e.jpeg)

**Comment by izzmeifter** [comment]
My 2 cents as this feature would greatly benefit us as well.

On iOS, having the indicator under the content definitely is more prominent as seen above.

The trick is though, you need a way to make the scroller stick at a pre-defined y-pos after being pulled so it doesn't bounce back up and cover the loading indicator until the operation is complete. We had a hard time efficiently making this happen with our in-house pull to refresh loaders.

**Comment by joshtynjala** [comment]
Thanks for the examples!
