### ISSUE TITLE
VerticalLayout not taking gap out with skipped layout children

### ISSUE THREAD

**Issue by teotigraphix** [BowlerHatLLC/feathers#1518]
I have a simple vertical layout that I am hiding two components out of say 6, using;

```
   instance.includeInLayout = instance.visible = isVisible;
```

When I have a gap of 8 in the layout I get image 2, when I set gap to 0, I get image 3, this is what I would expect from still using gap=8. I mage 1 shows the two groups that are hidden.

NOTE, there is a LayoutGroup with percentHeight = 100, so I would say the bug is that your layout measurment logic is not taking into account the two gaps removed when calculating the percentage height of that group.

I noticed this a long time ago but it didn't occur to me it had to do with hiding AND percentages.

1
![capture](https://cloud.githubusercontent.com/assets/226417/21463299/1cb4c21c-c935-11e6-92a2-2aa6f243d28d.PNG)

2
![capture2](https://cloud.githubusercontent.com/assets/226417/21463301/24560cd8-c935-11e6-8315-076f0a35f65c.PNG)

3
![capture3](https://cloud.githubusercontent.com/assets/226417/21463302/27a45bec-c935-11e6-8278-0978e0357727.PNG)

**Comment by joshtynjala** [comment]
It was not immediately clear to me what was wrong in your screenshots. However, I tried a few things at random and eventually figured it out. I can reproduce with the following code:

	var group:LayoutGroup = new LayoutGroup();
	group.height = this.stage.stageHeight;
	var layout:VerticalLayout = new VerticalLayout();
	layout.gap = 10;
	group.layout = layout;
	this.addChild(group);
	for(var i:int = 0; i < 10; i++)
	{
		var button:Button = new Button();
		button.defaultSkin = new Quad(40, 40, 0xff0000);
		if(i === 0)
		{
			button.layoutData = new VerticalLayoutData(NaN, 100);
		}
		if(i > 0 && i < 9)
		{
			button.includeInLayout = false;
			button.visible = false;
		}
		group.addChild(button);
	}

**Comment by teotigraphix** [comment]
Sorry Josh, I am just slammed for time and I know have repros saves you time. This I kind of just put up. :)

**Comment by teotigraphix** [comment]
Thanks Josh!
