### ISSUE TITLE
'interactionMode' conflicts with previous Declaration

### ISSUE THREAD

**Issue by cgascons** [BowlerHatLLC/feathers#1521]
Hi Josh,

This error appears everytime we make a build since we updated to the last version of Feathers, downloaded directly from Github, or even the feathers ui 3.1.1 downloaded directly from the website. We have recently updated to AIR 24 in case it helps.

Thanks,

**Comment by teotigraphix** [comment]
Are you using the SDK? If so are your using Apache Flex or any Flex SDK compiler?

This error comes from the change of using the [Style] metadata tag, there is nothing you can do to bypass it other than not using the conflicting SDK.

My errors came from the fact I was using FlexUnit and the UI, which uses the Flex SDK. I had to ditch the UI and create my own test runner.

**Comment by cgascons** [comment]
Hi teotigraphix, thanks for such quick response. We usually directly download the whole repository from the master branch here (https://github.com/BowlerHatLLC/feathers) and, since it was giving this issue I've tried downloading the zip: Feathers UI 3.1.1 (not the sdk). Hope that helps.

Regards,

**Comment by cgascons** [comment]
It's weird, now in addition to this, if I revert to the previous SDK, and still running on AIR 24, the game crashes 100% of the time when creating Text Inputs, giving a 3694 (content disposed) at StageTextTextEditor/createStageText()...

Not sure if related, but tried reverting Feathers to build 3.0.0 and Starling to 2.1 and still happens.

**Comment by teotigraphix** [comment]
Read this;

https://github.com/BowlerHatLLC/feathers/issues/1520

**Comment by cgascons** [comment]
You are the man teotigraphix! Thank you so much, after renaming all the "font" folders works as a charm.
