### ISSUE TITLE
List does not refresh after calling dataProvider.updateAll();

### ISSUE THREAD

**Issue by kevinfoley** [BowlerHatLLC/feathers#1522]
List does not visually refresh after calling `list.dataProvider.updateAll()` if new items have been added to the data source. The user must click on the List before changes will appear.

    private var _list:List;
    private var items:Array;
		
    override protected function initialize():void
    {
        items = [];
        this._list = new List();
        this._list.dataProvider = new ListCollection(items);
        Starling.juggler.delayCall(addItems, .5); //load the list items in half a second
    }

    private function addItems():void {
        for(var i:int = 0; i < 150; i++)
        {
            var item:Object = {text: "Item " + (i + 1).toString()};
            items[i] = item;
        }
        items.fixed = true;
        _list.dataProvider.updateAll(); //the list does not visually refresh until we click somewhere on it
    }

See attached class ListScreen, which is modified from ComponentExplorer and can be plugged directly into ComponentExplorer.
[ListScreen.as.txt](https://github.com/BowlerHatLLC/feathers/files/681664/ListScreen.as.txt)

Tested in Feathers 3.0.4 and 3.1.1. This issue did not occur in Feathers 2.3.

**Comment by joshtynjala** [comment]
updateAll() is actually meant to update item renderers that are rendering items that were already in the data provider. If it also caused new items in the data provider to be displayed too, that was not intended.

New items should generally be added using addItem(), addItemAt() and addAll() on the ListCollection. If it's a drastic change of data, you can also pass a new Array to the ListCollection's data property.

That said, I don't think it would hurt anything to make it check for added or removed items, so I'll make the change to support that use-case.
