### ISSUE TITLE
Possible memory leaks.

### ISSUE THREAD

**Issue by daicemirror** [BowlerHatLLC/feathers#1529]
Some components have the following code.
```
override protected function focusInHandler(event:Event):void
		{
			super.focusInHandler(event);
			this.stage.addEventListener(KeyboardEvent.KEY_DOWN, stage_keyDownHandler);
		}

		/**
		 * @private
		 */
		override protected function focusOutHandler(event:Event):void
		{
			super.focusOutHandler(event);
			this.stage.removeEventListener(KeyboardEvent.KEY_DOWN, stage_keyDownHandler);
		}
```
If the component suddenly disposed, the listener may not be removed.
My habit is once more to remove all listeners in the class with dispose().
If I'm wrong please correct me, thanks!

**Comment by joshtynjala** [comment]
The focus manager automatically dispatches FeathersEventType.FOCUS_OUT on a component if it is removed from the stage while it has focus. Assuming that you don't call dispose() before removing the child, you're fine.

In short, never call dispose() on a component if it hasn't been removed from the stage yet.

**Comment by daicemirror** [comment]
Thank you!
