### ISSUE TITLE
"This may be an infinite loop." error on a screen with complicated layout

### ISSUE THREAD

**Issue by antony-sklyar** [BowlerHatLLC/feathers#1531]
Hello, @joshtynjala .
I have recently updated my app to the latest Starling and Feathers (downloaded from official websites, not from GitHub, so the version is stable), and after code adaptation I have a problem that I seemingly cannot solve.

I keep getting `returned to validation queue too many times during validation. This may be an infinite loop.` error on one of my screens although I am using Feathers layout system to position my controls, doing nothing manually.

Could this be because of the large amount of containers and controls on the screen?
My basic layout is as follows:
* header panel at the top and a `ScrollContainer` with vertical layout filling the rest of the screen;
* in the scroll container there are several `LayoutGroup`s, each containing a logical group of controls
* contents of these layoutgroups differ: one has anchorlayout with photo, rating stars and comments count, one has a vertical layout with title and description, one has flowlayout with action buttons, etc.

From what I see in the source code of `FeathersControl`, there is a limit of 10 invalidate counts before the error is thrown. So I'd like to know, could the error in my case be because of the large amount of subcontainers and controls, or it is definitely an invalidation loop? Because it doesn't seem like I'm having any loop, as I'm using a combination of Feathers standart layouts.

Thanks in advance!

**Comment by teotigraphix** [comment]
Do you have any anchor layouts?

Also, watch out that you don not use too many percent width/height = 100, if you don't have some point of anchor dimension I have found you get these invalidation loops.

My advice is comment out all containers and build it back up until you find the loop, then you will learn what did it. :)

**Comment by teotigraphix** [comment]
BTW, I have some very complicated layouts, so I have learned much about some layouts/combinations the don't work.

Now that I have more time I am laying out more complicated layouts flat in a LayoutGroup and positioning them myself in draw().

Check out the showcase for LilDrumMachine and you will know what I am talking about. :)

https://feathersui.com/showcase/

**Comment by antony-sklyar** [comment]
Yes, I have some anchor layouts.

>I have learned much about some layouts/combinations the don't work

Interesting... And what combinations don't work well together?

I thought using layouts is a better practice than manual positioning, isn't it? I thought not using them is just for the sake of the performance, and if it's not the case, layouts give you more stability.

**Comment by teotigraphix** [comment]
AnchorLayouts can be a pain using percentages.

To many percentages can kill a layout because they will collapse on themselves.

> I  thought using layouts is a better practice than manual positioning, isn't it?

Nope, a manual layout will beat a layout every time if you know what you are doing. This is NOT to say Josh's layouts are not fast.

I am talking about building up composite components, that you know you have control over. Obviously using other layouts that are virtualized in Lists etc are a no brainer.

**Comment by joshtynjala** [comment]
This error happens when invalidate() is called during validation too many times. It's terrible for performance when that happens, so it's best to catch it instead of letting it go, like Feathers used to do.

Do you ever override the draw() method of a Feathers component? It could be that something that you are doing in this override is unintentionally invalidating the component. One example that I see sometimes when I see people post code in the forums is setting the component's own width or height properties inside its own draw() function. Many other properties can invalidate too, such as styles.

**Comment by teotigraphix** [comment]
@joshtynjala I had this the other day and I almost found the cause, it was with AnchorLayouts and percentages. When I fixed that, I got the maxWidth cannot be NaN error.

I ended up removing the AnchorLayout completely.

**Comment by antony-sklyar** [comment]
> Do you ever override the draw() method of a Feathers component?

Yes, I do. By the way, if I'm subclassing `LayoutGroup` is it right to call `super.draw()` *before* I update my custom controls or *after* I update them?

For example, `draw()` method of all my app screens base class is as follows:
```
override protected function draw():void 
{
	if (this.isInvalid(INVALIDATION_FLAG_DATA))
	{
		this.commitData();
		this.restoreSavedProperties();
	}
	if (this.isInvalid(INVALIDATION_FLAG_LAYOUT)) this.updateLayout();
	super.draw();
}
```
Is that a correct flow or should I do things differently?

**Comment by joshtynjala** [comment]
If you want to set properties on children of a LayoutGroup, you should do it before calling super.draw(). You want everything to be done before the layout is handled because the layout will automatically validate all of the children.

**Comment by antony-sklyar** [comment]
OK, so this is really it, I've been able to debug the place causing "infinite loop" on a simpler screen by commenting some of the code out. The problem is exactly like you've mentioned, @joshtynjala , when I update the layout of the screen it sets the background image size and crashes on infinite loop - probably because when the size of the element is changed the parent is invalidated.

I am sorry if that is a silly question and is highlighted somewhere in the manual (which I've read thoroughly though) but what is a proper way of doing things when I want to (a) prepare the initial layout of the screen and (b) update the UI when the data arrives from the server and (c) update the layout when the screen is rotated?

**Comment by joshtynjala** [comment]
When I designed LayoutGroup and ScrollContainer (including their subclasses, like screens), I pretty much assumed that changes to child layout properties would happen in things like event listeners (instead of draw()) or inside an ILayout implementation. If you override draw() and change things outside of the ILayout, that could indeed cause the container to invalidate during draw().

With that in mind, the best practice would be to create a [custom layout](https://feathersui.com/help/custom-layouts.html). That can be cumbersome, though.

LayoutGroupListItemRenderer has special preLayout() and postLayout() methods where you can modify children without causing invalidation. Perhaps I should bring those up a level and make them available to LayoutGroup (and ScrollContainer) to make things easier.

**Comment by antony-sklyar** [comment]
Hmm, but how can I setup the screen after I receive the data from the server? I mean, if I don't override `draw()`, is there some method to make the screen refresh the data (which include hide/show/add controls, update lists dataproviders, update styleName of the controls) without dealing with custom layout and without causing invalidation loop?

**Comment by joshtynjala** [comment]
Not everything you do to the children in draw() will cause the screen to invalidate. Setting data on the children shouldn't be a problem, for instance. Setting a child's width or height, modifying includeInLayout, or modifying the layoutData property are probably the main things to avoid in draw() in LayoutGroup or ScrollContainer. Setting a List's dataProvider, a component's styleName or any style properties, and stuff like that should be safe.

LayoutGroup and ScrollContainer both have an undocumented _ignoreChildChanges variable. If you absolutely had to, you do this in parts of the code that cause invalidation:

	this._ignoreChildChanges = true;
	child.width = 50;
	this._ignoreChildChanges = false;

**Comment by antony-sklyar** [comment]
Thanks, this approach helped! I just wrapped `this.updateLayout()` in `_ignoreChildChanges` and everything is almost fine now (background image on one of the screens is not updated, but I'll probably fix that, all the other things seem to be fine).

> LayoutGroupListItemRenderer has special preLayout() and postLayout() methods where you can modify children without causing invalidation. Perhaps I should bring those up a level and make them available to LayoutGroup (and ScrollContainer) to make things easier.

That would probably help, I'd vote for this change!

**Comment by joshtynjala** [comment]
@antony-sklyar Can you share with me the code from your updateLayout() function? I'd like to get a better idea of how you've caused invalidation too many times in there.

**Comment by antony-sklyar** [comment]
That's strange, but it seems I cannot.

I'm performing a heavy refactoring of the app these days, and it seems like the problem with "infinite loop" disappeared completely now, even when I commented out the `_ignoreChildChanges` lines the app is still working without any error.

I will try to find a git revision where the problem was evident and post the code here if I find it.

**Comment by antony-sklyar** [comment]
Hello again, @joshtynjala !
I was able to catch the above mentioned error again today. But further investigation proved that in today's case I was changing the width of the scroll container **twice** during the `updateLayout()` (part of `draw()`).

So the basic setup is as follows:
1. Let the app screens base class be `BaseAppScreen`. Let it define `updateLayout()` method that is called from `draw()` to update the screen layout.
2. Let the `BaseAppScreen.updateLayout()` set the width of the content area scroll container to match the width of the screen.
3. Then let us have a `RegisterScreen` that is a subclass of `BaseAppScreen` and let it override `updateLayout()` where it calls `super.updateLayout()` and then changes the width of the same scroll container to 3/4 width of the screen.

This is exactly the situation that is creating the invalidation loop for me. If I just comment out one of the two `scrollContainer.width = ...` statements (either in base class or in subclass) the things are going fine, no validation loop.

**Comment by joshtynjala** [comment]
For my own future reference, the following code will reproduce this issue:

	class CustomGroup extends LayoutGroup
	{
		private var _child:Button;

		override protected function initialize():void
		{
			super.initialize();

			this._child = new Button();
			this._child.label = "Click Me";
			this.addChild(this._child);
		}

		override protected function draw():void
		{
			this._child.width = Math.random() * 100;
			this._child.width = 150;
			super.draw();
		}
	}

Currently, one workaround is to do this:

	this._ignoreChildChanges = true;
	this._child.width = Math.random() * 100;
	this._child.width = 150;
	this._ignoreChildChanges = false;

The correct solution is to ensure that dimensions of the child are set once and do not change every validation cycle.

I'm looking into a way to make it work without requiring `_ignoreChildChanges` to be used in subclasses, as long as the changes happen before the layout is applied.

**Comment by joshtynjala** [comment]
Alright, I think I came up with a supported solution that I like. If you modify children in a LayoutGroup or ScrollContainer (or one of their subclasses, like Panel) before calling super.draw(), the error about validating too many times will no longer be thrown, starting in the upcoming Feathers 3.3. If you do it after calling super.draw(), the error will still be thrown because changes to the children really must happen before the layout is applied.
