### ISSUE TITLE
Should ToggleSwitch not claim ExclusiveTouch?

### ISSUE THREAD

**Issue by timoisalive** [BowlerHatLLC/feathers#1534]
I'm implementing a ScrollContainer with Sliders and ToggleSwitches in the content. The Sliders claim ExclusiveTouch but the ToggleSwitches don't, and hence also the content is being scrolled when scrolling/switching the ToggleSwitches. I would assume ToggleSwitch would also claim the ExclusiveTouch...

**Comment by joshtynjala** [comment]
I'll look into it!

**Comment by timoisalive** [comment]
Cheers! :)

**Comment by timoisalive** [comment]
Awesome, cheers! :)
