### ISSUE TITLE
PullView remains viewable in padded area

### ISSUE THREAD

**Issue by kevinfoley** [BowlerHatLLC/feathers#1535]
The PullView remains visible in the padding area of a List for one second after telling the List to hide its pullView. This looks very strange and I'm assuming it is unintended behavior.

    override protected function initialize():void
        [...]
        this._list.paddingTop = 30;
        this._pullView = new Quad(200, 100, 0xaa0000);
        this._list.topPullView = this._pullView;
        this._list.addEventListener(Event.UPDATE, list_updateHandler);			
    }
    private function list_updateHandler(e:Event):void {
        Starling.juggler.delayCall(hidePullView, .5);
    }		
    private function hidePullView():void {
        //after calling this, the pullView will remain visible in the padded area at the top of the list
        //for a full second before it is hidden
        this._list.isTopPullViewActive = false;
    }

**Comment by joshtynjala** [comment]
Thanks! I'll get it fixed.

**Comment by kevinfoley** [comment]
@joshtynjala  This issue still exists in Feathers 3.3. beta

**Comment by joshtynjala** [comment]
I cannot reproduce this issue. With the following code, the pull view is correctly clipped when hidden (pull down, then touch/click the pull view to hide it):

	new MetalWorksMobileTheme();
	var list:List = new List();
	list.paddingTop = 30;
	var pullView:Quad = new Quad(200, 100, 0xff0000);
	pullView.addEventListener(TouchEvent.TOUCH, function(event:TouchEvent):void
	{
		var touch:Touch = event.getTouch(pullView, TouchPhase.BEGAN);
		if(!touch)
		{
			return;
		}
		list.isTopPullViewActive = false;
	})
	list.topPullView = pullView;
	list.dataProvider = new ListCollection(
	[
		{label: "One"},
		{label: "Two"},
		{label: "Three"},
		{label: "Four"},
		{label: "Five"},
		{label: "Six"},
	]);
	list.setSize(200, 200);
	this.addChild(list);

**Comment by kevinfoley** [comment]
@joshtynjala  I figured out the issue; it doesn't measure the mask height correctly if the pull view's pivot is not aligned to the upper left corner. If you add `pullView.alignPivot()` to your code, you can see this occur.

**Comment by joshtynjala** [comment]
Thanks! I can reproduce when the pull view uses pivots.

**Comment by kevinfoley** [comment]
Out of curiosity, is there any reason you didn't use the `bounds` property? Is that for performance purposes?

**Comment by joshtynjala** [comment]
That's just how I've always treated pivots, ever since I first added support in layouts.
