### ISSUE TITLE
TabNavigator isSwipeEnabled null pointer exception

### ISSUE THREAD

**Issue by harry248** [BowlerHatLLC/feathers#1536]
Swiping between two screens works as long as the swipe is slow and controlled. Swiping fast I often get a null pointer (_savedNewScreen) exception in line 1353 of TabNavigator. The first screen contains a ScrollContainer the second one a List (both with a vertical layout).

**Comment by joshtynjala** [comment]
Thank you! I could reproduce, and it should be fixed in commit 4411abe5c9779e329ce641c6a8fa1b48cf74e253
