### ISSUE TITLE
Setting includeInLayout on header left/right items

### ISSUE THREAD

**Issue by harry248** [BowlerHatLLC/feathers#1540]
Would be nice if the includeInLayout property would be included during the layout of the left and right items of a Header control. Currently this doesn't seem to be the case.

**Comment by joshtynjala** [comment]
Good idea!

**Comment by joshtynjala** [comment]
After a quick test, this appears to be working correctly already! It may not have worked in an older version, but Header has been using HorizontalLayout internally for a while now.
