### ISSUE TITLE
ImageLoader ignores maxWidth and maxHeight when both are set

### ISSUE THREAD

**Issue by kevinfoley** [BowlerHatLLC/feathers#1541]
In Feathers 3.2-beta, if we give an ImageLoader a maxWidth _and_ a maxHeight while maintainAspectRatio is `true`, it ignores both of them:

    imageLoader = new ImageLoader();
    imageLoader.source = "https://feathersui.com/images/feathers-ui-three-iphones.png";
    imageLoader.maxWidth = 100;
    imageLoader.maxHeight = 100;
    imageLoader.maintainAspectRatio = true;
    addChild(imageLoader);
    //image appears at its original size

The behavior I would expect would be for the image to size itself such that the width was no greater than `maxWidth` _and_ the height was no greater than `maxHeight`.

Note that if you use `maintainAspectRatio = false`, the image sizes correctly. It also sizes correctly if you only set the `maxWidth` _or_ `maxHeight` but not both.

**Comment by joshtynjala** [comment]
Thank you! I can reproduce.
