### ISSUE TITLE
List.scrollToPageIndex() not working in 3.2.0 beta

### ISSUE THREAD

**Issue by timoisalive** [BowlerHatLLC/feathers#1542]
Something seems to have broken the scrollToPageIndex between 3.1.2 and 3.2.0 beta.

My following code scrolls fine with 3.1.2 but on 3.2.0 beta it doesn't scroll anywhere, always stays on the first page.

BTW, it would nice to be able to define 0 for animationDuration if no animation is wanted...

```actionscript
_list = new List();
_list.addEventListener(FeathersEventType.RENDERER_ADD, onListRendererAdd);
_list.addEventListener(FeathersEventType.RENDERER_REMOVE, onListRendererRemove);
_list.itemRendererType = TipDialogItemRenderer;
_list.layout = new HorizontalLayout();
_list.snapToPages = true;
_list.dataProvider = dataProvider;
addChild(_list);
			
for(var i:int=0; i<_list.dataProvider.length; i++) {
	if(_list.dataProvider.getItemAt(i).id == tipId) {
		_list.scrollToPageIndex(i, 0, 0.01);
		break;
	}
}
```

**Comment by joshtynjala** [comment]
> BTW, it would nice to be able to define 0 for animationDuration if no animation is wanted...

Interesting that I didn't make setters for the horizontalPageIndex and verticalPageIndex properties. I was just going to suggest that you set those instead of calling scrollToPageIndex() if you don't want animation, but I guess that won't work!

**Comment by joshtynjala** [comment]
The code that you provided seems to be working for me. The one thing that I needed to change was to set the width, so maybe you forgot that?

**Comment by joshtynjala** [comment]
Setting the duration to 0 also worked, but since scrollToPageIndex() is designed specifically for animation, it doesn't truly happen immediately. It will happen as soon as the List validates, though, so you should be able to simply call validate().

**Comment by joshtynjala** [comment]
Here is the modified code that I used, by the way:

	new MetalWorksMobileTheme();
	var _list:List = new List();
	_list.layout = new HorizontalLayout();
	_list.snapToPages = true;
	_list.setSize(stage.stageWidth, stage.stageHeight);
	_list.dataProvider = new ListCollection(
	[
		{ label: "01" },
		{ label: "02" },
		{ label: "03" },
		{ label: "04" },
		{ label: "05" },
		{ label: "06" },
		{ label: "07" },
		{ label: "08" },
		{ label: "09" },
		{ label: "10" },
		{ label: "11" },
		{ label: "12" },
		{ label: "13" },
		{ label: "14" },
		{ label: "15" },
		{ label: "16" },
		{ label: "17" },
		{ label: "18" },
		{ label: "19" },
		{ label: "20" },
	]);
	addChild(_list);
				
	for(var i:int=0; i<_list.dataProvider.length; i++) {
		if(_list.dataProvider.getItemAt(i).label == "13") {
			_list.scrollToPageIndex(i, 0, 0);
			break;
		}
	}

**Comment by joshtynjala** [comment]
I created #1543 for the horizontalPageIndex and verticalPageIndex setters.

**Comment by timoisalive** [comment]
Ok, I found the problem in my code which was related to setting the width, thanks Josh! Still don't understand why it worked with 3.1.2 and not 3.2.0, but that doesn't matter! :)

Yeah, I was kinda looking for those setters as well, but now the 0 duration works for me too, so that'll do fine until we get the setters. Thanks again! :)
