### ISSUE TITLE
Request: simplify ImageSkin default 'selected' button states

### ISSUE THREAD

**Issue by kevinfoley** [BowlerHatLLC/feathers#1544]
Say you have a ToggleButton or Check which only has two visual states, "selected" and "not selected". You'd probably be inclined to style the control something like this:

    var imageSkin:ImageSkin = new ImageSkin(checkIconTexture);
    imageSkin.setTextureForState(ButtonState.UP_AND_SELECTED, checkSelectedIconTexture);
    check.defaultIcon = imageSkin;

However, if you use this approach, if the button/check is selected and you hover or press down on it, it will show the _`UP`_ skin instead of the _UP_AND_SELECTED_ skin.

This forces you to define the `DOWN_AND_SELECTED` and `HOVER_AND_SELECTED` states, which can end up being a lot of boilerplate if you have to do it for dozens of controls:

    var imageSkin:ImageSkin = new ImageSkin(checkIconTexture);
    imageSkin.setTextureForState(ButtonState.DOWN_AND_SELECTED, checkSelectedIconTexture);
    imageSkin.setTextureForState(ButtonState.UP_AND_SELECTED, checkSelectedIconTexture);
    imageSkin.setTextureForState(ButtonState.HOVER_AND_SELECTED, checkSelectedIconTexture);

It would be nice if the ImageSkin used the `UP_AND_SELECTED` skin for the `DOWN_AND_SELECTED` state and the `HOVER_AND_SELECTED` states, if the user hasn't manually set a skin for the latter two states. If I remember correctly, this is how the `SmartDisplayObjectStateValueSelector` from Feathers 2.x worked.

**Comment by joshtynjala** [comment]
[selectedTexture](https://feathersui.com/api-reference/feathers/skins/ImageSkin.html#selectedTexture) to the rescue!

	var imageSkin:ImageSkin = new ImageSkin(checkIconTexture);
	imageSkin.selectedTexture = checkSelectedIconTexture;

**Comment by kevinfoley** [comment]
D'oh!
