### ISSUE TITLE
Incorrect text positioning in Label with custom leading

### ISSUE THREAD

**Issue by subdan** [BowlerHatLLC/feathers#1551]
Hello, Josh.

Look at the right Label. The text inside label should be centered but it doesn't.

![screenshot_2](https://cloud.githubusercontent.com/assets/410293/25046041/82c8814a-212f-11e7-832e-535240c519df.png)

It happens if I change `Label.fontStyle.leading` from default value to new value. Both Labels have `wordWrap=true`

	var quad1:Quad = new Quad(300,70,0xCCCCCC);
	quad1.x = 400;
	quad1.y = 100;
	addChild(quad1);
	
	var label1:Label = new Label();
	label1.width = 300;
	label1.height = 70;
	label1.x = 400;
	label1.y = 100;
	label1.textRendererFactory = function ():ITextRenderer
	{
		var textRenderer:TextFieldTextRenderer = new TextFieldTextRenderer();
		textRenderer.updateSnapshotOnScaleChange = true;
		textRenderer.embedFonts = true;
		return textRenderer;
	};
	label1.text = "Text with 1 line of text.";
	label1.fontStyles = new TextFormat("Arial",14,0x000000);
	label1.fontStyles.leading = 20;
	label1.wordWrap = true;
	addChild(label1);
	
	
	var quad:Quad = new Quad(200,70,0xCCCCCC);
	quad.x = 100;
	quad.y = 100;
	addChild(quad);
	
	var label:Label = new Label();
	label.width = 200;
	label.height = 70;
	label.x = 100;
	label.y = 100;
	label.textRendererFactory = function ():ITextRenderer
	{
		var textRenderer:TextFieldTextRenderer = new TextFieldTextRenderer();
		textRenderer.updateSnapshotOnScaleChange = true;
		textRenderer.embedFonts = true;
		return textRenderer;
	};
	label.text = "Text with 2 lines\n of text.";
	label.fontStyles = new TextFormat("Arial",14,0x000000);
	label.fontStyles.leading = 20;
	label.wordWrap = true;
	addChild(label);

**Comment by joshtynjala** [comment]
Unfortunately, this is simply how flash.text.TextField behaves. If you run the following code in a non-Starling project, you can see that the leading in the second flash.text.TextField is included in the border:

	var tf1:TextField = new TextField();
	tf1.autoSize = TextFieldAutoSize.LEFT;
	var format1:TextFormat = new TextFormat("Arial", 20);
	tf1.defaultTextFormat = format1;
	tf1.text = "Hello World";
	tf1.x = 10;
	tf1.y = 10;
	tf1.border = true;
	this.addChild(tf1);

	var tf2:TextField = new TextField();
	tf2.autoSize = TextFieldAutoSize.LEFT;
	var format2:TextFormat = new TextFormat("Arial", 20);
	format2.leading = 20;
	tf2.defaultTextFormat = format2;
	tf2.text = "Hello World";
	tf2.x = 10;
	tf2.y = 100;
	tf2.border = true;
	this.addChild(tf2);

**Comment by subdan** [comment]
Ok. Thanks.
