### ISSUE TITLE
BitmapFontTextRenderer: wordWrap does not break word that is longer than available width

### ISSUE THREAD

**Issue by yuhengh** [BowlerHatLLC/feathers#1552]
The following code snippet should be able to reproduce the issue. If I change the first line to new MetalWorksMobileTheme() then the label can be wrapped correctly. I'm using Feathers 3.2.

			new MinimalMobileTheme();
			var label:Label = new Label();
			label.width = 20;
			label.wordWrap = true;
			label.text = "abcdefghijklmnopqrst";
			addChild(label);
			//text printed in a single line

**Comment by joshtynjala** [comment]
Thanks, but BitmapFontTextRenderer wraps at whitespace only. There are no spaces in your text.

**Comment by yuhengh** [comment]
I see, then I don't think it will be an issue in real world.
