### ISSUE TITLE
Suggestion: add initializeFontSizes() to theme

### ISSUE THREAD

**Issue by kevinfoley** [BowlerHatLLC/feathers#1555]
In each of the included themes, the `initializeFonts()` function starts by defining the font sizes:

    protected function initializeFonts():void
    {
        this.smallFontSize = 10;
        this.regularFontSize = 12;
        this.largeFontSize = 14;
        this.extraLargeFontSize = 18;

        this.lightFontStyles = new TextFormat(FONT_NAME, this.regularFontSize, LIGHT_TEXT_COLOR, HorizontalAlign.LEFT, VerticalAlign.TOP);
        this.darkFontStyles = new TextFormat(FONT_NAME, this.regularFontSize, DARK_TEXT_COLOR, HorizontalAlign.LEFT, VerticalAlign.TOP);
        [etc]

Let's say we want to create a child theme that extends MetalWorksMobileTheme. We want to use all of the font styles from MetalWorksMobileTheme, but change the default font sizes. We can't do this:

    override protected function initializeFonts():void {
        this.smallFontSize = 8;
        this.regularFontSize = 12;
        this.largeFontSize = 16;
        this.extraLargeFontSize = 24;
        super.initializeFonts();
    }

because the font sizes will get reset at the beginning of `initializeFonts()` in the BaseMetalWorksMobileTheme. So we end-up having to copy-paste override the entire 50-line function to change the first 4 lines of code in it.

I suggest adding a function called `initializeFontSizes()` that we can override to change the font sizes without needing to copy-paste override all of `initializeFonts`:

    protected function initializeFontSizes():void {
        this.smallFontSize = 8;
        this.regularFontSize = 12;
        this.largeFontSize = 16;
        this.extraLargeFontSize = 24;
    }

    protected function initializeFonts():void {
        initializeFontSizes();

        this.lightFontStyles = new TextFormat(FONT_NAME, this.regularFontSize, LIGHT_TEXT_COLOR, HorizontalAlign.LEFT, VerticalAlign.TOP);
        this.darkFontStyles = new TextFormat(FONT_NAME, this.regularFontSize, DARK_TEXT_COLOR, HorizontalAlign.LEFT, VerticalAlign.TOP);
        [etc]

**Comment by joshtynjala** [comment]
It's a good idea!

**Comment by Klug76** [comment]
+1
