### ISSUE TITLE
Children with coordinates (or pivots that push them into negative coordinates) did not affect the minimum scroll position

### ISSUE THREAD

**Issue by denisgl777** [BowlerHatLLC/feathers#1556]
This problem is still relevant, I can make an example

**Comment by joshtynjala** [comment]
Okay, please make an example. :)

**Comment by denisgl777** [comment]
Project created in Flashdevelop

https://drive.google.com/open?id=0B4pDy53MM-JhVVdfZS1iOFBmS1k

**Comment by joshtynjala** [comment]
This issue is resolved. I forgot that pivotX and pivotY were in the display object's local coordinate system instead of the parent coordinate system, so scaleX and scaleY needed to be included manually.
