### ISSUE TITLE
ListDataViewPort

### ISSUE THREAD

**Issue by denisgl777** [BowlerHatLLC/feathers#1557]
#1556 by denisgl777 was closed 30 minutes ago 

Fixed LayoutViewPort.as
Perhaps the same thing is needed in ListDataViewPort.as
Because in the gallery the problem continue
In my proposed example, the change in the size of the sheet elements

https://drive.google.com/open?id=0B4pDy53MM-JhVVdfZS1iOFBmS1k

**Comment by joshtynjala** [comment]
You have a ScrollContainer in your GalleryItemRenderer. ScrollContainer doesn't use ListDataViewPort.

Just remove that HorizontalLayout and use the default behavior when layout is null. I would not have closed your issue if it did not fix your example.

**Comment by denisgl777** [comment]
Yes it solved my problem!
Excuse for troubling:)
Thanks Josh!
