### ISSUE TITLE
Poss typo-bug in line 3003 of BaseDefaultItemRenderer

### ISSUE THREAD

**Issue by Stray** [BowlerHatLLC/feathers#1561]
Hi Josh,

digging through the depths to do some custom item rendering... I noticed, in line **3003** of **BaseDefaultItemRenderer**:

    public function set skinSourceField(value:String):void
		{
			if(this._iconSourceField == value)
			{
				return;
			}
			this._skinSourceField = value;
			this.invalidate(INVALIDATION_FLAG_DATA);
		}

I may be wrong, but I expect the test against `this._iconSourceField` should be against `this._skinSourceField`.

It's such a small change I didn't think patching and sending a pull request was efficient!

Thanks,

Stray

**Comment by joshtynjala** [comment]
Thanks! Good catch.
