### ISSUE TITLE
Scroller scrollbar bug

### ISSUE THREAD

**Issue by subdan** [BowlerHatLLC/feathers#1562]
Hello, Josh.

I have a very long List. Scroll position is zero (I see the first item). I press on the list and move my finger down. When I release my finger scrollbar immediately dissappears but it should wait while scroll animation ends (It's default iOS and Android behabiour). Moreover If I press on the list again when scroll animation isn't finish the scrollbar doesn't appear but it should.

I fixed it by removing line 8043: `this.hideVerticalScrollBar();` of function `stage_touchHandler`.

**Comment by joshtynjala** [comment]
I cannot reproduce this issue. For me, the scroll bar is not hidden until the scroll animation ends.

**Comment by subdan** [comment]
I will record a video tomorrow to show you the issue.

**Comment by joshtynjala** [comment]
If you could also put together some simple example code that will reproduce the issue, that would be ideal.

**Comment by subdan** [comment]
How it looks now https://drive.google.com/open?id=0B9zVeCnEAzqeOVJIMWNfa0FMNmM
How it should looks https://drive.google.com/open?id=0B9zVeCnEAzqeQk5QMXdxbU1CZW8
If you don't see any difference I can explain.

**Comment by joshtynjala** [comment]
I can reproduce the issue where the scroll bar immediately disappears when you drag into negative scroll position and end the touch. It should scroll back to 0 and then disappear.
