### ISSUE TITLE
TextInput doesn't clear focus after touch return key (ReturnKeyLabel.DONE)

### ISSUE THREAD

**Issue by subdan** [BowlerHatLLC/feathers#1563]
Hi, Josh. Adobe fixed the bug [AIR-4198260 On Android StageText not firing ENTER event](https://tracker.adobe.com/#/view/AIR-4198260). Why TextInput still doesn't clear focus when touching Done button?

I use `FeathersEventType.ENTER` event and `clearFocus` method to fix this issue:
```
nameInput = new TextInput();
nameInput.textEditorProperties.returnKeyLabel = ReturnKeyLabel.DONE;
nameInput.addEventListener(FeathersEventType.ENTER, nameInput_enterHandler);
function nameInput_enterHandler(event:Event):void
{
	nameInput.clearFocus();
}
```

**Comment by joshtynjala** [comment]
In many cases, when Enter is pressed, the TextInput should remain focus. For instance, the Todos example uses this behavior so that you can add multiple to-dos without tapping the TextInput multiple times.

Calling clearFocus() is the correct solution here. You're doing it right!

**Comment by subdan** [comment]
Ok. Thanks.
