### ISSUE TITLE
VideoPlayer exception

### ISSUE THREAD

**Issue by CrazyFlasher** [BowlerHatLLC/feathers#1564]
VideoPlayer doesn't want to play video on Android 7.
But plays in fine on desktop
Throws exception:
```
[trace] [Starling] Context restored.
[Fault] exception, information=Error: Error #3605: Sampler 0 binds an invalid texture.
```
Do I need to handle somehow lost context manually in this case?
I use release version if Feathers 3.2.0 and build project with AIR 25 merged with Flex SDK 4.16.0

**Comment by joshtynjala** [comment]
Have you tried using Android's old video pipeline? Adobe added a way to fall back to it in AIR 25.

https://helpx.adobe.com/flash-player/release-note/fp_25_air_25_release_notes.html#OptiontofallbacktoolderVideopipelineforAndroid

**Comment by CrazyFlasher** [comment]
Adding `<disableMediaCodec>true</disableMediaCodec>` helped.
Thanks!
