### ISSUE TITLE
Problems building examples against Feathers 3.2 SDK

### ISSUE THREAD

**Issue by Stray** [BowlerHatLLC/feathers#1565]
Hi Josh,

I ran in to the dreaded '2 input textfields... crash' bug in Air 24. So I updated to Feathers 3.2 SDK, with Air 25. Then I could no longer compile, so I tried 3.2 against the ComponentsExplorer example.

The examples use the following in sdk.properties:

    compc = ${flashsdk.root}/lib/compc-cli.jar
    mxmlc = ${flashsdk.root}/lib/mxmlc-cli.jar

It seems `compc-cli.jar` and `mxmlc-cli.jar` no longer exist in Air 25 SDK. I changed these to match the files that do exist (`compc.jar` and `mxmlc.jar`), but then I run in to:

    defaults: Error: unable to open './macFonts.ser'

The `macFonts.ser` file does exist, and is `./` from the config file, but possibly not `./` from where mxmlc thinks it is running.

Are you able to build the examples against the 3.2 SDK? Have I missed something obvious?

Thanks,

Stray

**Comment by joshtynjala** [comment]
The Ant scripts to build the Feathers UI library examples are meant to be used with the AIR SDK & Compiler. They won't work with the Feathers SDK or Flex SDK. It's not that mxmlc-cli.jar and compc-cli.jar were renamed at some point. It's actually that different SDKs contain different compilers. The AIR SDK & Compiler contains "ASC 2.0", and the Feathers SDK and Flex SDK contain what you might call "ASC 1.0".

I don't actually distribute the Ant scripts with official builds of Feathers UI library. They're mostly just for my personal use during development, so I haven't bothered to make them work with other SDKs.

The Feathers SDK has its own set of examples, but unfortunately, not all of the same ones that exist in Feathers UI library. You can find them in the `examples` directory of the SDK.

**Comment by Stray** [comment]
Thanks Josh - that makes sense. 

I'll go back to the SDK set up I was using and the source for 3.2 rather than the Feathers SDK. I thought I was 'doing the right thing' in changing from my cobbled-together-libs to the official Feathers SDK... but my apps were initially grown from looking at your examples, so I'll stick with what works and just manually update my AIR SDK.

Thanks for such a prompt response - I could have spent hours wandering around in the depths of compiler errors :)

Stray

**Comment by joshtynjala** [comment]
I should add that the Feathers SDK should be able to compile the examples from the Feathers UI library without errors. However, you'd need to use the command line compiler or an IDE instead of the Ant scripts. I actually haven't tried it, though.

Ultimately, the main reason to use the Feathers SDK is to get support for MXML. If you don't need MXML, then it's probably easier to stick with your current workflow.

**Comment by teotigraphix** [comment]
I have and am still making some huge Android/desktop apps with the SDK and it works. I used to think a year ago I would need to build the SDK but it's so solid now, even if you have a bug, Josh would fix it and build the SDK and release it, he did that once for me.

I tried building it and we realized it was going to happen. :)

**Comment by Stray** [comment]
Excellent - that sets my mind at rest then - I don't use mxml, only as3, so I'm all good!

**Comment by teotigraphix** [comment]
@Stray  I know you have been in AS3 for a long time. Curious if you are coming back to it after some years or have been tinkering the last few years and are just now messing with feathers (last couple months).

**Comment by Stray** [comment]
Hi Michael,

I've never left AS3 - my main work for several years was a big Air-based e-learning and training system for a major engineering company. The system needs to interact with their local file system etc and HTML simply doesn't deliver what they need so I never moved away.

What's new is that I'm now doing some work on mobile as well, hence picking up feathers. I've done a little tinkering with native iOS and so on, but my clients are keen to have cross platform apps, so for now Air + Feathers is the ideal solution.

Cheers for the question :)

Stray
