### ISSUE TITLE
VideoPlayer. Width and hight == 0

### ISSUE THREAD

**Issue by CrazyFlasher** [BowlerHatLLC/feathers#1568]
Hi.
When Event.READY is dispatched, width and height of player are still 0
```
player.addEventListener(Event.READY, onReady);
```
Though nativeWidth and nativeHeight are correct values, I need correct bounds of DisplayObject.
Currently I use ugly delay for this.
I there any way / event to listen, when player width and height have correct values?

**Comment by joshtynjala** [comment]
After you pass the VideoPlayer's texture to the ImageLoader, you can call validate() on the VideoPlayer to have it immediately measure itself.
