### ISSUE TITLE
VideoPlayer. Doesn't play on samsung galaxy s3

### ISSUE THREAD

**Issue by CrazyFlasher** [BowlerHatLLC/feathers#1569]
VideoPlayer just shows the first frame of video and doesn't play further.
So user see only 1st frame and after some time video complete dispatched.
I use AIR 25 and `<disableMediaCodec>true</disableMediaCodec>`
Video codec: H.264
Tried different levels: 3 - 5
Profile: Main

**Comment by joshtynjala** [comment]
Sorry, but that's something you'll need to ask Adobe.
