### ISSUE TITLE
ListCollection Constructor setting data

### ISSUE THREAD

**Issue by teotigraphix** [BowlerHatLLC/feathers#1570]
Hi,

I have been refactoring some of my code and I am making a read-only ListCollection.

One thing I noticed, you set the property data in the constructor using the setter instead of _data. Ok, it's obvious you init data descriptors but dispatching events? You can't even listen to them yet.

It would be nice if you could break the data descriptor creation into a new method and set data with it's member field so I can disallow data setting in my subclass, as it stands, I can't because the constructor always calls data.

I know this might sound trivial but since there isn't an interface for ListCollection, I am bound to subclass it for use with Feathers List and such. (all my views)

**Comment by joshtynjala** [comment]
Feathers 3.3 is going to introduce a new [IListCollection](https://github.com/BowlerHatLLC/feathers/blob/master/source/feathers/data/IListCollection.as) interface. 😄

**Comment by teotigraphix** [comment]
Wow, you have been busy, this is what I get for not looking at the commits lately. 

I guess I am right on your wave with refactoring, nice to see that interface in List!
