### ISSUE TITLE
Feathers Button should not reset state to UP if mouse on the button after click

### ISSUE THREAD

**Issue by subdan** [BowlerHatLLC/feathers#1575]
Hi, Josh.

Button should not reset state to ButtonState.UP if mouse pointer is on the button after click.

See video — https://drive.google.com/open?id=0B9zVeCnEAzqeWXB1X1N2STJQODA
I use this colors to show the issue:
`
button.upSkin = new Quad(40,40,0x0000FF);
button.hoverSkin = new Quad(40,40,0x00FF00);
button.downSkin = new Quad(40,40,0xFF0000);`

At 00:05 I clicked on the button.
At 00:07 I released mouse. Button state changed to UP but it should stay on HOVER state.

**Comment by joshtynjala** [comment]
This behavior is required as a workaround for the following Starling issue: Gamua/Starling-Framework#146

**Comment by subdan** [comment]
Ok. I've reminded Daniel about this issue.

**Comment by subdan** [comment]
When do you plan to fix this issue?

**Comment by joshtynjala** [comment]
This issue will be fixed in 3.4. I don't want to risk any unexpected side effects in 3.3.

**Comment by subdan** [comment]
Ok.
