### ISSUE TITLE
Support styleName in ButtonGroup dataProvider

### ISSUE THREAD

**Issue by esidegallery** [BowlerHatLLC/feathers#1578]
Perhaps this contravenes Feathers styling guidelines, but it would be really useful to be able to specify individual Button styles in a ButtonGroup's dataProvider. A specific use case would be a delete confirmation Alert, in which the 'Delete' button would have a style name of Button.ALTERNATE_STYLE_NAME_DANGER_BUTTON.

**Comment by joshtynjala** [comment]
Can you use [customFirstButtonStyleName](https://feathersui.com/api-reference/feathers/controls/ButtonGroup.html#style:customFirstButtonStyleName) or [customLastButtonStyleName](https://feathersui.com/api-reference/feathers/controls/ButtonGroup.html#style:customLastButtonStyleName) for your delete button? Or is it not the first or last button?

**Comment by esidegallery** [comment]
Ah yes, of course, and `alert.footerProperties.customFirstButtonStyleName` for the Alert itself. Thanks Josh.
