### ISSUE TITLE
Incorrect behaviour of SpinnerList with HorizontalSpinnerLayout and repeatItems = false

### ISSUE THREAD

**Issue by subdan** [BowlerHatLLC/feathers#1579]
See video demo here: https://drive.google.com/open?id=0B9zVeCnEAzqeZ0pJWnFjaXhFc0E

Issues:
1. Scroll to the 3-rd item. Put finger on the 3-rd item. Move finger to the left. Release finger. SpinnerList jumps to the first item. Why? It should jump to the 4-th item.
2. Scroll from the 1-st item to the last item with one swipe gesture. The last item doesn't selected. Why? It should be selected.

Code:
```
public class SimpleScreen extends Screen
{
	override protected function initialize():void
	{
		super.initialize();
		
		this.layout = new AnchorLayout();
		
		var layout:HorizontalSpinnerLayout = new HorizontalSpinnerLayout();
		layout.repeatItems = false;
		
		var spinner:SpinnerList = new SpinnerList();
		spinner.verticalScrollPolicy = ScrollPolicy.OFF;
		spinner.horizontalScrollPolicy = ScrollPolicy.ON;
		spinner.backgroundSkin = new Quad(30,30, 0xC6C6C6);
		spinner.itemRendererFactory = function ():IListItemRenderer
		{
			var itemRenderer:DefaultListItemRenderer = new DefaultListItemRenderer();
			itemRenderer.horizontalAlign = HorizontalAlign.CENTER;
			itemRenderer.verticalAlign = VerticalAlign.MIDDLE;
			return itemRenderer;
		};
	
		spinner.verticalScrollPolicy = ScrollPolicy.OFF;
		spinner.layout = layout;
		spinner.layoutData = new AnchorLayoutData(0, 0, NaN, 0);
		addChild(spinner);
		
		spinner.dataProvider = new ListCollection([
			{label: "111111111111"},
			{label: "222222222"},
			{label: "333333"},
			{label: "222222"}
		]);
	}
...
```

**Comment by subdan** [comment]
Can you reproduce this issue?

**Comment by joshtynjala** [comment]
Sorry, I have not yet had a chance to take a look at this one.

**Comment by joshtynjala** [comment]
I am not able to reproduce the issue using the code that you provided.

What kind of mobile device are you simulating? I tried with iPhone Retina and Nexus One, but it's quite possible that another device might make the page size and contentScaleFactor different and create the right conditions for this to happen.

**Comment by subdan** [comment]
iPhone 6s, 4.7 inch.
-screensize 750x1334:750x1334 -XscreenDPI 326 -XversionPlatform IOS
