### ISSUE TITLE
Item Renderer font styles issue

### ISSUE THREAD

**Issue by subdan** [BowlerHatLLC/feathers#1582]
Hello.

I have a List with two types of Item Renderers. One Item Renderer has blue text. Another Item Renderer has red text.

Code:
```
var collection:ListCollection = new ListCollection([{label: "Item 1",value:1}, {label: "Item 2",value:2}]);

var list:List = new List();
list.layoutData = new AnchorLayoutData(0, 0, 0, 0);
list.dataProvider = collection;
addChild(list);

function blueFactory():IListItemRenderer
{
	var itemRenderer:DefaultListItemRenderer = new DefaultListItemRenderer();
	itemRenderer.styleName = "item-renderer-blue";
	return itemRenderer;
}

list.setItemRendererFactoryWithID("blueFactory", blueFactory);

function redFactory():IListItemRenderer
{
	var itemRenderer:DefaultListItemRenderer = new DefaultListItemRenderer();
	itemRenderer.styleName = "item-renderer-red";
	return itemRenderer;
}

list.setItemRendererFactoryWithID("redFactory", redFactory);

list.factoryIDFunction = function (item:Object, index:int):String
{
	if (item.label == "Item 1")
		return "blueFactory";
	else if (item.label == "Item 2")
		return "redFactory";
	else return "";
};
```

Styles:

```
protected function setHeaderBlueListItemRendererStyles(itemRenderer:BaseDefaultItemRenderer):void
{
	setItemRendererStyles(itemRenderer);
	itemRenderer.fontStyles = smallBlueFontStyles;
	
}

protected function setRegularBlueListItemRendererStyles(itemRenderer:BaseDefaultItemRenderer):void
{
	setItemRendererStyles(itemRenderer);
	itemRenderer.fontStyles = smallBlueFontStyles;
}

protected function setRegularRedListItemRendererStyles(itemRenderer:BaseDefaultItemRenderer):void
{
	setItemRendererStyles(itemRenderer);
	itemRenderer.fontStyles = smallRedFontStyles;
}

protected function setHeaderRedListItemRendererStyles(itemRenderer:BaseDefaultItemRenderer):void
{
	setItemRendererStyles(itemRenderer);
	itemRenderer.fontStyles = smallRedFontStyles;
}
```

This is a default function of BaseTopcoatLightMobileTheme class.
setItemRendererStyles(itemRenderer);

I tested this issue with the latest master version of Feathers and 3.2.0.

The 3.2.0 version doesn't have this issue.
![screenshot_2](https://user-images.githubusercontent.com/410293/27278711-76f1cb9c-54e2-11e7-9c6a-90489fc0bb6e.png)

This issue happens on latest master version.
![screenshot_1](https://user-images.githubusercontent.com/410293/27278705-71a06db0-54e2-11e7-9018-dd6529eb5d86.png)

**Comment by joshtynjala** [comment]
I am unable to reproduce this issue. I can see the blue text when I run your code.

Most likely, you are changing the color property of smallBlueFontStyles in another part of your code. Changing the color property of a TextFormat is supposed to affect every component that uses the same TextFormat. However, until very recently, there was a bug where changes to TextFormat properties would not be properly detected. That has been fixed.

I recommend using clone() in your theme to help avoid these conflicts:

```
itemRenderer.fontStyles = smallBlueFontStyles.clone();
```

**Comment by subdan** [comment]
Added .clone(). Now, I see blue text. Thanks.

**Comment by joshtynjala** [comment]
One extra little tip:

```
list.factoryIDFunction = function (item:Object, index:int):String
{
	if (item.label == "Item 1")
		return "blueFactory";
	else if (item.label == "Item 2")
		return "redFactory";
	else return "";
};
```
If you want it to use the default itemRendererFactory, you should return null instead of "".

**Comment by Adrian-S** [comment]
Found a similar problem on item renderer while I was changing the styleName, but managed to reduce it to a simple test code:

```
var myLabel:Label = new Label();
var tf_A:TextFormat = new TextFormat(BaseMetalWorksMobileTheme.FONT_NAME, 10, 0xff0000);
var tf_B:TextFormat = new TextFormat(BaseMetalWorksMobileTheme.FONT_NAME, 10, 0x0000ff);
			
myLabel.fontStyles = tf_A;
myLabel.fontStyles = tf_B;
trace("Color:", tf_A.color.toString(16));
```

You will find color from format B on format A. And .clone will solve it, but it should not happen at all.

**Comment by joshtynjala** [comment]
@Adrian-S I created a new issue for you: #1617
