### ISSUE TITLE
ItemRenderer ignores padding before mouse hover

### ISSUE THREAD

**Issue by subdan** [BowlerHatLLC/feathers#1583]
Hello, Josh.

I have a List that contains two items. First item contains a label with some text. Second item has only an accessory. The accessory is a Button. I want to add padding around button.

How it should looks:
![screenshot_3](https://user-images.githubusercontent.com/410293/27329683-d00257f4-55b6-11e7-817b-e56f85e946aa.png)

How it looks right now:
![screenshot_2](https://user-images.githubusercontent.com/410293/27329688-d3216e84-55b6-11e7-811d-d361c39f19f0.png)

Item Renderer ignores padding value. But when I hover mouse cursor on item padding appears. Why?

This is a IR Factory for Button:
```
function buttonFactory():IListItemRenderer
{
	var itemRenderer:DefaultListItemRenderer = new DefaultListItemRenderer();
	itemRenderer.itemHasLabel = false;
	itemRenderer.horizontalAlign = Align.CENTER;
	itemRenderer.padding = 20;
	return itemRenderer;
}
```

**Comment by joshtynjala** [comment]
Are you using 3.2 or older? Try updating to the latest source code from Github. I recently fixed an issue that sounds like what you describe.

**Comment by subdan** [comment]
I use the latest version from master branch.

**Comment by subdan** [comment]
I noticed that accessoryHeight property inside addAccessoryHeight method equals 0 but after mouse hover it doesn't equals 0.

**Comment by subdan** [comment]
I added `actionButton.validate();` and now it works!

```
var actionButton:Button = new Button();
actionButton.label = "Стереть данные";
actionButton.styleName = Button.ALTERNATE_STYLE_NAME_DANGER_BUTTON;
actionButton.addEventListener(Event.TRIGGERED, actionButton_triggeredHandler);
actionButton.validate();

var lc:ListCollection = new ListCollection(
		[
			{
				accessory: actionButton
			}
		]);
list.dataProvider = lc;
```

**Comment by joshtynjala** [comment]
You should not be required to manually validate an accessory. That's something the item renderer should do automatically.
