### ISSUE TITLE
List returned to validation queue too many times during validation

### ISSUE THREAD

**Issue by denisgl777** [BowlerHatLLC/feathers#1585]
Here is a mistake when using the gallery
Appears sometimes

`Error: feathers.controls::List returned to validation queue too many times during validation. This may be an infinite loop. Try to avoid doing anything that calls invalidate() during validation.
	at feathers.core::FeathersControl/invalidate()
	at feathers.controls.supportClasses::ListDataViewPort/invalidateParent()
	at feathers.controls.supportClasses::ListDataViewPort/layout_changeHandler()
	at starling.events::EventDispatcher/invokeEvent()
	at starling.events::EventDispatcher/dispatchEvent()
	at starling.events::EventDispatcher/dispatchEventWith()
	at feathers.layout::HorizontalLayout/layout()`

**Comment by joshtynjala** [comment]
Is this with the official Gallery example, or your own project?

Is that the entire stack trace(), or is there more before layout()?

Is there any chance that a custom item renderer that you created may be involved?

**Comment by denisgl777** [comment]
I can not reproduce the error, maybe there was a problem with using the index of the sheet item. I thought that the itemrenderer index is the same as the serial number, but is it optional?

**Comment by joshtynjala** [comment]
The index is the position of the item renderer's data in the List's data provider. Basically, another way to derive the index would be to use the data property like this:

    var index:int = this.owner.dataProvider.getItemIndex(this.data);

The index is set by the List and the getter is required to return the same value that is passed to the setter. If you return a different value that what was passed in by the List, things will break.

**Comment by denisgl777** [comment]
Yet the problem is not in index
`if(this._invalidateCount >= 10)
				{
					throw new Error(getQualifiedClassName(this) + " returned to validation queue too many times during validation. This may be an infinite loop. Try to avoid doing anything that calls invalidate() during validation.");
				}`


`feathers.core::FeathersControl/invalidate at E:\Project\MalinaBarApp\src\feathers\core\FeathersControl.as:1973
feathers.controls.supportClasses::ListDataViewPort/layout_changeHandler at E:\Project\MalinaBarApp\src\feathers\controls\supportClasses\ListDataViewPort.as:1567
feathers.controls.supportClasses::ListDataViewPort/layout_changeHandler
starling.events::EventDispatcher/invokeEvent at E:\Project\MalinaBarApp\src\starling\events\EventDispatcher.as:156
starling.events::EventDispatcher/dispatchEvent at E:\Project\MalinaBarApp\src\starling\events\EventDispatcher.as:126
starling.events::EventDispatcher/dispatchEventWith at E:\Project\MalinaBarApp\src\starling\events\EventDispatcher.as:207
feathers.layout::HorizontalLayout/layout at E:\Project\MalinaBarApp\src\feathers\layout\HorizontalLayout.as:1117
feathers.controls.supportClasses::ListDataViewPort/draw at E:\Project\MalinaBarApp\src\feathers\controls\supportClasses\ListDataViewPort.as:775
feathers.core::FeathersControl/validate at E:\Project\MalinaBarApp\src\feathers\core\FeathersControl.as:2020
feathers.core::FeathersControl/validate
feathers.controls::Scroller/refreshViewPortBoundsForLayout at E:\Project\MalinaBarApp\src\feathers\controls\Scroller.as:4992
feathers.controls::Scroller/refreshViewPort at E:\Project\MalinaBarApp\src\feathers\controls\Scroller.as:4480
feathers.controls::Scroller/draw at E:\Project\MalinaBarApp\src\feathers\controls\Scroller.as:4401
feathers.controls::Scroller/draw
feathers.controls::List/draw at E:\Project\MalinaBarApp\src\feathers\controls\List.as:1544
feathers.core::FeathersControl/validate at E:\Project\MalinaBarApp\src\feathers\core\FeathersControl.as:2020
feathers.core::ValidationQueue/advanceTime at E:\Project\MalinaBarApp\src\feathers\core\ValidationQueue.as:173
starling.animation::Juggler/advanceTime at E:\Project\MalinaBarApp\src\starling\animation\Juggler.as:354
starling.core::Starling/advanceTime at E:\Project\MalinaBarApp\src\starling\core\Starling.as:398
starling.core::Starling/nextFrame at E:\Project\MalinaBarApp\src\starling\core\Starling.as:383
starling.core::Starling/onEnterFrame at E:\Project\MalinaBarApp\src\starling\core\Starling.as:602
starling.core::Starling/onEnterFrame
`

**Comment by denisgl777** [comment]
To bring the code of the gallery? It is the same in meaning, I added a listener for a single touch and a couple of elements

**Comment by denisgl777** [comment]
The cause of the problem is not clear. Perhaps a large number of sheet elements

**Comment by denisgl777** [comment]
Also, some gallery elements incorrectly calculate the size
I added the same image and in a random order, about one in five there are such cases
https://ibb.co/ib7uyQ - Normal case
https://ibb.co/ikb9Xk 
I'm investigating

**Comment by denisgl777** [comment]
```
if(this._invalidateCount >= 30)
				{
					throw new Error(getQualifiedClassName(this) + " returned to validation queue too many times during validation. This may be an infinite loop. Try to avoid doing anything that calls invalidate() during validation.");
				}
				this._validationQueue.addControl(this);
```
Increased _invalidateCount
The error has disappeared, but I'm not sure that this is correct

**Comment by joshtynjala** [comment]
I made several attempts to reproduce this issue by interacting with the List with HorizontalLayout in the Gallery example. Please feel free to re-open once you can provide steps that will consistently reproduce the issue.

**Comment by denisgl777** [comment]
Try to choose and move to any index in the photo galleries
this.thumbnailList.selectedIndex = _data.currentPhotoCount;
or
this.fullSizeList.horizontalPageIndex = _data.currentPhotoCount;
The problem in this

**Comment by joshtynjala** [comment]
Sorry, I still can't reproduce! I also tried this:

```
this.thumbnailList.horizontalScrollPosition = this.thumbnailList.maxHorizontalScrollPosition;
```

**Comment by denisgl777** [comment]
The problem just appears and I do not understand the true reasons. I use a library to connect to a social network, from where I get links to images. Of them, and obtained a photo gallery. But sometimes when you download, the above problem appears
I can upload my project and send it to private messages

**Comment by denisgl777** [comment]
if(this._invalidateCount >= 10)
{
throw new Error(getQualifiedClassName(this) + " returned to validation queue too many times during validation. This may be an infinite loop. Try to avoid doing anything that calls invalidate() during validation.");
}
Sometimes when you enter the gallery _invalidateCount = 1
and sometimes All the same error
