### ISSUE TITLE
Recall Callout.show does not change the size of the content

### ISSUE THREAD

**Issue by denisgl777** [BowlerHatLLC/feathers#1588]
Create label
```
voltageLabel = new Label();
voltageLabel.fontStyles = new TextFormat('Arial', 35, 0xC0C0C0);
voltageLabel.backgroundSkin = new Quad(10, 10, 0xff0000);
voltageLabel.filter = new DropShadowFilter();
voltageLabel.paddingLeft = voltageLabel.paddingRight = 8;
```
Create a button to call Callout
```
voltageButton = new Button();
voltageButton.label = 'Voltage';
voltageButton.addEventListener(Event.TRIGGERED, onVoltageBtnClick);
private function onVoltageBtnClick(e:Event):void 
{
	voltageLabelActive = !voltageLabelActive;
	if (voltageLabelActive)
		voltageCallout = Callout.show(voltageLabel, _targetVoltageCallout, voltageCalloutDirection, false, skinnedCalloutFactory);
	else
		voltageCalloutClose();
}
```

Then I update the text
```
protected function updateVoltageCallout():void
{
	if (voltageLabel)
	{
		voltageLabel.text = ' ' + Math.round(this.U * 100) / 100 + ' В.';
		if (voltageCallout)
			voltageCallout.invalidate(FeathersControl.INVALIDATION_FLAG_SIZE);
	}
}
```
[https://ibb.co/jDtzhk](https://ibb.co/jDtzhk)
[https://ibb.co/dCrwTQ](https://ibb.co/dCrwTQ)
Parameters in the application change, the updateVoltageCallout function is called
Size automatically changes and all text is visible
But if I call again 
```voltageCallout = Callout.show(voltageLabel, _targetVoltageCallout, voltageCalloutDirection, false, skinnedCalloutFactory);```
Dimensions do not automatically change
[https://ibb.co/bJe5Nk](https://ibb.co/bJe5Nk)

**Comment by joshtynjala** [comment]
It's likely that the first callout set the width or height of the Label explicitly. The second callout will respect the explicit width or height and not change it. Try this:

```
voltageLabel.width = NaN;
voltageLabel.height = NaN;
voltageCallout = Callout.show(voltageLabel, _targetVoltageCallout, voltageCalloutDirection, false, skinnedCalloutFactory);
```

**Comment by denisgl777** [comment]
Yes, it works! Thank you Josh!!
