### ISSUE TITLE
Component unable to validate

### ISSUE THREAD

**Issue by urthling** [BowlerHatLLC/feathers#1590]
Working in 3.2 - error thrown when using 3.3

Error: A component cannot validate until after it has finished initializing.
	at feathers.core::FeathersControl/validate()[/Users/joshtynjala/Development/feathers/feathers-sdk/frameworks/projects/feathers/feathers/source/feathers/core/FeathersControl.as:2038]

**Comment by joshtynjala** [comment]
You can't call validate() inside initialize() anymore. In 3.2 and earlier, calling validate() in initialize() actually had no effect at all. The component did not actually validate. I added this error to make it perfectly clear that you shouldn't try to do that. I don't want people thinking that something is working when it's not.

**Comment by urthling** [comment]
Understood, ty Josh.
