### ISSUE TITLE
Property closeOnTouchBeganOutside

### ISSUE THREAD

**Issue by denisgl777** [BowlerHatLLC/feathers#1591]
I think it would be great if the closeOnTouchBeganOutside property worked somewhat differently
The point is that I need to make a touch outside the area of the callout, so that the callout was closed
But if I start using a touch on another object, I first have to touch to close the kalaut, and then work with another object.
Is it possible to do so that touching another object will close the callout without additional touch?

**Comment by joshtynjala** [comment]
When you call Callout.show(), set the isModal parameter to false. This will allow touches to reach objects below the Callout without closing there Callout first.
