### ISSUE TITLE
Is it possible to bring back all themes from the previous version?

### ISSUE THREAD

**Issue by born2net** [BowlerHatLLC/feathers#1592]
Is it possible to bring back all themes from the previous version? as current version does not include all the beautiful styles.

Thanks again for a great product!

Sean

**Comment by joshtynjala** [comment]
I'm not sure what you mean. I don't remember removing any themes... Can you provide more details about what seems to be missing?

**Comment by born2net** [comment]
I will re-test again and provide more details.
closing for now,
tx for the quick reply.
