### ISSUE TITLE
Scroller: error in verticalAutoScrollTween_onUpdate()

### ISSUE THREAD

**Issue by kevinfoley** [BowlerHatLLC/feathers#1595]
When scrolling up and down a list with Feathers 3.3 beta, I periodically get a null reference error in Scroller line 7766:

    this._verticalAutoScrollTween.advanceTime(this._verticalAutoScrollTween.totalTime);

The error occurs because `verticalAutoScrollTween_onUpdate()` has been called when `verticalAutoScrollTween` is null.

**Comment by joshtynjala** [comment]
I am not able to reproduce this issue.

I don't see a way for verticalAutoScrollTween_onUpdate() to be called if verticalAutoScrollTween is null because I always call Starling.juggler.remove() before setting it to null (except in the onComplete callback, but it will be removed automatically by the juggler in that situation).

Can you provide some code that will consistently reproduce the issue?

**Comment by kevinfoley** [comment]
@joshtynjala  For me, the easiest way to reproduce this issue is to minimize the app while the pull view is visible, and then restore the app. However, that doesn't seem to work with the ComponentExplorer project.

I've pieced together what happens through traces and following the call stack. In short, each time the verticalAutoScrollTween completes, the `verticalAutoScrollTween_onComplete` function gets called twice (you can verify this with trace statements). Depending on the current state of the Scroller, this can cause two new verticalAutoScrollTweens to be created at the same time, but the Scroller only knows about one of them.

1. The Juggler calls `advanceTime()` on a Tween
2. The Tween invokes the `onUpdate` callback, which calls `verticalAutoScrollTween_onUpdate`
3. `verticalAutoScrollTween_onUpdate()` calls `advanceTime()` on the same Tween (line 7766). **`advanceTime()` is now in the Stack twice for the same Tween**
4. The iteration of `advanceTime()` that was called in Step 3 invokes the `onComplete` callback, which calls `verticalAutoScrollTween_onComplete()`
5.  `verticalAutoScrollTween_onComplete()` calls `finishScrollingVertically()` (line 7779)
6. `finishScrollingVertically()` calls `throwTo()` (line 6641)
7. `throwTo()` creates a new verticalAutoScrollTween (line 6472)
8. The iteration of `advanceTime()` that was called in Step 1 invokes the `onComplete` callback, which calls `verticalAutoScrollTween_onComplete()`
9. **`verticalAutoScrollTween_onComplete()` nulls the reference to the new verticalAutoScrollTween created in step 7, although it still belongs to the Juggler and still has the onUpdate and onComplete callbacks**
10.  `verticalAutoScrollTween_onComplete()` calls `finishScrollingVertically()` (line 7779)
11. `finishScrollingVertically()` calls `throwTo()` (line 6641)
**12. `throwTo()` creates a second new verticalAutoScrollTween (line 6472). Now there are two Tweens on the Juggler to do the same thing, one of which the Scroller no longer has a reference to**
13. Both of the new Tweens will complete at approximately the same time. Whichever one finishes first will cause the reference to the Tween from step 12 to get nulled. If the other one has time to invoke `onUpdate` before it completes, the null reference error will occur

**Comment by joshtynjala** [comment]
Thanks! That's good info.

**Comment by joshtynjala** [comment]
I set the callbacks to null in the onComplete callback. Let me know if that works for you.
