### ISSUE TITLE
[Fault] exception, information=Error: feathers.controls.supportClasses::ListDataViewPort returned to validation queue too many times during validation. This may be an infinite loop. Try to avoid doing anything that calls invalidate() during validation.

### ISSUE THREAD

**Issue by denisgl777** [BowlerHatLLC/feathers#1598]
In the standard gallery, there is no error
But if I take links from the social network
```
var items:Vector.<GalleryItem> = new <GalleryItem>[];
			for (var i:int = 0; i < fullSizePhotoLinks.length; i++) 
			{
				if (fullSizePhotoLinks[i] != null && thumbnailLinks[i] != null)
				{
					var item:GalleryItem = new GalleryItem('',fullSizePhotoLinks[i], thumbnailLinks[i]);
					items.push(item);
				}
				
			}
			var collection:VectorCollection = new VectorCollection(items);
			fullSizeList.dataProvider = collection;
			thumbnailList.dataProvider = collection;
```
I get the above error
To conduct a full investigation, tell me where to start? Why does the counter start to increase?

**Comment by denisgl777** [comment]
```
nativeTexture = context.createRectangleTexture(

starling.textures::Texture$/empty at E:\Project\MalinaBarApp\src\starling\textures\Texture.as:543
feathers.controls::ImageLoader/replaceBitmapDataTexture at E:\Project\MalinaBarApp\src\feathers\controls\ImageLoader.as:2248
feathers.controls::ImageLoader/loader_completeHandler at E:\Project\MalinaBarApp\src\feathers\controls\ImageLoader.as:2596
feathers.controls::ImageLoader/loader_completeHandler
```
Also in the process of reusing the gallery I received such an error
But this is very rare

**Comment by joshtynjala** [comment]
The counter goes up by one if invalidate() is called one or more times from inside draw(). Any time that invalidate() is called, the component will need to validate, which calls draw() again. I seem to recall the error will be thrown when the counter reaches 10. So this error means that draw() has been called at least 10 times during the current frame because it kept invalidating itself again. Sometimes, that cannot be avoided, which is why Feathers waits for it to happen 10 times.

Reaching 10 times usually means that a custom component is doing something wrong (I'm not ruling out a bug in List, but usually, it's a custom item renderer that is the cause).

**Comment by joshtynjala** [comment]
> Also in the process of reusing the gallery I received such an error

You only included the stack trace! What's the error code and description?

**Comment by denisgl777** [comment]
I decided to print _invalidateCount
Sometimes when the gallery is turned on it is equal to 1, and sometimes the counter sharply dials 10+ and gives an error
On the second error I will give more information if I can call her again

**Comment by denisgl777** [comment]
Why did you choose _invalidateCount = 10?
Can I appoint more?
_invalidateCount  = 20..30

**Comment by denisgl777** [comment]
```
starling.textures::Texture$/empty at E:\Project\MalinaBarApp\src\starling\textures\Texture.as:543
feathers.controls::ImageLoader/replaceBitmapDataTexture at E:\Project\MalinaBarApp\src\feathers\controls\ImageLoader.as:2248
feathers.controls::ImageLoader/loader_completeHandler at E:\Project\MalinaBarApp\src\feathers\controls\ImageLoader.as:2596
feathers.controls::ImageLoader/loader_completeHandler
```
Reproduced the second error
refers to 555 line starling.textures.Texture in public static function empty
 nativeTexture = context.createRectangleTexture(
                        actualWidth, actualHeight, format, optimizeForRenderToTexture);

**Comment by joshtynjala** [comment]
> Why did you choose _invalidateCount = 10?

I seriously considered choosing a value **less than 10**, actually. When a component returns itself to the validation queue 10 times in the same frame, there is no denying that it has a major bug that needs to be fixed. Most components shouldn't need to do that more than once. Ideally, I would have chosen 2-3 instead of 10, but I decided to make it a little less strict than I'd prefer, so I bumped it up to 10.

> Can I appoint more?
> _invalidateCount = 20..30

It's open source, so you can do whatever you want. However, something is buggy, and that will only hide the bug.

**Comment by joshtynjala** [comment]
> Reproduced the second error

Okay, great! So what's the error code and message?

**Comment by denisgl777** [comment]
[Fault] exception, information=ArgumentError: Error #3766: RectangleTexture too big (max is the larger of 2048x2048 or the size of the backbuffer).

**Comment by joshtynjala** [comment]
> [Fault] exception, information=ArgumentError: Error #3766: RectangleTexture too big (max is the larger of 2048x2048 or the size of the backbuffer).

Yeah, Stage 3D does not allow textures larger than a certain size. I guess to keep an error from being thrown, ImageLoader can catch this error, dispatch Event.IO_ERROR, and display its errorTexture. That would ensure that your app would still run at least. However, you'll still need to deal with the fact that your image file is too large for Stage 3D to use.

**Comment by denisgl777** [comment]
In my gallery, I saved the same code as in the example
In fact, only the links change
Found such an error

[Fault] exception, information=Error: feathers.controls::List stuck in an infinite loop during measurement and validation. This may be an issue with the layout or children, such as custom item renderers.

**Comment by joshtynjala** [comment]
Until I can reproduce this issue on my computer, there isn't much more that I can do to help. If the only difference is the image URLs, can you share with me a list of image URLs to load?

**Comment by denisgl777** [comment]
I get links to images through the library
https://github.com/marpies/vk-ane  - Russian social network
Vector of links I pass to the screen
The links are exactly working, I displayed them on the screen
I can even upload a project to the test, but it's done in flashdevelop

**Comment by joshtynjala** [comment]
It looks like I need to sign up for VK and register an app. Is there any way that you could share a list of links with me in a private message on the forum?

**Comment by joshtynjala** [comment]
Even using those images, I could not reproduce the issue. I guess you'll need to send me that project.

**Comment by denisgl777** [comment]
Sent to the forum in private messages

**Comment by joshtynjala** [comment]
What do I need to do to reproduce in your app? I assume that I need to go to the screen with the monkeys, but I'm not seeing any errors when I scroll through things on that screen.

**Comment by denisgl777** [comment]
Because you are testing in the mode of Windows. VK library works only android iOS
I understand this is a lot of things, but to understand the problem - will have to run the test on the mobile phone. And instead of monkeys, real photos will appear.
Nevertheless, I think that the problem is not because of the VC library. It is very difficult to calculate this error

**Comment by joshtynjala** [comment]
I'm on macOS, so I don't have FlashDevelop. I can't seem to figure out how to set up the project's ANEs in another IDE. It just crashes the debugger when I try to launch over USB on Android.

Sorry, but I'm going to need a significantly simpler project if I'm going to investigate further. If you can get it to reproduce in the AIR simulator on desktop, that would be even better.

**Comment by denisgl777** [comment]
i'll try something
