### ISSUE TITLE
TextInput clearFocus() bug

### ISSUE THREAD

**Issue by subdan** [BowlerHatLLC/feathers#1600]
If I call `input.clearFocus();` after `input.visible = false;` the TextInput will appears but it shouldnot

```
input = new TextInput();
input.maxChars = _correctText.length;
input.backgroundSkin = bg;
input.textEditorFactory = function ():ITextEditor
{
	var textEditor:StageTextTextEditor = new StageTextTextEditor();
	textEditor.updateSnapshotOnScaleChange = true;
	textEditor.styleProvider = null;
	textEditor.returnKeyLabel = ReturnKeyLabel.NEXT;
	textEditor.fontSize = 20*1.5;
	textEditor.color = 0x93278F;
	return textEditor;
};
input.width = width;
addChild(input);

setTimeout(function ():void
{
	input.visible = false;
}, 3000);

setTimeout(function ():void
{
	input.clearFocus();
}, 4000);
```

**Comment by joshtynjala** [comment]
I'm not able to reproduce the issue with the code that you provided. The TextInput is hidden when visible is set to false, and clearFocus() wouldn't do anything anyway, since it never had focus in the first place.

**Comment by joshtynjala** [comment]
If I give the TextInput some text, and I click to give it focus before visible is set to false, I can reproduce.
