### ISSUE TITLE
Callout documentation is outdated

### ISSUE THREAD

**Issue by kevinfoley** [BowlerHatLLC/feathers#1603]
The [documentation for Callout ](https://feathersui.com/help/callout.html)refers to the deprecated `direction` argument rather than the new `supportedPositions` argument.

**Comment by joshtynjala** [comment]
Thanks!

**Comment by kevinfoley** [comment]
Fastest response in the history of GitHub!

**Comment by joshtynjala** [comment]
Haha! I happened to check my email just at the right time, I guess.
