### ISSUE TITLE
BitmapFontTextEditor.restrict doesn't handle some escaped characters

### ISSUE THREAD

**Issue by tconkling** [BowlerHatLLC/feathers#1605]
I use the following restrict string in a number of TextInputs in my code; it's intended to allow any ASCII character:

```
public static const ASCII_CHARS :String =
    "0123456789" +
    "ABCDEFGHIJKLMNOPQRSTUVWXYZ" +
    "abcdefghijklmnopqrstuvwxyz" +
    " !\"#$%&'()*+,./:;<=>?@[]_`{}|~\\-\\^\\\\";
```

(I'm deliberately avoiding using the hyphen as a range operator so that I can index directly into the `ASCII_CHARS` string in other places in my code.)

Per [Adobe's docs](http://help.adobe.com/en_US/FlashPlatform/reference/actionscript/3/flash/text/TextField.html#restrict), I'm using `\\-` as an escaped hyphen, `\\^` as an escaped caret, and `\\\\` as an escaped backslash, to explicitly allow these characters in my TextFields, and prevent the hyphen and caret from being interpreted as range and exclude operators.

This works fine with `StageTextTextEditor` -- all the above characters are accepted and printed in my TextInput. But `BitmapFontTextEditor` fails to accept "^", "-", and "\". (`TextInputRestrict.isCharacterAllowed` is returning false for these characters, given the above restrict string.)

**Comment by joshtynjala** [comment]
Thanks! I can reproduce this issue.

**Comment by tconkling** [comment]
Thanks for the fix!
