### ISSUE TITLE
scrollToPageIndex() does not dispatch an event

### ISSUE THREAD

**Issue by NeoMarine** [BowlerHatLLC/feathers#1607]
In my case, I need a FeathersEventType.SCROLL_START event to be dispatched by scrollToPageIndex()

FeathersEventType.SCROLL_COMPLETE can be used for when a scroller has completed it's animation (e.g. after scrollToPageIndex() has completed). However, there is no event for when SCROLL_START occurs (only BEGIN_INTERACTION, but would not be able to tell if the user scrolled by way on a button, instead of the scroller itself).

**Comment by joshtynjala** [comment]
I just gave it a try, and I am seeing FeathersEventType.SCROLL_START being dispatched correctly when I call scrollToPageIndex(). Can you put together a simple example where it doesn't get dispatched?

**Comment by NeoMarine** [comment]
Hi josh,

This was a mistake on my part. Sorry for the confusion! I will close the issue now.
