### ISSUE TITLE
ImageLoader : Key "XXX" already exists in the cache

### ISSUE THREAD

**Issue by glowbl-backstage** [BowlerHatLLC/feathers#1608]
Hello,
This problem can be reproduce only after context restoration, the ImageLoader seems to correctly release texture in the cache.

But the key now exist in the  "_unretainedTextures" dictionnary from TextureCache, when the "findSourceInCache()" method is called "_isRestoringTexture" is true and _textureCache.hasTexture() isnt called.

After that, _textureCache.addTexture() is called because findSourceInCache() return false and TextureCache throw the argument error : "Key already exists in the cache"

**Comment by joshtynjala** [comment]
Thank you! I can reproduce this issue.
