### ISSUE TITLE
ScreenDensityScaleFactorManager lag

### ISSUE THREAD

**Issue by devlfm** [BowlerHatLLC/feathers#1609]
Hi @joshtynjala ,

On a WindowedApplication if you resize the window, there is a huge lag updating the stage3d content.. Is this a stage3d issue?

Thank you

**Comment by joshtynjala** [comment]
Can be more detailed about what you mean by "lag". Maybe a video would be more clear. Thanks!

**Comment by joshtynjala** [comment]
I'm also not clear why you mentioned ScreenDensityScaleFactorManager. Does it not lag when you don't use this class?

**Comment by devlfm** [comment]
I mention it because is what I'm using for handling the resize of the stage according to examples. 

I'll make a gif with a flex component over a feathers component, both with horizontalCenter and verticalCenter, the feathers component have a big delay, but is not a deal breaker.. I was just testing things 
 :)

**Comment by joshtynjala** [comment]
If I remember correctly, Stage 3D may lose context when the back buffer is resized, so that's probably what's happening...

**Comment by rui-cruz** [comment]
here's the gif: https://pasteboard.co/images/GD4Kb7q.gif/download

**Comment by joshtynjala** [comment]
That may very well be the delay caused by recreating the back buffer at a different size. I don't think that's a cheap operation.

**Comment by rui-cruz** [comment]
Ok, no problem, its not a deal breaker.. 

thank you and keep your good work, as it is more important now than ever! I'm porting 2 huge app's do desktop.. and creating a new one from scratch with starling+feathers
