### ISSUE TITLE
Bug: Incorrect ToggleButton state after touch

### ISSUE THREAD

**Issue by subdan** [BowlerHatLLC/feathers#1613]
Hello. When I tap on a ToggleButton the state of the button changed to "hover_and_selected" but it should change to "up_and_selected".

```
var toggleButton:ToggleButton = new ToggleButton();
toggleButton.addEventListener(FeathersEventType.STATE_CHANGE, function (event:Event):void {
	trace(toggleButton.currentState);
});
addChild(toggleButton);
```
It happens only on iOS device.

Also, when I press on the ToggleButton I see:
[trace] hover
[trace] down

Why button state changed to "hover" before "down".

**Comment by joshtynjala** [comment]
It appears that Starling is dispatching TouchPhase.HOVER before TouchPhase.DOWN, so the Feathers button enters ButtonState.HOVER before ButtonState.DOWN.

On TouchPhase.ENDED, a button will return to the hover state if there was a TouchPhase.HOVER event before TouchPhase.BEGAN and the mouse/touch is still over the button.

The button is behaving correctly based on the events that it receives. If you prefer not to see a hoverSkin, you should not set one.

**Comment by subdan** [comment]
I think it's a bug.

Look at this code:

```
var toggleButton:ToggleButton = new ToggleButton();
toggleButton.x = 100;
toggleButton.y = 100;
toggleButton.width = 100;
toggleButton.height = 100;
addChild(toggleButton);

var imageSkin:ImageSkin = new ImageSkin(Texture.fromColor(100,100,0xFFFFFF));
imageSkin.setColorForState(ButtonState.UP,0xFFFFFF);
imageSkin.setColorForState(ButtonState.UP_AND_SELECTED,0x43AD34); // light green
imageSkin.setColorForState(ButtonState.DOWN,0xCCCCCC);
imageSkin.setColorForState(ButtonState.DOWN_AND_SELECTED,0x2D7423); // dark green

toggleButton.defaultSkin = imageSkin;
```

At the start button is white.
When I put my finger on a button the button is gray. It's ok.
When I release my finger the button is gray but is should be light green. (UP_AND_SELECTED)
Next, I put my finger on the button and it is dark green. It's ok.
When I release my finger the button is still dark green but it should be white.

**Comment by joshtynjala** [comment]
I recommend using use defaultColor and selectedColor instead of calling setColorForState() with ButtonState.UP and ButtonState.UP_AND_SELECTED. This ensures that any states that are unexpected (like hover... or any new states that might be added in the future) will be skinned the same as the up state.

> Feathers 3.1 with Starling 2.1 doesn't have this issue.

Daniel recently fixed an issue in Starling related to TouchPhase.ENDED and TouchPhase.HOVER. You didn't realize it, but were relying on buggy behavior in these versions.

**Comment by subdan** [comment]
Ok, Josh. I'll try it tomorrow.
