### ISSUE TITLE
maxHorizontalScrollPosition after validate is 0

### ISSUE THREAD

**Issue by denisgl777** [BowlerHatLLC/feathers#1615]
```
scroolContainer = new ScrollContainer();
scroolContainer.layoutData = new AnchorLayoutData(0, 0, 0, 0);
scroolContainer.layout = new HorizontalLayout();
scroolContainer.snapToPages = true;
scroolContainer.pageWidth = stage.stageWidth;
scroolContainer.verticalScrollPolicy = ScrollPolicy.OFF;

scroolContainer.addChild(someContainer);
scroolContainer.snapScrollPositionsToPixels = true;
scroolContainer.validate();

trace(scroolContainer.maxHorizontalScrollPosition); 
```
Output 0

**Comment by joshtynjala** [comment]
The ScrollContainer is using AnchorLayoutData, which means that its parent needs to set the width of the container. When you validate the ScrollContainer in your example code, the parent hasn't validated yet, so the ScrollContainer doesn't have an explicit width. It will auto-size to fit its children instead.

You need to validate the parent, in this case.
