### ISSUE TITLE
SpinnerList: optimize transition from end to beginning (or reverse) when data provider is very large

### ISSUE THREAD

**Issue by Adrian-S** [BowlerHatLLC/feathers#1616]
I have an infinite spinner list (with 10 items), and I've notice the horizontalPageIndex goes to positive and negative numbers. This index was very helpful to me to reuse the same items and just calculate what content I should have. So far I've done this with a simple code that looks like this:

```
var newIndex:int = spinner.horizontalPageIndex;
var pageCount:int = listDataProvider.length;
if(oldIndex != newIndex) {
	listDataProvider.getItemAt(absMod(newIndex+4, pageCount)).label = int(newIndex + 4).toString();
	listDataProvider.getItemAt(absMod(newIndex+3, pageCount)).label = int(newIndex + 3).toString();
	listDataProvider.getItemAt(absMod(newIndex+2, pageCount)).label = int(newIndex + 2).toString();
	listDataProvider.getItemAt(absMod(newIndex+1, pageCount)).label = int(newIndex + 1).toString();
	listDataProvider.getItemAt(absMod(newIndex, pageCount)).label = newIndex.toString();
	listDataProvider.getItemAt(absMod(newIndex-1, pageCount)).label = int(newIndex - 1).toString();
	listDataProvider.getItemAt(absMod(newIndex-2, pageCount)).label = int(newIndex - 2).toString();
	listDataProvider.getItemAt(absMod(newIndex-3, pageCount)).label = int(newIndex - 3).toString();
	listDataProvider.getItemAt(absMod(newIndex-4, pageCount)).label = int(newIndex - 4).toString();
}
```

This requires me to have at least 9 items, while I only show 3 items tops (4 while in transition). As my program evolved, all need to update at a certain point and right now this is causing a lot of time hanging. 

Having an absolute index on item renderer, would help me to avoid transmitting data trough label data. This simple index could cut the number of items I need by a factor of 3, and increase the potential performance almost 300%.

If you have any other options, i'm open to them. I'm also a bit puzzled by the fact that all items (+2) were created, and not only the visible needed ones, as I know it happens on List.

Thank you.

**Comment by joshtynjala** [comment]
It sounds like you're trying to do something similar to DateTimeSpinner. It would be bad for performance to populate a ListCollection with the number of values that need to be displayed in some of the internal SpinnerLists inside DateTimeSpinner. However, that's where the IListCollection interface comes in. You can basically generate "items" on the fly.

I created an IntegerRangeCollection for DateTimeSpinner, and I think it might be helpful to you here. It might not be exactly what you need, but maybe you can tweak it... or create something similar using the same concept.

``` actionscript
class IntegerRangeCollection extends EventDispatcher implements IListCollection
{
	public function IntegerRangeCollection(minimum:int = 0, maximum:int = 1, step:int = 1)
	{
		this._minimum = minimum;
		this._maximum = maximum;
		this._step = step;
	}

	protected var _minimum:int;

	public function get minimum():int
	{
		return this._minimum;
	}

	public function set minimum(value:int):void
	{
		if(this._minimum === value)
		{
			return;
		}
		this._minimum = value;
		this.dispatchEventWith(CollectionEventType.RESET);
		this.dispatchEventWith(Event.CHANGE);
	}

	protected var _maximum:int;

	public function get maximum():int
	{
		return this._maximum;
	}

	public function set maximum(value:int):void
	{
		if(this._maximum === value)
		{
			return;
		}
		this._maximum = value;
		this.dispatchEventWith(CollectionEventType.RESET);
		this.dispatchEventWith(Event.CHANGE);
	}

	protected var _step:int;

	public function get step():int
	{
		return this._step;
	}

	public function set step(value:int):void
	{
		if(this._step === value)
		{
			return;
		}
		this._step = value;
		this.dispatchEventWith(CollectionEventType.RESET);
		this.dispatchEventWith(Event.CHANGE);
	}

	public function get filterFunction():Function
	{
		return null;
	}

	public function set filterFunction(value:Function):void
	{
		throw new Error("Not implemented");
	}

	public function get data():Object
	{
		return null;
	}

	public function set data(value:Object):void
	{
		throw new Error("Not implemented");
	}

	public function get length():int
	{
		return 1 + int((this._maximum - this._minimum) / this._step);
	}

	public function getItemAt(index:int):Object
	{
		var maximum:int = this._maximum;
		var result:int = this._minimum + index * this._step;
		if(result > maximum)
		{
			result = maximum;
		}
		return result;
	}

	public function contains(item:Object):Boolean
	{
		if(!(item is int))
		{
			return false;
		}
		var value:int = item as int;
		return Math.ceil((value - this._minimum) / this._step) !== -1;
	}

	public function getItemIndex(item:Object):int
	{
		if(!(item is int))
		{
			return -1;
		}
		var value:int = item as int;
		return Math.ceil((value - this._minimum) / this._step);
	}

	public function refreshFilter():void
	{
		throw new Error("Not implemented");
	}

	public function setItemAt(item:Object, index:int):void
	{
		throw new Error("Not implemented");
	}

	public function addItem(item:Object):void
	{
		throw new Error("Not implemented");
	}

	public function addItemAt(item:Object, index:int):void
	{
		throw new Error("Not implemented");
	}

	public function push(item:Object):void
	{
		throw new Error("Not implemented");
	}

	public function shift():Object
	{
		throw new Error("Not implemented");
	}

	public function removeItem(item:Object):void
	{
		throw new Error("Not implemented");
	}

	public function removeItemAt(index:int):Object
	{
		throw new Error("Not implemented");
	}

	public function unshift(item:Object):void
	{
		throw new Error("Not implemented");
	}

	public function removeAll():void
	{
		throw new Error("Not implemented");
	}

	public function pop():Object
	{
		throw new Error("Not implemented");
	}

	public function addAll(collection:IListCollection):void
	{
		throw new Error("Not implemented");
	}

	public function addAllAt(collection:IListCollection, index:int):void
	{
		throw new Error("Not implemented");
	}

	public function reset(collection:IListCollection):void
	{
		throw new Error("Not implemented");
	}

	public function updateItemAt(index:int):void
	{
		this.dispatchEventWith(CollectionEventType.UPDATE_ITEM, false, index);
	}

	public function updateAll():void
	{
		this.dispatchEventWith(CollectionEventType.UPDATE_ALL);
	}

	public function dispose(callback:Function):void
	{
		throw new Error("Not implemented");
	}
}
```

**Comment by Adrian-S** [comment]
Ok, I've tested this out and it works for small numbers.

```
var intDataProvider:IntegerRangeCollection = new IntegerRangeCollection(0, 999999);
spinner.dataProvider = intDataProvider;
```

This gives an extremely low performance when sliding around 999999 to 1, no idea why. Very ugly with big numbers.
If I work with negative numbers, if I use `IntegerRangeCollection(-5000, 5000)`, horizontalPageIndex needs to be offset by 5000, and that didn't integrate well with my code.

And the worst, that I was trying to avoid, I still have 11 item renderers created. So far 11 seams to be the magical number, I have managed to get it down to 7 item renderers by using list of 4 items + typicalItem. Using a list of 5 items + typicalItem generates 10 item renderers.

I'm not exactly sure how the number of item renderers is decided, but it seams that 12 is the max item renderes I can get to any list size.

If I can't get the number of renderers down, the absolute index would not help by much.

Thanks for the help, if you have any other ideas please let me know and I will test.

**Comment by joshtynjala** [comment]
I'm curious why it matters how many item renderers are created. That should just be an implementation detail of the SpinnerList and its layout with no particular impact on anything external to the list.

**Comment by Adrian-S** [comment]
Well my item renderer contains two types of vertical spinner list, and each type holds a bunch of other element, lets say about 50 elements each with a label. When I need to swipe the type of vertical spinner, I need to generate the elements again.

I will probably end up in doing some sort of lazy load. No idea how, but I'll find something. I already have a function that will generate a subtexture of the ui (texture is generated on the fly on first load). This can replace 80-90% of the ui elements I need to generate for a blank vertical list.

**Comment by joshtynjala** [comment]
> 50 elements each

Whoa. That's insane!

> When I need to switch the type of vertical spinner, I need to generate the elements again.

One of the best ways to optimize a list's item renderers is to make sure that they can reuse as many of their children as possible when they start rendering a new item. I'd recommend trying to do that, if you can.

It's worth mentioning that a list can use multiple types of item renderers, so if you can't make a single type of item renderer that can be reused, you might be able to do it with a new different types.

**Comment by Adrian-S** [comment]
Each vertical list is a day out of a clendar and I need to show hours at intervals... worst case is 5 minutes. 24 * 12 labels. Also items from each day can be dragged around from one list to another. For best controll I decided to use a simple scroller. The horizontal spinner list is just changeing the visible 1 to 3 days.

And the code... let say it works but I often find myself with no idea of what I wrote in it.

**Comment by Adrian-S** [comment]
I just found out, the first `for` in `layout()` in `HorizontalSpinnerLayout` class, that calculates `positionX`, **creates the slowdown** when using `IntegerRangeCollection(0, 999999);`

**Comment by joshtynjala** [comment]
I can see how that might happen. HorizontalSpinnerLayout implements the ITrimmedVirtualLayout interface as an optimization, but it can't be optimized when rolling over from 999999 to 0. ITrimmedVirtualLayout usually works well because it allows the layout skip items at the beginning and the end so that loops can be shorter. However, that doesn't work when items are repeated and you roll over from the end back to the beginning. In that case, nothing can be "trimmed" because items from both the beginning and the end are required. It ends up doing a full loop from 0 to 999999 instead of over a small subset of that range.

**Comment by Adrian-S** [comment]
Having the total number of items could help in this case. From what I gathered you have DisplayObjects in sequence, so this means you also have a huge gap, that you can calculate and skip.

**Comment by joshtynjala** [comment]
Yes, it should basically be a matter of skipping the middle items in the loop instead of the beginning and end items. I will need to think about the best approach for this.

**Comment by joshtynjala** [comment]
I have determined how to improve performance when near the point when the items repeat in a SpinnerList, and I'll commit some changes when I start working on Feathers 3.5 in the next couple of weeks.
