### ISSUE TITLE
Button doesn't reset state to UP after tap.

### ISSUE THREAD

**Issue by subdan** [BowlerHatLLC/feathers#1618]
Hello. I have a button that doesn't have skin. It has only a label. After I tap on a button the button state remains ButtonState.DOWN. It should reset state to ButtonState.UP.

```
var upFont:TextFormat = this.lightFontStyles.clone();
upFont.color = 0xFFFFFF;

var downFont:TextFormat = this.lightFontStyles.clone();
downFont.color = 0x777777;

var disabledFont:TextFormat = this.lightFontStyles.clone();
disabledFont.color = 0xCCCCCC;

button.setFontStylesForState(ButtonState.UP, upFont);
button.setFontStylesForState(ButtonState.DOWN, downFont);
button.setFontStylesForState(ButtonState.DISABLED, disabledFont);
```

**Comment by subdan** [comment]
If I set defaultSkin, downSkin and disabledSkin after tap I will see "defaultSkin" and "downFont" but I should see "defaultSkin" and "upFont".

**Comment by joshtynjala** [comment]
It may be in the focused state. Try setting fontStyles instead of button.setFontStylesForState(ButtonState.UP, upFont). fontStyles is similar to defaultSkin.

**Comment by subdan** [comment]
A Button Class has only `fontStyles `and `disabledFontStyles `properties. I need `downFontStyles `property.

**Comment by subdan** [comment]
Setted:
```
button.fontStyles = upFont;
button.disabledFontStyles = disabledFont;
button.setFontStylesForState(ButtonState.DOWN, downFont);
```
Now it works. Thanks!
