### ISSUE TITLE
TextInput | setFocus() followed by selectRange(x, -1) no effect

### ISSUE THREAD

**Issue by urthling** [BowlerHatLLC/feathers#1619]
iOS - Feathers 3.3.0

This works as expected - the KB raises and the cursor is set to the end of unhighlighted text:
ti.text = 'something';
ti.setFocus()
ti.selectRange(0, -1);

HOWEVER - if the following is called after a delay or arbitrarily like from a button click:

ti.setFocus();
ti.selectRange(0, -1);

Any values for x or y set in selectRange(x, y) appear to be ignored.  Following a setFocus() the entire string is always selected.

Work around requires setting and resetting the text:

existing  = ti.text;
ti.text = '';
ti.text = existing;
ti.setFocus();
ti.selectRange(0, -1);

**Comment by joshtynjala** [comment]
selectRange() with StageText is a little quirky on iOS. Adobe's documentation says this:

> On iOS, for non-multiline StageText objects, this function is not supported and always returns -1. If you call this method selecting the complete text string, the selection is visible. However, if you call this method selecting a subset of the text string, the selection is not visible.

I've noticed other strange behaviors too, and I wouldn't be surprised if there's no good way to fix this.

**Comment by urthling** [comment]
Gotcha - providing we have a workaround - no big deal.

Kudos on Feathers and the latest release btw - you've opened the door for development of any type of APP - absolutely spot on.
