### ISSUE TITLE
TextInput doesn't dissapear when “visible” property equals “false” after FOCUS_OUT event

### ISSUE THREAD

**Issue by subdan** [BowlerHatLLC/feathers#1620]
Hello.

I want to hide TextInput when a user taps outside TextInput.

```
input.addEventListener(FeathersEventType.FOCUS_OUT, onFocusOut);

function onFocusOut(event:Event):void
{
	input.visible = false;
}
```

It doesn't work. The TextInput doesn't dissapear.

**Comment by joshtynjala** [comment]
I can reproduce. I can see that the background skin disappears, but the StageText is still visible.

**Comment by joshtynjala** [comment]
As a workaround, you can set visible to false after a short delay using Starling.juggler.delayCall():

	Starling.juggler.delayCall(function():void
	{
		input.visible = false;
	}, 0.1);

**Comment by subdan** [comment]
Already use this workaround but sometimes it fails.
