### ISSUE TITLE
TouchToState - Touch access

### ISSUE THREAD

**Issue by teotigraphix** [BowlerHatLLC/feathers#1622]
Hey,

This is such an awesome class and I can get rid of so much boiler plate code but... For some operations I need the actual Touch that changed the state.

I know I could subclass but it seems that adding the actual touch to the callback arguments would seem acceptable to me.

Example, I was using drag and drop, manager needs the touch. I was using this class for the DOWN state to start the drag.

Maybe I am missing something easy to get this?

**Comment by joshtynjala** [comment]
I think you should listen for the regular TouchEvent.TOUCH and get the Touch object for TouchPhase.BEGAN that way. TouchToState is designed to do one thing well, and exposing the touch is leaking abstraction, in my opinion.

**Comment by teotigraphix** [comment]
Fair enough, thinking about it in retrospect I agree with the abstraction point.

Anyway thanks for the class because it does get rid of a lot of code for me.
