### ISSUE TITLE
[Starling] Context restored when switch video player to full screen

### ISSUE THREAD

**Issue by denisgl777** [BowlerHatLLC/feathers#1624]
Context restored when switch video player to full screen and back.
I use the command player.toggleFullScreen();
Video format mp4
latest versions Starling and Fearhers
adobe air 25
iOS

**Comment by joshtynjala** [comment]
That's just how AIR works! 😄

**Comment by denisgl777** [comment]
Probably about it or this have informed?
is this an incorrigible problem?
