### ISSUE TITLE
DeviceCapabilities.isTablet() suggestion

### ISSUE THREAD

**Issue by kevinfoley** [BowlerHatLLC/feathers#1629]
Every time we call `isTablet()`, it ends up looking like this:

    if (DeviceCapabilities.isTablet(Starling.current.nativeStage)) {

Is it even possible for an AIR application to have more than one native stage?

It would be great if the default value of the `stage` argument was null, and Feathers automatically used the current stage in this case:

    public static function isTablet(stage:Stage = null):Boolean
    {
        if (stage == null) stage = Starling.current.nativeStage;

        var screenWidth:Number = screenPixelWidth;
        if(screenWidth !== screenWidth) //isNaN
        {
            screenWidth = stage.fullScreenWidth;
        }
        var screenHeight:Number = screenPixelHeight;
        if(screenHeight !== screenHeight) //isNaN
        {
            screenHeight = stage.fullScreenHeight;
        }
        if(screenWidth < screenHeight)
        {
            screenWidth = screenHeight;
        }
        return (screenWidth / dpi) >= tabletScreenMinimumInches;
    }

**Comment by joshtynjala** [comment]
Good idea!
