### ISSUE TITLE
Scroller : pulltorefresh problems

### ISSUE THREAD

**Issue by glowbl-backstage** [BowlerHatLLC/feathers#1630]
Hello,
I have tested pulltorefresh feature, it seems only works when list height > list viewport height and if verticalscrollposition > 0 when scroll started.

I think it could be better if we start pull just on scroll down and if verticalscrollposition=0

Thanks

**Comment by joshtynjala** [comment]
Unfortunately, I cannot reproduce either of these issues! Pull to refresh seems to work correctly for me, even when the list doesn't have enough content to require scrolling, and it works just fine when verticalScrollPosition === 0. Can you provide some code that demonstrates the issue? Thanks!

**Comment by glowbl-backstage** [comment]
I have found the problem, the Scroller class must have **hasElasticEdges** property set to true for pullviews works correctly.
If not, update event will be not dispatched.

Sorry for the lack of precision.

**Comment by glowbl-backstage** [comment]
A way to do this, i've added a condition :
` || (this._topPullView !== null && this._verticalScrollPosition >= this._minVerticalScrollPosition)`
I'm not sure of consequences but it works.

checkForDrag method
```
			if(!this._isDraggingVertically &&
				(
					this._verticalScrollPolicy == ScrollPolicy.ON ||
					(this._verticalScrollPolicy == ScrollPolicy.AUTO && this._minVerticalScrollPosition != this._maxVerticalScrollPosition) ||
					(this._topPullView !== null && (this._currentTouchY > this._startTouchY || this._verticalScrollPosition < this._minVerticalScrollPosition)) ||
					(this._bottomPullView !== null && (this._currentTouchY < this._startTouchY || this._verticalScrollPosition > this._minVerticalScrollPosition))
				) &&
				(
					((verticalInchesMoved <= -this._minimumDragDistance) && (this._hasElasticEdges || this._verticalScrollPosition < this._maxVerticalScrollPosition) || (this._bottomPullView !== null && this._verticalScrollPosition <= this._maxVerticalScrollPosition)) ||
					((verticalInchesMoved >= this._minimumDragDistance) && (this._hasElasticEdges || this._verticalScrollPosition > this._minVerticalScrollPosition || (this._topPullView !== null && this._verticalScrollPosition >= this._minVerticalScrollPosition)))
				))
			{
				if(this.verticalScrollBar)
				{
					this.revealVerticalScrollBar();
				}
				this._startTouchY = this._currentTouchY;
				this._startVerticalScrollPosition = this._verticalScrollPosition;
				this._isDraggingVertically = true;
				if(!this._isDraggingHorizontally)
				{
					exclusiveTouch = ExclusiveTouch.forStage(this.stage);
					exclusiveTouch.removeEventListener(Event.CHANGE, exclusiveTouch_changeHandler);
					exclusiveTouch.claimTouch(this._touchPointID, this);
					this.dispatchEventWith(FeathersEventType.BEGIN_INTERACTION);
					this.startScroll();
				}
			}
```

**Comment by joshtynjala** [comment]
Yes, I can see that it has somehow broken when hasElasticEdges is false. Thanks!
