### ISSUE TITLE
Add support for MSDF fonts for BitmapFontTextRenderer

### ISSUE THREAD

**Issue by subdan** [BowlerHatLLC/feathers#1633]
Starling [now supports](https://github.com/Gamua/Starling-Framework/issues/994) MSDF fonts.

```
var tf:TextField = new TextField(300,200,"Hello");
tf.format = new TextFormat("Bold", 12, 0x000000,Align.LEFT);
tf.style = new DistanceFieldStyle();
(tf.style as DistanceFieldStyle).multiChannel = true;
addChild(tf);
```

Can you please add support of MSDF fonts for BitmapFontTextRenderer?

**Comment by subdan** [comment]
I tried to set style property for BitmapFontTextRenderer but the text becomes blurry and the bound size is incorrect.

![screen shot 2017-09-09 at 13 40 20](https://user-images.githubusercontent.com/410293/30239405-94a5340e-9564-11e7-89f2-4f68040f0417.png)
![screen shot 2017-09-09 at 13 40 17](https://user-images.githubusercontent.com/410293/30239407-94cc18da-9564-11e7-828c-fa961ef0db04.png)

Top — Starling TextField. Bottom — Feathers Label.
![screen shot 2017-09-09 at 13 40 28](https://user-images.githubusercontent.com/410293/30239406-94cbcd8a-9564-11e7-96d4-d2ec2646e720.png)

**Comment by joshtynjala** [comment]
I'm surprised that it doesn't "just work". I could be wrong, but I would expect it to be handled entirely in the DistanceFieldStyle class. For regular distance fields, all I had to do was make sure that a custom MeshStyle could be passed to the internal Images.

**Comment by subdan** [comment]
Look at the button with MSDF font set for label.
![screen shot 2017-09-12 at 23 40 19](https://user-images.githubusercontent.com/410293/30347149-cd2332f2-9813-11e7-92fc-446b23ea707e.png)
![screen shot 2017-09-12 at 23 40 05](https://user-images.githubusercontent.com/410293/30347150-cd5540c6-9813-11e7-9229-b2f02657ce7d.png)
The bound size of the label is incorrect.

**Comment by joshtynjala** [comment]
If you add a letter that descends below the baseline, like a lowercase g or y, you should see that it's correct.

**Comment by subdan** [comment]
Look at the screenshot:
![screen shot 2017-09-13 at 22 56 02](https://user-images.githubusercontent.com/410293/30397814-c3e18306-98d6-11e7-8a67-4d9e0e1d9dcb.png)
On the left side — Feathers Button with TTF font set for Label. The Label is centred as it should be.
On the right side — Feathers Button with MSDF font set for Label. The Label is not in the centre of the Button.

**Comment by joshtynjala** [comment]
BitmapFontTextRenderer simply uses the lineHeight property reported by the BitmapFont.
