### ISSUE TITLE
ButtonGroup.equalButtonSizes (or something to that effect)

### ISSUE THREAD

**Issue by esidegallery** [BowlerHatLLC/feathers#1634]
ButtonGroup has a property distributeButtonSizes that makes all button sizes equal, but this is distributed across the entire width of the group if the group has an explicit width (in this case ButtonGroup.direction is horizontal).

What I would find very useful is a property that makes all buttons the same size according to the largest button, so e.g. the OK button isn't narrower than the Cancel button.

I am able to achieve this functionality in a LayoutGroup with a TiledRowsLayout set up like the following, but the ButtonGroup is so much handier and tidier:
```
var trl:TiledRowsLayout = new TiledRowsLayout;
trl.requestedRowCount = 1;
trl.horizontalAlign = HorizontalAlign.RIGHT;
trl.tileHorizontalAlign = HorizontalAlign.JUSTIFY;
trl.useSquareTiles = false;
trl.horizontalGap = Theme.SIZE_GAP;
buttonGroup.layout = trl;
```

**Comment by joshtynjala** [comment]
Good catch! Thanks.
