### ISSUE TITLE
List with TiledColumnsLayout may incorrectly cut its content

### ISSUE THREAD

**Issue by Klug76** [BowlerHatLLC/feathers#1635]
I found a bug when using the List with TiledColumnsLayout. The List may not display content correctly, by cutting it off to the right. This can happen when scrolling, especially after resizing. Code to reproduce:
```
		{
			new MetalWorksMobileTheme();

			layout = new AnchorLayout();

			var al: TiledColumnsLayout = new TiledColumnsLayout();
			al.gap = 16;
			al.useSquareTiles = false;
			al.distributeHeights = true;
			al.tileVerticalAlign = VerticalAlign.MIDDLE;

			var list: List = new List();
			list.layoutData = new AnchorLayoutData(0, 0, 0, 0);

			var arr: Array = [];
			for (var i: int = 0; i < 50; ++i)
			{
				arr[i] =
				{
					text: "item #" + i
				}
			}
			list.dataProvider = new ArrayCollection(arr);
			list.itemRendererFactory = function(): IListItemRenderer
			{
				var itemRenderer: DefaultListItemRenderer = new DefaultListItemRenderer();
				itemRenderer.labelField = "text";
				itemRenderer.setSize(320, 200);
				itemRenderer.defaultSkin = new Quad(1, 1, 0x406040);
				return itemRenderer;
			};
			list.layout = al;
			addChild(list);
		}
```
Screenshot:
![bug image](https://github.com/Klug76/feathers_sandbox/blob/TiledColumnsLayout_resize_bug/images/bug.png?raw=true)
Items 20 and 21 are not visible, although they fit the list area.

**Comment by joshtynjala** [comment]
Thanks, I can reproduce!

**Comment by Klug76** [comment]
any luck?

**Comment by joshtynjala** [comment]
Looks like this one got lost in the shuffle. Sorry about that! I'll make sure to look into it again soon.

**Comment by Klug76** [comment]
Please fix this bug - it becomes annoying.

**Comment by esidegallery** [comment]
Hi, was just about to submit this one too! My offset is happening on the left side, though it has occuured on the right side too. The offset appears to be affected by the `gap` property.

**Comment by esidegallery** [comment]
Thank you Josh!

**Comment by Klug76** [comment]
Yes, thank you Josh!
