### ISSUE TITLE
getDefaultMeshStyle error

### ISSUE THREAD

**Issue by yooni126** [BowlerHatLLC/feathers#1637]
when I download your github project I see this error when my app compile:
BitmapFontTextRenderer.as:1041:Error: Call to a possibly undefined method getDefaultMeshStyle through a reference with static type BitmapFont.

this._defaultStyle = this._currentTextFormat.font.getDefaultMeshStyle(this._defaultStyle, this._currentFontStyles, null);

**Comment by joshtynjala** [comment]
You need to use the latest Starling from Github too!

**Comment by yooni126** [comment]
ok solved  👍
