### ISSUE TITLE
Left aligned HorizontalSpinnerLayout

### ISSUE THREAD

**Issue by Adrian-S** [BowlerHatLLC/feathers#1639]
Hey, got a new / old problem with the spinner list.

I've made one small change, in `HorizontalSpinnerLayout` class I set: `var horizontalAlignOffsetX:Number = 0;`.
This worked perfectly with 2-3 columns, but I recently wanted to try a desktop size and that required 6 columns and I only got about 4-5. The last column jumped out around the 4.5 * column width mark.

You can see how it looks from the screenshot below:
![image](https://user-images.githubusercontent.com/1580105/30974746-115b30e8-a479-11e7-9235-f5697d7ef357.png)

Left most column is the currently selected `horizontalPageIndex` on the spinner. On each column in the top left corner you can see it's corresponding index. I've asked you about index in [Issue #1616](https://github.com/BowlerHatLLC/feathers/issues/1616).

Now I think this problem has to do with the way the items vector is made, and `_layoutIndexOffset` in `ListDataViewPort`. At this point I realised I will not be able to change this class safely, and apply changes only to one SpinnerList.

Do you have any idea on how to fix the items position?

Thanks.

**Comment by joshtynjala** [comment]
Have you tried the latest version of HorizontalSpinnerLayout that's here on Github? I've added a new horizontalAlign property, which adds support for aligning the selected item to the left or right instead of being limited the center. As I recall, this change required more than simply setting horizontalAlignOffsetX to 0.

**Comment by Adrian-S** [comment]
Works like a charm.

To our lord and saviour, we send many thanks.
