### ISSUE TITLE
Error 1009 - feathers.controls::Alert/alert_nativeStage_keyDownHandler()

### ISSUE THREAD

**Issue by teotigraphix** [BowlerHatLLC/feathers#1644]
Hey,

I received this from a crash email on my drum machine. No real stack trace but it seems like there are places that I use Alert as a message box and do not have buttonsDataProvider.

I am pretty sure based on different use cases, you might want to check for null on `_buttonsDataProvider`.

I am betting the user pressed the back button.

If this is my implementation error, let me know.

**Comment by joshtynjala** [comment]
Thanks!
