### ISSUE TITLE
List item layout bug

### ISSUE THREAD

**Issue by kevinfoley** [BowlerHatLLC/feathers#1645]
I've noticed a list item renderer layout bug that occurs when the data source is an array containing only null values:

    var collection:ListCollection = this.list.dataProvider as ListCollection;
    collection.removeAll();
    collection.push(null);

In such a situation, my item renderer's anchor layout does not behave correctly, and the controls on the item renderer are misaligned. 

You can view this issue using the attached sample code. Use `Main.mxml` as the document class. Notice that when you press the "Single null item" button, the list item renderer's controls are misaligned vertically.
[List item layout bug.zip](https://github.com/BowlerHatLLC/feathers/files/1389705/List.item.layout.bug.zip)

Tested with AIR 27, Starling 2.1, Feathers SDK 3.3.1

**Comment by joshtynjala** [comment]
As a workaround, you can should be able to set the List's typicalItem property to a non-null value.

**Comment by joshtynjala** [comment]
My commit didn't seem to close the issue properly, so pasting the hash here:

056b19111c47a4076c922eed7517ae6d34d04993

**Comment by kevinfoley** [comment]
Looks like that did the trick. Thanks for the quick turnaround!
