### ISSUE TITLE
List incorrectly calculates maxVerticalScrollPosition when using setItemRendererFactoryWithID

### ISSUE THREAD

**Issue by denisgl777** [BowlerHatLLC/feathers#1647]
```
			var layoutForMessagesList:VerticalLayout = new VerticalLayout();
			layoutForMessagesList.hasVariableItemDimensions = true;
			layoutForMessagesList.horizontalAlign = HorizontalAlign.JUSTIFY;
			layoutForMessagesList.verticalAlign = VerticalAlign.BOTTOM;
			layoutForMessagesList.gap = 10;
			layoutForMessagesList.paddingBottom = 10;
			layoutForMessagesList.paddingLeft = 10;

			messagesList = new List();
			messagesList.layout = layoutForMessagesList;
			listDataProvider = new ListCollection();
			messagesList.dataProvider = listDataProvider;

			messagesList.setItemRendererFactoryWithID(Config.TYPE_MESSEGE, function():IListItemRenderer
{
				var itemRenderer:ChatMessageItemRenderer = new ChatMessageItemRenderer();
				itemRenderer.textureCache = avatarCache;
				return itemRenderer;
});
			
			messagesList.setItemRendererFactoryWithID(Config.TYPE_DATA, function():IListItemRenderer
						{
							var itemRenderer:ChatDataItemRenderer = new ChatDataItemRenderer();
							return itemRenderer;
			});
			messagesList.factoryIDFunction = function(item:Object):String
			{
				if(item.type === Config.TYPE_DATA)
				{
					return Config.TYPE_DATA;
				}
				return Config.TYPE_MESSEGE;
			};

			private function onsendMessage(e:DBEvents):void 
		{
			var obj:Object = e.dataSnapshot.value;
			var date:Date = new Date(Number(obj.timestamp));
			var dateFormater:DateTimeFormatter = new DateTimeFormatter('ru_RU');
			dateFormater.setDateTimePattern('d MMMM');						
			var newDate:String = dateFormater.format(date);
			if (newDate != prevDate)
			{
				var timeObj:Object = {};
				timeObj.date = newDate;
				timeObj.type = TYPE_DATA;
				listDataProvider.addItem(timeObj);
				prevDate = newDate;
			}
			listDataProvider.addItem(obj);
			messagesList.validate();
			messagesList.scrollToPosition(0, messagesList.maxVerticalScrollPosition, 0.4);		
		}  
```

if commented listDataProvider.addItem(timeObj) the vertical position is calculated correctly

**Comment by joshtynjala** [comment]
When it completes scrolling after the call to scrollToPosition(), is the value of maxVerticalScrollPoisition different?

**Comment by denisgl777** [comment]
`messagesList.validate();
messagesList.scrollToPosition(0, messagesList.maxVerticalScrollPosition, 0);
trace('verticalScrollPosition = ' + messagesList.verticalScrollPosition.toString());
trace('maxVerticalScrollPosition = ' + messagesList.maxVerticalScrollPosition.toString());`

verticalScrollPosition = 8744
maxVerticalScrollPosition = 8818
verticalScrollPosition = 8818
maxVerticalScrollPosition = 8844
verticalScrollPosition = 8844
maxVerticalScrollPosition = 8918

they do not match, is it a feather error or did I do something wrong?

**Comment by joshtynjala** [comment]
This is actually the correct behavior. List uses a concept [layout virtualization](https://feathersui.com/help/faq/layout-virtualization.html) to optimize performance. This means that it creates item renderers only for the items that are visible at the current scroll position. The height of any items that haven't been displayed yet are estimated, but may be a little bit inaccurate. Once you scroll a bit, the real height is calculated for more items, and this causes the maxVerticalScrollPosition to change to a more accurate value.

You could call scrollToPosition() again when scrolling completes. However, that might not look good if the animation slows to a stop and then continues immediately. You might consider using Starling.juggler.delayCall() to check if the maxVerticalScrollPosition before the animation has finished, and then call scrollToPosition() immediately if it has. The old animation will be paused and the new maxVerticalScrollPosition will be used.
