### ISSUE TITLE
Missing link to Feathers SDK help

### ISSUE THREAD

**Issue by kevinfoley** [BowlerHatLLC/feathers#1648]
The header for the Feathers SDK section of your help website has a link to the Feathers UI help, but the Feathers UI help does not have a link to the Feathers SDK help:

![feathers sdk help link](https://user-images.githubusercontent.com/7231744/32130126-19ac10e8-bb47-11e7-9001-cc7069916cf5.png)

This makes it more difficult to find help for the Feathers SDK

**Comment by joshtynjala** [comment]
That was meant to be more like breadcrumbs, but I think it would make sense to link to the SDK help from the UI help.

**Comment by joshtynjala** [comment]
The Help link on https://feathersui.com/sdk/ now goes directly to SDK help. I also added a drop-down menu for desktop that has links to UI Help, SDK Help, and the API Reference.
