### ISSUE TITLE
Tree doesn't shrink its background

### ISSUE THREAD

**Issue by CrazyFlasher** [BowlerHatLLC/feathers#1653]
When tree branch is closed, its background still remains enlarged
![tree](https://user-images.githubusercontent.com/1607138/32802802-05df1154-c98a-11e7-85da-799a4b1794e4.gif)

**Comment by joshtynjala** [comment]
The width of all item renderers in a list or tree is set to the width of the largest item that has ever been displayed by that list/tree. Unfortunately, there's no good way for Feathers to automatically determine that the old width should be restored after a tree branch is closed.

However, if you provide a custom VerticalLayout with the resetTypicalItemDimensionsOnMeasure property set to true, it should work the way that you want.

**Comment by joshtynjala** [comment]
Were you able to use resetTypicalItemDimensionsOnMeasure successfully?

**Comment by joshtynjala** [comment]
Closing because there was no response.
