### ISSUE TITLE
Verticalscrollposition after changing the size of the list

### ISSUE THREAD

**Issue by denisgl777** [BowlerHatLLC/feathers#1658]
I'm using the list together textinput
[https://ibb.co/e7QnSm](url)
I change the size and position of the list after the appearance of the keyboard
```
private function onKeyboardEvent(e:MeasureKeyboardEvent):void 
{
	var stage:Stage = Starling.current.nativeStage;
	var layoutData:AnchorLayoutData = bottomGroup.layoutData as AnchorLayoutData;
	var height:Number = stage.softKeyboardRect.height / Starling.contentScaleFactor;
	var tween:Tween = new Tween(layoutData, 0.2);
	tween.animate('bottom', height);
	messagesList.validate();
	var pos:Number = messagesList.verticalScrollPosition;
	Starling.juggler.add(tween);
}
```
[https://ibb.co/eiVbL6](url)
but the vertical position of list is not saved
How can I move to the correct vertical position of the list after the change? I tried to save the variable before the change, but it did not work.
I apologize to Josh that I often ask questions :)

**Comment by joshtynjala** [comment]
Unless you replace the data provider, the scroll position should not change when you resize the list. However, I think it may appear that the position has changes because your aligns to the bottom instead of the top. So the verticalScrollPosition is probably the same, but it's the item on top that remains visible, but you're expecting the item on bottom to remain visible.

With that in mind, I think you may need to increase the verticalScrollPosition by the amount that you decrease the height of the list.

**Comment by denisgl777** [comment]
Thanks josh! It works perfectly

**Comment by denisgl777** [comment]
Can I clarify without creating a new topic?
If I add items to the top of the list, do I also need to calculate the new sheet position to keep the last object visible?

**Comment by joshtynjala** [comment]
If you add items to the top of the list, the existing items will be repositioned by the layout. The verticalScrollPosition will remain the same, but you will probably see different items. If you want the same items to be visible, then yes, you need to calculate a new scroll position.

**Comment by denisgl777** [comment]
Thanks Josh!

**Comment by denisgl777** [comment]
Josh, do you think it makes sense to add the ability of feathers to keep objects visible when adding items to the top of the list?

**Comment by joshtynjala** [comment]
That would be difficult to implement in a general way because Feathers supports different layouts, including custom ones.
