### ISSUE TITLE
TextFieldTextEditor: add property to turn off behavior that resets scroll position on focus out

### ISSUE THREAD

**Issue by pol2095** [BowlerHatLLC/feathers#1659]
Hello,

with TextFieldTextEditor, if the caret is on "skinnable" word  when the TextInput lose focus, the TextInput return to the position 0

```xml
<?xml version="1.0"?>
<f:Application xmlns:fx="http://ns.adobe.com/mxml/2009"
    xmlns:f="library://ns.feathersui.com/mxml"
	theme="feathers.themes.MetalWorksDesktopTheme"
	addedToStage="ats(event)">

	<fx:Script>
		<![CDATA[
			import feathers.controls.text.TextFieldTextEditor;
			import feathers.core.ITextEditor;
			
			private function style():ITextEditor
			{
				var textRenderer:TextFieldTextEditor = new TextFieldTextEditor();
				return textRenderer;
			}
			private function ats(event:Event):void
			{
				input.textEditorFactory = style;
				input.text = "Build mobile & desktop games + apps with fully-skinnable UI controls"; 
			}
		]]>
	</fx:Script>

	<f:TextInput width="300" id="input"/>

</f:Application>
```
![GitHub Logo](http://pol2095.free.Fr/img/TextInput.png)
![GitHub Logo](http://pol2095.free.Fr/img/TextInputOut.png)

Thanks

**Comment by joshtynjala** [comment]
This is actually by design. Generally, that's a good behavior to have on mobile. However, I suppose I can add an option to disable it, since that's not usually how they're supposed to behave on desktop.

**Comment by pol2095** [comment]
Thanks, where is the code that causes this behavior.

**Comment by joshtynjala** [comment]
It looks like you can subclass TextFieldTextEditor and set the protected variable resetScrollOnFocusOut to false in the constructor.
