### ISSUE TITLE
Auto resize of panel

### ISSUE THREAD

**Issue by CrazyFlasher** [BowlerHatLLC/feathers#1661]
Hi,
There is a panel with vertical layout and child container with vertical layout and children inside.
I want to have possibility to hide or show container with children inside panel.
I set true or false of includeInLayout of child container in panel, but panel size only changes, when I resize stage (see gif attached).
Is there any method, that I can call to recalculate panel size in this case?
Thanks!
![buggy](https://user-images.githubusercontent.com/1607138/33186443-51a56188-d092-11e7-85c0-3f1f76774b16.gif)

**Comment by CrazyFlasher** [comment]
Calling `readjustLayout` of parent container helped to resolve the problem

**Comment by joshtynjala** [comment]
I tried to reproduce this issue, but the Panel correctly resizes for me.

I tested with the following code:

``` actionscript
var panel:Panel = new Panel();
panel.layout = new VerticalLayout();
panel.title = "Panel";
this.addChild(panel);

var container:ScrollContainer = new ScrollContainer();
container.layout = new VerticalLayout();
container.addChild(new Quad(100, 100, 0x000000));
container.addChild(new Quad(100, 100, 0x333333));
container.addChild(new Quad(100, 100, 0x666666));
panel.addChild(container);

var button:Button = new Button();
button.label = "Click Me";
button.addEventListener(Event.TRIGGERED, function():void
{
	container.includeInLayout = !container.includeInLayout;
});
button.move(130, 10);
this.addChild(button);
```

Do you think you could try to modify this code, or perhaps put together a similarly small example that can reproduce this issue?

**Comment by joshtynjala** [comment]
Please feel free to comment if you can provide additional information. Closing for now.
