### ISSUE TITLE
custom layout incorrectly determines the position of the list itemrenderer

### ISSUE THREAD

**Issue by denisgl7** [BowlerHatLLC/feathers#1663]
https://forum.starling-framework.org/topic/modifying-the-spinnerlist-and-pickerlist-component-skin
I used this theme to use a class SpinnerListFadingEffect extends VerticalSpinnerLayout 
The change in transparency works well, but when you add a list to the stage, the initial transparency settings are incorrectly defined.
But the change in size does lead to problems in calculating the current situation. The list behaves incorrectly. I have established an additional condition that the initial conditions do not go beyond
else if (scaleCorrection > 1)
	scaleCorrection = 1
Elements of spinerlist looks good, but here the list behaves incorrectly

**Comment by joshtynjala** [comment]
Can you share a video/GIF? Or maybe the source code for SpinnerListFadingEffect? I can't tell from your description what the problem is.

**Comment by denisgl777** [comment]
```
public class MainRoadApp extends LayoutGroup
	{
		private var spinerList:SpinnerList;
		override protected function initialize():void
		{
			
			new MetalWorksMobileTheme();
			
			this.layout = new AnchorLayout();
			this.width = stage.stageWidth;
			this.height = stage.stageHeight;
			spinerList = new SpinnerList();
			var layout:SpinnerListFadingEffect = new SpinnerListFadingEffect();
			spinerList.layout = layout;
			spinerList.width = stage.stageWidth * 0.3;
			spinerList.height = stage.stageHeight * 0.2;
			spinerList.dataProvider = new ArrayCollection(
			[
				{ text: "some text1"},
				{ text: "some text2"},
				{ text: "some text3"},
				{ text: "some text4"},
			]);
			
			spinerList.itemRendererFactory = function():IListItemRenderer
			{
				var itemRenderer:DefaultListItemRenderer = new DefaultListItemRenderer();
				itemRenderer.labelField = "text";
				return itemRenderer;
			};
			spinerList.layoutData = new AnchorLayoutData(NaN, NaN, NaN, NaN, 0, 0);
			
			this.addChild(spinerList);
			
		}
		
	}
```
```
public class SpinnerListFadingEffect extends VerticalSpinnerLayout 
	{
		
		public function SpinnerListFadingEffect() 
		{
			super();
			
		}
		
		override public function layout(items:Vector.<DisplayObject>, viewPortBounds:ViewPortBounds = null, result:LayoutBoundsResult = null):LayoutBoundsResult
		{
			super.layout(items, viewPortBounds, result);
			var itemCount:int = items.length;
			var alphaCorrection:Number = 1;
			var scaleCorrection:Number = 1;
 
			for ( var i:int = 0; i < itemCount; i++ )
			{
				var item:DisplayObject = items[i];
				//figure out how to change the alpha here
				if ( result != null )
				{
					if ( item != null )
					{
						alphaCorrection = 1 -  1.66 * Math.abs( ( ( DefaultListItemRenderer(item).owner.height - 2 ) / 2 - ( DefaultListItemRenderer(item).y + DefaultListItemRenderer(item).height / 2 - viewPortBounds.scrollY ) ) ) / ( DefaultListItemRenderer(item).owner.height - 2 );
						scaleCorrection = 1 - 0.33 * Math.abs( ( ( DefaultListItemRenderer(item).owner.height - 2 ) / 2 - ( DefaultListItemRenderer(item).y + DefaultListItemRenderer(item).height / 2 - viewPortBounds.scrollY ) ) ) / ( DefaultListItemRenderer(item).owner.height - 2 );
						if (alphaCorrection < 0)
						{
							alphaCorrection = 0;
						}
 
						if (scaleCorrection < 0)
							scaleCorrection = 0;
						else if (scaleCorrection > 1)
							scaleCorrection = 1;
						
 						trace(scaleCorrection);
						DefaultListItemRenderer(item).alpha = alphaCorrection;
						DefaultListItemRenderer(item).scale = scaleCorrection;
					}
				}
			}
 
			return result;
		}
		
	}
```


<a href="https://ibb.co/iBqrf6"><img src="https://preview.ibb.co/kzrKYR/fade.gif" alt="fade" border="0" /></a>

**Comment by joshtynjala** [comment]
This value probably isn't what you think it is:

> DefaultListItemRenderer(item).height

Because when you set the scale, it also affects the height:

> DefaultListItemRenderer(item).scale = scaleCorrection;

**Comment by denisgl777** [comment]
On the animation above, I created the rotation only down. In this case, scrolling always returns to the beginning. Is this normal behavior?

**Comment by denisgl777** [comment]
scale values ​​by the formula are in the range 0.7-1
but spinnerlist does not move to the desired position, returns back

**Comment by joshtynjala** [comment]
One thing worth mentioning is that SpinnerList expects all items in a vertical layout to have exactly the same height. SpinnerList enables snapToPages and the height of each item is considered the pageHeight. Scroller does not support pages with variable heights.

If you want to scale the text smaller, it's probably something that you need to do inside the item renderer. However, the height of the item renderer must remain the same, so the text should only scale.

**Comment by denisgl777** [comment]
Thank you Josh!
So will it be right to determine the font size in the overridden function draw in item renderer?

**Comment by joshtynjala** [comment]
The layout will probably validate the item renderer before positioning it, so if you base the font size on the y position of the item renderer, you might not calculate a perfectly accurate value.

I think your calculation of scaleCorrection in the layout makes sense. You might consdier creating a new property on the item renderer to pass it in from the layout. Then, use the new property to calculate an appropriate font size inside the item renderer. draw() might work, but it might not be the most optimized. commitData() might be more appropriate.

**Comment by denisgl777** [comment]
Does not a commitData apply once?
```
if ( item != null )
					{
						alphaCorrection = 1 -  1.66 * Math.abs( ( ( LayoutGroupListItemRenderer(item).owner.height - 2 ) / 2 - ( LayoutGroupListItemRenderer(item).y + LayoutGroupListItemRenderer(item).height / 2 - viewPortBounds.scrollY ) ) ) / ( LayoutGroupListItemRenderer(item).owner.height - 2 );
						scaleCorrection = 1 - 0.33 * Math.abs( ( ( LayoutGroupListItemRenderer(item).owner.height - 2 ) / 2 - ( LayoutGroupListItemRenderer(item).y + LayoutGroupListItemRenderer(item).height / 2 - viewPortBounds.scrollY ) ) ) / ( LayoutGroupListItemRenderer(item).owner.height - 2 );
						//scaleCorrection = 1 - 0.33 * Math.abs( ( ( LayoutGroupListItemRenderer(item).owner.height - 2 ) / 2 - ( LayoutGroupListItemRenderer(item).y + LayoutGroupListItemRenderer(item).height / 2 - viewPortBounds.scrollY ) ) ) / ( LayoutGroupListItemRenderer(item).owner.height - 2 );
						if (alphaCorrection < 0)
						{
							alphaCorrection = 0;
						}
 
						if (scaleCorrection < 0)
							scaleCorrection = 0;
						else if (scaleCorrection > 1)
							scaleCorrection = 1;
						FadeSpinnerListItemRender(item).alpha = alphaCorrection;
						FadeSpinnerListItemRender(item).scaleCorrection = scaleCorrection;
					}
```
```
override protected function draw():void 
		{
			
			if (scaleCorrection !== NaN)
			{
				//change size
			}
			super.draw();
		}
```
so I'm on the right track?

**Comment by joshtynjala** [comment]
commitData() is called if INVALIDATION_FLAG_DATA is set. You could call invalidate(INVALIDATION_FLAG_DATA) in your scaleCorrection setter, and that would ensure that commitData() is called.

Any time before the call to super.draw() should be fine too. I don't see any problem with your override of draw(). While I would probably try to use commitData(), your solution also looks perfectly valid.

**Comment by denisgl777** [comment]
Thank you Josh!
