### ISSUE TITLE
Shift + HOME / END doesn't do selection on AutoComplete

### ISSUE THREAD

**Issue by CrazyFlasher** [BowlerHatLLC/feathers#1665]
OS: Windows
Component: AutoComplete (probably TextInput also)

**Comment by joshtynjala** [comment]
Interesting. That's not a keyboard shortcut that I'm familiar with.

**Comment by CrazyFlasher** [comment]
If you select line for ex. some where in the middle, hold shift and press END - line will be selected from cursor position until the end of line.
![gif](https://user-images.githubusercontent.com/1607138/33513200-8b736d82-d746-11e7-860f-5b7798c4e597.gif)
