### ISSUE TITLE
TextBlockTextRenderer doesn't show GraphicElement on some devices

### ISSUE THREAD

**Issue by subdan** [BowlerHatLLC/feathers#1669]
Hello. I want to show text with image by using TextBlockTextRender.
To show image I use GraphicElement.
```
var content:Vector.<ContentElement> = new Vector.<ContentElement>();
image = new EmbeddedImage();
elementImage = new GraphicElement(image,image.width,image.height, regular);
content.push(elementImage);
```
On iPad everything works fine, I see the image. But when I test my app on iPhone I don't see theimage.

I check this on iPad emulator:
`adl.exe ... -screensize 768x1004:768x1024 -XscreenDPI 132 -XversionPlatform IOS ...`
I see the image.
I changed DPI to 200 and I see only text without image.
`adl.exe ... -screensize 768x1004:768x1024 -XscreenDPI 200 -XversionPlatform IOS ...`

Why GraphicElement dissapears on high PPI values?

**Comment by joshtynjala** [comment]
I tried the following code on a variety of screen sizes and densities, but it worked fine.

``` actionscript
var image:Bitmap = new EMBEDDED_IMAGE();
var elementImage:GraphicElement = new GraphicElement(image,image.width,image.height, new ElementFormat());

var textRenderer:TextBlockTextRenderer = new TextBlockTextRenderer();
textRenderer.content = elementImage;
this.addChild(textRenderer);
```

```
[Embed(source="test-pattern1.png")]
private static const EMBEDDED_IMAGE:Class;
```

**Comment by subdan** [comment]
Ok. Thanks. I'll try to find the issue in my code.
