### ISSUE TITLE
ImageLoader drawToBitmapData() and ScaleMode.NO_BORDER

### ISSUE THREAD

**Issue by king514jy** [BowlerHatLLC/feathers#1672]
In Application
![111](https://user-images.githubusercontent.com/5669543/33829503-82aef24a-deab-11e7-915c-5d06e1442403.jpg)

``` actionscript
photoImage = new ImageLoader();
 photoImage.move(_data.photo.x,_data.photo.y);
photoImage.setSize(_data.photo.width,_data.photo.height);
 addChild(photoImage);
 photoImage.source = DataManage.getInstance().getPhotoUrl();

var bd:BitmapData = new BitmapData(picGroup.width,picGroup.height);
        picGroup.drawToBitmapData(bd);
        return bd;

var fs:FileStream = new FileStream();
        var file:File = _saveFolder.resolvePath(StringUtil.getDateString()+".jpg")
        fs.open(file,FileMode.WRITE);
        var byt:ByteArray = new ByteArray();
        bd.encode(bd.rect,new JPEGEncoderOptions(100),byt);
        fs.writeBytes(byt);
        fs.close();
        fs = null;
```

![333](https://user-images.githubusercontent.com/5669543/33829675-32efb3d8-deac-11e7-93a0-c4257df4039b.jpg)

This is the correct result！

photoImage.scaleMode = ScaleMode.NO_BORDER;

![222](https://user-images.githubusercontent.com/5669543/33829683-3bc58cf8-deac-11e7-9a47-774a88132ce0.jpg)

If you set the scaleMode result will be wrong

**Comment by joshtynjala** [comment]
If I understand you correctly, ScaleMode.NO_BORDER only fails after you've saved your image to JPG and reloaded the saved file?

**Comment by king514jy** [comment]
@joshtynjala No, the saved JPG file failed. Wrong image is JPG file

**Comment by joshtynjala** [comment]
@king514jy Have you tried opening the JPG file in Photoshop (or another program like that) to ensure that the file looks correct without the Feathers ImageLoader?

**Comment by king514jy** [comment]
@joshtynjala ![1](https://user-images.githubusercontent.com/5669543/33865611-7053acf8-df2d-11e7-9a45-88788a4e71bb.png)

**Comment by king514jy** [comment]
`import com.greensock.events.LoaderEvent;
import com.greensock.loading.ImageLoader;

import flash.display.BitmapData;
import flash.display.Sprite;

import starling.display.Image;
import starling.textures.Texture;

public class ScaleModuleImage extends Image
{
    protected var _bmpData:BitmapData;
    private var _url:String;
    private var isAlign:Boolean;
    private var _sW:Number;
    private var _sH:Number;
    private var imageLoader:ImageLoader;
    private var spr:Sprite;
    private var _scaleMode:String;
    public function ScaleModuleImage(width:Number, height:Number,scaleMode:String ="proportionalOutside" )
    {
        super(null);
        _sW = width;
        _sH = height;
        this._scaleMode = scaleMode;
        this.width = _sW;
        this.height = _sH;
    }
    public function load(url:String):void
    {
        this._url = url;
        spr = new Sprite();
        imageLoader = new ImageLoader(url,{container:spr,smoothing:true,width:_sW,height:_sH,
            scaleMode:_scaleMode,onComplete:loadComplete,onError:errorHandle});
        imageLoader.autoDispose = true;
        imageLoader.load(true);
    }
    protected function errorHandle(e:LoaderEvent):void
    {
        trace("error:"+_url);
    }
    protected function loadComplete(e:LoaderEvent):void
    {
        _bmpData = new BitmapData(_sW,_sH,true,0);
        _bmpData.draw(spr);
        texture = Texture.fromBitmapData(_bmpData);
        spr.removeChildren();
        spr = null;
        imageLoader.dispose(true);
        imageLoader.unload();
        imageLoader = null;
        dispatchEventWith("complete");
    }
    public function disposeImage():void
    {

    }
    override public function dispose():void
    {
        if(_bmpData)_bmpData.dispose();
        _bmpData = null;
        if(texture)texture.dispose();
        texture = null;
        super .dispose();
    }

    public function get url():String {
        return _url;
    }

    public function get scaleMode():String {
        return _scaleMode;
    }`

I am using this type of replacement for now and he can work normally

**Comment by joshtynjala** [comment]
@king514jy Are you waiting for Event.COMPLETE?

It's also possible that you need to call validate() on the ImageLoader.

**Comment by joshtynjala** [comment]
@king514jy Still waiting on a response to my previous questions. Thanks!
