### ISSUE TITLE
Wrong measure text field height in TextFieldTextEditor

### ISSUE THREAD

**Issue by TerenceZ** [BowlerHatLLC/feathers#1675]
In `TextFieldTextEditor`, `this.measure()`'s height for `this.measureTextField` is wrong when the used font family is embed, because `commitStylesAndData()` only sets `this.textField.embedFont` property, not the passed argument `textField`'s `embedFont` property. 

Issue Relative Code Lines are

https://github.com/BowlerHatLLC/feathers/blob/master/source/feathers/controls/text/TextFieldTextEditor.as#L1924

and

https://github.com/BowlerHatLLC/feathers/blob/master/source/feathers/controls/text/TextFieldTextEditor.as#L1930

**Comment by joshtynjala** [comment]
Good catch! I'll get it fixed.
