### ISSUE TITLE
ScreenDensityScaleFactorManager: let us override scale factor

### ISSUE THREAD

**Issue by kevinfoley** [BowlerHatLLC/feathers#1678]
Often when developing, it is useful to precisely replicate the screen layout of a particular mobile device in the AIR debugger on a desktop. This allows us to fine-tune our layout without having to install a build on the mobile device each time we make an adjustment.

It would be great if we could override the scale factor in ScreenDensityScaleFactorManager to simulate a particular device. For example, to simulate the screen of an iPhone SE or iPod Touch, we would set the debugger window dimensions to `640 x 1136` and the scale factor to `2`.

A possible implementation would be to add a second, optional argument to the constructor which lets us declare an explicit scale factor:

    starling = new Starling(MyApp, stage, null, null, "auto", "auto");
    scaler = new ScaleFactorManager(starling, 2);

Presumably the new constructor would look something like this, with `-1` used to indicate that the calculated scale factor should be used:

    public function ScreenDensityScaleFactorManager(starling:Starling, explicitScaleFactor:int = -1) {

Another option would be to add a public function to override the scale factor:

    starling = new Starling(MyApp, stage, null, null, "auto", "auto");
    scaler = new ScaleFactorManager(starling);
    scaler.overrideScaleFactor(2);

**Comment by joshtynjala** [comment]
ADL can simulate screen density, and most IDEs can too.

From the command line, you can use the following option when launching ADL:

```
-XscreenDPI 326
```

Replace 326 with the density of the screen you want to simulate.

I know for sure that Flash Builder, IntelliJ IDEA, and Visual Studio Code all support customizing this value in the debug launch options. Animate CC doesn't, though.

I definitely wouldn't create ScreenDensityScaleFactorManager without a way to use it when testing mobile apps on desktop. 😀

**Comment by kevinfoley** [comment]
Thanks, that argument isn't mentioned in the [ADL documentation](https://help.adobe.com/en_US/air/build/WSfffb011ac560372f-6fa6d7e0128cca93d31-8000.html)!

**Comment by joshtynjala** [comment]
Yeah, it's not officially documented. As I understand it, from reading some of the comments in the debugger source code donated to Apache Flex, Adobe intended to add the screen density into -screensize eventually, but I guess they never got around to it. Thankfully, the community has figured out this undocumented one!

There's another undocumented one that simulates the custom three letter OS string returned by Capabilities.version, like "AND" or "IOS". I don't have it on hand right now, but I think i recall that it's -Xplatform.

```
-Xplatform IOS
```

**Comment by kevinfoley** [comment]
It looks like the argument for platform is `XversionPlatform`, e.g.
    
    adl -screensize iPhone5Retina -XscreenDPI 326 -XversionPlatform IOS
