### ISSUE TITLE
ScrollText: support padding outside of view port, similar to Panel's outerPadding

### ISSUE THREAD

**Issue by kevinfoley** [BowlerHatLLC/feathers#1679]
I have a ScrollText which uses a background skin. The background skin has a border which I don't want the text to scroll over. However, regardless of the padding settings used, the text always scrolls flush with the top and bottom edge of the ScrollText.

Is there any way to tweak the scroll area so that the text won't appear on top of the top and bottom border of the background skin?
![scrolltext overlap background border](https://user-images.githubusercontent.com/7231744/34579818-747ed5b8-f13f-11e7-9acd-21cc747659c8.png)

**Comment by joshtynjala** [comment]
Hmm... no, that doesn't seem to be possible. It looks like ScrollText needs something similar to Panel's outerPadding properties to support something like that.

**Comment by joshtynjala** [comment]
For now, you can add the ScrollText to a LayoutGroup. The LayoutGroup should render the background, and then you can use a layout to add padding around the ScrollText.
