### ISSUE TITLE
Ugly look, when scaling container with component

### ISSUE THREAD

**Issue by CrazyFlasher** [BowlerHatLLC/feathers#1680]
Hi.
In my app I use custom algorithms to scale content.
I couple of world I scale starling root container instead of starling stage and re-position it.
I decided to use feathers UI for prototype, but they are blurry because of root container scaling:
![image](https://user-images.githubusercontent.com/1607138/34800787-037a4d00-f66e-11e7-99af-3bb690c80f64.png)
Is it possible to fix it somehow?

**Comment by CrazyFlasher** [comment]
The issue is that texts are blurry

**Comment by joshtynjala** [comment]
Feathers text renderers generally try to snap to the nearest pixel so that the texture won't become blurry, but I think it only works with contentScaleFactor, and not when using scaleX/scaleY.

You might be able to adjust things like the padding values on the Alert to account for your scaling.

**Comment by CrazyFlasher** [comment]
Ok, Thanks. I tried different way of scaling and everything work as I expected
![image](https://user-images.githubusercontent.com/1607138/34843814-4706a1cc-f718-11e7-809c-fb1123056eb9.png)
