### ISSUE TITLE
[Bug] Unable to deselect items in Tree component

### ISSUE THREAD

**Issue by subdan** [BowlerHatLLC/feathers#1682]
Hello, Josh.

I've found bug in Tree component. I'm unable to deslect selected item with code.

I tried to set `tree.selectedItem = null` but the selectedItem is still selected.

I tried to set `tree.selectedLocation = new <int>[];` as you said [here](https://feathersui.com/help/tree.html) but I get this error:
`RangeError: Error #1125: The index -1 is out of range 0.`

How to repeat:
Add next code to the initialize method of TreeScreen class of ComponentsExplorer example.

```
Starling.juggler.delayCall(deselectItems, 5);
function deselectItems():void
{
	trace("yep");
	_tree.selectedItem = null;
	_tree.selectedLocation = new <int>[];
}

```
Select any item in Tree and wait 5 sec. You will notice that selected item is still selected but the _tree.selectedItem is null.

**Comment by subdan** [comment]
I noticed that if I scroll the Tree the selected item became unselected.

**Comment by joshtynjala** [comment]
Confirmed. I'll take a look!

**Comment by subdan** [comment]
Thanks!
