### ISSUE TITLE
[Bug] PopUpManager.removeAllPopUps throws exception for Callout that has another Callout as its origin

### ISSUE THREAD

**Issue by subdan** [BowlerHatLLC/feathers#1685]
I want to manual close all Callouts. I call PopUpManager.removeAllPopUps(true); and get:
`[Fault] exception, information=ArgumentError: Display object is not a pop-up.`

**Comment by joshtynjala** [comment]
Can you provide some simple code that can reproduces the issue? Thanks!

**Comment by joshtynjala** [comment]
Confirmed. I'll investigate!

**Comment by joshtynjala** [comment]
So you're using a Callout as the origin for another Callout? Feathers definitely shouldn't stop you from doing that, if that's what you really want to do, but I'd recommend avoiding this sort of thing.

It's worth mentioning that the official iOS Human Interface Guidelines specifically say that you should not open a popover (their name for a callout) from another popover, so I'm not just stating my own opinion here. I wouldn't expect Apple to reject your app for doing this, but it's worth understanding that they've made an official recommendation of this type of UX.

**Comment by subdan** [comment]
Thanks for explanation, Josh. I will not use a Callout as the origin for another Callout.
