### ISSUE TITLE
When isSwipeToPopEnabled=true fast swipe stops transition and throw an error

### ISSUE THREAD

**Issue by subdan** [BowlerHatLLC/feathers#1691]
I found a bug with transition when isSwipeToPopEnabled = true; If I swipe very fast transition stops and both screens is visible on the screen.

It happens because this._dragEffectContext is null.
Method `handleDragEnd` line 1422, class StackScreenNavigator.

**Comment by joshtynjala** [comment]
Thanks!

**Comment by subdan** [comment]
Thank you!
