### ISSUE TITLE
Iris.createIrisOpenEffectAtRatio() throws “argument count mismatch error‘

### ISSUE THREAD

**Issue by subdan** [BowlerHatLLC/feathers#1698]
Steps to reproduce:
`navigator.replaceScreen("helpScreen", Iris.createIrisOpenEffectAtRatio(0.5,0.5,0.3));`

`[Fault] exception, information=ArgumentError: Error #1063: Argument count mismatch on Function/Iris.as$0:anonymous(). Expected 1, got 3.`

Why can't I pass Iris parameters to createIrisOpenEffectAtRatio function?

This function expects at least two parametes:
`public static function createIrisOpenEffectAtRatio(ratioX:Number, ratioY:Number, duration:Number = 0.5, ease:Object = Transitions.EASE_OUT):Function`

**Comment by joshtynjala** [comment]
You're trying to use the iris "effect", but you need to use the iris "transition" instead.

**Comment by subdan** [comment]
Sorry.
