### ISSUE TITLE
Invalidating size only seems capable of shrinking things

### ISSUE THREAD

**Issue by kevinfoley** [BowlerHatLLC/feathers#1700]
In a desktop app, I have dialog class which extends LayoutGroup and gets added to the stage using PopupManager. In its initialization function, I have this code:

    Starling.current.stage.addEventListener(ResizeEvent.RESIZE, updateDimensions);
    updateDimensions();

The class also includes this function:

    private function updateDimensions(e:* = null):void {
        maxHeight = Starling.current.stage.stageHeight * .8;
        readjustLayout();
    }

If the window size is small when the dialog is shown, the LayoutGroup sizes itself to its `maxHeight`. If the window size is large, LayoutGroup sizes itself to fit its contents and it doesn't reach `maxHeight`.

If I shrink the window while the dialog is visible, it will scale itself down so that it doesn't exceed `maxHeight`. However, if I increase the size of the window, the dialog won't scale itself _up_. The only way to increase the size of the dialog is to set the size manually, or set `minHeight`, but either of these solutions requires me to calculate the correct size to fit the contents.

LayoutGroups are clearly capable of sizing themselves to fit their contents, since they do this by default when initialized. Is there a way to force a LayoutGroup to re-run its initial layout code and size itself to fit its contents?

**Comment by joshtynjala** [comment]
Usually, when this sort of thing happens, it's because the height property has been set explicitly somewhere. Try setting the height property to NaN when you update maxHeight.

**Comment by joshtynjala** [comment]
It's also possible that LayoutGroup's maxHeight is causing the children of the LayoutGroup to be given an explicit height. In that case, any of the children's explicit height values will need to be cleared with NaN.

**Comment by kevinfoley** [comment]
Thanks Josh. I was never setting the explicit height myself, but I guess it was getting set somewhere, because setting the height to NaN before calling `readjustLayout()` fixes it!
