### ISSUE TITLE
Re-create header of panel after component is created

### ISSUE THREAD

**Issue by CrazyFlasher** [BowlerHatLLC/feathers#1702]
Hi.
I need to change style of panel header real time (call headerFactory).
Is it possible?

**Comment by joshtynjala** [comment]
There are a few of options:

1. If you're simply changing styles to make the panel look different, you can change customHeaderStyleName. The header will be recreated and styled differently.

2. You can create two (or more, if needed) functions that each customize the header differently. Simply pass a different function to headerFactory to recreate it.

3. You can set headerFactory to null and then set it back to the original function.

**Comment by CrazyFlasher** [comment]
Works but with problem:
```actionscript
        private function updateHeader():void
	{
		headerFactory = null;
		headerFactory = hFactory;
	}

	private function hFactory():DisplayObject
	{
		if (_backBtn.visible || noNet.visible)
		{
			var header:Header = new Header();
			header.leftItems = new <DisplayObject>[_backBtn];
			header.centerItems = new <DisplayObject>[noNet];

			return header;
		}

		return new LayoutGroup();
	}
```
*In this case `_backBtn`* is always invisible

**Screen 1:**
 I create panel without header
```hFactory`` returns ```new LayoutGroup```
![image](https://user-images.githubusercontent.com/1607138/36925210-6f2b4cf0-1e7a-11e8-8ae9-77b96690129a.png)

**Screen 2:**
Then I call ``updateHeader``` and ```hFactory``` returns ```new Header```
![image](https://user-images.githubusercontent.com/1607138/36925327-10a0c2a4-1e7b-11e8-8b1e-4b2adbb7e258.png)

**Screen 3:**
Then I call `updateHeader` and like in 1st step `hFactory` return `new LayoutGroup` (everything as expected now)

**Screen 4:**
Then I call ``updateHeader``` and ```hFactory``` returns ```new Header``` (like in step 2)
![image](https://user-images.githubusercontent.com/1607138/36925383-59928330-1e7b-11e8-9e17-43cfdd9e7c23.png)

As you can see on screen, `centerItems` are invisble, but if I debug their properties, `visible` and `includeInLayout` are `true`

**Comment by joshtynjala** [comment]
You will probably need to recreate any children that are added to the header, or you could possibly remove them all before changing the header. The header is disposed before the panel recreates it, so all children are automatically disposed too (as is common with any Starling display object).

**Comment by CrazyFlasher** [comment]
```actionscript
        private function updateHeader():void
	{
		if (_backBtn.parent) _backBtn.removeFromParent();
		if (noNet.parent) noNet.removeFromParent();

		headerFactory = null;
		headerFactory = hFactory;
	}
```
Added these lines, but didn't help
```
if (_backBtn.parent) _backBtn.removeFromParent();
if (noNet.parent) noNet.removeFromParent();
```

**Comment by joshtynjala** [comment]
It looks like Header loops through leftItems, rightItems, and centerItems and disposes everything. You'll need to set those properties to null.

**Comment by CrazyFlasher** [comment]
Hm...still doesn't work:
```actionscript
private var _header:Header;
```
```actionscript
        private function hFactory():DisplayObject
	{
		if (_backBtn.visible || noNet.visible)
		{
			if (_header)
			{
				_header.leftItems = null;
				_header.centerItems = null;
			}

			_header = new Header();
			_header.leftItems = new <DisplayObject>[_backBtn];
			_header.centerItems = new <DisplayObject>[noNet];

			return _header;
		}

		return new LayoutGroup();
	}
```

**Comment by joshtynjala** [comment]
_header will already be disposed by the time that hFactory is called.

It's probably better to simply create all of the header's children inside hFactory to avoid this mess.

**Comment by CrazyFlasher** [comment]
ok, creating new instances helped to resolve the problem.
thanks!
