### ISSUE TITLE
Incorrect scale factor for iPhone X

### ISSUE THREAD

**Issue by subdan** [BowlerHatLLC/feathers#1703]
iPhone X has 458 PPI but the ScreenDensityScaleFactorManager returns 4x factor. It should be 3x.

**Comment by joshtynjala** [comment]
I don't have an iPhone X for testing, but when I simulate a device with 458 DPI in the AIR Debug Launcher, ScreenDensityScaleFactorManager correctly determines that the contentScaleFactor value should be 3.

Do you have iPhone X? When you run an AIR app on it, what is the value of flash.system.Capabilities.screenDPI? It's possible that this value is wrong on a real device, for some reason.

**Comment by subdan** [comment]
I updated Feathers sources and now scale factor is 3. So all is ok.
