### ISSUE TITLE
Button touch down and touch up events?

### ISSUE THREAD

**Issue by CrazyFlasher** [BowlerHatLLC/feathers#1708]
Is it possible to listen Button down and up events without extending it?
Also without listening TouchEvent and checking touch phase?

**Comment by joshtynjala** [comment]
You can listen for the standard TouchEvent.TOUCH that all Starling display objects dispatch.

You could also listen for FeathersEventType.STATE_CHANGE and check the value of currentState.

**Comment by CrazyFlasher** [comment]
I see that states are deprecated.
![image](https://user-images.githubusercontent.com/1607138/38217786-3a835260-36d8-11e8-9370-461535d93cd1.png)
Ok. Then I'll check touch phase.
Thanks

**Comment by CrazyFlasher** [comment]
Oh. Sorry. I missed ButtonState
