### ISSUE TITLE
DataGrid selectedIndex does not change when sorting columns?

### ISSUE THREAD

**Issue by martinrossil** [BowlerHatLLC/feathers#1709]
Hi Josh :)

I've created a DataGrid with your test dataProvider data and custom Header / Cell Renderers.

DataGrid looks like this:

![datagrid](https://user-images.githubusercontent.com/1506340/38332079-61fd1a46-3855-11e8-97ad-0302f9fc1919.png)

I select index 2 like this:

![datagridselected](https://user-images.githubusercontent.com/1506340/38332139-845987d2-3855-11e8-82a6-6e3231b1f1e3.png)

I now click the Item Header so the DataGrid sorts the Columns like this:

![datagridselectedsameindex](https://user-images.githubusercontent.com/1506340/38332192-adf7b5a0-3855-11e8-99ea-aa7e348a46c2.png)

The selected index is still 2.

Is this the correct behavior or should the selectedIndex change to 0?

Thanx a million for this awesome project, I couldn't have build my apps without it! :)

**Comment by joshtynjala** [comment]
Good catch. Thanks!

**Comment by martinrossil** [comment]
That was a fast response! :)

I'm glad I could help! :)
