### ISSUE TITLE
PickerList. Scroll the list and tap again

### ISSUE THREAD

**Issue by denisgl777** [BowlerHatLLC/feathers#1718]
If you scroll the sheet and remove your finger, tapping the sheet again closes the sheet if it is still in the scroll state.
That is, if our sheet has a lot of elements, then at the end of it you can scroll only all the time waiting for the end of scrolling and touch your finger again

**Comment by joshtynjala** [comment]
That sounds like a side effect of this enhancement:

 fe90ce7

I'll take a look. Thanks!
