### ISSUE TITLE
DropDownPopUpContentManager: content.height not calculated correctly?

### ISSUE THREAD

**Issue by m-a-v** [BowlerHatLLC/feathers#1722]
We use a DropDownPopUpContentManager to show several list items. No problems on a iPhone 6. There is enough space, so no scrollbar has to be drawn. If we test it on a iPhone 7 Plus there is even more place to show the whole list, but content.height seems to be calculated incorrectly.

![iphone7plus](https://user-images.githubusercontent.com/16197536/40028141-aacef13e-57dd-11e8-88c4-e4eb5a9b4b22.png)
![iphone6](https://user-images.githubusercontent.com/16197536/40028142-aaeaf8c0-57dd-11e8-95e1-9a7bc73b2d27.png)

We are using the v3.4.x branch. I also tried to update the DropDownPopUpContentManager.as file from  master, but that didn't change anything. Testing with master would need more work.

Any ideas why this doesn't work correclty?

**Comment by joshtynjala** [comment]
Have you checked if maxRowCount is set? Perhaps in the theme?

**Comment by m-a-v** [comment]
Thank you for the hint. Just checked it, maxRowCount is not set anywhere.

**Comment by m-a-v** [comment]
The app didn't support landscape mode when I looked into the bug. The problem is the content.height variable which seems to be calculated wrong. As far as I've seen this is done by rendering the whole list. Correct? If you can give me other hints I can have a look at it later.

**Comment by joshtynjala** [comment]
Yes, that's correct.

DropDownPopUpContentManager validates its content at the beginning of layout(). The content will calculate its own height during validation, and DropDownPopUpContentManager tries not to change the height value, if possible. By default, a List component will try to show all of its item renderers without scrolling, so something may be setting the height or maxHeight on the List. At the end of layout(), DropDownPopUpContentManager may set the maxHeight if the List won't fit within the bounds of the stage. However, that should not be happening here. The restriction is probably coming from somewhere else.

**Comment by m-a-v** [comment]
In this specific theme explicitHeight was set depending on a call DeviceCapabilities.isTablet(). This seems to return true on iPhone 7 Plus, but not on iPhone 6. In summary: No bug in DropDownPopUpContentManager.

Probably the method isTablet coudl be improved. what do you think?

Thank you very much for your help.

**Comment by joshtynjala** [comment]
> Probably the method isTablet coudl be improved. what do you think?

Starting in Feathers 3.5, DeviceCapabilities.isTablet() returns false on iPhone 6/7/8 Plus, Pixel XL, Galaxy Note, and other large phones. A new function isLargePhone() has also been added.

**Comment by m-a-v** [comment]
Is it already planned when Feathers 3.5 will be released?
