### ISSUE TITLE
ArgumentError: horizontalScrollPosition cannot be NaN.

### ISSUE THREAD

**Issue by Adrian-S** [BowlerHatLLC/feathers#1723]
Hey, we've got into this error and traced it back to this line:

https://github.com/BowlerHatLLC/feathers/blob/master/source/feathers/controls/Scroller.as#L5032

The variable `this.actualPageWidth` is set to Infinity, causing `roundUpToNearest` to return a NaN.

I am investigating now why `actualPageWidth` got to Infinity.

**Comment by Adrian-S** [comment]
I was setting `pageWidth` to infinity by mistake, this caused the error, but this could be easily prevented.

**Comment by joshtynjala** [comment]
I'm happy that you figured it out!

**Comment by Adrian-S** [comment]
I strongly suggest, a limit for `pageWidth`. That's what I did to find it and could help others in debug process.

**Comment by joshtynjala** [comment]
I imagine that trying to pass in infinity would cause similar strange errors for the vast majority of properties defined in Feathers. If I add a special check here, there are hundreds of other places that I should do the same, and these checks have performance and other implications to consider.

For example, I once tried adding a simple if statement in the x and y setters to validate the value, and I saw a huge drop in performance. Those two properties are used much more frequently than pageWidth, of course, but even smaller validation checks start to add up. Generally, if I see an issue come up frequently enough, that's when I start thinking about adding a validation check. Right now, this issue with pageWidth and infinity is pretty rare, but I'll keep it in mind if others start running into it more often.
