### ISSUE TITLE
App crashes after setting `text` property of TextInput

### ISSUE THREAD

**Issue by subdan** [BowlerHatLLC/feathers#1727]
Hello, Josh. I use the latest version of Feathers and Starling. I have a simple TextInput:

```
var nameInput:TextInput = new TextInput();
nameInput.addEventListener(Event.CHANGE, nameInput_changeHandler);
nameInput.prompt = "Your name";
// nameInput.text = "John";
addChild(nameInput);
```

If I uncomment `nameInput.text = "John";` my app crashes.

Why my app crashes? 

If I set text property after 5 sec it doesn't crash.
```
setTimeout(setName, 5000);
function setName()void
{
	nameInput.text = "John";
}
```

**Comment by joshtynjala** [comment]
Which platform? Which ITextEditor? Which version of AIR?

**Comment by subdan** [comment]
Android, AIR 29, StageTextTextEditor, TopcoatLightMobileTheme

**Comment by joshtynjala** [comment]
I tried to reproduce this issue on a couple of different Android devices (Google Nexus 5 and Samsung Galaxy S5), but I could not make it crash.

I implemented nameInput_changeHandler like this:

``` actionscript
private function nameInput_changeHandler(event:Event):void
{
	trace("change", TextInput(event.currentTarget).text);
}
```

**Comment by subdan** [comment]
I do not know why it doesn't crash on your devices. I use a workaround to avoid this issue. You can close this issue.
