### ISSUE TITLE
Button: scaleWhenDown doesn't unscale back to 1

### ISSUE THREAD

**Issue by CrazyFlasher** [BowlerHatLLC/feathers#1742]
Hi,
I setted ```button.scaleWhenDown = 1.2;``` to button style, but after click it doesn't return back to normal scale:
![gif](https://user-images.githubusercontent.com/1607138/42407344-e7af73a8-81c2-11e8-8d41-fbfd36266955.gif)

**Comment by CrazyFlasher** [comment]
This works as ugly workaround :)
```
                private function setButtonStyles(button:Button):void
		{
			button.addEventListener(FeathersEventType.STATE_CHANGE, function ():void
			{
				if (button.currentState == ButtonState.DOWN)
				{
					button.pivotX = button.width / 2;
					button.pivotY = button.height / 2;
					button.scale = 1.2;
				} else
				{
					button.scale = 1.0;
				}
			});
		}
```

**Comment by joshtynjala** [comment]
I cannot reproduce this issue. I tried the following code, and the button's scale returned to 1.0 as expected.

``` actionscript
var button:Button = new Button();
button.label = "Hello";
button.move(50, 50);
button.scaleWhenDown = 1.2;
this.addChild(button);
```

**Comment by CrazyFlasher** [comment]
I thinks there are some extra conditions I need ti investigate, because some buttons work fine.
I'll investigate ASAP and provide more detailed info

**Comment by CrazyFlasher** [comment]
This is weird, but I cannot reproduce it on my home machine...I'll investigate more

**Comment by CrazyFlasher** [comment]
By the way, Is the a simple way to animate scaling?

**Comment by joshtynjala** [comment]
You can animate scaleX and scaleY with a regular Tween. However, that doesn't working exactly the same as scaleWhenDown. scaleWhenDown doesn't affect layouts, but scaleX and scaleY might.

**Comment by CrazyFlasher** [comment]
This is really weird, but this happens with some textures from atlas:
![gif1](https://user-images.githubusercontent.com/1607138/42841871-19f7b3c6-8a14-11e8-9e73-9dc9dcb32567.gif)
If I use other textures, it works fine.
The code is simple:
```
private function setGuiScreenAddSilverStyles(button:Button):void
{
	button.setScaleForState(ButtonState.DOWN, 1.2);

	button.defaultSkin = ift.imageFromTexture(TexturesNames.GENERAL_ADD_COINS_BTN);
}
```
I've attached atlas. Texture name is `General/add-coins-btn.png`
[ui.zip](https://github.com/BowlerHatLLC/feathers/files/2203186/ui.zip)

**Comment by joshtynjala** [comment]
I tried the following code, but I still cannot reproduce the issue.

``` actionscript
[Embed(source="ui.png")]
private static const ATLAS_IMAGE:Class;

[Embed(source="ui.xml",mimeType="application/octet-stream")]
private static const ATLAS_XML:Class;
```

``` actionscript
var atlas:TextureAtlas = new TextureAtlas(Texture.fromEmbeddedAsset(ATLAS_IMAGE), XML(new ATLAS_XML()));
var button:Button = new Button();
button.move(50, 50);
button.setScaleForState(ButtonState.DOWN, 1.2);
button.defaultSkin = new ImageSkin(atlas.getTexture("General/add-coins-btn.png"));
this.addChild(button);
```

I also tried with keepDownStateOnRollOut, and that is working correctly too.

**Comment by CrazyFlasher** [comment]
Ok, I'll try to reproduce it in simple project and attach it here soon

**Comment by CrazyFlasher** [comment]
OK, the issue was in `skipUnchangedFrames` setted to `true` :)
This is a good feature of Starling 2.
Need to think, how to keep this flag enabled.
Any suggestions?

**Comment by joshtynjala** [comment]
I'm pretty sure that I had skipUnchangedFrames enabled when I was trying to reproduce this issue. However, this is a good clue. If I can figure out how to get the button to change state without modifying the display list, I may be able to reproduce it now.
