### ISSUE TITLE
VideoPlayer issue

### ISSUE THREAD

**Issue by Seraphim-AT** [BowlerHatLLC/feathers#1743]
I use VideoPlayer: create it's instance, load video source, while it's loading - I try to load another file and getting error in 'videoPlayer_progress_enterFrameHandler' function, it still listen for load progress of previous file even after it's disposing (can't find this._netStream when it's null, that's it).

**Comment by joshtynjala** [comment]
Thanks! I'll take a look soon to see if I can reproduce the same error.

**Comment by joshtynjala** [comment]
I wasn't able to figure out how to reproduce, since all of my videos seemed to buffer completely. However, I'm pretty sure that I got it fixed.

**Comment by Seraphim-AT** [comment]
thanks, Josh!
