### ISSUE TITLE
ImageLoader: Add support for MeshStyle

### ISSUE THREAD

**Issue by subdan** [BowlerHatLLC/feathers#1746]
Hello, Josh.

I want to set `style` property of ImageLoader but the ImageLoader doesn't support it. Could you please add this feature?

**Comment by joshtynjala** [comment]
Just to clarify, do you mean that you'd like to be able to use a [`MeshStyle`](http://doc.starling-framework.org/current/starling/styles/MeshStyle.html) with `ImageLoader`?

**Comment by subdan** [comment]
Yes, I would like to use MeshStyle (TextureMaskStyle and DistanceFieldStyle).

**Comment by subdan** [comment]
Thanks!
