### ISSUE TITLE
Problems with HyperlinkTextFieldTextRenderer

### ISSUE THREAD

**Issue by m-a-v** [BowlerHatLLC/feathers#1747]
When using the following HTML text in a HyperlinkTextFieldTextRenderer only the word "to" is a link. The cascaded word "Google" is not a link. Can you reproduce this wrong behaviour? 

``` html
<p align="justify">Always go <a href="https://www.google.com">to <font color="#0086FF">Google</font></a> first before ...</p>
```

**Comment by m-a-v** [comment]
Is this a known bug? Is a workaround available?

**Comment by joshtynjala** [comment]
As noted <a href="https://forum.starling-framework.org/topic/textfields-with-hyperlinks/page/4#post-52324">here</a>, where i first shared this component,:

> This text renderer is purely EXPERIMENTAL, and I have no plans to officially add this component to the Feathers core library at this time. USE AT YOUR OWN RISK. If you discover that it is broken in some way, don't say that I didn't warn you. Also, I may not be able to help you if you run into trouble with it, so please be ready to figure out issues entirely on your own.

**Comment by m-a-v** [comment]
I wasn't aware of this. Many thanks for the clarification.
