### ISSUE TITLE
ScreenDensityScaleFactorManager: black bars

### ISSUE THREAD

**Issue by CrazyFlasher** [BowlerHatLLC/feathers#1759]
Samsung Galaxy S9 in landscape mode

**Comment by joshtynjala** [comment]
Could you post a screenshot?

What are the values of nativeStage.stageWidth, nativeStage.stageHeight, and Capabilities.screenDPI when you're in landscape mode on this device?

**Comment by CrazyFlasher** [comment]
**Details:**
```
[trace] nativeStage.stageWidth: 1920
[trace] nativeStage.stageHeight: 1080
[trace] Capabilities.screenDPI: 420
```

**Actual:**
![image](https://user-images.githubusercontent.com/1607138/45157628-5f0dbe80-b1ea-11e8-8e51-168a7571ec31.png)

**Expected:**
![image](https://user-images.githubusercontent.com/1607138/45157658-75b41580-b1ea-11e8-9215-8f1d65ccc550.png)

**Comment by joshtynjala** [comment]
ScreenDensityScaleFactorManager is behaving correctly. It seems to be an AIR issue because the native stage is not filling the full screen resolution of the device. According to a quick Google search, it should be 2220x1080 pixels instead of 1920x1080 pixels.
