### ISSUE TITLE
[Bug] ItemRenderer, Drag&Drop with HorizontalLayout and HorizontalAlign.CENTER

### ISSUE THREAD

**Issue by subdan** [BowlerHatLLC/feathers#1766]
Hello.

In my app I use a List with this layout:
```
var layout:HorizontalLayout = new HorizontalLayout();
layout.horizontalAlign = HorizontalAlign.CENTER;
list.layout = layout;
```

Drag&drop works incorrect when I set `layout.horizontalAlign = HorizontalAlign.CENTER;`.

To explain the issue I've recorded two video:
1. [Without `layout.horizontalAlign = HorizontalAlign.CENTER;`](https://drive.google.com/open?id=1TjDd7RLuzMcMh5nFtC2Xs-JyJljNu-gl)
2. [With `layout.horizontalAlign = HorizontalAlign.CENTER;`](https://drive.google.com/open?id=1RdjXBjatgvp3I1TwlB3JGtS4aJ05p0jU)

As you can see when I set `layout.horizontalAlign = HorizontalAlign.CENTER;` distance between dropIndicator and ItemRenderer is very big. There is an offset. This issue happens only when number of items is less than List width. Could you fix it?

**Comment by subdan** [comment]
There is another issue I've found right now.
![screenshot_1](https://user-images.githubusercontent.com/410293/47071803-c0b34680-d1f4-11e8-994c-42fa93cd778d.png)
If I set `layout.verticalAlign = VerticalAlign.MIDDLE;` then Y position of `dropIndicator` is incorrect. `dropIndicator` Y position must me equal to ItemRenderer's Y position.

**Comment by subdan** [comment]
Is it possible to add delay before ItemRenderer starts to drag to avoid drag&drop while scrolling.

**Comment by joshtynjala** [comment]
> Is it possible to add delay before ItemRenderer starts to drag to avoid drag&drop while scrolling.

Not at this time. If you're using DefaultListItemRenderer, you should provide a dragIcon. If you have a custom item renderer, you should implement IDragAndDropItemRenderer and provide a dragProxy for the same purpose. This will allow a small region of your item renderer to be draggable, while you can touch other parts of the item renderer to scroll.

**Comment by joshtynjala** [comment]
Fixed. Thanks!

**Comment by subdan** [comment]
Thank you!
