### ISSUE TITLE
Keyboard navigation is not respecting the ScrollPolicy.OFF

### ISSUE THREAD

**Issue by Adrian-S** [BowlerHatLLC/feathers#1773]
I have a Screen object, that has a child outside the visible area on the right side. I've noticed that if I press RIGHT arrow, screen scrolls and shows me this object and I can't scroll back. Any other key becomes useless after this, and ScrollPolicy is OFF for that screen.

I fixed it using the code below on my screen:
`override protected function nativeStage_keyDownHandler(event:KeyboardEvent):void { }`

**Comment by joshtynjala** [comment]
I assume that it's actually a PanelScreen or a ScrollScreen rather than a Screen?

**Comment by Adrian-S** [comment]
Yes, it's a `PanelScreen`.
