### ISSUE TITLE
Broken link on the FAQ page

### ISSUE THREAD

**Issue by chrisvelevitch** [BowlerHatLLC/feathers#1774]
On the [FAQ](https://feathersui.com/help/faq/index.html) in the paragraph
```
When I add a Feathers component to the display list, why don't I see anything?
```
the link [Getting Started With Feathers](https://feathersui.com/help/faq/getting-started.html) (`https://feathersui.com/help/faq/getting-started.html`) is broken. What should that link be?

**Comment by joshtynjala** [comment]
I see that you've already found the correct link, but I'll copy it here for completeness:

https://feathersui.com/help/getting-started.html
