### ISSUE TITLE
Label component cut off text after context restore

### ISSUE THREAD

**Issue by subdan** [BowlerHatLLC/feathers#1778]
Hello, Josh.

This is a Label with backgroundSkin:
![screenshot_2](https://user-images.githubusercontent.com/410293/49275447-60b6ed80-f48c-11e8-90ec-9435ead42407.png)

I simulate context restore by calling Starling.current.context.dispose();

When context restore happens Label cut off some text:
![screenshot_3](https://user-images.githubusercontent.com/410293/49275490-8217d980-f48c-11e8-8b4a-83ba8e7f77c1.png)

I use TextFieldTextRenderer.

Why it happens? Is it a bug? How to fix this issue?

I created a repository with demo project [https://github.com/subdan/feathes-label-issue](https://github.com/subdan/feathes-label-issue)

**Comment by joshtynjala** [comment]
Thank you! I can reproduce this issue.

It can be reproduced with both TextFieldTextRenderer and TextBlockTextRenderer.

When using Align.TOP and Align.LEFT in the TextFormat, the text is not cut off. It seems to be cut off only when using other alignment values like Align.CENTER, Align.RIGHT, and Align.BOTTOM.

The following simplified code will reproduce the issue on my computer:

``` actionscript
var headerLabel:Label = new Label();
headerLabel.textRendererFactory = function():ITextRenderer
{
	return new TextFieldTextRenderer();
};
var fontStyles:TextFormat = new TextFormat("Arial", 20, 0xFFFFFF, Align.CENTER, Align.CENTER);
headerLabel.fontStyles = fontStyles;
headerLabel.text = "Title — Name";
headerLabel.setSize(200, 80);
addChild(headerLabel);

var button:Button = new Button();
button.label = "Click Me";
button.x = 10;
button.y = 100;
button.addEventListener(Event.TRIGGERED, function():void
{
	Starling.current.context.dispose();
})
addChild(button);
```

**Comment by subdan** [comment]
When do you plan to fix this issue? Fixing this issue is very important for me.

**Comment by joshtynjala** [comment]
I plan to fix it before I release the stable build of 4.0. By the end of December for sure, but sooner if find time.

**Comment by subdan** [comment]
Thank you! It works!
