### ISSUE TITLE
TextArea focus with prompt

### ISSUE THREAD

**Issue by denisgl7** [BowlerHatLLC/feathers#1781]
If we add a property  textArea.prompt = someText , then when hovering over the text, the focus immediately disappears. If you remove the prompt, the text area works fine.

**Comment by joshtynjala** [comment]
Unfortunately, I cannot reproduce this issue. I tried using every type of text renderer for the prompt, and the focus was not lost on hover.

``` actionscript
var textArea:TextArea = new TextArea();
textArea.prompt = "Test test";
this.addChild(textArea);
```
