### ISSUE TITLE
First item renderer in SlideShowLayout is not recycled/disposed

### ISSUE THREAD

**Issue by esidegallery** [BowlerHatLLC/feathers#1786]
This seems to happen no matter what I set minimumItemCount to. Is this intended, and if so how can I disable the functionality?

**Comment by joshtynjala** [comment]
Set a typicalItem on the List that isn't in the data providerm. By default, the first item on the data provider is used.

You will still have an extra item renderer that isn't visible. There's no way around that. It's needed for measurement.

**Comment by esidegallery** [comment]
That did it! Thank you Josh.
