### ISSUE TITLE
MXML Support

### ISSUE THREAD

**Issue by joshtynjala** [BowlerHatLLC/feathers#186]
Updated: I have forked the Apache Flex SDK, and I am modifying the compiler to support Starling and Feathers. See the blog post [Adding support for MXML to Feathers](http://joshblog.net/2015/adding-support-for-mxml-in-feathers/) for details about this project.

Special thanks to [YETi CGI](http://yeticgi.com/) for sponsoring this project.

**Comment by yangboz** [comment]
Without ID for binding, there is a work around to get the component:

//<feathers:ImageLoader name="name_imageLoader" source="
private function get id_imageLoader():ImageLoader{
	return (this.id_scrollContainer.getChildByName("name_imageLoader") as ImageLoader);
}

Notice: You should layer by layer (container used) to get it.

And, how to customize feathersUI's MXML component ?

Finally, thanks for this great work!
