### ISSUE TITLE
Weird issue in Flash Builder 4.7

### ISSUE THREAD

**Issue by FLEXIncubator** [BowlerHatLLC/feathers#223]
This is pretty weird and maybe this is not Feathers related thing at all. Still, want to point out. I am using Flash Builder 4.7 now with AIR SDK 3.4. I downloaded latest Feathers code today from github. And now, from time to time, strange compile-time errors appears. The thing is that they always appear at same 2 places (in VectorListCollectionDataDescriptor)
- public function addItemAt(data:Object, item:Object, index:int):void
- public function removeItemAt(data:Object, index:int):Object

The whole bunch of errors (for removeItemAt) is pasted below. Cleaning the project does not help ( I mean the Clean command menu item in Flash builder). But, when you close Flash Builder, then open again then do clean - errors disappear. Then, just after some time (maybe an hour, maybe less or more), they spontaneously appear again. I just tried (for testing purpose) to delete the whole contents of AddItemAt, and the error disappeared too. Can it be related to new compiler?

com.google.common.collect.ComputationException: java.lang.NullPointerException at com.google.common.collect.ComputingConcurrentHashMap
 $ComputingSegment.compute(ComputingConcurrentHashMap.java:167) at com.google.common.collect.ComputingConcurrentHashMap
 $ComputingSegment.compute(ComputingConcurrentHashMap.java:116) at 
 com.google.common.collect.ComputingConcurrentHashMap.apply(ComputingConcurrentHashMap.java:67) at com.google.common.collect.MapMaker
 $ComputingMapAdapter.get(MapMaker.java:623) at com.adobe.flash.compiler.internal.projects.CompilerProject.getCacheForScope(CompilerProject.java:701) at 
 com.adobe.flash.compiler.internal.scopes.ASScope.findPropertyQualified(ASScope.java:1476) at 
 com.adobe.flash.compiler.internal.definitions.references.ResolvedQualifiersReference.resolve(ResolvedQualifiersReference.java:80) at 
 com.adobe.flash.compiler.internal.definitions.DefinitionBase.resolveType(DefinitionBase.java:1049) at 
 com.adobe.flash.compiler.internal.definitions.DefinitionBase.resolveType(DefinitionBase.java:1089) at 
 com.adobe.flash.compiler.internal.definitions.ClassDefinition.resolveBaseClass(ClassDefinition.java:373) at 
 com.adobe.flash.compiler.internal.definitions.TypeDefinitionBase$TypeIterator.pushChildren(TypeDefinitionBase.java:284) at 
 com.adobe.flash.compiler.internal.definitions.TypeDefinitionBase$TypeIterator.next(TypeDefinitionBase.java:218) at 
 com.adobe.flash.compiler.internal.definitions.TypeDefinitionBase$TypeIterator.next(TypeDefinitionBase.java:176) at 
 com.adobe.flash.compiler.internal.scopes.TypeScope.getPropertyForScopeChain(TypeScope.java:261) at 
 com.adobe.flash.compiler.internal.scopes.TypeScope.getPropertyForScopeChain(TypeScope.java:188) at 
 com.adobe.flash.compiler.internal.scopes.ASScope.findProperty(ASScope.java:1038) at com.adobe.flash.compiler.internal.scopes.ASScope.findProperty(ASScope.java:
 981) at com.adobe.flash.compiler.internal.scopes.ASScope.findProperty(ASScope.java:1161) at 
 com.adobe.flash.compiler.internal.scopes.ASScope.findProperty(ASScope.java:919) at 
 com.adobe.flash.compiler.internal.scopes.ASScopeCache.findPropertyQualified(ASScopeCache.java:267) at 
 com.adobe.flash.compiler.internal.scopes.ASScope.findPropertyQualified(ASScope.java:1478) at 
 com.adobe.flash.compiler.internal.definitions.references.ResolvedQualifiersReference.resolve(ResolvedQualifiersReference.java:80) at 
 com.adobe.flash.compiler.internal.definitions.DefinitionBase.resolveType(DefinitionBase.java:1049) at 
 com.adobe.flash.compiler.internal.definitions.DefinitionBase.resolveType(DefinitionBase.java:1089) at 
 com.adobe.flash.compiler.internal.definitions.DefinitionBase.resolveType(DefinitionBase.java:871) at 
 com.adobe.flash.compiler.internal.semantics.MethodBodySemanticChecker.checkFormalsVsActuals(MethodBodySemanticChecker.java:758) at 
 com.adobe.flash.compiler.internal.semantics.MethodBodySemanticChecker.checkFunctionCall(MethodBodySemanticChecker.java:842) at 
 com.adobe.flash.compiler.internal.as.codegen.ABCGeneratingReducer.reduce_functionAsMemberExpr(ABCGeneratingReducer.java:3960) at 
 com.adobe.flash.compiler.internal.as.codegen.CmcEmitter.action_327(CmcEmitter.java:5339) at 
 com.adobe.flash.compiler.internal.as.codegen.CmcEmitter.dispatchAction(CmcEmitter.java:8606) at 
 com.adobe.flash.compiler.internal.as.codegen.CmcEmitter.reduceAntecedent(CmcEmitter.java:39704) at 
 com.adobe.flash.compiler.internal.as.codegen.CmcEmitter.reduce(CmcEmitter.java:39681) at 
 com.adobe.flash.compiler.internal.as.codegen.CmcEmitter.reduceSubgoals(CmcEmitter.java:39723) at 
 com.adobe.flash.compiler.internal.as.codegen.CmcEmitter.reduceAntecedent(CmcEmitter.java:39703) at 
 com.adobe.flash.compiler.internal.as.codegen.CmcEmitter.reduce(CmcEmitter.java:39681) at 
 com.adobe.flash.compiler.internal.as.codegen.CmcEmitter.reduceSubgoals(CmcEmitter.java:39723) at 
 com.adobe.flash.compiler.internal.as.codegen.CmcEmitter.reduceAntecedent(CmcEmitter.java:39703) at 
 com.adobe.flash.compiler.internal.as.codegen.CmcEmitter.reduce(CmcEmitter.java:39681) at 
 com.adobe.flash.compiler.internal.as.codegen.CmcEmitter.reduceSubgoals(CmcEmitter.java:39732) at 
 com.adobe.flash.compiler.internal.as.codegen.CmcEmitter.reduceAntecedent(CmcEmitter.java:39703) at 
 com.adobe.flash.compiler.internal.as.codegen.CmcEmitter.reduce(CmcEmitter.java:39681) at 
 com.adobe.flash.compiler.internal.as.codegen.CmcEmitter.reduceSubgoals(CmcEmitter.java:39723) at 
 com.adobe.flash.compiler.internal.as.codegen.CmcEmitter.reduceAntecedent(CmcEmitter.java:39703) at 
 com.adobe.flash.compiler.internal.as.codegen.CmcEmitter.reduce(CmcEmitter.java:39681) at 
 com.adobe.flash.compiler.internal.as.codegen.CmcEmitter.burm(CmcEmitter.java:39983) at 
 com.adobe.flash.compiler.internal.as.codegen.ABCGenerator.generateInstructions(ABCGenerator.java:232) at 
 com.adobe.flash.compiler.internal.as.codegen.ABCGenerator.generateMethodBodyForFunction(ABCGenerator.java:397) at 
 com.adobe.flash.compiler.internal.as.codegen.ABCGenerator.generateMethodBodyForFunction(ABCGenerator.java:351) at 
 com.adobe.flash.compiler.internal.as.codegen.ABCGenerator.generateFunction(ABCGenerator.java:266) at 
 com.adobe.flash.compiler.internal.as.codegen.ClassDirectiveProcessor.declareFunction(ClassDirectiveProcessor.java:646) at 
 com.adobe.flash.compiler.internal.as.codegen.DirectiveProcessor.processNode(DirectiveProcessor.java:215) at 
 com.adobe.flash.compiler.internal.as.codegen.DirectiveProcessor.traverse(DirectiveProcessor.java:189) at 
 com.adobe.flash.compiler.internal.as.codegen.GlobalDirectiveProcessor.declareClass(GlobalDirectiveProcessor.java:423) at 
 com.adobe.flash.compiler.internal.as.codegen.DirectiveProcessor.processNode(DirectiveProcessor.java:207) at 
 com.adobe.flash.compiler.internal.as.codegen.DirectiveProcessor.traverse(DirectiveProcessor.java:189) at 
 com.adobe.flash.compiler.internal.as.codegen.GlobalDirectiveProcessor.declarePackage(GlobalDirectiveProcessor.java:449) at 
 com.adobe.flash.compiler.internal.as.codegen.DirectiveProcessor.processNode(DirectiveProcessor.java:224) at 
 com.adobe.flash.compiler.internal.as.codegen.DirectiveProcessor.traverse(DirectiveProcessor.java:189) at 
 com.adobe.flash.compiler.internal.as.codegen.ABCGenerator.generate(ABCGenerator.java:126) at 
 com.adobe.flash.compiler.internal.units.ASCompilationUnit.handleABCBytesRequest(ASCompilationUnit.java:374) at 
 com.adobe.flash.compiler.internal.units.CompilationUnitBase.processABCBytesRequest(CompilationUnitBase.java:866) at 
 com.adobe.flash.compiler.internal.units.CompilationUnitBase.access$300(CompilationUnitBase.java:107) at 
 com.adobe.flash.compiler.internal.units.CompilationUnitBase$4$1.call(CompilationUnitBase.java:309) at com.adobe.flash.compiler.internal.units.CompilationUnitBase
 $4$1.call(CompilationUnitBase.java:305) at com.adobe.flash.compiler.internal.units.requests.RequestMaker$1.call(RequestMaker.java:228) at 
 com.adobe.flash.compiler.internal.units.requests.RequestMaker$1.call(RequestMaker.java:222) at java.util.concurrent.FutureTask$Sync.innerRun(Unknown Source) at 
 java.util.concurrent.FutureTask.run(Unknown Source) at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(Unknown Source) at 
 java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) at java.lang.Thread.run(Unknown Source) Caused by: java.lang.NullPointerException at 
 com.google.common.base.Preconditions.checkNotNull(Preconditions.java:187) at 
 com.google.common.collect.CustomConcurrentHashMap.hash(CustomConcurrentHashMap.java:1432) at 
 com.google.common.collect.ComputingConcurrentHashMap.apply(ComputingConcurrentHashMap.java:66) at com.google.common.collect.MapMaker
 $ComputingMapAdapter.get(MapMaker.java:623) at 
 com.adobe.flash.compiler.internal.scopes.ASProjectScope.addScopeToCompilationUnitScopeList(ASProjectScope.java:1306) at 
 com.adobe.flash.compiler.internal.projects.CompilerProject$ScopeMakerFunction.apply(CompilerProject.java:106) at 
 com.adobe.flash.compiler.internal.projects.CompilerProject$ScopeMakerFunction.apply(CompilerProject.java:95) at 
 com.google.common.collect.ComputingConcurrentHashMap$ComputingSegment.compute(ComputingConcurrentHashMap.java:155) ... 70 more

**Comment by kheftel** [comment]
This issue still exists, on mac now, whereas before I was on a win8 laptop. Screwing around with combinations of "Mark Occurrences" on and off, running clean on my projects, and restarting FB eventually got it to go away.  For now.  For me, this comes up every few weeks or so.

**Comment by GaiusCoffey** [comment]
Not sure whether or not this is coincidental, but I saw the same issue on a clean FB install and seem to have resolved it through updating to the current SDK as per this; https://helpx.adobe.com/flash-builder/kb/overlay-air-sdk-flash-builder.html

**Comment by joshtynjala** [comment]
Good to know! Starling 2.0 and Feathers 3.0 require AIR 19, so going forward, everyone will have no choice but to update the AIR SDK used by Flash Builder.
