### ISSUE TITLE
Add visual debug for layouts

### ISSUE THREAD

**Issue by wrench7** [BowlerHatLLC/feathers#242]
It would be great to be able to have a visual debugging overlay for layouts that displayed the width, height and the padding associated with the layout in question (similar to the Inspect Element functionality of Firebug in the browser).

**Comment by joshtynjala** [comment]
My [monsterdebugger-client-starling](https://github.com/joshtynjala/monsterdebugger-client-starling) project for use with [Monster Debugger](http://www.monsterdebugger.com/) is recommended for visual debugging. Supported by both Starling 1.x and 2.x.
