### ISSUE TITLE
GroupedList: implement "sticky" headers where the header of the current group doesn't scroll away until the last item scrolls away

### ISSUE THREAD

**Issue by joshtynjala** [BowlerHatLLC/feathers#342]
Similar to iOS. The header for the group near the beginning is sticky until the next group header pushes it up.

Will probably require support in both GroupedList and in the layouts (VerticalLayout and HorizontalLayout at minimum).

**Comment by GV3** [comment]
In my opinion this feature is major! The UX of today expects the headers of the groups to behave as "sticky headers"

Is this feature planed soon? If not, I gladly offer myself to Fork and code it for a later review.

**Comment by joshtynjala** [comment]
I'll try to fit it into the roadmap for 2.3.
