### ISSUE TITLE
Layouts: functions to get index to the top/right/bottom/left of a specific index

### ISSUE THREAD

**Issue by joshtynjala** [BowlerHatLLC/feathers#376]
To support keyboard navigation in list. For instance, a list with a vertical layout would just need up and down arrow keys. However, a list with a tile layout could go in all four directions with arrow keys.

**Comment by joshtynjala** [comment]
https://feathersui.com/api-reference/feathers/layout/ILayout.html#calculateNavigationDestination()

**Comment by devlfm** [comment]
I think this will make drag/drop on Lists much easier!
