### ISSUE TITLE
New Feature for the ScreenNavigator: showPreviousScreen(), prevoiusScreenID

### ISSUE THREAD

**Issue by ghost** [BowlerHatLLC/feathers#381]
Feathers 1.0.0:
It would be nice if there was next to the method "showScreen(id:String)" a method named "showPreviousScreen()" to navigate within the Stack. A Property like "perviousScreenID" makes it perfekt.

		protected var _previousScreenID:String;

		public function get previousScreenID():String
		{
			return this._previousScreenID;
		}

		public function showPreviousScreen():void
		{
			showScreen(_previousScreenID);
		}

		public function showScreen(id:String):DisplayObject
		{
			if(!this._screens.hasOwnProperty(id))
			{
				throw new IllegalOperationError("Screen with id '" + id + "' cannot be shown because it has not been defined.");
			}

			if(this._activeScreenID == id)
			{
				return this._activeScreen;
			}

			if(this._transitionIsActive)
			{
				this._nextScreenID = id;
				this._clearAfterTransition = false;
				return null;
			}
			
			this._previousScreenID = _activeScreenID;

...

Thank you.
Peter

**Comment by joshtynjala** [comment]
Closing because this was added in Feathers 2.1 with the new StackScreenNavigator component.
