### ISSUE TITLE
Starling filters does not work with FeathersControl when it is placed in ScrollContainer

### ISSUE THREAD

**Issue by FLEXIncubator** [BowlerHatLLC/feathers#398]
As far as I know ScrollContainer is some basic type of container in Feathers. It can be used not only for content which needs scrolling, but just for layout purpose. However, it seems that Starling filter does not work on components which are inside ScrollContainer. I tested with Label. Filter works just perfectly when Lable is added directly to Screen. But it is not applied at all when Label is added to ScrollContainer.

**Comment by hejiacong** [comment]
if i set filter.cache(),the displayobject is disappear again!
