### ISSUE TITLE
Scale9Image repeat property for scaled regions

### ISSUE THREAD

**Issue by 62316e** [BowlerHatLLC/feathers#634]
Possible?

**Comment by Klug76** [comment]
Is there a chance to see it in version 3.0?

**Comment by joshtynjala** [comment]
I'm not planning to add this to Feathers 3.0. Actually, [Daniel has said that he's planning to add scale-9, scale-3 and tiling to Starling 2.0](https://github.com/Gamua/Starling-Framework/issues/773#issuecomment-149137544), so I will probably remove Scale9Image, Scale3Image, and TiledImage in Feathers 3.0.
