### ISSUE TITLE
Duplicated item in dataProvider of List causes crash

### ISSUE THREAD

**Issue by ingweland** [BowlerHatLLC/feathers#684]
How to reproduce:
1) the amount of items in dataProvider should be larger than amount of item renderers which can be placed on stage at once
2) create such a data provider, when say first item and some other item are same object (another item should be in such position, so it will be placed in the list only after scrolling)
3) scroll the list

The Error goes from 
this._layoutItems[index + this._layoutIndexOffset] = DisplayObject(renderer);
in renderUnrenderedData() in ListDataViewPort. 

Valid for stable release 1.1.0

Expected behavior: list implementation should not limit the structure of data.

**Comment by kingrichardthethird** [comment]
I just tripped over this too. I really think a sensible error would be appropriate to save folks investigating and eventually ending up here - how about this simple check when the data is set for the list?
```
for (var i:int = 0; i < data.length; i ++) {
  if (data.getItemIndex(data[i]) != i) {
    throw new Error('List does not support duplicate items');
  }
}
```

**Comment by joshtynjala** [comment]
Unfortunately, some data providers can be quite large. Looping through 10 thousand items and calling getItemIndex() on each one would have a *severe* performance impact.
