### ISSUE TITLE
Add tooltip support

### ISSUE THREAD

**Issue by jamikado** [BowlerHatLLC/feathers#84]
Granted this would be a very very low priority enhancement request that is only useful for desktop apps, 

but I realize now that you have nice support for callouts and you now have desktop support for hover events (with hoverSkins)
you could imagine also supporting a nice clean way of allowing foxhole controls to have an optional tooltip string property that gets automatically displayed and hidden with delay timed hover event handlers using callouts as a display rendering.

Possibly app-wide tooltip properties or a factory for how these tooltip callouts look as well as properties for the delay time to show and hide tooltips. Though this does also imply maybe wanting a way to also hook in localized methods of setting tooltip strings or this could just be handled externally by the app developer.

Just a thought.

**Comment by manofspirit** [comment]
Hi Josh, will it be available on MetalMobileTheme? As we use this theme for both Desktop, Web and Mobile Platforms.
Thanks

**Comment by joshtynjala** [comment]
No, but you can enable it manually.

**Comment by manofspirit** [comment]
Awesome :+1:

**Comment by Fabrice-Montfort** [comment]
Hi there,

Is there any sample code on how to customize tooltip skin (with or without a theme) ?

Thanks a lot.

**Comment by joshtynjala** [comment]
The default tool tip is a Label component with the Label.ALTERNATE_STYLE_NAME_TOOL_TIP style name. You can target it in the theme like this:

``` actionscript
this.getStyleProviderForClass(Label)
	.setFunctionForStyleName(Label.ALTERNATE_STYLE_NAME_TOOL_TIP, setToolTipStyles);
```

**Comment by Fabrice-Montfort** [comment]
It works perfectly. Thanks you very much Josh.
