### ISSUE TITLE
Allow scroll bar be always shown in ScrollContainer in SCROLL_BAR_DISPLAY_MODE_FLOAT mode

### ISSUE THREAD

**Issue by minimedj** [BowlerHatLLC/feathers#982]
I use ScrollContainer with scrollBarDisplayMode set to SCROLL_BAR_DISPLAY_MODE_FLOAT. I want scrollBar to be always shown.

More details here:
http://forum.starling-framework.org/topic/how-to-always-show-scrollbar-in-scrollcontainer

**Comment by joshtynjala** [comment]
Closing because SCROLL_BAR_DISPLAY_MODE_FIXED_FLOAT was added.
