### ISSUE TITLE
StageTextTextEditor: uncaught Argument Error when ViewPort is invalid

### ISSUE THREAD

**Issue by rozd** [BowlerHatLLC/feathers#998]
Setting `x` or `y` property of `StageText.viewPort` out of the range between **-8192** and **8191** causes _Argument Error_ exception.

The code

``` as3
import feathers.controls.TextInput;
...
var input:TextInput = new TextInput();
addChild(input);
input.y = -8192;
```

causes

```
[trace] ArgumentError: Error #2006: The supplied index is out of bounds.
[trace]     at flash.text::StageText/set viewPort()
[trace]     at feathers.controls.text::StageTextTextEditor/render()[/Users/***/feathers/source/feathers/controls/text/StageTextTextEditor.as:1091]
[trace]     at starling.display::DisplayObjectContainer/render()[/Users/***/starling/starling/src/starling/display/DisplayObjectContainer.as:355]
...
```

**Comment by joshtynjala** [comment]
One thing that didn't occur to me is that a ScrollContainer or List could cause this error to happen. If I need code for future reference, this is easy to reproduce:

	var container:ScrollContainer = new ScrollContainer();
	var input:TextInput = new TextInput();
	input.y = 10000;
	input.verticalAlign = VerticalAlign.JUSTIFY;
	container.addChild(input);
	container.setSize(this.stage.stageWidth, this.stage.stageHeight);
	this.addChild(container);
